# TODO ####\
# Remove plot_name and tag


################################# transformer n 1 layer ##########################
# python get_activations.py alpaca_7B trivia_qa --token answer_last --file_name trivia_qa_greedy_responses_train5000  --device 0 --save_path /home/local/data/ms/honest_llama_data
# python get_activations.py alpaca_7B trivia_qa --token answer_last --file_name trivia_qa_greedy_responses_validation1800  --device 0 --save_path /home/local/data/ms/honest_llama_data

# python get_activations_and_probe_transformer.py alpaca_7B trivia_qa --train_file_name trivia_qa_greedy_responses_train5000 --test_file_name trivia_qa_greedy_responses_validation1800 --train_labels_file_name trivia_qa_greedy_responses_labels_train5000 --test_labels_file_name trivia_qa_greedy_responses_labels_validation1800 --len_dataset 5000 --num_folds 1 --using_act layer --token answer_last --method transformer_kmeans_hallu_pos --bs 128 --epochs 50 --lr_list 0.00005,0.0005,0.005 --save_probes True --save_path /home/local/data/ms/honest_llama_data --fast_mode True  --use_best_val_t True --seed_list 42,101,2650 --best_using_auc True --skip_train True --top_k_list 1 --dist_metric mahalanobis_centers --pca_dims_list 0.9,0.8,0.7 --which_checkpoint bestusinglast

################################### transformer n*aug 1 layer ####################################

# python get_activations.py alpaca_7B trivia_qa --token answer_last --file_name trivia_qa_sampledplus_responses_train5000  --device 0 --save_path /home/local/data/ms/honest_llama_data
# python get_activations.py alpaca_7B trivia_qa --token answer_last --file_name trivia_qa_greedy_responses_validation1800  --device 0 --save_path /home/local/data/ms/honest_llama_data

# python get_activations_and_probe_transformer.py alpaca_7B trivia_qa --train_file_name trivia_qa_sampledplus_responses_train5000 --test_file_name trivia_qa_greedy_responses_validation1800 --train_labels_file_name trivia_qa_sampledplus_responses_labels_train5000 --test_labels_file_name trivia_qa_greedy_responses_labels_validation1800 --len_dataset 55000 --num_folds 1 --using_act layer --token answer_last --method transformer_knn_hallu_pos --bs 128 --epochs 50 --lr_list 0.00005,0.0005,0.005 --save_probes True --save_path /home/local/data/ms/honest_llama_data --fast_mode True  --plot_name transformer-n*aug --tag main-transformer-5kbestauc-knn --use_best_val_t True  --seed_list 42,101,2650 --best_using_auc True --skip_train True
################################# transformer n 2 layer ##########################################

# python get_activations_and_probe_transformer.py alpaca_7B trivia_qa --train_file_name trivia_qa_greedy_responses_train5000 --test_file_name trivia_qa_greedy_responses_validation1800 --train_labels_file_name trivia_qa_greedy_responses_labels_train5000 --test_labels_file_name trivia_qa_greedy_responses_labels_validation1800 --len_dataset 5000 --num_folds 1 --using_act layer --token answer_last --method transformer2_knn_hallu_pos --bs 128 --epochs 50 --lr_list 0.00005,0.0005,0.005 --save_probes True --save_path /home/local/data/ms/honest_llama_data --fast_mode True  --plot_name transformer2-n --tag main-transformer-5kbestauc-knn --use_best_val_t True  --seed_list 42,101,2650 --best_using_auc True --skip_train True

################################# transformer n 1 layer : ntx ##########################
# python get_activations_and_probe_transformer.py alpaca_7B trivia_qa --train_file_name trivia_qa_greedy_responses_train5000 --test_file_name trivia_qa_greedy_responses_validation1800 --train_labels_file_name trivia_qa_greedy_responses_labels_train5000 --test_labels_file_name trivia_qa_greedy_responses_labels_validation1800 --len_dataset 5000 --num_folds 1 --using_act layer --token answer_last --method transformer_supcon_knn_hallu_pos --bs 256 --epochs 500 --lr_list 0.000005,0.00005,0.0005,0.005 --save_probes True --save_path /home/local/data/ms/honest_llama_data --fast_mode True  --plot_name transformer_ntx-n --tag main-transformer-contrast-5kbestauc-knn --use_best_val_t True --seed_list 42,101,2650 --best_using_auc True --skip_train True

################################# transformer n 1 layer : supcon ##########################
# python get_activations_and_probe_transformer.py alpaca_7B trivia_qa --train_file_name trivia_qa_greedy_responses_train5000 --test_file_name trivia_qa_greedy_responses_validation1800 --train_labels_file_name trivia_qa_greedy_responses_labels_train5000 --test_labels_file_name trivia_qa_greedy_responses_labels_validation1800 --len_dataset 5000 --num_folds 1 --using_act layer --token answer_last --method transformer_supconv2_knn_hallu_pos --bs 256 --epochs 500 --lr_list 0.000005,0.00005,0.0005 --save_probes True --save_path /home/local/data/ms/honest_llama_data --fast_mode True  --plot_name transformer_supconv2-n --tag main-transformer-contrast-5kbestauc-knn --use_best_val_t True --seed_list 42,101,2650 --best_using_auc True --skip_train True
# (python get_activations_and_probe_transformer.py alpaca_7B trivia_qa --train_file_name trivia_qa_greedy_responses_train5000 --test_file_name trivia_qa_greedy_responses_validation1800 --train_labels_file_name trivia_qa_greedy_responses_labels_train5000 --test_labels_file_name trivia_qa_greedy_responses_labels_validation1800 --len_dataset 5000 --num_folds 1 --using_act layer --token answer_last --method transformer_supconv2_knn_hallu_pos --bs 256 --epochs 500 --lr_list 0.000005,0.00005,0.0005 --save_probes True --save_path /home/local/data/ms/honest_llama_data --fast_mode True  --plot_name transformer_supconv2-n-k20 --tag main-transformer-contrast-5kbestauc-knn --use_best_val_t True --seed_list 42,101,2650 --best_using_auc True --skip_train True --top_k 20)
# (python get_activations_and_probe_transformer.py alpaca_7B trivia_qa --train_file_name trivia_qa_greedy_responses_train5000 --test_file_name trivia_qa_greedy_responses_validation1800 --train_labels_file_name trivia_qa_greedy_responses_labels_train5000 --test_labels_file_name trivia_qa_greedy_responses_labels_validation1800 --len_dataset 5000 --num_folds 1 --using_act layer --token answer_last --method transformer_supconv2_knn_hallu_pos --bs 256 --epochs 500 --lr_list 0.000005,0.00005,0.0005 --save_probes True --save_path /home/local/data/ms/honest_llama_data --fast_mode True  --plot_name transformer_supconv2-n-k50 --tag main-transformer-contrast-5kbestauc-knn --use_best_val_t True --seed_list 42,101,2650 --best_using_auc True --skip_train True --top_k 50)
# (python get_activations_and_probe_transformer.py alpaca_7B trivia_qa --train_file_name trivia_qa_greedy_responses_train5000 --test_file_name trivia_qa_greedy_responses_validation1800 --train_labels_file_name trivia_qa_greedy_responses_labels_train5000 --test_labels_file_name trivia_qa_greedy_responses_labels_validation1800 --len_dataset 5000 --num_folds 1 --using_act layer --token answer_last --method transformer_supconv2_knn_hallu_pos --bs 256 --epochs 500 --lr_list 0.000005,0.00005,0.0005 --save_probes True --save_path /home/local/data/ms/honest_llama_data --fast_mode True  --plot_name transformer_supconv2-n-c --tag main-transformer-contrast-5kbestauc-knn --use_best_val_t True --seed_list 42,101,2650 --best_using_auc True --skip_train True --dist_metric cosine)
CUDA_VISIBLE_DEVICES=1 python get_activations_and_probe_transformer.py alpaca_7B trivia_qa --train_file_name trivia_qa_greedy_responses_train5000 --test_file_name trivia_qa_greedy_responses_validation1800 --train_labels_file_name trivia_qa_greedy_responses_labels_train5000 --test_labels_file_name trivia_qa_greedy_responses_labels_validation1800 --len_dataset 5000 --num_folds 1 --using_act layer --token answer_last --method transformer_supconv2_knn_hallu_pos --bs 256 --epochs 500 --lr_list 0.000005,0.00005,0.0005 --save_probes True --save_path /home/local/data/ms/honest_llama_data --fast_mode True  --use_best_val_t True --seed_list 42,101,2650 --best_using_auc True --skip_train True --top_k 3 --dist_metric mahalanobis
CUDA_VISIBLE_DEVICES=1 python get_activations_and_probe_transformer.py alpaca_7B trivia_qa --train_file_name trivia_qa_greedy_responses_train5000 --test_file_name trivia_qa_greedy_responses_validation1800 --train_labels_file_name trivia_qa_greedy_responses_labels_train5000 --test_labels_file_name trivia_qa_greedy_responses_labels_validation1800 --len_dataset 5000 --num_folds 1 --using_act layer --token answer_last --method transformer_supconv2_knn_hallu_pos --bs 256 --epochs 500 --lr_list 0.000005,0.00005,0.0005 --save_probes True --save_path /home/local/data/ms/honest_llama_data --fast_mode True  --use_best_val_t True --seed_list 42,101,2650 --best_using_auc True --skip_train True --top_k 5 --dist_metric mahalanobis
CUDA_VISIBLE_DEVICES=1 python get_activations_and_probe_transformer.py alpaca_7B trivia_qa --train_file_name trivia_qa_greedy_responses_train5000 --test_file_name trivia_qa_greedy_responses_validation1800 --train_labels_file_name trivia_qa_greedy_responses_labels_train5000 --test_labels_file_name trivia_qa_greedy_responses_labels_validation1800 --len_dataset 5000 --num_folds 1 --using_act layer --token answer_last --method transformer_supconv2_knn_hallu_pos --bs 256 --epochs 500 --lr_list 0.000005,0.00005,0.0005 --save_probes True --save_path /home/local/data/ms/honest_llama_data --fast_mode True  --use_best_val_t True --seed_list 42,101,2650 --best_using_auc True --skip_train True --top_k 10 --dist_metric mahalanobis
CUDA_VISIBLE_DEVICES=1 python get_activations_and_probe_transformer.py alpaca_7B trivia_qa --train_file_name trivia_qa_greedy_responses_train5000 --test_file_name trivia_qa_greedy_responses_validation1800 --train_labels_file_name trivia_qa_greedy_responses_labels_train5000 --test_labels_file_name trivia_qa_greedy_responses_labels_validation1800 --len_dataset 5000 --num_folds 1 --using_act layer --token answer_last --method transformer_supconv2_kmeans_hallu_pos --bs 256 --epochs 500 --lr_list 0.000005,0.00005,0.0005,0.005 --save_probes True --save_path /home/local/data/ms/honest_llama_data --fast_mode True  --use_best_val_t True --seed_list 42,101,2650 --best_using_auc True --skip_train True --top_k_list 1 --dist_metric mahalanobis_centers --supcon_temp_list 0.1,0.3,0.5,0.7,1.0,2.0 --pca_dims_list 0.9,0.8,0.7 --which_checkpoint bestusinglast


################################# transformer n*aug 1 layer : ntx ##########################
# python get_activations_and_probe_transformer.py alpaca_7B trivia_qa --train_file_name trivia_qa_sampledplus_responses_train5000 --test_file_name trivia_qa_greedy_responses_validation1800 --train_labels_file_name trivia_qa_sampledplus_responses_labels_train5000 --test_labels_file_name trivia_qa_greedy_responses_labels_validation1800 --len_dataset 55000 --num_folds 1 --using_act layer --token answer_last --method transformer_supcon_knn_hallu_pos --bs 256 --epochs 500 --lr_list 0.000005,0.00005,0.0005,0.005 --save_probes True --save_path /home/local/data/ms/honest_llama_data --fast_mode True  --plot_name transformer_ntx-n*aug --tag main-transformer-contrast-5kbestauc-knn --use_best_val_t True  --seed_list 42,101,2650 --best_using_auc True --skip_train True

################################# transformer n*aug 1 layer : supcon ##########################
# python get_activations_and_probe_transformer.py alpaca_7B trivia_qa --train_file_name trivia_qa_sampledplus_responses_train5000 --test_file_name trivia_qa_greedy_responses_validation1800 --train_labels_file_name trivia_qa_sampledplus_responses_labels_train5000 --test_labels_file_name trivia_qa_greedy_responses_labels_validation1800 --len_dataset 55000 --num_folds 1 --using_act layer --token answer_last --method transformer_supconv2_knn_hallu_pos --bs 256 --epochs 500 --lr_list 0.000005,0.00005,0.0005,0.005 --save_probes True --save_path /home/local/data/ms/honest_llama_data --fast_mode True  --plot_name transformer_supconv2-n*aug --tag main-transformer-contrast-5kbestauc-knn --use_best_val_t True  --seed_list 42,101,2650 --best_using_auc True --skip_train True
# python get_activations_and_probe_transformer.py alpaca_7B trivia_qa --train_file_name trivia_qa_sampledplus_responses_train5000 --test_file_name trivia_qa_greedy_responses_validation1800 --train_labels_file_name trivia_qa_sampledplus_responses_labels_train5000 --test_labels_file_name trivia_qa_greedy_responses_labels_validation1800 --len_dataset 55000 --num_folds 1 --using_act layer --token answer_last --method transformer_supconv2_knn_hallu_pos --bs 275 --epochs 500 --lr_list 0.000005,0.00005,0.0005,0.005 --save_probes True --save_path /home/local/data/ms/honest_llama_data --fast_mode True  --plot_name transformer_supconv2-n*aug-b --tag main-transformer-contrast-5kbestauc-knn --use_best_val_t True  --seed_list 42,101,2650 --best_using_auc True --skip_train True --no_batch_sampling True

################################# transformer n 1 layer : supcon+ ##########################
# python get_activations_and_probe_transformer.py alpaca_7B trivia_qa --train_file_name trivia_qa_greedy_responses_train5000 --test_file_name trivia_qa_greedy_responses_validation1800 --train_labels_file_name trivia_qa_greedy_responses_labels_train5000 --test_labels_file_name trivia_qa_greedy_responses_labels_validation1800 --len_dataset 5000 --num_folds 1 --using_act layer --token answer_last --method transformer_supconv2_pos_knn_hallu_pos --bs 256 --epochs 500 --lr_list 0.000005,0.00005,0.0005,0.005 --save_probes True --save_path /home/local/data/ms/honest_llama_data --fast_mode True  --plot_name transformer_supconv2_pos-n --tag main-transformer-contrast-5kbestauc-knn --use_best_val_t True --seed_list 42,101,2650 --best_using_auc True --skip_train True

################################# transformer n*aug 1 layer : supcon+ ##########################
# python get_activations_and_probe_transformer.py alpaca_7B trivia_qa --train_file_name trivia_qa_sampledplus_responses_train5000 --test_file_name trivia_qa_greedy_responses_validation1800 --train_labels_file_name trivia_qa_sampledplus_responses_labels_train5000 --test_labels_file_name trivia_qa_greedy_responses_labels_validation1800 --len_dataset 55000 --num_folds 1 --using_act layer --token answer_last --method transformer_supconv2_pos_knn_hallu_pos --bs 256 --epochs 500 --lr_list 0.000005,0.00005,0.0005,0.005 --save_probes True --save_path /home/local/data/ms/honest_llama_data --fast_mode True  --plot_name transformer_supconv2_pos-n*aug --tag main-transformer-contrast-5kbestauc-knn --use_best_val_t True  --seed_list 42,101,2650 --best_using_auc True --skip_train True
# python get_activations_and_probe_transformer.py alpaca_7B trivia_qa --train_file_name trivia_qa_sampledplus_responses_train5000 --test_file_name trivia_qa_greedy_responses_validation1800 --train_labels_file_name trivia_qa_sampledplus_responses_labels_train5000 --test_labels_file_name trivia_qa_greedy_responses_labels_validation1800 --len_dataset 55000 --num_folds 1 --using_act layer --token answer_last --method transformer_supconv2_pos_kmeans_hallu_pos --bs 352 --epochs 500 --lr_list 0.000005,0.00005,0.0005,0.005 --save_probes True --save_path /home/local/data/ms/honest_llama_data --fast_mode True --use_best_val_t True  --seed_list 42,101,2650 --best_using_auc True --skip_train True --no_batch_sampling True --top_k_list 1 --dist_metric mahalanobis_centers --supcon_temp_list 0.1,0.3,0.5,0.7,1.0,2.0 --pca_dims_list 0.9,0.8,0.7 --which_checkpoint bestusinglast

################################# transformer n*aug 1 layer : supcon* ##########################
# python get_activations_and_probe_transformer.py alpaca_7B trivia_qa --train_file_name trivia_qa_sampledplus_responses_train5000 --test_file_name trivia_qa_greedy_responses_validation1800 --train_labels_file_name trivia_qa_sampledplus_responses_labels_train5000 --test_labels_file_name trivia_qa_greedy_responses_labels_validation1800 --len_dataset 55000 --num_folds 1 --using_act layer --token answer_last --method transformer_supconv2_wp_kmeans_hallu_pos --bs 275 --epochs 500 --lr_list 0.000005,0.00005,0.0005,0.005 --save_probes True --save_path /home/local/data/ms/honest_llama_data --fast_mode True  --use_best_val_t True  --seed_list 42,101,2650 --best_using_auc True --skip_train True --no_batch_sampling True --top_k_list 1 --dist_metric mahalanobis_centers --supcon_temp_list 0.1,0.3,0.5,0.7,1.0,2.0 --which_checkpoint bestusinglast

################################# transformer n*aug 1 layer : supcon+* ##########################
# python get_activations_and_probe_transformer.py alpaca_7B trivia_qa --train_file_name trivia_qa_sampledplus_responses_train5000 --test_file_name trivia_qa_greedy_responses_validation1800 --train_labels_file_name trivia_qa_sampledplus_responses_labels_train5000 --test_labels_file_name trivia_qa_greedy_responses_labels_validation1800 --len_dataset 55000 --num_folds 1 --using_act layer --token answer_last --method transformer_supconv2_pos_wp_knn_hallu_pos --bs 275 --epochs 500 --lr_list 0.000005,0.00005,0.0005,0.005 --save_probes True --save_path /home/local/data/ms/honest_llama_data --fast_mode True  --plot_name transformer_supconv2_pos_wp-n*aug-b --tag main-transformer-contrast-5kbestauc-knn --use_best_val_t True  --seed_list 42,101,2650 --best_using_auc True --skip_train True --no_batch_sampling True
python get_activations_and_probe_transformer.py alpaca_7B trivia_qa --train_file_name trivia_qa_sampledplus_responses_train5000 --test_file_name trivia_qa_greedy_responses_validation1800 --train_labels_file_name trivia_qa_sampledplus_responses_labels_train5000 --test_labels_file_name trivia_qa_greedy_responses_labels_validation1800 --len_dataset 55000 --num_folds 1 --using_act layer --token answer_last --method transformer_supconv2_pos_wp_kmeans_hallu_pos --bs 352 --epochs 500 --lr_list 0.00005,0.000005,0.00005 --save_probes True --save_path /home/local/data/ms/honest_llama_data --fast_mode True --use_best_val_t True  --seed_list 42,101,2650 --best_using_auc True --skip_train True --no_batch_sampling True --top_k_list 1 --dist_metric mahalanobis_centers --skip_hypsearch True --supcon_temp_list 0.7,2.0,0.7
python get_activations_and_probe_transformer.py alpaca_7B trivia_qa --train_file_name trivia_qa_sampledplus_responses_train5000 --test_file_name trivia_qa_greedy_responses_validation1800 --train_labels_file_name trivia_qa_sampledplus_responses_labels_train5000 --test_labels_file_name trivia_qa_greedy_responses_labels_validation1800 --len_dataset 55000 --num_folds 1 --using_act layer --token answer_last --method transformer_supconv2_pos_wp_kmeans_hallu_pos --bs 352 --epochs 500 --lr_list 0.00005,0.000005,0.00005 --save_probes True --save_path /home/local/data/ms/honest_llama_data --fast_mode True --use_best_val_t True  --seed_list 42,101,2650 --best_using_auc True --skip_train True --no_batch_sampling True --top_k_list 1 --dist_metric mahalanobis_centers --skip_hypsearch True --supcon_temp_list 0.7,2.0,0.7 --pca_dims_list 30,15,10
python get_activations_and_probe_transformer.py alpaca_7B trivia_qa --train_file_name trivia_qa_sampledplus_responses_train5000 --test_file_name trivia_qa_greedy_responses_validation1800 --train_labels_file_name trivia_qa_sampledplus_responses_labels_train5000 --test_labels_file_name trivia_qa_greedy_responses_labels_validation1800 --len_dataset 55000 --num_folds 1 --using_act layer --token answer_last --method transformer_supconv2_pos_wp_kmeans_hallu_pos --bs 352 --epochs 500 --lr_list 0.000005,0.00005,0.0005 --save_probes True --save_path /home/local/data/ms/honest_llama_data --fast_mode True --use_best_val_t True  --seed_list 42,101,2650 --best_using_auc True --skip_train True --no_batch_sampling True --top_k_list 1 --dist_metric mahalanobis_centers --supcon_temp_list 0.1,0.3,0.5,0.7,1.0,2.0 --pca_dims_list 0.9,0.8,0.7 --which_checkpoint bestusinglast