# python get_activations_and_probe.py alpaca_7B nq_open --train_file_name nq_open_greedy_responses_train5000 --train_labels_file_name nq_open_greedy_responses_labels_train5000 --test_file_name nq_open_greedy_responses_1800 --test_labels_file_name nq_open_greedy_responses_labels_1800 --len_dataset 5000 --num_folds 1 --using_act mlp --token answer_last --method individual_linear --bs 32 --epochs 5 --use_class_wgt True --save_probes True --device 0 --save_path ~/Desktop/honest_llama_data
# python get_activations_and_probe.py alpaca_7B nq_open --train_file_name nq_open_greedy_responses_train5000 --train_labels_file_name nq_open_greedy_responses_labels_train5000 --test_file_name nq_open_greedy_responses_1800 --test_labels_file_name nq_open_greedy_responses_labels_1800 --len_dataset 5000 --num_folds 1 --using_act mlp --token prompt_last --method individual_linear --bs 32 --epochs 5 --use_class_wgt True --save_probes True --device 0 --save_path ~/Desktop/honest_llama_data
# python get_activations_and_probe.py alpaca_7B nq_open --train_file_name nq_open_greedy_responses_train5000 --train_labels_file_name nq_open_greedy_responses_labels_train5000 --test_file_name nq_open_greedy_responses_1800 --test_labels_file_name nq_open_greedy_responses_labels_1800 --len_dataset 5000 --num_folds 1 --using_act mlp --token maxpool_all --method individual_linear --bs 32 --epochs 5 --use_class_wgt True --save_probes True --device 0 --save_path ~/Desktop/honest_llama_data
# python get_activations_and_probe.py alpaca_7B nq_open --train_file_name nq_open_greedy_responses_train5000 --train_labels_file_name nq_open_greedy_responses_labels_train5000 --test_file_name nq_open_greedy_responses_1800 --test_labels_file_name nq_open_greedy_responses_labels_1800 --len_dataset 5000 --num_folds 1 --using_act mlp_l1 --token answer_last --method individual_linear --bs 32 --epochs 5 --use_class_wgt True --save_probes True --device 0 --save_path ~/Desktop/honest_llama_data

# without cls_wgt
# python get_activations_and_probe.py alpaca_7B nq_open --train_file_name nq_open_greedy_responses_train5000 --train_labels_file_name nq_open_greedy_responses_labels_train5000 --test_file_name nq_open_greedy_responses_1800 --test_labels_file_name nq_open_greedy_responses_labels_1800 --len_dataset 5000 --num_folds 1 --using_act mlp --token answer_last --method individual_linear --bs 32 --epochs 5 --save_probes True --device 0 --save_path ~/Desktop/honest_llama_data
# python get_activations_and_probe.py alpaca_7B nq_open --train_file_name nq_open_greedy_responses_train5000 --train_labels_file_name nq_open_greedy_responses_labels_train5000 --test_file_name nq_open_greedy_responses_1800 --test_labels_file_name nq_open_greedy_responses_labels_1800 --len_dataset 5000 --num_folds 1 --using_act mlp --token prompt_last --method individual_linear --bs 32 --epochs 5 --save_probes True --device 0 --save_path ~/Desktop/honest_llama_data
# python get_activations_and_probe.py alpaca_7B nq_open --train_file_name nq_open_greedy_responses_train5000 --train_labels_file_name nq_open_greedy_responses_labels_train5000 --test_file_name nq_open_greedy_responses_1800 --test_labels_file_name nq_open_greedy_responses_labels_1800 --len_dataset 5000 --num_folds 1 --using_act mlp_l1 --token answer_last --method individual_linear --bs 32 --epochs 5 --save_probes True --device 0 --save_path ~/Desktop/honest_llama_data

##########################################################################################################################
# bs=64, epochs=10 (ES), lr=0.05 (Adam+schr), cls_wgt=False, train on 5000 (train), test on 1800 (val)
# python get_activations_and_probe.py alpaca_7B nq_open --train_file_name nq_open_greedy_responses_train5000 --train_labels_file_name nq_open_greedy_responses_labels_train5000 --test_file_name nq_open_greedy_responses_1800 --test_labels_file_name nq_open_greedy_responses_labels_1800 --len_dataset 5000 --num_folds 1 --using_act mlp --token answer_last --method individual_linear --bs 64 --epochs 10 --lr 0.05 --optimizer Adam_w_lr_sch --save_probes True --device 0 --save_path ~/Desktop/honest_llama_data
