# python get_activations_and_probe.py llama_7B nq_open --train_file_name nq_open_greedy_responses_1800 --train_labels_file_name nq_open_greedy_responses_labels_1800 --test_file_name nq_open_greedy_responses_1800 --test_labels_file_name nq_open_greedy_responses_labels_1800 --len_dataset 1800 --num_folds 1 --using_act mlp --token tagged_tokens --method individual_linear --device 0 --save_path ~/Desktop/honest_llama_data;
# python get_activations_and_probe.py llama_7B nq_open --train_file_name nq_open_greedy_responses_1800 --train_labels_file_name nq_open_greedy_responses_labels_1800 --test_file_name nq_open_greedy_responses_1800 --test_labels_file_name nq_open_greedy_responses_labels_1800 --len_dataset 1800 --num_folds 1 --using_act mlp --token all --method individual_linear --device 0 --save_path ~/Desktop/honest_llama_data;
# python get_activations_and_probe.py llama_7B nq_open --train_file_name nq_open_greedy_responses_1800 --train_labels_file_name nq_open_greedy_responses_labels_1800 --test_file_name nq_open_greedy_responses_1800 --test_labels_file_name nq_open_greedy_responses_labels_1800 --len_dataset 1800 --num_folds 1 --using_act mlp --token answer_last --method individual_linear --device 0 --save_path ~/Desktop/honest_llama_data;
# python get_activations_and_probe.py llama_7B nq_open --train_file_name nq_open_greedy_responses_1800 --train_labels_file_name nq_open_greedy_responses_labels_1800 --test_file_name nq_open_greedy_responses_1800 --test_labels_file_name nq_open_greedy_responses_labels_1800 --len_dataset 1800 --num_folds 1 --using_act mlp --token answer_last --method individual_linear --bs 4 --epochs 3 --device 0 --save_path ~/Desktop/honest_llama_data;
# python get_activations_and_probe.py llama_7B nq_open --train_file_name nq_open_greedy_responses_1800 --train_labels_file_name nq_open_greedy_responses_labels_1800 --test_file_name nq_open_greedy_responses_1800 --test_labels_file_name nq_open_greedy_responses_labels_1800 --len_dataset 1800 --num_folds 1 --using_act mlp --token answer_last --method individual_linear --bs 8 --epochs 3 --device 0 --save_path ~/Desktop/honest_llama_data;
# python get_activations_and_probe.py llama_7B nq_open --train_file_name nq_open_greedy_responses_1800 --train_labels_file_name nq_open_greedy_responses_labels_1800 --test_file_name nq_open_greedy_responses_1800 --test_labels_file_name nq_open_greedy_responses_labels_1800 --len_dataset 1800 --num_folds 1 --using_act mlp --token answer_last --method individual_linear --bs 16 --epochs 3 --device 0 --save_path ~/Desktop/honest_llama_data;
python get_activations_and_probe.py llama_7B nq_open --train_file_name nq_open_greedy_responses_1800 --train_labels_file_name nq_open_greedy_responses_labels_1800 --test_file_name nq_open_greedy_responses_1800 --test_labels_file_name nq_open_greedy_responses_labels_1800 --len_dataset 1800 --num_folds 1 --using_act mlp --token answer_last --method individual_linear --bs 32 --epochs 3 --device 0 --save_path ~/Desktop/honest_llama_data;

# bs=4, epochs=3
# python get_activations_and_probe.py llama_7B nq_open --train_file_name nq_open_greedy_responses_1800 --train_labels_file_name nq_open_greedy_responses_labels_1800 --test_file_name nq_open_greedy_responses_1800 --test_labels_file_name nq_open_greedy_responses_labels_1800 --len_dataset 1800 --num_folds 1 --using_act mlp_l1 --token tagged_tokens --method individual_linear --device 0 --save_path ~/Desktop/honest_llama_data;
# python get_activations_and_probe.py llama_7B nq_open --train_file_name nq_open_greedy_responses_1800 --train_labels_file_name nq_open_greedy_responses_labels_1800 --test_file_name nq_open_greedy_responses_1800 --test_labels_file_name nq_open_greedy_responses_labels_1800 --len_dataset 1800 --num_folds 1 --using_act mlp_l1 --token all --method individual_linear --device 0 --save_path ~/Desktop/honest_llama_data;
# python get_activations_and_probe.py llama_7B nq_open --train_file_name nq_open_greedy_responses_1800 --train_labels_file_name nq_open_greedy_responses_labels_1800 --test_file_name nq_open_greedy_responses_1800 --test_labels_file_name nq_open_greedy_responses_labels_1800 --len_dataset 1800 --num_folds 1 --using_act mlp_l1 --token maxpool_all --method individual_linear --device 0 --save_path ~/Desktop/honest_llama_data;
# python get_activations_and_probe.py llama_7B nq_open --train_file_name nq_open_greedy_responses_1800 --train_labels_file_name nq_open_greedy_responses_labels_1800 --test_file_name nq_open_greedy_responses_1800 --test_labels_file_name nq_open_greedy_responses_labels_1800 --len_dataset 1800 --num_folds 1 --using_act mlp_l1 --token answer_last --method individual_linear --device 0 --save_path ~/Desktop/honest_llama_data;
# python get_activations_and_probe.py llama_7B nq_open --train_file_name nq_open_greedy_responses_1800 --train_labels_file_name nq_open_greedy_responses_labels_1800 --test_file_name nq_open_greedy_responses_1800 --test_labels_file_name nq_open_greedy_responses_labels_1800 --len_dataset 1800 --num_folds 1 --using_act mlp_l1 --token prompt_last --method individual_linear --device 0 --save_path ~/Desktop/honest_llama_data;

# python get_activations_and_probe.py alpaca_7B nq_open --train_file_name nq_open_greedy_responses_1800 --train_labels_file_name nq_open_greedy_responses_labels_1800 --test_file_name nq_open_greedy_responses_1800 --test_labels_file_name nq_open_greedy_responses_labels_1800 --len_dataset 1800 --num_folds 1 --using_act mlp --token all --method individual_linear --device 0 --save_path ~/Desktop/honest_llama_data;
# python get_activations_and_probe.py alpaca_7B nq_open --train_file_name nq_open_greedy_responses_1800 --train_labels_file_name nq_open_greedy_responses_labels_1800 --test_file_name nq_open_greedy_responses_1800 --test_labels_file_name nq_open_greedy_responses_labels_1800 --len_dataset 1800 --num_folds 1 --using_act mlp --token maxpool_all --method individual_linear --device 0 --save_path ~/Desktop/honest_llama_data;
# python get_activations_and_probe.py alpaca_7B nq_open --train_file_name nq_open_greedy_responses_1800 --train_labels_file_name nq_open_greedy_responses_labels_1800 --test_file_name nq_open_greedy_responses_1800 --test_labels_file_name nq_open_greedy_responses_labels_1800 --len_dataset 1800 --num_folds 1 --using_act mlp --token answer_last --method individual_linear --device 0 --save_path ~/Desktop/honest_llama_data;
# python get_activations_and_probe.py alpaca_7B nq_open --train_file_name nq_open_greedy_responses_1800 --train_labels_file_name nq_open_greedy_responses_labels_1800 --test_file_name nq_open_greedy_responses_1800 --test_labels_file_name nq_open_greedy_responses_labels_1800 --len_dataset 1800 --num_folds 1 --using_act mlp --token prompt_last --method individual_linear --device 0 --save_path ~/Desktop/honest_llama_data;

# python get_activations_and_probe.py alpaca_7B nq_open --train_file_name nq_open_greedy_responses_1800 --train_labels_file_name nq_open_greedy_responses_labels_1800 --test_file_name nq_open_greedy_responses_1800 --test_labels_file_name nq_open_greedy_responses_labels_1800 --len_dataset 1800 --num_folds 1 --using_act mlp_l1 --token all --method individual_linear --device 0 --save_path ~/Desktop/honest_llama_data;
# python get_activations_and_probe.py alpaca_7B nq_open --train_file_name nq_open_greedy_responses_1800 --train_labels_file_name nq_open_greedy_responses_labels_1800 --test_file_name nq_open_greedy_responses_1800 --test_labels_file_name nq_open_greedy_responses_labels_1800 --len_dataset 1800 --num_folds 1 --using_act mlp_l1 --token maxpool_all --method individual_linear --device 0 --save_path ~/Desktop/honest_llama_data;
# python get_activations_and_probe.py alpaca_7B nq_open --train_file_name nq_open_greedy_responses_1800 --train_labels_file_name nq_open_greedy_responses_labels_1800 --test_file_name nq_open_greedy_responses_1800 --test_labels_file_name nq_open_greedy_responses_labels_1800 --len_dataset 1800 --num_folds 1 --using_act mlp_l1 --token answer_last --method individual_linear --device 0 --save_path ~/Desktop/honest_llama_data;
# python get_activations_and_probe.py alpaca_7B nq_open --train_file_name nq_open_greedy_responses_1800 --train_labels_file_name nq_open_greedy_responses_labels_1800 --test_file_name nq_open_greedy_responses_1800 --test_labels_file_name nq_open_greedy_responses_labels_1800 --len_dataset 1800 --num_folds 1 --using_act mlp_l1 --token prompt_last --method individual_linear --device 0 --save_path ~/Desktop/honest_llama_data;

