# python get_activations_and_probe.py llama_7B nq_open --train_file_name nq_open_greedy_responses_1800 --train_labels_file_name nq_open_greedy_responses_labels_1800 --test_file_name nq_open_greedy_responses_1800 --test_labels_file_name nq_open_greedy_responses_labels_1800 --len_dataset 1800 --num_folds 1 --using_act mlp --token tagged_tokens --method individual_linear --device 0 --save_path ~/Desktop/honest_llama_data;
# python get_activations_and_probe.py llama_7B nq_open --train_file_name nq_open_greedy_responses_1800 --train_labels_file_name nq_open_greedy_responses_labels_1800 --test_file_name nq_open_greedy_responses_1800 --test_labels_file_name nq_open_greedy_responses_labels_1800 --len_dataset 1800 --num_folds 1 --using_act mlp --token all --method individual_linear --device 0 --save_path ~/Desktop/honest_llama_data;
# python get_activations_and_probe.py llama_7B nq_open --train_file_name nq_open_greedy_responses_1800 --train_labels_file_name nq_open_greedy_responses_labels_1800 --test_file_name nq_open_greedy_responses_1800 --test_labels_file_name nq_open_greedy_responses_labels_1800 --len_dataset 1800 --num_folds 1 --using_act mlp --token answer_last --method individual_linear --device 0 --save_path ~/Desktop/honest_llama_data;
# python get_activations_and_probe.py llama_7B nq_open --train_file_name nq_open_greedy_responses_1800 --train_labels_file_name nq_open_greedy_responses_labels_1800 --test_file_name nq_open_greedy_responses_1800 --test_labels_file_name nq_open_greedy_responses_labels_1800 --len_dataset 1800 --num_folds 1 --using_act mlp --token answer_last --method individual_linear --bs 4 --epochs 3 --device 0 --save_path ~/Desktop/honest_llama_data;
# python get_activations_and_probe.py llama_7B nq_open --train_file_name nq_open_greedy_responses_1800 --train_labels_file_name nq_open_greedy_responses_labels_1800 --test_file_name nq_open_greedy_responses_1800 --test_labels_file_name nq_open_greedy_responses_labels_1800 --len_dataset 1800 --num_folds 1 --using_act mlp --token answer_last --method individual_linear --bs 8 --epochs 3 --device 0 --save_path ~/Desktop/honest_llama_data;
# python get_activations_and_probe.py llama_7B nq_open --train_file_name nq_open_greedy_responses_1800 --train_labels_file_name nq_open_greedy_responses_labels_1800 --test_file_name nq_open_greedy_responses_1800 --test_labels_file_name nq_open_greedy_responses_labels_1800 --len_dataset 1800 --num_folds 1 --using_act mlp --token answer_last --method individual_linear --bs 16 --epochs 3 --device 0 --save_path ~/Desktop/honest_llama_data;
# python get_activations_and_probe.py llama_7B nq_open --train_file_name nq_open_greedy_responses_1800 --train_labels_file_name nq_open_greedy_responses_labels_1800 --test_file_name nq_open_greedy_responses_1800 --test_labels_file_name nq_open_greedy_responses_labels_1800 --len_dataset 1800 --num_folds 1 --using_act mlp --token answer_last --method individual_linear --bs 32 --epochs 3 --device 0 --save_path ~/Desktop/honest_llama_data;
# python get_activations_and_probe.py llama_7B nq_open --train_file_name nq_open_greedy_responses_1800 --train_labels_file_name nq_open_greedy_responses_labels_1800 --test_file_name nq_open_greedy_responses_1800 --test_labels_file_name nq_open_greedy_responses_labels_1800 --len_dataset 1800 --num_folds 1 --using_act mlp --token answer_last --method individual_linear --bs 32 --epochs 5 --device 0 --save_path ~/Desktop/honest_llama_data;
# python get_activations_and_probe.py llama_7B nq_open --train_file_name nq_open_greedy_responses_1800 --train_labels_file_name nq_open_greedy_responses_labels_1800 --test_file_name nq_open_greedy_responses_1800 --test_labels_file_name nq_open_greedy_responses_labels_1800 --len_dataset 1800 --num_folds 1 --using_act mlp --token answer_last --method individual_linear --bs 32 --epochs 1 --device 0 --save_path ~/Desktop/honest_llama_data;
# python get_activations_and_probe.py llama_7B nq_open --train_file_name nq_open_greedy_responses_1800 --train_labels_file_name nq_open_greedy_responses_labels_1800 --test_file_name nq_open_greedy_responses_1800 --test_labels_file_name nq_open_greedy_responses_labels_1800 --len_dataset 1800 --num_folds 1 --using_act mlp --token answer_last --method individual_linear --bs 32 --epochs 1 --lr 0.005 --device 0 --save_path ~/Desktop/honest_llama_data;

# bs=4, epochs=3
# python get_activations_and_probe.py llama_7B nq_open --train_file_name nq_open_greedy_responses_1800 --train_labels_file_name nq_open_greedy_responses_labels_1800 --test_file_name nq_open_greedy_responses_1800 --test_labels_file_name nq_open_greedy_responses_labels_1800 --len_dataset 1800 --num_folds 1 --using_act mlp_l1 --token tagged_tokens --method individual_linear --device 0 --save_path ~/Desktop/honest_llama_data;
# python get_activations_and_probe.py llama_7B nq_open --train_file_name nq_open_greedy_responses_1800 --train_labels_file_name nq_open_greedy_responses_labels_1800 --test_file_name nq_open_greedy_responses_1800 --test_labels_file_name nq_open_greedy_responses_labels_1800 --len_dataset 1800 --num_folds 1 --using_act mlp_l1 --token all --method individual_linear --device 0 --save_path ~/Desktop/honest_llama_data;
# python get_activations_and_probe.py llama_7B nq_open --train_file_name nq_open_greedy_responses_1800 --train_labels_file_name nq_open_greedy_responses_labels_1800 --test_file_name nq_open_greedy_responses_1800 --test_labels_file_name nq_open_greedy_responses_labels_1800 --len_dataset 1800 --num_folds 1 --using_act mlp_l1 --token maxpool_all --method individual_linear --device 0 --save_path ~/Desktop/honest_llama_data;
# python get_activations_and_probe.py llama_7B nq_open --train_file_name nq_open_greedy_responses_1800 --train_labels_file_name nq_open_greedy_responses_labels_1800 --test_file_name nq_open_greedy_responses_1800 --test_labels_file_name nq_open_greedy_responses_labels_1800 --len_dataset 1800 --num_folds 1 --using_act mlp_l1 --token answer_last --method individual_linear --device 0 --save_path ~/Desktop/honest_llama_data;
# python get_activations_and_probe.py llama_7B nq_open --train_file_name nq_open_greedy_responses_1800 --train_labels_file_name nq_open_greedy_responses_labels_1800 --test_file_name nq_open_greedy_responses_1800 --test_labels_file_name nq_open_greedy_responses_labels_1800 --len_dataset 1800 --num_folds 1 --using_act mlp_l1 --token prompt_last --method individual_linear --device 0 --save_path ~/Desktop/honest_llama_data;

# python get_activations_and_probe.py alpaca_7B nq_open --train_file_name nq_open_greedy_responses_1800 --train_labels_file_name nq_open_greedy_responses_labels_1800 --test_file_name nq_open_greedy_responses_1800 --test_labels_file_name nq_open_greedy_responses_labels_1800 --len_dataset 1800 --num_folds 1 --using_act mlp --token all --method individual_linear --device 0 --save_path ~/Desktop/honest_llama_data;
# python get_activations_and_probe.py alpaca_7B nq_open --train_file_name nq_open_greedy_responses_1800 --train_labels_file_name nq_open_greedy_responses_labels_1800 --test_file_name nq_open_greedy_responses_1800 --test_labels_file_name nq_open_greedy_responses_labels_1800 --len_dataset 1800 --num_folds 1 --using_act mlp --token maxpool_all --method individual_linear --device 0 --save_path ~/Desktop/honest_llama_data;
# python get_activations_and_probe.py alpaca_7B nq_open --train_file_name nq_open_greedy_responses_1800 --train_labels_file_name nq_open_greedy_responses_labels_1800 --test_file_name nq_open_greedy_responses_1800 --test_labels_file_name nq_open_greedy_responses_labels_1800 --len_dataset 1800 --num_folds 1 --using_act mlp --token answer_last --method individual_linear --device 0 --save_path ~/Desktop/honest_llama_data;
# python get_activations_and_probe.py alpaca_7B nq_open --train_file_name nq_open_greedy_responses_1800 --train_labels_file_name nq_open_greedy_responses_labels_1800 --test_file_name nq_open_greedy_responses_1800 --test_labels_file_name nq_open_greedy_responses_labels_1800 --len_dataset 1800 --num_folds 1 --using_act mlp --token prompt_last --method individual_linear --device 0 --save_path ~/Desktop/honest_llama_data;

# python get_activations_and_probe.py alpaca_7B nq_open --train_file_name nq_open_greedy_responses_1800 --train_labels_file_name nq_open_greedy_responses_labels_1800 --test_file_name nq_open_greedy_responses_1800 --test_labels_file_name nq_open_greedy_responses_labels_1800 --len_dataset 1800 --num_folds 1 --using_act mlp_l1 --token all --method individual_linear --device 0 --save_path ~/Desktop/honest_llama_data;
# python get_activations_and_probe.py alpaca_7B nq_open --train_file_name nq_open_greedy_responses_1800 --train_labels_file_name nq_open_greedy_responses_labels_1800 --test_file_name nq_open_greedy_responses_1800 --test_labels_file_name nq_open_greedy_responses_labels_1800 --len_dataset 1800 --num_folds 1 --using_act mlp_l1 --token maxpool_all --method individual_linear --device 0 --save_path ~/Desktop/honest_llama_data;
# python get_activations_and_probe.py alpaca_7B nq_open --train_file_name nq_open_greedy_responses_1800 --train_labels_file_name nq_open_greedy_responses_labels_1800 --test_file_name nq_open_greedy_responses_1800 --test_labels_file_name nq_open_greedy_responses_labels_1800 --len_dataset 1800 --num_folds 1 --using_act mlp_l1 --token answer_last --method individual_linear --device 0 --save_path ~/Desktop/honest_llama_data;
# python get_activations_and_probe.py alpaca_7B nq_open --train_file_name nq_open_greedy_responses_1800 --train_labels_file_name nq_open_greedy_responses_labels_1800 --test_file_name nq_open_greedy_responses_1800 --test_labels_file_name nq_open_greedy_responses_labels_1800 --len_dataset 1800 --num_folds 1 --using_act mlp_l1 --token prompt_last --method individual_linear --device 0 --save_path ~/Desktop/honest_llama_data;

# bs=32, epochs=5
# python get_activations_and_probe.py llama_7B nq_open --train_file_name nq_open_greedy_responses_1800 --train_labels_file_name nq_open_greedy_responses_labels_1800 --test_file_name nq_open_greedy_responses_1800 --test_labels_file_name nq_open_greedy_responses_labels_1800 --len_dataset 1800 --num_folds 1 --using_act mlp_l1 --token maxpool_all --method individual_linear --bs 32 --epochs 5 --device 0 --save_path ~/Desktop/honest_llama_data;
# python get_activations_and_probe.py llama_7B nq_open --train_file_name nq_open_greedy_responses_1800 --train_labels_file_name nq_open_greedy_responses_labels_1800 --test_file_name nq_open_greedy_responses_1800 --test_labels_file_name nq_open_greedy_responses_labels_1800 --len_dataset 1800 --num_folds 1 --using_act mlp_l1 --token answer_last --method individual_linear --bs 32 --epochs 5 --device 0 --save_path ~/Desktop/honest_llama_data;
# python get_activations_and_probe.py llama_7B nq_open --train_file_name nq_open_greedy_responses_1800 --train_labels_file_name nq_open_greedy_responses_labels_1800 --test_file_name nq_open_greedy_responses_1800 --test_labels_file_name nq_open_greedy_responses_labels_1800 --len_dataset 1800 --num_folds 1 --using_act mlp_l1 --token prompt_last --method individual_linear --bs 32 --epochs 5 --device 0 --save_path ~/Desktop/honest_llama_data;

# python get_activations_and_probe.py alpaca_7B nq_open --train_file_name nq_open_greedy_responses_1800 --train_labels_file_name nq_open_greedy_responses_labels_1800 --test_file_name nq_open_greedy_responses_1800 --test_labels_file_name nq_open_greedy_responses_labels_1800 --len_dataset 1800 --num_folds 1 --using_act mlp_l1 --token maxpool_all --method individual_linear --bs 32 --epochs 5 --device 0 --save_path ~/Desktop/honest_llama_data;
# python get_activations_and_probe.py alpaca_7B nq_open --train_file_name nq_open_greedy_responses_1800 --train_labels_file_name nq_open_greedy_responses_labels_1800 --test_file_name nq_open_greedy_responses_1800 --test_labels_file_name nq_open_greedy_responses_labels_1800 --len_dataset 1800 --num_folds 1 --using_act mlp_l1 --token answer_last --method individual_linear --bs 32 --epochs 5 --device 0 --save_path ~/Desktop/honest_llama_data;
# python get_activations_and_probe.py alpaca_7B nq_open --train_file_name nq_open_greedy_responses_1800 --train_labels_file_name nq_open_greedy_responses_labels_1800 --test_file_name nq_open_greedy_responses_1800 --test_labels_file_name nq_open_greedy_responses_labels_1800 --len_dataset 1800 --num_folds 1 --using_act mlp_l1 --token prompt_last --method individual_linear --bs 32 --epochs 5 --device 0 --save_path ~/Desktop/honest_llama_data;

# bs=32, epochs=3
# python get_activations_and_probe.py llama_7B nq_open --train_file_name nq_open_greedy_responses_1800 --train_labels_file_name nq_open_greedy_responses_labels_1800 --test_file_name nq_open_greedy_responses_1800 --test_labels_file_name nq_open_greedy_responses_labels_1800 --len_dataset 1800 --num_folds 1 --using_act mlp --token maxpool_all --method individual_linear --bs 32 --epochs 3 --save_probes True --device 0 --save_path ~/Desktop/honest_llama_data;
# python get_activations_and_probe.py llama_7B nq_open --train_file_name nq_open_greedy_responses_1800 --train_labels_file_name nq_open_greedy_responses_labels_1800 --test_file_name nq_open_greedy_responses_1800 --test_labels_file_name nq_open_greedy_responses_labels_1800 --len_dataset 1800 --num_folds 1 --using_act mlp --token prompt_last --method individual_linear --bs 32 --epochs 3 --save_probes True --device 0 --save_path ~/Desktop/honest_llama_data;
# python get_activations_and_probe.py llama_7B nq_open --train_file_name nq_open_greedy_responses_1800 --train_labels_file_name nq_open_greedy_responses_labels_1800 --test_file_name nq_open_greedy_responses_1800 --test_labels_file_name nq_open_greedy_responses_labels_1800 --len_dataset 1800 --num_folds 1 --using_act mlp_l1 --token maxpool_all --method individual_linear --bs 32 --epochs 3 --save_probes True --device 0 --save_path ~/Desktop/honest_llama_data;
# python get_activations_and_probe.py llama_7B nq_open --train_file_name nq_open_greedy_responses_1800 --train_labels_file_name nq_open_greedy_responses_labels_1800 --test_file_name nq_open_greedy_responses_1800 --test_labels_file_name nq_open_greedy_responses_labels_1800 --len_dataset 1800 --num_folds 1 --using_act mlp_l1 --token answer_last --method individual_linear --bs 32 --epochs 3 --save_probes True --device 0 --save_path ~/Desktop/honest_llama_data;
# python get_activations_and_probe.py llama_7B nq_open --train_file_name nq_open_greedy_responses_1800 --train_labels_file_name nq_open_greedy_responses_labels_1800 --test_file_name nq_open_greedy_responses_1800 --test_labels_file_name nq_open_greedy_responses_labels_1800 --len_dataset 1800 --num_folds 1 --using_act mlp_l1 --token prompt_last --method individual_linear --bs 32 --epochs 3 --save_probes True --device 0 --save_path ~/Desktop/honest_llama_data;

# python get_activations_and_probe.py alpaca_7B nq_open --train_file_name nq_open_greedy_responses_1800 --train_labels_file_name nq_open_greedy_responses_labels_1800 --test_file_name nq_open_greedy_responses_1800 --test_labels_file_name nq_open_greedy_responses_labels_1800 --len_dataset 1800 --num_folds 1 --using_act mlp_l1 --token maxpool_all --method individual_linear --bs 32 --epochs 3 --save_probes True --device 0 --save_path ~/Desktop/honest_llama_data;
# python get_activations_and_probe.py alpaca_7B nq_open --train_file_name nq_open_greedy_responses_1800 --train_labels_file_name nq_open_greedy_responses_labels_1800 --test_file_name nq_open_greedy_responses_1800 --test_labels_file_name nq_open_greedy_responses_labels_1800 --len_dataset 1800 --num_folds 1 --using_act mlp_l1 --token answer_last --method individual_linear --bs 32 --epochs 3 --save_probes True --device 0 --save_path ~/Desktop/honest_llama_data;
# python get_activations_and_probe.py alpaca_7B nq_open --train_file_name nq_open_greedy_responses_1800 --train_labels_file_name nq_open_greedy_responses_labels_1800 --test_file_name nq_open_greedy_responses_1800 --test_labels_file_name nq_open_greedy_responses_labels_1800 --len_dataset 1800 --num_folds 1 --using_act mlp_l1 --token prompt_last --method individual_linear --bs 32 --epochs 3 --save_probes True --device 0 --save_path ~/Desktop/honest_llama_data;

######################################
# (echo 1000 > /proc/self/oom_score_adj && exec /usr/bin/blah)
##########################################################################################################################
# Bkp: lr decay = 0.9
# lr decay = 0.75
# bs=32, epochs=5, lr=0.05(default), cls_wgt=True, train on 1500 (train), test on 1800 (val)
# python get_activations_and_probe.py alpaca_7B nq_open --train_file_name nq_open_greedy_responses_train5000 --train_labels_file_name nq_open_greedy_responses_labels_train5000 --test_file_name nq_open_greedy_responses_1800 --test_labels_file_name nq_open_greedy_responses_labels_1800 --len_dataset 1500 --num_folds 1 --using_act mlp --token answer_last --method individual_linear --bs 32 --epochs 5 --save_probes True --device 0 --save_path ~/Desktop/honest_llama_data
# python get_activations_and_probe.py alpaca_7B nq_open --train_file_name nq_open_greedy_responses_train5000 --train_labels_file_name nq_open_greedy_responses_labels_train5000 --test_file_name nq_open_greedy_responses_1800 --test_labels_file_name nq_open_greedy_responses_labels_1800 --len_dataset 1500 --num_folds 1 --using_act mlp --token answer_last --method individual_linear --bs 32 --epochs 5 --use_class_wgt True --save_probes True --device 0 --save_path ~/Desktop/honest_llama_data
# python get_activations_and_probe.py alpaca_7B nq_open --train_file_name nq_open_greedy_responses_train5000 --train_labels_file_name nq_open_greedy_responses_labels_train5000 --test_file_name nq_open_greedy_responses_1800 --test_labels_file_name nq_open_greedy_responses_labels_1800 --len_dataset 1500 --num_folds 1 --using_act mlp --token prompt_last --method individual_linear --bs 32 --epochs 5 --use_class_wgt True --save_probes True --device 0 --save_path ~/Desktop/honest_llama_data
# python get_activations_and_probe.py alpaca_7B nq_open --train_file_name nq_open_greedy_responses_train5000 --train_labels_file_name nq_open_greedy_responses_labels_train5000 --test_file_name nq_open_greedy_responses_1800 --test_labels_file_name nq_open_greedy_responses_labels_1800 --len_dataset 1500 --num_folds 1 --using_act mlp --token maxpool_all --method individual_linear --bs 32 --epochs 5 --use_class_wgt True --save_probes True --device 0 --save_path ~/Desktop/honest_llama_data
# python get_activations_and_probe.py alpaca_7B nq_open --train_file_name nq_open_greedy_responses_train5000 --train_labels_file_name nq_open_greedy_responses_labels_train5000 --test_file_name nq_open_greedy_responses_1800 --test_labels_file_name nq_open_greedy_responses_labels_1800 --len_dataset 1500 --num_folds 1 --using_act mlp_l1 --token answer_last --method individual_linear --bs 32 --epochs 5 --use_class_wgt True --save_probes True --device 0 --save_path ~/Desktop/honest_llama_data
# python get_activations_and_probe.py alpaca_7B nq_open --train_file_name nq_open_greedy_responses_train5000 --train_labels_file_name nq_open_greedy_responses_labels_train5000 --test_file_name nq_open_greedy_responses_1800 --test_labels_file_name nq_open_greedy_responses_labels_1800 --len_dataset 1500 --num_folds 1 --using_act mlp_l1 --token prompt_last --method individual_linear --bs 32 --epochs 5 --use_class_wgt True --save_probes True --device 0 --save_path ~/Desktop/honest_llama_data
# python get_activations_and_probe.py alpaca_7B nq_open --train_file_name nq_open_greedy_responses_train5000 --train_labels_file_name nq_open_greedy_responses_labels_train5000 --test_file_name nq_open_greedy_responses_1800 --test_labels_file_name nq_open_greedy_responses_labels_1800 --len_dataset 1500 --num_folds 1 --using_act mlp_l1 --token maxpool_all --method individual_linear --bs 32 --epochs 5 --use_class_wgt True --save_probes True --device 0 --save_path ~/Desktop/honest_llama_data

# python get_activations_and_probe.py alpaca_7B nq_open --train_file_name nq_open_greedy_responses_train5000 --train_labels_file_name nq_open_greedy_responses_labels_train5000 --test_file_name nq_open_greedy_responses_1800 --test_labels_file_name nq_open_greedy_responses_labels_1800 --len_dataset 5000 --num_folds 1 --using_act mlp --token all --method individual_linear --bs 32 --epochs 5 --use_class_wgt True --save_probes True --load_act True --device 0 --save_path ~/Desktop/honest_llama_data
# python get_activations_and_probe.py alpaca_7B nq_open --train_file_name nq_open_greedy_responses_train5000 --train_labels_file_name nq_open_greedy_responses_labels_train5000 --test_file_name nq_open_greedy_responses_1800 --test_labels_file_name nq_open_greedy_responses_labels_1800 --len_dataset 5000 --num_folds 1 --using_act mlp --token tagged_tokens --method individual_linear --bs 32 --epochs 5 --use_class_wgt True --save_probes True --load_act True --device 0 --save_path ~/Desktop/honest_llama_data

# bs=32, epochs=5, lr=0.02, cls_wgt=both, train on 1500 (train), test on 1800 (val)
# python get_activations_and_probe.py alpaca_7B nq_open --train_file_name nq_open_greedy_responses_train5000 --train_labels_file_name nq_open_greedy_responses_labels_train5000 --test_file_name nq_open_greedy_responses_1800 --test_labels_file_name nq_open_greedy_responses_labels_1800 --len_dataset 1500 --num_folds 1 --using_act mlp --token answer_last --method individual_linear --bs 32 --epochs 5 --lr 0.02 --save_probes True --device 0 --save_path ~/Desktop/honest_llama_data
# python get_activations_and_probe.py alpaca_7B nq_open --train_file_name nq_open_greedy_responses_train5000 --train_labels_file_name nq_open_greedy_responses_labels_train5000 --test_file_name nq_open_greedy_responses_1800 --test_labels_file_name nq_open_greedy_responses_labels_1800 --len_dataset 1500 --num_folds 1 --using_act mlp --token answer_last --method individual_linear --bs 32 --epochs 5 --lr 0.02 --use_class_wgt True --save_probes True --device 0 --save_path ~/Desktop/honest_llama_data

# bs=32, epochs=5, lr=0.01, cls_wgt=both, train on 1500 (train), test on 1800 (val)
# python get_activations_and_probe.py alpaca_7B nq_open --train_file_name nq_open_greedy_responses_train5000 --train_labels_file_name nq_open_greedy_responses_labels_train5000 --test_file_name nq_open_greedy_responses_1800 --test_labels_file_name nq_open_greedy_responses_labels_1800 --len_dataset 1500 --num_folds 1 --using_act mlp --token answer_last --method individual_linear --bs 32 --epochs 5 --lr 0.01 --save_probes True --device 0 --save_path ~/Desktop/honest_llama_data
# python get_activations_and_probe.py alpaca_7B nq_open --train_file_name nq_open_greedy_responses_train5000 --train_labels_file_name nq_open_greedy_responses_labels_train5000 --test_file_name nq_open_greedy_responses_1800 --test_labels_file_name nq_open_greedy_responses_labels_1800 --len_dataset 1500 --num_folds 1 --using_act mlp --token answer_last --method individual_linear --bs 32 --epochs 5 --lr 0.01 --use_class_wgt True --save_probes True --device 0 --save_path ~/Desktop/honest_llama_data

# bs=32, epochs=5, lr=0.005, cls_wgt=both, train on 1500 (train), test on 1800 (val)
# python get_activations_and_probe.py alpaca_7B nq_open --train_file_name nq_open_greedy_responses_train5000 --train_labels_file_name nq_open_greedy_responses_labels_train5000 --test_file_name nq_open_greedy_responses_1800 --test_labels_file_name nq_open_greedy_responses_labels_1800 --len_dataset 1500 --num_folds 1 --using_act mlp --token answer_last --method individual_linear --bs 32 --epochs 5 --lr 0.005 --save_probes True --device 0 --save_path ~/Desktop/honest_llama_data
# python get_activations_and_probe.py alpaca_7B nq_open --train_file_name nq_open_greedy_responses_train5000 --train_labels_file_name nq_open_greedy_responses_labels_train5000 --test_file_name nq_open_greedy_responses_1800 --test_labels_file_name nq_open_greedy_responses_labels_1800 --len_dataset 1500 --num_folds 1 --using_act mlp --token answer_last --method individual_linear --bs 32 --epochs 5 --lr 0.005 --use_class_wgt True --save_probes True --device 0 --save_path ~/Desktop/honest_llama_data

# bs=32, epochs=5, lr=0.001, cls_wgt=both, train on 1500 (train), test on 1800 (val)
# python get_activations_and_probe.py alpaca_7B nq_open --train_file_name nq_open_greedy_responses_train5000 --train_labels_file_name nq_open_greedy_responses_labels_train5000 --test_file_name nq_open_greedy_responses_1800 --test_labels_file_name nq_open_greedy_responses_labels_1800 --len_dataset 1500 --num_folds 1 --using_act mlp --token answer_last --method individual_linear --bs 32 --epochs 5 --lr 0.001 --save_probes True --device 0 --save_path ~/Desktop/honest_llama_data
# python get_activations_and_probe.py alpaca_7B nq_open --train_file_name nq_open_greedy_responses_train5000 --train_labels_file_name nq_open_greedy_responses_labels_train5000 --test_file_name nq_open_greedy_responses_1800 --test_labels_file_name nq_open_greedy_responses_labels_1800 --len_dataset 1500 --num_folds 1 --using_act mlp --token answer_last --method individual_linear --bs 32 --epochs 5 --lr 0.001 --use_class_wgt True --save_probes True --device 0 --save_path ~/Desktop/honest_llama_data

# bs=32, epochs=5, lr=0.05(default), cls_wgt=False, train on 1500 (train), test on 1800 (val)
# python get_activations_and_probe.py alpaca_7B nq_open --train_file_name nq_open_greedy_responses_train5000 --train_labels_file_name nq_open_greedy_responses_labels_train5000 --test_file_name nq_open_greedy_responses_1800 --test_labels_file_name nq_open_greedy_responses_labels_1800 --len_dataset 1500 --num_folds 1 --using_act mlp --token prompt_last --method individual_linear --bs 32 --epochs 5 --save_probes True --device 0 --save_path ~/Desktop/honest_llama_data
# python get_activations_and_probe.py alpaca_7B nq_open --train_file_name nq_open_greedy_responses_train5000 --train_labels_file_name nq_open_greedy_responses_labels_train5000 --test_file_name nq_open_greedy_responses_1800 --test_labels_file_name nq_open_greedy_responses_labels_1800 --len_dataset 1500 --num_folds 1 --using_act mlp --token maxpool_all --method individual_linear --bs 32 --epochs 5 --save_probes True --device 0 --save_path ~/Desktop/honest_llama_data
python get_activations_and_probe.py alpaca_7B nq_open --train_file_name nq_open_greedy_responses_train5000 --train_labels_file_name nq_open_greedy_responses_labels_train5000 --test_file_name nq_open_greedy_responses_1800 --test_labels_file_name nq_open_greedy_responses_labels_1800 --len_dataset 1500 --num_folds 1 --using_act mlp_l1 --token answer_last --method individual_linear --bs 32 --epochs 5 --save_probes True --device 0 --save_path ~/Desktop/honest_llama_data
# python get_activations_and_probe.py alpaca_7B nq_open --train_file_name nq_open_greedy_responses_train5000 --train_labels_file_name nq_open_greedy_responses_labels_train5000 --test_file_name nq_open_greedy_responses_1800 --test_labels_file_name nq_open_greedy_responses_labels_1800 --len_dataset 1500 --num_folds 1 --using_act mlp_l1 --token prompt_last --method individual_linear --bs 32 --epochs 5 --save_probes True --device 0 --save_path ~/Desktop/honest_llama_data
# python get_activations_and_probe.py alpaca_7B nq_open --train_file_name nq_open_greedy_responses_train5000 --train_labels_file_name nq_open_greedy_responses_labels_train5000 --test_file_name nq_open_greedy_responses_1800 --test_labels_file_name nq_open_greedy_responses_labels_1800 --len_dataset 1500 --num_folds 1 --using_act mlp_l1 --token maxpool_all --method individual_linear --bs 32 --epochs 5 --save_probes True --device 0 --save_path ~/Desktop/honest_llama_data

# bs=32, epochs=10 (ES), lr=0.05(default), cls_wgt=False, train on 1500 (train), test on 1800 (val)
# python get_activations_and_probe.py alpaca_7B nq_open --train_file_name nq_open_greedy_responses_train5000 --train_labels_file_name nq_open_greedy_responses_labels_train5000 --test_file_name nq_open_greedy_responses_1800 --test_labels_file_name nq_open_greedy_responses_labels_1800 --len_dataset 1500 --num_folds 1 --using_act mlp --token answer_last --method individual_linear --bs 32 --epochs 10 --save_probes True --device 0 --save_path ~/Desktop/honest_llama_data