python get_activations.py hl_llama_7B trivia_qa --token prompt_last --file_name trivia_qa_greedy_responses_train5000  --device 0 --save_path ~/honest_llama_data
python get_activations.py hl_llama_7B trivia_qa --token prompt_last --file_name trivia_qa_greedy_responses_validation1800  --device 0 --save_path ~/honest_llama_data

python get_activations_and_probe_non_linear_supcon_bce.py hl_llama_7B trivia_qa --train_file_name trivia_qa_greedy_responses_train5000 --test_file_name trivia_qa_greedy_responses_validation1800 --train_labels_file_name trivia_qa_greedy_responses_labels_train5000 --test_labels_file_name trivia_qa_greedy_responses_labels_validation1800 --len_dataset 2000 --num_folds 1 --using_act layer --token prompt_last --method individual_linear_hallu_pos --bs 128 --epochs 50 --lr 0.00005 --save_probes True --save_path ~/honest_llama_data --fast_mode True  --plot_name prompt_last-linear-n-0.00005b --tag additional-tokens --use_best_val_t True 
python get_activations_and_probe_non_linear_supcon_bce.py hl_llama_7B trivia_qa --train_file_name trivia_qa_greedy_responses_train5000 --test_file_name trivia_qa_greedy_responses_validation1800 --train_labels_file_name trivia_qa_greedy_responses_labels_train5000 --test_labels_file_name trivia_qa_greedy_responses_labels_validation1800 --len_dataset 2000 --num_folds 1 --using_act layer --token prompt_last --method individual_linear_hallu_pos --bs 128 --epochs 50 --lr 0.0005 --save_probes True --save_path ~/honest_llama_data --fast_mode True  --plot_name prompt_last-linear-n-0.0005b --tag additional-tokens --use_best_val_t True 
python get_activations_and_probe_non_linear_supcon_bce.py hl_llama_7B trivia_qa --train_file_name trivia_qa_greedy_responses_train5000 --test_file_name trivia_qa_greedy_responses_validation1800 --train_labels_file_name trivia_qa_greedy_responses_labels_train5000 --test_labels_file_name trivia_qa_greedy_responses_labels_validation1800 --len_dataset 2000 --num_folds 1 --using_act layer --token prompt_last --method individual_linear_hallu_pos --bs 128 --epochs 50 --lr 0.005 --save_probes True --save_path ~/honest_llama_data --fast_mode True  --plot_name prompt_last-linear-n-0.005b --tag additional-tokens --use_best_val_t True 
python get_activations_and_probe_non_linear_supcon_bce.py hl_llama_7B trivia_qa --train_file_name trivia_qa_greedy_responses_train5000 --test_file_name trivia_qa_greedy_responses_validation1800 --train_labels_file_name trivia_qa_greedy_responses_labels_train5000 --test_labels_file_name trivia_qa_greedy_responses_labels_validation1800 --len_dataset 2000 --num_folds 1 --using_act layer --token prompt_last --method individual_linear_hallu_pos --bs 128 --epochs 50 --lr 0.05 --save_probes True --save_path ~/honest_llama_data --fast_mode True  --plot_name prompt_last-linear-n-0.05b --tag additional-tokens --use_best_val_t True 
python get_activations_and_probe_non_linear_supcon_bce.py hl_llama_7B trivia_qa --train_file_name trivia_qa_greedy_responses_train5000 --test_file_name trivia_qa_greedy_responses_validation1800 --train_labels_file_name trivia_qa_greedy_responses_labels_train5000 --test_labels_file_name trivia_qa_greedy_responses_labels_validation1800 --len_dataset 2000 --num_folds 1 --using_act layer --token prompt_last --method individual_linear_hallu_pos --bs 128 --epochs 50 --lr 0.5 --save_probes True --save_path ~/honest_llama_data --fast_mode True  --plot_name prompt_last-linear-n-0.5b --tag additional-tokens --use_best_val_t True 

python get_activations_and_probe_non_linear_supcon_bce.py hl_llama_7B trivia_qa --train_file_name trivia_qa_greedy_responses_train5000 --test_file_name trivia_qa_greedy_responses_validation1800 --train_labels_file_name trivia_qa_greedy_responses_labels_train5000 --test_labels_file_name trivia_qa_greedy_responses_labels_validation1800 --len_dataset 2000 --num_folds 1 --using_act layer --token prompt_last --method individual_linear_hallu_pos --bs 128 --epochs 50 --lr 0.00005 --save_probes True --save_path ~/honest_llama_data --fast_mode True  --plot_name prompt_last-101-linear-n-0.00005b --tag additional-tokens --use_best_val_t True --seed 101
python get_activations_and_probe_non_linear_supcon_bce.py hl_llama_7B trivia_qa --train_file_name trivia_qa_greedy_responses_train5000 --test_file_name trivia_qa_greedy_responses_validation1800 --train_labels_file_name trivia_qa_greedy_responses_labels_train5000 --test_labels_file_name trivia_qa_greedy_responses_labels_validation1800 --len_dataset 2000 --num_folds 1 --using_act layer --token prompt_last --method individual_linear_hallu_pos --bs 128 --epochs 50 --lr 0.0005 --save_probes True --save_path ~/honest_llama_data --fast_mode True  --plot_name prompt_last-101-linear-n-0.0005b --tag additional-tokens --use_best_val_t True --seed 101
python get_activations_and_probe_non_linear_supcon_bce.py hl_llama_7B trivia_qa --train_file_name trivia_qa_greedy_responses_train5000 --test_file_name trivia_qa_greedy_responses_validation1800 --train_labels_file_name trivia_qa_greedy_responses_labels_train5000 --test_labels_file_name trivia_qa_greedy_responses_labels_validation1800 --len_dataset 2000 --num_folds 1 --using_act layer --token prompt_last --method individual_linear_hallu_pos --bs 128 --epochs 50 --lr 0.005 --save_probes True --save_path ~/honest_llama_data --fast_mode True  --plot_name prompt_last-101-linear-n-0.005b --tag additional-tokens --use_best_val_t True --seed 101
python get_activations_and_probe_non_linear_supcon_bce.py hl_llama_7B trivia_qa --train_file_name trivia_qa_greedy_responses_train5000 --test_file_name trivia_qa_greedy_responses_validation1800 --train_labels_file_name trivia_qa_greedy_responses_labels_train5000 --test_labels_file_name trivia_qa_greedy_responses_labels_validation1800 --len_dataset 2000 --num_folds 1 --using_act layer --token prompt_last --method individual_linear_hallu_pos --bs 128 --epochs 50 --lr 0.05 --save_probes True --save_path ~/honest_llama_data --fast_mode True  --plot_name prompt_last-101-linear-n-0.05b --tag additional-tokens --use_best_val_t True --seed 101
python get_activations_and_probe_non_linear_supcon_bce.py hl_llama_7B trivia_qa --train_file_name trivia_qa_greedy_responses_train5000 --test_file_name trivia_qa_greedy_responses_validation1800 --train_labels_file_name trivia_qa_greedy_responses_labels_train5000 --test_labels_file_name trivia_qa_greedy_responses_labels_validation1800 --len_dataset 2000 --num_folds 1 --using_act layer --token prompt_last --method individual_linear_hallu_pos --bs 128 --epochs 50 --lr 0.5 --save_probes True --save_path ~/honest_llama_data --fast_mode True  --plot_name prompt_last-101-linear-n-0.5b --tag additional-tokens --use_best_val_t True --seed 101

python get_activations_and_probe_non_linear_supcon_bce.py hl_llama_7B trivia_qa --train_file_name trivia_qa_greedy_responses_train5000 --test_file_name trivia_qa_greedy_responses_validation1800 --train_labels_file_name trivia_qa_greedy_responses_labels_train5000 --test_labels_file_name trivia_qa_greedy_responses_labels_validation1800 --len_dataset 2000 --num_folds 1 --using_act layer --token prompt_last --method individual_linear_hallu_pos --bs 128 --epochs 50 --lr 0.00005 --save_probes True --save_path ~/honest_llama_data --fast_mode True  --plot_name prompt_last-2650-linear-n-0.00005b --tag additional-tokens --use_best_val_t True --seed 2650
python get_activations_and_probe_non_linear_supcon_bce.py hl_llama_7B trivia_qa --train_file_name trivia_qa_greedy_responses_train5000 --test_file_name trivia_qa_greedy_responses_validation1800 --train_labels_file_name trivia_qa_greedy_responses_labels_train5000 --test_labels_file_name trivia_qa_greedy_responses_labels_validation1800 --len_dataset 2000 --num_folds 1 --using_act layer --token prompt_last --method individual_linear_hallu_pos --bs 128 --epochs 50 --lr 0.0005 --save_probes True --save_path ~/honest_llama_data --fast_mode True  --plot_name prompt_last-2650-linear-n-0.0005b --tag additional-tokens --use_best_val_t True --seed 2650
python get_activations_and_probe_non_linear_supcon_bce.py hl_llama_7B trivia_qa --train_file_name trivia_qa_greedy_responses_train5000 --test_file_name trivia_qa_greedy_responses_validation1800 --train_labels_file_name trivia_qa_greedy_responses_labels_train5000 --test_labels_file_name trivia_qa_greedy_responses_labels_validation1800 --len_dataset 2000 --num_folds 1 --using_act layer --token prompt_last --method individual_linear_hallu_pos --bs 128 --epochs 50 --lr 0.005 --save_probes True --save_path ~/honest_llama_data --fast_mode True  --plot_name prompt_last-2650-linear-n-0.005b --tag additional-tokens --use_best_val_t True --seed 2650
python get_activations_and_probe_non_linear_supcon_bce.py hl_llama_7B trivia_qa --train_file_name trivia_qa_greedy_responses_train5000 --test_file_name trivia_qa_greedy_responses_validation1800 --train_labels_file_name trivia_qa_greedy_responses_labels_train5000 --test_labels_file_name trivia_qa_greedy_responses_labels_validation1800 --len_dataset 2000 --num_folds 1 --using_act layer --token prompt_last --method individual_linear_hallu_pos --bs 128 --epochs 50 --lr 0.05 --save_probes True --save_path ~/honest_llama_data --fast_mode True  --plot_name prompt_last-2650-linear-n-0.05b --tag additional-tokens --use_best_val_t True --seed 2650
python get_activations_and_probe_non_linear_supcon_bce.py hl_llama_7B trivia_qa --train_file_name trivia_qa_greedy_responses_train5000 --test_file_name trivia_qa_greedy_responses_validation1800 --train_labels_file_name trivia_qa_greedy_responses_labels_train5000 --test_labels_file_name trivia_qa_greedy_responses_labels_validation1800 --len_dataset 2000 --num_folds 1 --using_act layer --token prompt_last --method individual_linear_hallu_pos --bs 128 --epochs 50 --lr 0.5 --save_probes True --save_path ~/honest_llama_data --fast_mode True  --plot_name prompt_last-2650-linear-n-0.5b --tag additional-tokens --use_best_val_t True --seed 2650

python get_activations.py hl_llama_7B trivia_qa --token least_likely --file_name trivia_qa_greedy_responses_train5000  --device 0 --save_path ~/honest_llama_data
python get_activations.py hl_llama_7B trivia_qa --token least_likely --file_name trivia_qa_greedy_responses_validation1800  --device 0 --save_path ~/honest_llama_data

python get_activations_and_probe_non_linear_supcon_bce.py hl_llama_7B trivia_qa --train_file_name trivia_qa_greedy_responses_train5000 --test_file_name trivia_qa_greedy_responses_validation1800 --train_labels_file_name trivia_qa_greedy_responses_labels_train5000 --test_labels_file_name trivia_qa_greedy_responses_labels_validation1800 --len_dataset 2000 --num_folds 1 --using_act layer --token least_likely --method individual_linear_hallu_pos --bs 128 --epochs 50 --lr 0.00005 --save_probes True --save_path ~/honest_llama_data --fast_mode True  --plot_name least_likely-linear-n-0.00005b --tag additional-tokens --use_best_val_t True 
python get_activations_and_probe_non_linear_supcon_bce.py hl_llama_7B trivia_qa --train_file_name trivia_qa_greedy_responses_train5000 --test_file_name trivia_qa_greedy_responses_validation1800 --train_labels_file_name trivia_qa_greedy_responses_labels_train5000 --test_labels_file_name trivia_qa_greedy_responses_labels_validation1800 --len_dataset 2000 --num_folds 1 --using_act layer --token least_likely --method individual_linear_hallu_pos --bs 128 --epochs 50 --lr 0.0005 --save_probes True --save_path ~/honest_llama_data --fast_mode True  --plot_name least_likely-linear-n-0.0005b --tag additional-tokens --use_best_val_t True 
python get_activations_and_probe_non_linear_supcon_bce.py hl_llama_7B trivia_qa --train_file_name trivia_qa_greedy_responses_train5000 --test_file_name trivia_qa_greedy_responses_validation1800 --train_labels_file_name trivia_qa_greedy_responses_labels_train5000 --test_labels_file_name trivia_qa_greedy_responses_labels_validation1800 --len_dataset 2000 --num_folds 1 --using_act layer --token least_likely --method individual_linear_hallu_pos --bs 128 --epochs 50 --lr 0.005 --save_probes True --save_path ~/honest_llama_data --fast_mode True  --plot_name least_likely-linear-n-0.005b --tag additional-tokens --use_best_val_t True 
python get_activations_and_probe_non_linear_supcon_bce.py hl_llama_7B trivia_qa --train_file_name trivia_qa_greedy_responses_train5000 --test_file_name trivia_qa_greedy_responses_validation1800 --train_labels_file_name trivia_qa_greedy_responses_labels_train5000 --test_labels_file_name trivia_qa_greedy_responses_labels_validation1800 --len_dataset 2000 --num_folds 1 --using_act layer --token least_likely --method individual_linear_hallu_pos --bs 128 --epochs 50 --lr 0.05 --save_probes True --save_path ~/honest_llama_data --fast_mode True  --plot_name least_likely-linear-n-0.05b --tag additional-tokens --use_best_val_t True 
python get_activations_and_probe_non_linear_supcon_bce.py hl_llama_7B trivia_qa --train_file_name trivia_qa_greedy_responses_train5000 --test_file_name trivia_qa_greedy_responses_validation1800 --train_labels_file_name trivia_qa_greedy_responses_labels_train5000 --test_labels_file_name trivia_qa_greedy_responses_labels_validation1800 --len_dataset 2000 --num_folds 1 --using_act layer --token least_likely --method individual_linear_hallu_pos --bs 128 --epochs 50 --lr 0.5 --save_probes True --save_path ~/honest_llama_data --fast_mode True  --plot_name least_likely-linear-n-0.5b --tag additional-tokens --use_best_val_t True 

python get_activations_and_probe_non_linear_supcon_bce.py hl_llama_7B trivia_qa --train_file_name trivia_qa_greedy_responses_train5000 --test_file_name trivia_qa_greedy_responses_validation1800 --train_labels_file_name trivia_qa_greedy_responses_labels_train5000 --test_labels_file_name trivia_qa_greedy_responses_labels_validation1800 --len_dataset 2000 --num_folds 1 --using_act layer --token least_likely --method individual_linear_hallu_pos --bs 128 --epochs 50 --lr 0.00005 --save_probes True --save_path ~/honest_llama_data --fast_mode True  --plot_name least_likely-101-linear-n-0.00005b --tag additional-tokens --use_best_val_t True --seed 101
python get_activations_and_probe_non_linear_supcon_bce.py hl_llama_7B trivia_qa --train_file_name trivia_qa_greedy_responses_train5000 --test_file_name trivia_qa_greedy_responses_validation1800 --train_labels_file_name trivia_qa_greedy_responses_labels_train5000 --test_labels_file_name trivia_qa_greedy_responses_labels_validation1800 --len_dataset 2000 --num_folds 1 --using_act layer --token least_likely --method individual_linear_hallu_pos --bs 128 --epochs 50 --lr 0.0005 --save_probes True --save_path ~/honest_llama_data --fast_mode True  --plot_name least_likely-101-linear-n-0.0005b --tag additional-tokens --use_best_val_t True --seed 101
python get_activations_and_probe_non_linear_supcon_bce.py hl_llama_7B trivia_qa --train_file_name trivia_qa_greedy_responses_train5000 --test_file_name trivia_qa_greedy_responses_validation1800 --train_labels_file_name trivia_qa_greedy_responses_labels_train5000 --test_labels_file_name trivia_qa_greedy_responses_labels_validation1800 --len_dataset 2000 --num_folds 1 --using_act layer --token least_likely --method individual_linear_hallu_pos --bs 128 --epochs 50 --lr 0.005 --save_probes True --save_path ~/honest_llama_data --fast_mode True  --plot_name least_likely-101-linear-n-0.005b --tag additional-tokens --use_best_val_t True --seed 101
python get_activations_and_probe_non_linear_supcon_bce.py hl_llama_7B trivia_qa --train_file_name trivia_qa_greedy_responses_train5000 --test_file_name trivia_qa_greedy_responses_validation1800 --train_labels_file_name trivia_qa_greedy_responses_labels_train5000 --test_labels_file_name trivia_qa_greedy_responses_labels_validation1800 --len_dataset 2000 --num_folds 1 --using_act layer --token least_likely --method individual_linear_hallu_pos --bs 128 --epochs 50 --lr 0.05 --save_probes True --save_path ~/honest_llama_data --fast_mode True  --plot_name least_likely-101-linear-n-0.05b --tag additional-tokens --use_best_val_t True --seed 101
python get_activations_and_probe_non_linear_supcon_bce.py hl_llama_7B trivia_qa --train_file_name trivia_qa_greedy_responses_train5000 --test_file_name trivia_qa_greedy_responses_validation1800 --train_labels_file_name trivia_qa_greedy_responses_labels_train5000 --test_labels_file_name trivia_qa_greedy_responses_labels_validation1800 --len_dataset 2000 --num_folds 1 --using_act layer --token least_likely --method individual_linear_hallu_pos --bs 128 --epochs 50 --lr 0.5 --save_probes True --save_path ~/honest_llama_data --fast_mode True  --plot_name least_likely-101-linear-n-0.5b --tag additional-tokens --use_best_val_t True --seed 101

python get_activations_and_probe_non_linear_supcon_bce.py hl_llama_7B trivia_qa --train_file_name trivia_qa_greedy_responses_train5000 --test_file_name trivia_qa_greedy_responses_validation1800 --train_labels_file_name trivia_qa_greedy_responses_labels_train5000 --test_labels_file_name trivia_qa_greedy_responses_labels_validation1800 --len_dataset 2000 --num_folds 1 --using_act layer --token least_likely --method individual_linear_hallu_pos --bs 128 --epochs 50 --lr 0.00005 --save_probes True --save_path ~/honest_llama_data --fast_mode True  --plot_name least_likely-2650-linear-n-0.00005b --tag additional-tokens --use_best_val_t True --seed 2650
python get_activations_and_probe_non_linear_supcon_bce.py hl_llama_7B trivia_qa --train_file_name trivia_qa_greedy_responses_train5000 --test_file_name trivia_qa_greedy_responses_validation1800 --train_labels_file_name trivia_qa_greedy_responses_labels_train5000 --test_labels_file_name trivia_qa_greedy_responses_labels_validation1800 --len_dataset 2000 --num_folds 1 --using_act layer --token least_likely --method individual_linear_hallu_pos --bs 128 --epochs 50 --lr 0.0005 --save_probes True --save_path ~/honest_llama_data --fast_mode True  --plot_name least_likely-2650-linear-n-0.0005b --tag additional-tokens --use_best_val_t True --seed 2650
python get_activations_and_probe_non_linear_supcon_bce.py hl_llama_7B trivia_qa --train_file_name trivia_qa_greedy_responses_train5000 --test_file_name trivia_qa_greedy_responses_validation1800 --train_labels_file_name trivia_qa_greedy_responses_labels_train5000 --test_labels_file_name trivia_qa_greedy_responses_labels_validation1800 --len_dataset 2000 --num_folds 1 --using_act layer --token least_likely --method individual_linear_hallu_pos --bs 128 --epochs 50 --lr 0.005 --save_probes True --save_path ~/honest_llama_data --fast_mode True  --plot_name least_likely-2650-linear-n-0.005b --tag additional-tokens --use_best_val_t True --seed 2650
python get_activations_and_probe_non_linear_supcon_bce.py hl_llama_7B trivia_qa --train_file_name trivia_qa_greedy_responses_train5000 --test_file_name trivia_qa_greedy_responses_validation1800 --train_labels_file_name trivia_qa_greedy_responses_labels_train5000 --test_labels_file_name trivia_qa_greedy_responses_labels_validation1800 --len_dataset 2000 --num_folds 1 --using_act layer --token least_likely --method individual_linear_hallu_pos --bs 128 --epochs 50 --lr 0.05 --save_probes True --save_path ~/honest_llama_data --fast_mode True  --plot_name least_likely-2650-linear-n-0.05b --tag additional-tokens --use_best_val_t True --seed 2650
python get_activations_and_probe_non_linear_supcon_bce.py hl_llama_7B trivia_qa --train_file_name trivia_qa_greedy_responses_train5000 --test_file_name trivia_qa_greedy_responses_validation1800 --train_labels_file_name trivia_qa_greedy_responses_labels_train5000 --test_labels_file_name trivia_qa_greedy_responses_labels_validation1800 --len_dataset 2000 --num_folds 1 --using_act layer --token least_likely --method individual_linear_hallu_pos --bs 128 --epochs 50 --lr 0.5 --save_probes True --save_path ~/honest_llama_data --fast_mode True  --plot_name least_likely-2650-linear-n-0.5b --tag additional-tokens --use_best_val_t True --seed 2650

python get_activations.py hl_llama_7B trivia_qa --token maxpool_all --file_name trivia_qa_greedy_responses_train5000  --device 0 --save_path ~/honest_llama_data
python get_activations.py hl_llama_7B trivia_qa --token maxpool_all --file_name trivia_qa_greedy_responses_validation1800  --device 0 --save_path ~/honest_llama_data

python get_activations_and_probe_non_linear_supcon_bce.py hl_llama_7B trivia_qa --train_file_name trivia_qa_greedy_responses_train5000 --test_file_name trivia_qa_greedy_responses_validation1800 --train_labels_file_name trivia_qa_greedy_responses_labels_train5000 --test_labels_file_name trivia_qa_greedy_responses_labels_validation1800 --len_dataset 2000 --num_folds 1 --using_act layer --token maxpool_all --method individual_linear_hallu_pos --bs 128 --epochs 50 --lr 0.00005 --save_probes True --save_path ~/honest_llama_data --fast_mode True  --plot_name maxpool_all-linear-n-0.00005b --tag additional-tokens --use_best_val_t True 
python get_activations_and_probe_non_linear_supcon_bce.py hl_llama_7B trivia_qa --train_file_name trivia_qa_greedy_responses_train5000 --test_file_name trivia_qa_greedy_responses_validation1800 --train_labels_file_name trivia_qa_greedy_responses_labels_train5000 --test_labels_file_name trivia_qa_greedy_responses_labels_validation1800 --len_dataset 2000 --num_folds 1 --using_act layer --token maxpool_all --method individual_linear_hallu_pos --bs 128 --epochs 50 --lr 0.0005 --save_probes True --save_path ~/honest_llama_data --fast_mode True  --plot_name maxpool_all-linear-n-0.0005b --tag additional-tokens --use_best_val_t True 
python get_activations_and_probe_non_linear_supcon_bce.py hl_llama_7B trivia_qa --train_file_name trivia_qa_greedy_responses_train5000 --test_file_name trivia_qa_greedy_responses_validation1800 --train_labels_file_name trivia_qa_greedy_responses_labels_train5000 --test_labels_file_name trivia_qa_greedy_responses_labels_validation1800 --len_dataset 2000 --num_folds 1 --using_act layer --token maxpool_all --method individual_linear_hallu_pos --bs 128 --epochs 50 --lr 0.005 --save_probes True --save_path ~/honest_llama_data --fast_mode True  --plot_name maxpool_all-linear-n-0.005b --tag additional-tokens --use_best_val_t True 
python get_activations_and_probe_non_linear_supcon_bce.py hl_llama_7B trivia_qa --train_file_name trivia_qa_greedy_responses_train5000 --test_file_name trivia_qa_greedy_responses_validation1800 --train_labels_file_name trivia_qa_greedy_responses_labels_train5000 --test_labels_file_name trivia_qa_greedy_responses_labels_validation1800 --len_dataset 2000 --num_folds 1 --using_act layer --token maxpool_all --method individual_linear_hallu_pos --bs 128 --epochs 50 --lr 0.05 --save_probes True --save_path ~/honest_llama_data --fast_mode True  --plot_name maxpool_all-linear-n-0.05b --tag additional-tokens --use_best_val_t True 
python get_activations_and_probe_non_linear_supcon_bce.py hl_llama_7B trivia_qa --train_file_name trivia_qa_greedy_responses_train5000 --test_file_name trivia_qa_greedy_responses_validation1800 --train_labels_file_name trivia_qa_greedy_responses_labels_train5000 --test_labels_file_name trivia_qa_greedy_responses_labels_validation1800 --len_dataset 2000 --num_folds 1 --using_act layer --token maxpool_all --method individual_linear_hallu_pos --bs 128 --epochs 50 --lr 0.5 --save_probes True --save_path ~/honest_llama_data --fast_mode True  --plot_name maxpool_all-linear-n-0.5b --tag additional-tokens --use_best_val_t True 

python get_activations_and_probe_non_linear_supcon_bce.py hl_llama_7B trivia_qa --train_file_name trivia_qa_greedy_responses_train5000 --test_file_name trivia_qa_greedy_responses_validation1800 --train_labels_file_name trivia_qa_greedy_responses_labels_train5000 --test_labels_file_name trivia_qa_greedy_responses_labels_validation1800 --len_dataset 2000 --num_folds 1 --using_act layer --token maxpool_all --method individual_linear_hallu_pos --bs 128 --epochs 50 --lr 0.00005 --save_probes True --save_path ~/honest_llama_data --fast_mode True  --plot_name maxpool_all-101-linear-n-0.00005b --tag additional-tokens --use_best_val_t True --seed 101
python get_activations_and_probe_non_linear_supcon_bce.py hl_llama_7B trivia_qa --train_file_name trivia_qa_greedy_responses_train5000 --test_file_name trivia_qa_greedy_responses_validation1800 --train_labels_file_name trivia_qa_greedy_responses_labels_train5000 --test_labels_file_name trivia_qa_greedy_responses_labels_validation1800 --len_dataset 2000 --num_folds 1 --using_act layer --token maxpool_all --method individual_linear_hallu_pos --bs 128 --epochs 50 --lr 0.0005 --save_probes True --save_path ~/honest_llama_data --fast_mode True  --plot_name maxpool_all-101-linear-n-0.0005b --tag additional-tokens --use_best_val_t True --seed 101
python get_activations_and_probe_non_linear_supcon_bce.py hl_llama_7B trivia_qa --train_file_name trivia_qa_greedy_responses_train5000 --test_file_name trivia_qa_greedy_responses_validation1800 --train_labels_file_name trivia_qa_greedy_responses_labels_train5000 --test_labels_file_name trivia_qa_greedy_responses_labels_validation1800 --len_dataset 2000 --num_folds 1 --using_act layer --token maxpool_all --method individual_linear_hallu_pos --bs 128 --epochs 50 --lr 0.005 --save_probes True --save_path ~/honest_llama_data --fast_mode True  --plot_name maxpool_all-101-linear-n-0.005b --tag additional-tokens --use_best_val_t True --seed 101
python get_activations_and_probe_non_linear_supcon_bce.py hl_llama_7B trivia_qa --train_file_name trivia_qa_greedy_responses_train5000 --test_file_name trivia_qa_greedy_responses_validation1800 --train_labels_file_name trivia_qa_greedy_responses_labels_train5000 --test_labels_file_name trivia_qa_greedy_responses_labels_validation1800 --len_dataset 2000 --num_folds 1 --using_act layer --token maxpool_all --method individual_linear_hallu_pos --bs 128 --epochs 50 --lr 0.05 --save_probes True --save_path ~/honest_llama_data --fast_mode True  --plot_name maxpool_all-101-linear-n-0.05b --tag additional-tokens --use_best_val_t True --seed 101
python get_activations_and_probe_non_linear_supcon_bce.py hl_llama_7B trivia_qa --train_file_name trivia_qa_greedy_responses_train5000 --test_file_name trivia_qa_greedy_responses_validation1800 --train_labels_file_name trivia_qa_greedy_responses_labels_train5000 --test_labels_file_name trivia_qa_greedy_responses_labels_validation1800 --len_dataset 2000 --num_folds 1 --using_act layer --token maxpool_all --method individual_linear_hallu_pos --bs 128 --epochs 50 --lr 0.5 --save_probes True --save_path ~/honest_llama_data --fast_mode True  --plot_name maxpool_all-101-linear-n-0.5b --tag additional-tokens --use_best_val_t True --seed 101

python get_activations_and_probe_non_linear_supcon_bce.py hl_llama_7B trivia_qa --train_file_name trivia_qa_greedy_responses_train5000 --test_file_name trivia_qa_greedy_responses_validation1800 --train_labels_file_name trivia_qa_greedy_responses_labels_train5000 --test_labels_file_name trivia_qa_greedy_responses_labels_validation1800 --len_dataset 2000 --num_folds 1 --using_act layer --token maxpool_all --method individual_linear_hallu_pos --bs 128 --epochs 50 --lr 0.00005 --save_probes True --save_path ~/honest_llama_data --fast_mode True  --plot_name maxpool_all-2650-linear-n-0.00005b --tag additional-tokens --use_best_val_t True --seed 2650
python get_activations_and_probe_non_linear_supcon_bce.py hl_llama_7B trivia_qa --train_file_name trivia_qa_greedy_responses_train5000 --test_file_name trivia_qa_greedy_responses_validation1800 --train_labels_file_name trivia_qa_greedy_responses_labels_train5000 --test_labels_file_name trivia_qa_greedy_responses_labels_validation1800 --len_dataset 2000 --num_folds 1 --using_act layer --token maxpool_all --method individual_linear_hallu_pos --bs 128 --epochs 50 --lr 0.0005 --save_probes True --save_path ~/honest_llama_data --fast_mode True  --plot_name maxpool_all-2650-linear-n-0.0005b --tag additional-tokens --use_best_val_t True --seed 2650
python get_activations_and_probe_non_linear_supcon_bce.py hl_llama_7B trivia_qa --train_file_name trivia_qa_greedy_responses_train5000 --test_file_name trivia_qa_greedy_responses_validation1800 --train_labels_file_name trivia_qa_greedy_responses_labels_train5000 --test_labels_file_name trivia_qa_greedy_responses_labels_validation1800 --len_dataset 2000 --num_folds 1 --using_act layer --token maxpool_all --method individual_linear_hallu_pos --bs 128 --epochs 50 --lr 0.005 --save_probes True --save_path ~/honest_llama_data --fast_mode True  --plot_name maxpool_all-2650-linear-n-0.005b --tag additional-tokens --use_best_val_t True --seed 2650
python get_activations_and_probe_non_linear_supcon_bce.py hl_llama_7B trivia_qa --train_file_name trivia_qa_greedy_responses_train5000 --test_file_name trivia_qa_greedy_responses_validation1800 --train_labels_file_name trivia_qa_greedy_responses_labels_train5000 --test_labels_file_name trivia_qa_greedy_responses_labels_validation1800 --len_dataset 2000 --num_folds 1 --using_act layer --token maxpool_all --method individual_linear_hallu_pos --bs 128 --epochs 50 --lr 0.05 --save_probes True --save_path ~/honest_llama_data --fast_mode True  --plot_name maxpool_all-2650-linear-n-0.05b --tag additional-tokens --use_best_val_t True --seed 2650
python get_activations_and_probe_non_linear_supcon_bce.py hl_llama_7B trivia_qa --train_file_name trivia_qa_greedy_responses_train5000 --test_file_name trivia_qa_greedy_responses_validation1800 --train_labels_file_name trivia_qa_greedy_responses_labels_train5000 --test_labels_file_name trivia_qa_greedy_responses_labels_validation1800 --len_dataset 2000 --num_folds 1 --using_act layer --token maxpool_all --method individual_linear_hallu_pos --bs 128 --epochs 50 --lr 0.5 --save_probes True --save_path ~/honest_llama_data --fast_mode True  --plot_name maxpool_all-2650-linear-n-0.5b --tag additional-tokens --use_best_val_t True --seed 2650
