# python get_activations_and_probe_non_linear_supcon_bce.py hl_llama_7B gsm8k --train_file_name gsm8k_sampledplus_responses_train2000 --test_file_name gsm8k_greedy_responses_test1800 --train_labels_file_name gsm8k_sampledplus_responses_labels_train2000 --test_labels_file_name gsm8k_greedy_responses_labels_test1800 --len_dataset 21989 --num_folds 1 --using_act layer --token answer_last --method individual_linear_hallu_pos --bs 128 --epochs 50 --lr 0.00005 --norm_input True --save_probes True --save_path ~/honest_llama_data --fast_mode True  --plot_name linear-n*aug-0.00005b --tag main --num_samples 11 --use_best_val_t True
# python get_activations_and_probe_non_linear_supcon_bce.py hl_llama_7B gsm8k --train_file_name gsm8k_sampledplus_responses_train2000 --test_file_name gsm8k_greedy_responses_test1800 --train_labels_file_name gsm8k_sampledplus_responses_labels_train2000 --test_labels_file_name gsm8k_greedy_responses_labels_test1800 --len_dataset 21989 --num_folds 1 --using_act layer --token answer_last --method individual_linear_hallu_pos --bs 128 --epochs 50 --lr 0.0005 --norm_input True --save_probes True --save_path ~/honest_llama_data --fast_mode True  --plot_name linear-n*aug-0.0005b --tag main --num_samples 11 --use_best_val_t True
# python get_activations_and_probe_non_linear_supcon_bce.py hl_llama_7B gsm8k --train_file_name gsm8k_sampledplus_responses_train2000 --test_file_name gsm8k_greedy_responses_test1800 --train_labels_file_name gsm8k_sampledplus_responses_labels_train2000 --test_labels_file_name gsm8k_greedy_responses_labels_test1800 --len_dataset 21989 --num_folds 1 --using_act layer --token answer_last --method individual_linear_hallu_pos --bs 128 --epochs 50 --lr 0.005 --norm_input True --save_probes True --save_path ~/honest_llama_data --fast_mode True  --plot_name linear-n*aug-0.005b --tag main --num_samples 11 --use_best_val_t True
# python get_activations_and_probe_non_linear_supcon_bce.py hl_llama_7B gsm8k --train_file_name gsm8k_sampledplus_responses_train2000 --test_file_name gsm8k_greedy_responses_test1800 --train_labels_file_name gsm8k_sampledplus_responses_labels_train2000 --test_labels_file_name gsm8k_greedy_responses_labels_test1800 --len_dataset 21989 --num_folds 1 --using_act layer --token answer_last --method individual_linear_hallu_pos --bs 128 --epochs 50 --lr 0.05 --norm_input True --save_probes True --save_path ~/honest_llama_data --fast_mode True  --plot_name linear-n*aug-0.05b --tag main --num_samples 11 --use_best_val_t True
# python get_activations_and_probe_non_linear_supcon_bce.py hl_llama_7B gsm8k --train_file_name gsm8k_sampledplus_responses_train2000 --test_file_name gsm8k_greedy_responses_test1800 --train_labels_file_name gsm8k_sampledplus_responses_labels_train2000 --test_labels_file_name gsm8k_greedy_responses_labels_test1800 --len_dataset 21989 --num_folds 1 --using_act layer --token answer_last --method individual_linear_hallu_pos --bs 128 --epochs 50 --lr 0.5 --norm_input True --save_probes True --save_path ~/honest_llama_data --fast_mode True  --plot_name linear-n*aug-0.5b --tag main --num_samples 11 --use_best_val_t True

python get_activations.py hl_llama_7B gsm8k --token answer_last --file_name gsm8k_greedy_responses_train2000  --device 0 --save_path ~/honest_llama_data
python get_activations.py hl_llama_7B gsm8k --token answer_last --file_name gsm8k_greedy_responses_test1800  --device 0 --save_path ~/honest_llama_data

python get_activations_and_probe_non_linear_supcon_bce.py hl_llama_7B gsm8k --train_file_name gsm8k_greedy_responses_train2000 --test_file_name gsm8k_greedy_responses_test1800 --len_dataset 1999 --num_folds 1 --using_act layer --token answer_last --method individual_linear_hallu_pos --bs 128 --epochs 50 --lr 0.00005 --save_probes True --save_path ~/honest_llama_data --fast_mode True  --plot_name linear-n-0.00005b --tag main-baseline --use_best_val_t True
python get_activations_and_probe_non_linear_supcon_bce.py hl_llama_7B gsm8k --train_file_name gsm8k_greedy_responses_train2000 --test_file_name gsm8k_greedy_responses_test1800 --len_dataset 1999 --num_folds 1 --using_act layer --token answer_last --method individual_linear_hallu_pos --bs 128 --epochs 50 --lr 0.0005 --save_probes True --save_path ~/honest_llama_data --fast_mode True  --plot_name linear-n-0.0005b --tag main-baseline --use_best_val_t True
python get_activations_and_probe_non_linear_supcon_bce.py hl_llama_7B gsm8k --train_file_name gsm8k_greedy_responses_train2000 --test_file_name gsm8k_greedy_responses_test1800 --len_dataset 1999 --num_folds 1 --using_act layer --token answer_last --method individual_linear_hallu_pos --bs 128 --epochs 50 --lr 0.005 --save_probes True --save_path ~/honest_llama_data --fast_mode True  --plot_name linear-n-0.005b --tag main-baseline --use_best_val_t True
python get_activations_and_probe_non_linear_supcon_bce.py hl_llama_7B gsm8k --train_file_name gsm8k_greedy_responses_train2000 --test_file_name gsm8k_greedy_responses_test1800 --len_dataset 1999 --num_folds 1 --using_act layer --token answer_last --method individual_linear_hallu_pos --bs 128 --epochs 50 --lr 0.05 --save_probes True --save_path ~/honest_llama_data --fast_mode True  --plot_name linear-n-0.05b --tag main-baseline --use_best_val_t True
python get_activations_and_probe_non_linear_supcon_bce.py hl_llama_7B gsm8k --train_file_name gsm8k_greedy_responses_train2000 --test_file_name gsm8k_greedy_responses_test1800 --len_dataset 1999 --num_folds 1 --using_act layer --token answer_last --method individual_linear_hallu_pos --bs 128 --epochs 50 --lr 0.5 --save_probes True --save_path ~/honest_llama_data --fast_mode True  --plot_name linear-n-0.5b --tag main-baseline --use_best_val_t True

python get_activations_and_probe_non_linear_supcon_bce.py hl_llama_7B gsm8k --train_file_name gsm8k_greedy_responses_train2000 --test_file_name gsm8k_greedy_responses_test1800 --len_dataset 1999 --num_folds 1 --using_act layer --token answer_last --method individual_linear_hallu_pos --bs 128 --epochs 50 --lr 0.00005 --norm_input True --save_probes True --save_path ~/honest_llama_data --fast_mode True  --plot_name linear-n-norm-0.00005b --tag main-baseline --use_best_val_t True
python get_activations_and_probe_non_linear_supcon_bce.py hl_llama_7B gsm8k --train_file_name gsm8k_greedy_responses_train2000 --test_file_name gsm8k_greedy_responses_test1800 --len_dataset 1999 --num_folds 1 --using_act layer --token answer_last --method individual_linear_hallu_pos --bs 128 --epochs 50 --lr 0.0005 --norm_input True --save_probes True --save_path ~/honest_llama_data --fast_mode True  --plot_name linear-n-norm-0.0005b --tag main-baseline --use_best_val_t True
python get_activations_and_probe_non_linear_supcon_bce.py hl_llama_7B gsm8k --train_file_name gsm8k_greedy_responses_train2000 --test_file_name gsm8k_greedy_responses_test1800 --len_dataset 1999 --num_folds 1 --using_act layer --token answer_last --method individual_linear_hallu_pos --bs 128 --epochs 50 --lr 0.005 --norm_input True --save_probes True --save_path ~/honest_llama_data --fast_mode True  --plot_name linear-n-norm-0.005b --tag main-baseline --use_best_val_t True
python get_activations_and_probe_non_linear_supcon_bce.py hl_llama_7B gsm8k --train_file_name gsm8k_greedy_responses_train2000 --test_file_name gsm8k_greedy_responses_test1800 --len_dataset 1999 --num_folds 1 --using_act layer --token answer_last --method individual_linear_hallu_pos --bs 128 --epochs 50 --lr 0.05 --norm_input True --save_probes True --save_path ~/honest_llama_data --fast_mode True  --plot_name linear-n-norm-0.05b --tag main-baseline --use_best_val_t True
python get_activations_and_probe_non_linear_supcon_bce.py hl_llama_7B gsm8k --train_file_name gsm8k_greedy_responses_train2000 --test_file_name gsm8k_greedy_responses_test1800 --len_dataset 1999 --num_folds 1 --using_act layer --token answer_last --method individual_linear_hallu_pos --bs 128 --epochs 50 --lr 0.5 --norm_input True --save_probes True --save_path ~/honest_llama_data --fast_mode True  --plot_name linear-n-norm-0.5b --tag main-baseline --use_best_val_t True

python get_activations_and_probe_non_linear_supcon_bce.py hl_llama_7B gsm8k --train_file_name gsm8k_greedy_responses_train2000 --test_file_name gsm8k_greedy_responses_test1800 --len_dataset 1999 --num_folds 1 --using_act layer --token answer_last --method individual_non_linear_4_hallu_pos --bs 128 --epochs 50 --lr 0.00005 --save_probes True --save_path ~/honest_llama_data --fast_mode True  --plot_name nlinear-n-0.00005b --tag main-baseline --use_best_val_t True
python get_activations_and_probe_non_linear_supcon_bce.py hl_llama_7B gsm8k --train_file_name gsm8k_greedy_responses_train2000 --test_file_name gsm8k_greedy_responses_test1800 --len_dataset 1999 --num_folds 1 --using_act layer --token answer_last --method individual_non_linear_4_hallu_pos --bs 128 --epochs 50 --lr 0.0005 --save_probes True --save_path ~/honest_llama_data --fast_mode True  --plot_name nlinear-n-0.0005b --tag main-baseline --use_best_val_t True
python get_activations_and_probe_non_linear_supcon_bce.py hl_llama_7B gsm8k --train_file_name gsm8k_greedy_responses_train2000 --test_file_name gsm8k_greedy_responses_test1800 --len_dataset 1999 --num_folds 1 --using_act layer --token answer_last --method individual_non_linear_4_hallu_pos --bs 128 --epochs 50 --lr 0.005 --save_probes True --save_path ~/honest_llama_data --fast_mode True  --plot_name nlinear-n-0.005b --tag main-baseline --use_best_val_t True
python get_activations_and_probe_non_linear_supcon_bce.py hl_llama_7B gsm8k --train_file_name gsm8k_greedy_responses_train2000 --test_file_name gsm8k_greedy_responses_test1800 --len_dataset 1999 --num_folds 1 --using_act layer --token answer_last --method individual_non_linear_4_hallu_pos --bs 128 --epochs 50 --lr 0.05 --save_probes True --save_path ~/honest_llama_data --fast_mode True  --plot_name nlinear-n-0.05b --tag main-baseline --use_best_val_t True
python get_activations_and_probe_non_linear_supcon_bce.py hl_llama_7B gsm8k --train_file_name gsm8k_greedy_responses_train2000 --test_file_name gsm8k_greedy_responses_test1800 --len_dataset 1999 --num_folds 1 --using_act layer --token answer_last --method individual_non_linear_4_hallu_pos --bs 128 --epochs 50 --lr 0.5 --save_probes True --save_path ~/honest_llama_data --fast_mode True  --plot_name nlinear-n-0.5b --tag main-baseline --use_best_val_t True

python get_activations_and_probe_non_linear_supcon_bce.py hl_llama_7B gsm8k --train_file_name gsm8k_greedy_responses_train2000 --test_file_name gsm8k_greedy_responses_test1800 --len_dataset 1999 --num_folds 1 --using_act layer --token answer_last --method individual_non_linear_4_hallu_pos --bs 128 --epochs 50 --lr 0.00005 --norm_input True --save_probes True --save_path ~/honest_llama_data --fast_mode True  --plot_name nlinear-n-norm-0.00005b --tag main-baseline --use_best_val_t True
python get_activations_and_probe_non_linear_supcon_bce.py hl_llama_7B gsm8k --train_file_name gsm8k_greedy_responses_train2000 --test_file_name gsm8k_greedy_responses_test1800 --len_dataset 1999 --num_folds 1 --using_act layer --token answer_last --method individual_non_linear_4_hallu_pos --bs 128 --epochs 50 --lr 0.0005 --norm_input True --save_probes True --save_path ~/honest_llama_data --fast_mode True  --plot_name nlinear-n-norm-0.0005b --tag main-baseline --use_best_val_t True
python get_activations_and_probe_non_linear_supcon_bce.py hl_llama_7B gsm8k --train_file_name gsm8k_greedy_responses_train2000 --test_file_name gsm8k_greedy_responses_test1800 --len_dataset 1999 --num_folds 1 --using_act layer --token answer_last --method individual_non_linear_4_hallu_pos --bs 128 --epochs 50 --lr 0.005 --norm_input True --save_probes True --save_path ~/honest_llama_data --fast_mode True  --plot_name nlinear-n-norm-0.005b --tag main-baseline --use_best_val_t True
python get_activations_and_probe_non_linear_supcon_bce.py hl_llama_7B gsm8k --train_file_name gsm8k_greedy_responses_train2000 --test_file_name gsm8k_greedy_responses_test1800 --len_dataset 1999 --num_folds 1 --using_act layer --token answer_last --method individual_non_linear_4_hallu_pos --bs 128 --epochs 50 --lr 0.05 --norm_input True --save_probes True --save_path ~/honest_llama_data --fast_mode True  --plot_name nlinear-n-norm-0.05b --tag main-baseline --use_best_val_t True
python get_activations_and_probe_non_linear_supcon_bce.py hl_llama_7B gsm8k --train_file_name gsm8k_greedy_responses_train2000 --test_file_name gsm8k_greedy_responses_test1800 --len_dataset 1999 --num_folds 1 --using_act layer --token answer_last --method individual_non_linear_4_hallu_pos --bs 128 --epochs 50 --lr 0.5 --norm_input True --save_probes True --save_path ~/honest_llama_data --fast_mode True  --plot_name nlinear-n-norm-0.5b --tag main-baseline --use_best_val_t True

python get_activations.py alpaca_7B gsm8k --token answer_last --file_name gsm8k_greedy_responses_train2000  --device 0 --save_path ~/honest_llama_data
python get_activations.py alpaca_7B gsm8k --token answer_last --file_name gsm8k_greedy_responses_test1800  --device 0 --save_path ~/honest_llama_data

python get_activations_and_probe_non_linear_supcon_bce.py alpaca_7B gsm8k --train_file_name gsm8k_greedy_responses_train2000 --test_file_name gsm8k_greedy_responses_test1800 --len_dataset 1999 --num_folds 1 --using_act layer --token answer_last --method individual_linear_hallu_pos --bs 128 --epochs 50 --lr 0.00005 --save_probes True --save_path ~/honest_llama_data --fast_mode True  --plot_name linear-n-0.00005b --tag main-baseline --use_best_val_t True
python get_activations_and_probe_non_linear_supcon_bce.py alpaca_7B gsm8k --train_file_name gsm8k_greedy_responses_train2000 --test_file_name gsm8k_greedy_responses_test1800 --len_dataset 1999 --num_folds 1 --using_act layer --token answer_last --method individual_linear_hallu_pos --bs 128 --epochs 50 --lr 0.0005 --save_probes True --save_path ~/honest_llama_data --fast_mode True  --plot_name linear-n-0.0005b --tag main-baseline --use_best_val_t True
python get_activations_and_probe_non_linear_supcon_bce.py alpaca_7B gsm8k --train_file_name gsm8k_greedy_responses_train2000 --test_file_name gsm8k_greedy_responses_test1800 --len_dataset 1999 --num_folds 1 --using_act layer --token answer_last --method individual_linear_hallu_pos --bs 128 --epochs 50 --lr 0.005 --save_probes True --save_path ~/honest_llama_data --fast_mode True  --plot_name linear-n-0.005b --tag main-baseline --use_best_val_t True
python get_activations_and_probe_non_linear_supcon_bce.py alpaca_7B gsm8k --train_file_name gsm8k_greedy_responses_train2000 --test_file_name gsm8k_greedy_responses_test1800 --len_dataset 1999 --num_folds 1 --using_act layer --token answer_last --method individual_linear_hallu_pos --bs 128 --epochs 50 --lr 0.05 --save_probes True --save_path ~/honest_llama_data --fast_mode True  --plot_name linear-n-0.05b --tag main-baseline --use_best_val_t True
python get_activations_and_probe_non_linear_supcon_bce.py alpaca_7B gsm8k --train_file_name gsm8k_greedy_responses_train2000 --test_file_name gsm8k_greedy_responses_test1800 --len_dataset 1999 --num_folds 1 --using_act layer --token answer_last --method individual_linear_hallu_pos --bs 128 --epochs 50 --lr 0.5 --save_probes True --save_path ~/honest_llama_data --fast_mode True  --plot_name linear-n-0.5b --tag main-baseline --use_best_val_t True

python get_activations_and_probe_non_linear_supcon_bce.py alpaca_7B gsm8k --train_file_name gsm8k_greedy_responses_train2000 --test_file_name gsm8k_greedy_responses_test1800 --len_dataset 1999 --num_folds 1 --using_act layer --token answer_last --method individual_linear_hallu_pos --bs 128 --epochs 50 --lr 0.00005 --norm_input True --save_probes True --save_path ~/honest_llama_data --fast_mode True  --plot_name linear-n-norm-0.00005b --tag main-baseline --use_best_val_t True
python get_activations_and_probe_non_linear_supcon_bce.py alpaca_7B gsm8k --train_file_name gsm8k_greedy_responses_train2000 --test_file_name gsm8k_greedy_responses_test1800 --len_dataset 1999 --num_folds 1 --using_act layer --token answer_last --method individual_linear_hallu_pos --bs 128 --epochs 50 --lr 0.0005 --norm_input True --save_probes True --save_path ~/honest_llama_data --fast_mode True  --plot_name linear-n-norm-0.0005b --tag main-baseline --use_best_val_t True
python get_activations_and_probe_non_linear_supcon_bce.py alpaca_7B gsm8k --train_file_name gsm8k_greedy_responses_train2000 --test_file_name gsm8k_greedy_responses_test1800 --len_dataset 1999 --num_folds 1 --using_act layer --token answer_last --method individual_linear_hallu_pos --bs 128 --epochs 50 --lr 0.005 --norm_input True --save_probes True --save_path ~/honest_llama_data --fast_mode True  --plot_name linear-n-norm-0.005b --tag main-baseline --use_best_val_t True
python get_activations_and_probe_non_linear_supcon_bce.py alpaca_7B gsm8k --train_file_name gsm8k_greedy_responses_train2000 --test_file_name gsm8k_greedy_responses_test1800 --len_dataset 1999 --num_folds 1 --using_act layer --token answer_last --method individual_linear_hallu_pos --bs 128 --epochs 50 --lr 0.05 --norm_input True --save_probes True --save_path ~/honest_llama_data --fast_mode True  --plot_name linear-n-norm-0.05b --tag main-baseline --use_best_val_t True
python get_activations_and_probe_non_linear_supcon_bce.py alpaca_7B gsm8k --train_file_name gsm8k_greedy_responses_train2000 --test_file_name gsm8k_greedy_responses_test1800 --len_dataset 1999 --num_folds 1 --using_act layer --token answer_last --method individual_linear_hallu_pos --bs 128 --epochs 50 --lr 0.5 --norm_input True --save_probes True --save_path ~/honest_llama_data --fast_mode True  --plot_name linear-n-norm-0.5b --tag main-baseline --use_best_val_t True

python get_activations_and_probe_non_linear_supcon_bce.py alpaca_7B gsm8k --train_file_name gsm8k_greedy_responses_train2000 --test_file_name gsm8k_greedy_responses_test1800 --len_dataset 1999 --num_folds 1 --using_act layer --token answer_last --method individual_non_linear_4_hallu_pos --bs 128 --epochs 50 --lr 0.00005 --save_probes True --save_path ~/honest_llama_data --fast_mode True  --plot_name nlinear-n-0.00005b --tag main-baseline --use_best_val_t True
python get_activations_and_probe_non_linear_supcon_bce.py alpaca_7B gsm8k --train_file_name gsm8k_greedy_responses_train2000 --test_file_name gsm8k_greedy_responses_test1800 --len_dataset 1999 --num_folds 1 --using_act layer --token answer_last --method individual_non_linear_4_hallu_pos --bs 128 --epochs 50 --lr 0.0005 --save_probes True --save_path ~/honest_llama_data --fast_mode True  --plot_name nlinear-n-0.0005b --tag main-baseline --use_best_val_t True
python get_activations_and_probe_non_linear_supcon_bce.py alpaca_7B gsm8k --train_file_name gsm8k_greedy_responses_train2000 --test_file_name gsm8k_greedy_responses_test1800 --len_dataset 1999 --num_folds 1 --using_act layer --token answer_last --method individual_non_linear_4_hallu_pos --bs 128 --epochs 50 --lr 0.005 --save_probes True --save_path ~/honest_llama_data --fast_mode True  --plot_name nlinear-n-0.005b --tag main-baseline --use_best_val_t True
python get_activations_and_probe_non_linear_supcon_bce.py alpaca_7B gsm8k --train_file_name gsm8k_greedy_responses_train2000 --test_file_name gsm8k_greedy_responses_test1800 --len_dataset 1999 --num_folds 1 --using_act layer --token answer_last --method individual_non_linear_4_hallu_pos --bs 128 --epochs 50 --lr 0.05 --save_probes True --save_path ~/honest_llama_data --fast_mode True  --plot_name nlinear-n-0.05b --tag main-baseline --use_best_val_t True
python get_activations_and_probe_non_linear_supcon_bce.py alpaca_7B gsm8k --train_file_name gsm8k_greedy_responses_train2000 --test_file_name gsm8k_greedy_responses_test1800 --len_dataset 1999 --num_folds 1 --using_act layer --token answer_last --method individual_non_linear_4_hallu_pos --bs 128 --epochs 50 --lr 0.5 --save_probes True --save_path ~/honest_llama_data --fast_mode True  --plot_name nlinear-n-0.5b --tag main-baseline --use_best_val_t True

python get_activations_and_probe_non_linear_supcon_bce.py alpaca_7B gsm8k --train_file_name gsm8k_greedy_responses_train2000 --test_file_name gsm8k_greedy_responses_test1800 --len_dataset 1999 --num_folds 1 --using_act layer --token answer_last --method individual_non_linear_4_hallu_pos --bs 128 --epochs 50 --lr 0.00005 --norm_input True --save_probes True --save_path ~/honest_llama_data --fast_mode True  --plot_name nlinear-n-norm-0.00005b --tag main-baseline --use_best_val_t True
python get_activations_and_probe_non_linear_supcon_bce.py alpaca_7B gsm8k --train_file_name gsm8k_greedy_responses_train2000 --test_file_name gsm8k_greedy_responses_test1800 --len_dataset 1999 --num_folds 1 --using_act layer --token answer_last --method individual_non_linear_4_hallu_pos --bs 128 --epochs 50 --lr 0.0005 --norm_input True --save_probes True --save_path ~/honest_llama_data --fast_mode True  --plot_name nlinear-n-norm-0.0005b --tag main-baseline --use_best_val_t True
python get_activations_and_probe_non_linear_supcon_bce.py alpaca_7B gsm8k --train_file_name gsm8k_greedy_responses_train2000 --test_file_name gsm8k_greedy_responses_test1800 --len_dataset 1999 --num_folds 1 --using_act layer --token answer_last --method individual_non_linear_4_hallu_pos --bs 128 --epochs 50 --lr 0.005 --norm_input True --save_probes True --save_path ~/honest_llama_data --fast_mode True  --plot_name nlinear-n-norm-0.005b --tag main-baseline --use_best_val_t True
python get_activations_and_probe_non_linear_supcon_bce.py alpaca_7B gsm8k --train_file_name gsm8k_greedy_responses_train2000 --test_file_name gsm8k_greedy_responses_test1800 --len_dataset 1999 --num_folds 1 --using_act layer --token answer_last --method individual_non_linear_4_hallu_pos --bs 128 --epochs 50 --lr 0.05 --norm_input True --save_probes True --save_path ~/honest_llama_data --fast_mode True  --plot_name nlinear-n-norm-0.05b --tag main-baseline --use_best_val_t True
python get_activations_and_probe_non_linear_supcon_bce.py alpaca_7B gsm8k --train_file_name gsm8k_greedy_responses_train2000 --test_file_name gsm8k_greedy_responses_test1800 --len_dataset 1999 --num_folds 1 --using_act layer --token answer_last --method individual_non_linear_4_hallu_pos --bs 128 --epochs 50 --lr 0.5 --norm_input True --save_probes True --save_path ~/honest_llama_data --fast_mode True  --plot_name nlinear-n-norm-0.5b --tag main-baseline --use_best_val_t True

python get_activations.py alpaca_7B strqa --token answer_last --file_name strqa_baseline_responses_train  --device 0 --save_path ~/honest_llama_data
python get_activations.py alpaca_7B strqa --token answer_last --file_name strqa_baseline_responses_test  --device 0 --save_path ~/honest_llama_data

python get_activations_and_probe_non_linear_supcon_bce.py alpaca_7B strqa --train_file_name strqa_baseline_responses_train --test_file_name strqa_baseline_responses_test --len_dataset 1832 --num_folds 1 --using_act layer --token answer_last --method individual_non_linear_4_hallu_pos --bs 128 --epochs 50 --lr 0.00005 --save_probes True --save_path ~/honest_llama_data --fast_mode True --plot_name nlinear-n-0.00005b --tag main-baseline --use_best_val_t True
python get_activations_and_probe_non_linear_supcon_bce.py alpaca_7B strqa --train_file_name strqa_baseline_responses_train --test_file_name strqa_baseline_responses_test --len_dataset 1832 --num_folds 1 --using_act layer --token answer_last --method individual_non_linear_4_hallu_pos --bs 128 --epochs 50 --lr 0.0005 --save_probes True --save_path ~/honest_llama_data --fast_mode True --plot_name nlinear-n-0.0005b --tag main-baseline --use_best_val_t True
python get_activations_and_probe_non_linear_supcon_bce.py alpaca_7B strqa --train_file_name strqa_baseline_responses_train --test_file_name strqa_baseline_responses_test --len_dataset 1832 --num_folds 1 --using_act layer --token answer_last --method individual_non_linear_4_hallu_pos --bs 128 --epochs 50 --lr 0.005 --save_probes True --save_path ~/honest_llama_data --fast_mode True --plot_name nlinear-n-0.005b --tag main-baseline --use_best_val_t True
python get_activations_and_probe_non_linear_supcon_bce.py alpaca_7B strqa --train_file_name strqa_baseline_responses_train --test_file_name strqa_baseline_responses_test --len_dataset 1832 --num_folds 1 --using_act layer --token answer_last --method individual_non_linear_4_hallu_pos --bs 128 --epochs 50 --lr 0.05 --save_probes True --save_path ~/honest_llama_data --fast_mode True --plot_name nlinear-n-0.05b --tag main-baseline --use_best_val_t True
python get_activations_and_probe_non_linear_supcon_bce.py alpaca_7B strqa --train_file_name strqa_baseline_responses_train --test_file_name strqa_baseline_responses_test --len_dataset 1832 --num_folds 1 --using_act layer --token answer_last --method individual_non_linear_4_hallu_pos --bs 128 --epochs 50 --lr 0.5 --save_probes True --save_path ~/honest_llama_data --fast_mode True --plot_name nlinear-n-0.5b --tag main-baseline --use_best_val_t True

python get_activations_and_probe_non_linear_supcon_bce.py alpaca_7B strqa --train_file_name strqa_baseline_responses_train --test_file_name strqa_baseline_responses_test --len_dataset 1832 --num_folds 1 --using_act layer --token answer_last --method individual_non_linear_4_hallu_pos --bs 128 --epochs 50 --lr 0.00005 --norm_input True --save_probes True --save_path ~/honest_llama_data --fast_mode True --plot_name nlinear-n-norm-0.00005b --tag main-baseline --use_best_val_t True
python get_activations_and_probe_non_linear_supcon_bce.py alpaca_7B strqa --train_file_name strqa_baseline_responses_train --test_file_name strqa_baseline_responses_test --len_dataset 1832 --num_folds 1 --using_act layer --token answer_last --method individual_non_linear_4_hallu_pos --bs 128 --epochs 50 --lr 0.0005 --norm_input True --save_probes True --save_path ~/honest_llama_data --fast_mode True --plot_name nlinear-n-norm-0.0005b --tag main-baseline --use_best_val_t True
python get_activations_and_probe_non_linear_supcon_bce.py alpaca_7B strqa --train_file_name strqa_baseline_responses_train --test_file_name strqa_baseline_responses_test --len_dataset 1832 --num_folds 1 --using_act layer --token answer_last --method individual_non_linear_4_hallu_pos --bs 128 --epochs 50 --lr 0.005 --norm_input True --save_probes True --save_path ~/honest_llama_data --fast_mode True --plot_name nlinear-n-norm-0.005b --tag main-baseline --use_best_val_t True
python get_activations_and_probe_non_linear_supcon_bce.py alpaca_7B strqa --train_file_name strqa_baseline_responses_train --test_file_name strqa_baseline_responses_test --len_dataset 1832 --num_folds 1 --using_act layer --token answer_last --method individual_non_linear_4_hallu_pos --bs 128 --epochs 50 --lr 0.05 --norm_input True --save_probes True --save_path ~/honest_llama_data --fast_mode True --plot_name nlinear-n-norm-0.05b --tag main-baseline --use_best_val_t True
python get_activations_and_probe_non_linear_supcon_bce.py alpaca_7B strqa --train_file_name strqa_baseline_responses_train --test_file_name strqa_baseline_responses_test --len_dataset 1832 --num_folds 1 --using_act layer --token answer_last --method individual_non_linear_4_hallu_pos --bs 128 --epochs 50 --lr 0.5 --norm_input True --save_probes True --save_path ~/honest_llama_data --fast_mode True --plot_name nlinear-n-norm-0.5b --tag main-baseline --use_best_val_t True

python get_activations_and_probe_non_linear_supcon_bce.py alpaca_7B strqa --train_file_name strqa_baseline_responses_train --test_file_name strqa_baseline_responses_test --len_dataset 1832 --num_folds 1 --using_act layer --token answer_last --method individual_linear_hallu_pos --bs 128 --epochs 50 --lr 0.00005 --save_probes True --save_path ~/honest_llama_data --fast_mode True --plot_name linear-n-0.00005b --tag main-baseline --use_best_val_t True
python get_activations_and_probe_non_linear_supcon_bce.py alpaca_7B strqa --train_file_name strqa_baseline_responses_train --test_file_name strqa_baseline_responses_test --len_dataset 1832 --num_folds 1 --using_act layer --token answer_last --method individual_linear_hallu_pos --bs 128 --epochs 50 --lr 0.0005 --save_probes True --save_path ~/honest_llama_data --fast_mode True --plot_name linear-n-0.0005b --tag main-baseline --use_best_val_t True
python get_activations_and_probe_non_linear_supcon_bce.py alpaca_7B strqa --train_file_name strqa_baseline_responses_train --test_file_name strqa_baseline_responses_test --len_dataset 1832 --num_folds 1 --using_act layer --token answer_last --method individual_linear_hallu_pos --bs 128 --epochs 50 --lr 0.005 --save_probes True --save_path ~/honest_llama_data --fast_mode True --plot_name linear-n-0.005b --tag main-baseline --use_best_val_t True
python get_activations_and_probe_non_linear_supcon_bce.py alpaca_7B strqa --train_file_name strqa_baseline_responses_train --test_file_name strqa_baseline_responses_test --len_dataset 1832 --num_folds 1 --using_act layer --token answer_last --method individual_linear_hallu_pos --bs 128 --epochs 50 --lr 0.05 --save_probes True --save_path ~/honest_llama_data --fast_mode True --plot_name linear-n-0.05b --tag main-baseline --use_best_val_t True
python get_activations_and_probe_non_linear_supcon_bce.py alpaca_7B strqa --train_file_name strqa_baseline_responses_train --test_file_name strqa_baseline_responses_test --len_dataset 1832 --num_folds 1 --using_act layer --token answer_last --method individual_linear_hallu_pos --bs 128 --epochs 50 --lr 0.5 --save_probes True --save_path ~/honest_llama_data --fast_mode True --plot_name linear-n-0.5b --tag main-baseline --use_best_val_t True

python get_activations_and_probe_non_linear_supcon_bce.py alpaca_7B strqa --train_file_name strqa_baseline_responses_train --test_file_name strqa_baseline_responses_test --len_dataset 1832 --num_folds 1 --using_act layer --token answer_last --method individual_linear_hallu_pos --bs 128 --epochs 50 --lr 0.00005 --norm_input True --save_probes True --save_path ~/honest_llama_data --fast_mode True --plot_name linear-n-norm-0.00005b --tag main-baseline --use_best_val_t True
python get_activations_and_probe_non_linear_supcon_bce.py alpaca_7B strqa --train_file_name strqa_baseline_responses_train --test_file_name strqa_baseline_responses_test --len_dataset 1832 --num_folds 1 --using_act layer --token answer_last --method individual_linear_hallu_pos --bs 128 --epochs 50 --lr 0.0005 --norm_input True --save_probes True --save_path ~/honest_llama_data --fast_mode True --plot_name linear-n-norm-0.0005b --tag main-baseline --use_best_val_t True
python get_activations_and_probe_non_linear_supcon_bce.py alpaca_7B strqa --train_file_name strqa_baseline_responses_train --test_file_name strqa_baseline_responses_test --len_dataset 1832 --num_folds 1 --using_act layer --token answer_last --method individual_linear_hallu_pos --bs 128 --epochs 50 --lr 0.005 --norm_input True --save_probes True --save_path ~/honest_llama_data --fast_mode True --plot_name linear-n-norm-0.005b --tag main-baseline --use_best_val_t True
python get_activations_and_probe_non_linear_supcon_bce.py alpaca_7B strqa --train_file_name strqa_baseline_responses_train --test_file_name strqa_baseline_responses_test --len_dataset 1832 --num_folds 1 --using_act layer --token answer_last --method individual_linear_hallu_pos --bs 128 --epochs 50 --lr 0.05 --norm_input True --save_probes True --save_path ~/honest_llama_data --fast_mode True --plot_name linear-n-norm-0.05b --tag main-baseline --use_best_val_t True
python get_activations_and_probe_non_linear_supcon_bce.py alpaca_7B strqa --train_file_name strqa_baseline_responses_train --test_file_name strqa_baseline_responses_test --len_dataset 1832 --num_folds 1 --using_act layer --token answer_last --method individual_linear_hallu_pos --bs 128 --epochs 50 --lr 0.5 --norm_input True --save_probes True --save_path ~/honest_llama_data --fast_mode True --plot_name linear-n-norm-0.5b --tag main-baseline --use_best_val_t True