################################# transformer n 1 layer ##########################
# python get_activations.py alpaca_7B nq_open --token answer_last --file_name nq_open_greedy_responses_train5000  --device 0 --save_path /home/local/data/ms/honest_llama_data
# python get_activations.py alpaca_7B nq_open --token answer_last --file_name nq_open_greedy_responses_validation1800  --device 0 --save_path /home/local/data/ms/honest_llama_data

# python get_activations_and_probe_transformer.py alpaca_7B nq_open --train_file_name nq_open_greedy_responses_train5000 --test_file_name nq_open_greedy_responses_validation1800 --train_labels_file_name nq_open_greedy_responses_labels_train5000 --test_labels_file_name nq_open_greedy_responses_labels_validation1800 --len_dataset 2000 --num_folds 1 --using_act layer --token answer_last --method transformer_hallu_pos --bs 128 --epochs 50 --lr 0.00005 --save_probes True --save_path /home/local/data/ms/honest_llama_data --fast_mode True  --plot_name transformer-n-0.00005b --tag main-transformer --use_best_val_t True 
# python get_activations_and_probe_transformer.py alpaca_7B nq_open --train_file_name nq_open_greedy_responses_train5000 --test_file_name nq_open_greedy_responses_validation1800 --train_labels_file_name nq_open_greedy_responses_labels_train5000 --test_labels_file_name nq_open_greedy_responses_labels_validation1800 --len_dataset 2000 --num_folds 1 --using_act layer --token answer_last --method transformer_hallu_pos --bs 128 --epochs 50 --lr 0.0005 --save_probes True --save_path /home/local/data/ms/honest_llama_data --fast_mode True  --plot_name transformer-n-0.0005b --tag main-transformer --use_best_val_t True 

# python get_activations_and_probe_transformer.py alpaca_7B nq_open --train_file_name nq_open_greedy_responses_train5000 --test_file_name nq_open_greedy_responses_validation1800 --train_labels_file_name nq_open_greedy_responses_labels_train5000 --test_labels_file_name nq_open_greedy_responses_labels_validation1800 --len_dataset 2000 --num_folds 1 --using_act layer --token answer_last --method transformer_hallu_pos --bs 128 --epochs 50 --lr 0.00005 --save_probes True --save_path /home/local/data/ms/honest_llama_data --fast_mode True  --plot_name 101-transformer-n-0.00005b --tag main-transformer --use_best_val_t True --seed 101
# python get_activations_and_probe_transformer.py alpaca_7B nq_open --train_file_name nq_open_greedy_responses_train5000 --test_file_name nq_open_greedy_responses_validation1800 --train_labels_file_name nq_open_greedy_responses_labels_train5000 --test_labels_file_name nq_open_greedy_responses_labels_validation1800 --len_dataset 2000 --num_folds 1 --using_act layer --token answer_last --method transformer_hallu_pos --bs 128 --epochs 50 --lr 0.0005 --save_probes True --save_path /home/local/data/ms/honest_llama_data --fast_mode True  --plot_name 101-transformer-n-0.0005b --tag main-transformer --use_best_val_t True --seed 101

# python get_activations_and_probe_transformer.py alpaca_7B nq_open --train_file_name nq_open_greedy_responses_train5000 --test_file_name nq_open_greedy_responses_validation1800 --train_labels_file_name nq_open_greedy_responses_labels_train5000 --test_labels_file_name nq_open_greedy_responses_labels_validation1800 --len_dataset 2000 --num_folds 1 --using_act layer --token answer_last --method transformer_hallu_pos --bs 128 --epochs 50 --lr 0.00005 --save_probes True --save_path /home/local/data/ms/honest_llama_data --fast_mode True  --plot_name 2650-transformer-n-0.00005b --tag main-transformer --use_best_val_t True --seed 2650
# python get_activations_and_probe_transformer.py alpaca_7B nq_open --train_file_name nq_open_greedy_responses_train5000 --test_file_name nq_open_greedy_responses_validation1800 --train_labels_file_name nq_open_greedy_responses_labels_train5000 --test_labels_file_name nq_open_greedy_responses_labels_validation1800 --len_dataset 2000 --num_folds 1 --using_act layer --token answer_last --method transformer_hallu_pos --bs 128 --epochs 50 --lr 0.0005 --save_probes True --save_path /home/local/data/ms/honest_llama_data --fast_mode True  --plot_name 2650-transformer-n-0.0005b --tag main-transformer --use_best_val_t True --seed 2650

################################### transformer n*aug 1 layer ####################################

python get_activations.py alpaca_7B nq_open --token answer_last --file_name nq_open_sampledplus_responses_train2000  --device 0 --save_path /home/local/data/ms/honest_llama_data
# python get_activations.py alpaca_7B nq_open --token answer_last --file_name nq_open_greedy_responses_validation1800  --device 0 --save_path /home/local/data/ms/honest_llama_data

python get_activations_and_probe_transformer.py alpaca_7B nq_open --train_file_name nq_open_sampledplus_responses_train2000 --test_file_name nq_open_greedy_responses_validation1800 --train_labels_file_name nq_open_sampledplus_responses_labels_train2000 --test_labels_file_name nq_open_greedy_responses_labels_validation1800 --len_dataset 22000 --num_folds 1 --using_act layer --token answer_last --method transformer_hallu_pos --bs 128 --epochs 50 --lr 0.00005 --save_probes True --save_path /home/local/data/ms/honest_llama_data --fast_mode True  --plot_name transformer-n*aug-0.00005b --tag main-transformer --use_best_val_t True 
python get_activations_and_probe_transformer.py alpaca_7B nq_open --train_file_name nq_open_sampledplus_responses_train2000 --test_file_name nq_open_greedy_responses_validation1800 --train_labels_file_name nq_open_sampledplus_responses_labels_train2000 --test_labels_file_name nq_open_greedy_responses_labels_validation1800 --len_dataset 22000 --num_folds 1 --using_act layer --token answer_last --method transformer_hallu_pos --bs 128 --epochs 50 --lr 0.0005 --save_probes True --save_path /home/local/data/ms/honest_llama_data --fast_mode True  --plot_name transformer-n*aug-0.0005b --tag main-transformer --use_best_val_t True 

python get_activations_and_probe_transformer.py alpaca_7B nq_open --train_file_name nq_open_sampledplus_responses_train2000 --test_file_name nq_open_greedy_responses_validation1800 --train_labels_file_name nq_open_sampledplus_responses_labels_train2000 --test_labels_file_name nq_open_greedy_responses_labels_validation1800 --len_dataset 22000 --num_folds 1 --using_act layer --token answer_last --method transformer_hallu_pos --bs 128 --epochs 50 --lr 0.00005 --save_probes True --save_path /home/local/data/ms/honest_llama_data --fast_mode True  --plot_name 101-transformer-n*aug-0.00005b --tag main-transformer --use_best_val_t True --seed 101
python get_activations_and_probe_transformer.py alpaca_7B nq_open --train_file_name nq_open_sampledplus_responses_train2000 --test_file_name nq_open_greedy_responses_validation1800 --train_labels_file_name nq_open_sampledplus_responses_labels_train2000 --test_labels_file_name nq_open_greedy_responses_labels_validation1800 --len_dataset 22000 --num_folds 1 --using_act layer --token answer_last --method transformer_hallu_pos --bs 128 --epochs 50 --lr 0.0005 --save_probes True --save_path /home/local/data/ms/honest_llama_data --fast_mode True  --plot_name 101-transformer-n*aug-0.0005b --tag main-transformer --use_best_val_t True --seed 101

python get_activations_and_probe_transformer.py alpaca_7B nq_open --train_file_name nq_open_sampledplus_responses_train2000 --test_file_name nq_open_greedy_responses_validation1800 --train_labels_file_name nq_open_sampledplus_responses_labels_train2000 --test_labels_file_name nq_open_greedy_responses_labels_validation1800 --len_dataset 22000 --num_folds 1 --using_act layer --token answer_last --method transformer_hallu_pos --bs 128 --epochs 50 --lr 0.00005 --save_probes True --save_path /home/local/data/ms/honest_llama_data --fast_mode True  --plot_name 2650-transformer-n*aug-0.00005b --tag main-transformer --use_best_val_t True --seed 2650
python get_activations_and_probe_transformer.py alpaca_7B nq_open --train_file_name nq_open_sampledplus_responses_train2000 --test_file_name nq_open_greedy_responses_validation1800 --train_labels_file_name nq_open_sampledplus_responses_labels_train2000 --test_labels_file_name nq_open_greedy_responses_labels_validation1800 --len_dataset 22000 --num_folds 1 --using_act layer --token answer_last --method transformer_hallu_pos --bs 128 --epochs 50 --lr 0.0005 --save_probes True --save_path /home/local/data/ms/honest_llama_data --fast_mode True  --plot_name 2650-transformer-n*aug-0.0005b --tag main-transformer --use_best_val_t True --seed 2650

################################ transformer n 2 layer ##########################################

# python get_activations_and_probe_transformer.py alpaca_7B nq_open --train_file_name nq_open_greedy_responses_train5000 --test_file_name nq_open_greedy_responses_validation1800 --train_labels_file_name nq_open_greedy_responses_labels_train5000 --test_labels_file_name nq_open_greedy_responses_labels_validation1800 --len_dataset 2000 --num_folds 1 --using_act layer --token answer_last --method transformer2_hallu_pos --bs 128 --epochs 50 --lr 0.00005 --save_probes True --save_path /home/local/data/ms/honest_llama_data --fast_mode True  --plot_name transformer2-n-0.00005b --tag main-transformer --use_best_val_t True 
# python get_activations_and_probe_transformer.py alpaca_7B nq_open --train_file_name nq_open_greedy_responses_train5000 --test_file_name nq_open_greedy_responses_validation1800 --train_labels_file_name nq_open_greedy_responses_labels_train5000 --test_labels_file_name nq_open_greedy_responses_labels_validation1800 --len_dataset 2000 --num_folds 1 --using_act layer --token answer_last --method transformer2_hallu_pos --bs 128 --epochs 50 --lr 0.0005 --save_probes True --save_path /home/local/data/ms/honest_llama_data --fast_mode True  --plot_name transformer2-n-0.0005b --tag main-transformer --use_best_val_t True 

# python get_activations_and_probe_transformer.py alpaca_7B nq_open --train_file_name nq_open_greedy_responses_train5000 --test_file_name nq_open_greedy_responses_validation1800 --train_labels_file_name nq_open_greedy_responses_labels_train5000 --test_labels_file_name nq_open_greedy_responses_labels_validation1800 --len_dataset 2000 --num_folds 1 --using_act layer --token answer_last --method transformer2_hallu_pos --bs 128 --epochs 50 --lr 0.00005 --save_probes True --save_path /home/local/data/ms/honest_llama_data --fast_mode True  --plot_name 101-transformer2-n-0.00005b --tag main-transformer --use_best_val_t True --seed 101
# python get_activations_and_probe_transformer.py alpaca_7B nq_open --train_file_name nq_open_greedy_responses_train5000 --test_file_name nq_open_greedy_responses_validation1800 --train_labels_file_name nq_open_greedy_responses_labels_train5000 --test_labels_file_name nq_open_greedy_responses_labels_validation1800 --len_dataset 2000 --num_folds 1 --using_act layer --token answer_last --method transformer2_hallu_pos --bs 128 --epochs 50 --lr 0.0005 --save_probes True --save_path /home/local/data/ms/honest_llama_data --fast_mode True  --plot_name 101-transformer2-n-0.0005b --tag main-transformer --use_best_val_t True --seed 101

# python get_activations_and_probe_transformer.py alpaca_7B nq_open --train_file_name nq_open_greedy_responses_train5000 --test_file_name nq_open_greedy_responses_validation1800 --train_labels_file_name nq_open_greedy_responses_labels_train5000 --test_labels_file_name nq_open_greedy_responses_labels_validation1800 --len_dataset 2000 --num_folds 1 --using_act layer --token answer_last --method transformer2_hallu_pos --bs 128 --epochs 50 --lr 0.00005 --save_probes True --save_path /home/local/data/ms/honest_llama_data --fast_mode True  --plot_name 2650-transformer2-n-0.00005b --tag main-transformer --use_best_val_t True --seed 2650
# python get_activations_and_probe_transformer.py alpaca_7B nq_open --train_file_name nq_open_greedy_responses_train5000 --test_file_name nq_open_greedy_responses_validation1800 --train_labels_file_name nq_open_greedy_responses_labels_train5000 --test_labels_file_name nq_open_greedy_responses_labels_validation1800 --len_dataset 2000 --num_folds 1 --using_act layer --token answer_last --method transformer2_hallu_pos --bs 128 --epochs 50 --lr 0.0005 --save_probes True --save_path /home/local/data/ms/honest_llama_data --fast_mode True  --plot_name 2650-transformer2-n-0.0005b --tag main-transformer --use_best_val_t True --seed 2650