################################# transformer n 1 layer ##########################
# python get_activations.py hl_llama_7B strqa --token answer_last --file_name strqa_baseline_responses_train  --device 0 --save_path /home/local/data/ms/honest_llama_data
# python get_activations.py hl_llama_7B strqa --token answer_last --file_name strqa_baseline_responses_test  --device 0 --save_path /home/local/data/ms/honest_llama_data

python get_activations_and_probe_transformer.py hl_llama_7B multi --dataset_list trivia_qa,nq_open,strqa --train_name_list trivia_qa_greedy_responses_train5000,nq_open_greedy_responses_train5000,strqa_baseline_responses_train --train_labels_name_list trivia_qa_greedy_responses_labels_train5000,nq_open_greedy_responses_labels_train5000,strqa_baseline_responses_train --test_file_name strqa_baseline_responses_test --len_dataset_list 5000,5000,1832 --num_folds 1 --using_act layer --token answer_last --method transformer_hallu_pos --bs 128 --epochs 50 --lr_list 0.00005,0.0005,0.005 --save_probes True --save_path /home/local/data/ms/honest_llama_data --fast_mode True  --plot_name transformer-n --tag main-transformer-5kbestauc-comb --use_best_val_t True  --seed_list 42,101,2650 --best_using_auc True

################################### transformer n*aug 1 layer ####################################

# python get_activations.py hl_llama_7B strqa --token answer_last --file_name strqa_sampledplus_responses_train  --device 0 --save_path /home/local/data/ms/honest_llama_data
# python get_activations.py hl_llama_7B strqa --token answer_last --file_name strqa_baseline_responses_test  --device 0 --save_path /home/local/data/ms/honest_llama_data

# python get_activations_and_probe_transformer.py hl_llama_7B multi --dataset_list trivia_qa,nq_open,strqa --train_name_list trivia_qa_greedy_responses_train5000,nq_open_greedy_responses_train5000,strqa_baseline_responses_train --train_labels_name_list trivia_qa_greedy_responses_labels_train5000,nq_open_greedy_responses_labels_train5000,strqa_baseline_responses_train --test_file_name strqa_baseline_responses_test --len_dataset_list 5000,5000,1832 --num_folds 1 --using_act layer --token answer_last --method transformer_hallu_pos --bs 128 --epochs 50 --lr_list 0.00005,0.0005,0.005 --save_probes True --save_path /home/local/data/ms/honest_llama_data --fast_mode True  --plot_name transformer-n*aug --tag main-transformer-5kbestauc-comb --use_best_val_t True  --seed_list 42,101,2650 --best_using_auc True

################################ transformer n 2 layer ##########################################
python get_activations_and_probe_transformer.py hl_llama_7B multi --dataset_list trivia_qa,nq_open,strqa --train_name_list trivia_qa_greedy_responses_train5000,nq_open_greedy_responses_train5000,strqa_baseline_responses_train --train_labels_name_list trivia_qa_greedy_responses_labels_train5000,nq_open_greedy_responses_labels_train5000,strqa_baseline_responses_train --test_file_name strqa_baseline_responses_test --len_dataset_list 5000,5000,1832 --num_folds 1 --using_act layer --token answer_last --method transformer2_hallu_pos --bs 128 --epochs 50 --lr_list 0.00005,0.0005,0.005 --save_probes True --save_path /home/local/data/ms/honest_llama_data --fast_mode True  --plot_name transformer2-n --tag main-transformer-5kbestauc-comb --use_best_val_t True  --seed_list 42,101,2650 --best_using_auc True

################################# transformer n 1 layer : ntx ##########################
# python get_activations_and_probe_transformer.py hl_llama_7B multi --dataset_list trivia_qa,nq_open,strqa --train_name_list trivia_qa_greedy_responses_train5000,nq_open_greedy_responses_train5000,strqa_baseline_responses_train --train_labels_name_list trivia_qa_greedy_responses_labels_train5000,nq_open_greedy_responses_labels_train5000,strqa_baseline_responses_train --test_file_name strqa_baseline_responses_test --len_dataset_list 5000,5000,1832 --num_folds 1 --using_act layer --token answer_last --method transformer_supcon_hallu_pos --bs 256 --epochs 500 --lr_list 0.000005,0.00005,0.0005,0.005 --save_probes True --save_path /home/local/data/ms/honest_llama_data --fast_mode True  --plot_name transformer_ntx-n --tag main-transformer-contrast-5kbestauc-comb --use_best_val_t True --seed_list 42,101,2650 --best_using_auc True

################################# transformer n 1 layer : supcon ##########################
# python get_activations_and_probe_transformer.py hl_llama_7B multi --dataset_list trivia_qa,nq_open,strqa --train_name_list trivia_qa_greedy_responses_train5000,nq_open_greedy_responses_train5000,strqa_baseline_responses_train --train_labels_name_list trivia_qa_greedy_responses_labels_train5000,nq_open_greedy_responses_labels_train5000,strqa_baseline_responses_train --test_file_name strqa_baseline_responses_test --len_dataset_list 5000,5000,1832 --num_folds 1 --using_act layer --token answer_last --method transformer_supconv2_hallu_pos --bs 256 --epochs 500 --lr_list 0.000005,0.00005,0.0005,0.005 --save_probes True --save_path /home/local/data/ms/honest_llama_data --fast_mode True  --plot_name transformer_supconv2-n --tag main-transformer-contrast-5kbestauc-comb --use_best_val_t True  --seed_list 42,101,2650 --best_using_auc True

################################# transformer n*aug 1 layer : ntx ##########################
# python get_activations_and_probe_transformer.py hl_llama_7B multi --dataset_list trivia_qa,nq_open,strqa --train_name_list trivia_qa_greedy_responses_train5000,nq_open_greedy_responses_train5000,strqa_baseline_responses_train --train_labels_name_list trivia_qa_greedy_responses_labels_train5000,nq_open_greedy_responses_labels_train5000,strqa_baseline_responses_train --test_file_name strqa_baseline_responses_test --len_dataset_list 5000,5000,1832 --num_folds 1 --using_act layer --token answer_last --method transformer_supcon_hallu_pos --bs 256 --epochs 500 --lr_list 0.000005,0.00005,0.0005,0.005 --save_probes True --save_path /home/local/data/ms/honest_llama_data --fast_mode True  --plot_name transformer_ntx-n*aug --tag main-transformer-contrast-5kbestauc-comb --use_best_val_t True   --seed_list 42,101,2650 --best_using_auc True

################################# transformer n*aug 1 layer : supcon ##########################
# python get_activations_and_probe_transformer.py hl_llama_7B multi --dataset_list trivia_qa,nq_open,strqa --train_name_list trivia_qa_greedy_responses_train5000,nq_open_greedy_responses_train5000,strqa_baseline_responses_train --train_labels_name_list trivia_qa_greedy_responses_labels_train5000,nq_open_greedy_responses_labels_train5000,strqa_baseline_responses_train --test_file_name strqa_baseline_responses_test --len_dataset_list 5000,5000,1832 --num_folds 1 --using_act layer --token answer_last --method transformer_supconv2_hallu_pos --bs 256 --epochs 500 --lr_list 0.000005,0.00005,0.0005,0.005 --save_probes True --save_path /home/local/data/ms/honest_llama_data --fast_mode True  --plot_name transformer_supconv2-n*aug --tag main-transformer-contrast-5kbestauc-comb --use_best_val_t True   --seed_list 42,101,2650 --best_using_auc True
# python get_activations_and_probe_transformer.py hl_llama_7B multi --dataset_list trivia_qa,nq_open,strqa --train_name_list trivia_qa_greedy_responses_train5000,nq_open_greedy_responses_train5000,strqa_baseline_responses_train --train_labels_name_list trivia_qa_greedy_responses_labels_train5000,nq_open_greedy_responses_labels_train5000,strqa_baseline_responses_train --test_file_name strqa_baseline_responses_test --len_dataset_list 5000,5000,1832 --num_folds 1 --using_act layer --token answer_last --method transformer_supconv2_hallu_pos --bs 270 --epochs 500 --lr_list 0.000005,0.00005,0.0005,0.005 --save_probes True --save_path /home/local/data/ms/honest_llama_data --fast_mode True  --plot_name transformer_supconv2-n*aug-b --tag main-transformer-contrast-5kbestauc-comb --use_best_val_t True   --seed_list 42,101,2650 --best_using_auc True  --no_batch_sampling True

################################# transformer n 1 layer : supcon+ ##########################
# python get_activations_and_probe_transformer.py hl_llama_7B multi --dataset_list trivia_qa,nq_open,strqa --train_name_list trivia_qa_greedy_responses_train5000,nq_open_greedy_responses_train5000,strqa_baseline_responses_train --train_labels_name_list trivia_qa_greedy_responses_labels_train5000,nq_open_greedy_responses_labels_train5000,strqa_baseline_responses_train --test_file_name strqa_baseline_responses_test --len_dataset_list 5000,5000,1832 --num_folds 1 --using_act layer --token answer_last --method transformer_supconv2_pos_hallu_pos --bs 256 --epochs 500 --lr_list 0.000005,0.00005,0.0005,0.005 --save_probes True --save_path /home/local/data/ms/honest_llama_data --fast_mode True  --plot_name transformer_supconv2_pos-n --tag main-transformer-contrast-5kbestauc-comb --use_best_val_t True  --seed_list 42,101,2650 --best_using_auc True

################################# transformer n*aug 1 layer : supcon+ ##########################
# python get_activations_and_probe_transformer.py hl_llama_7B multi --dataset_list trivia_qa,nq_open,strqa --train_name_list trivia_qa_greedy_responses_train5000,nq_open_greedy_responses_train5000,strqa_baseline_responses_train --train_labels_name_list trivia_qa_greedy_responses_labels_train5000,nq_open_greedy_responses_labels_train5000,strqa_baseline_responses_train --test_file_name strqa_baseline_responses_test --len_dataset_list 5000,5000,1832 --num_folds 1 --using_act layer --token answer_last --method transformer_supconv2_pos_hallu_pos --bs 256 --epochs 500 --lr_list 0.000005,0.00005,0.0005,0.005 --save_probes True --save_path /home/local/data/ms/honest_llama_data --fast_mode True  --plot_name transformer_supconv2_pos-n*aug --tag main-transformer-contrast-5kbestauc-comb --use_best_val_t True   --seed_list 42,101,2650 --best_using_auc True
# python get_activations_and_probe_transformer.py hl_llama_7B multi --dataset_list trivia_qa,nq_open,strqa --train_name_list trivia_qa_greedy_responses_train5000,nq_open_greedy_responses_train5000,strqa_baseline_responses_train --train_labels_name_list trivia_qa_greedy_responses_labels_train5000,nq_open_greedy_responses_labels_train5000,strqa_baseline_responses_train --test_file_name strqa_baseline_responses_test --len_dataset_list 5000,5000,1832 --num_folds 1 --using_act layer --token answer_last --method transformer_supconv2_pos_hallu_pos --bs 270 --epochs 500 --lr_list 0.000005,0.00005,0.0005,0.005 --save_probes True --save_path /home/local/data/ms/honest_llama_data --fast_mode True  --plot_name transformer_supconv2_pos-n*aug-b --tag main-transformer-contrast-5kbestauc-comb --use_best_val_t True   --seed_list 42,101,2650 --best_using_auc True --no_batch_sampling True

################################# transformer n*aug 1 layer : supcon* ##########################
# python get_activations_and_probe_transformer.py hl_llama_7B multi --dataset_list trivia_qa,nq_open,strqa --train_name_list trivia_qa_greedy_responses_train5000,nq_open_greedy_responses_train5000,strqa_baseline_responses_train --train_labels_name_list trivia_qa_greedy_responses_labels_train5000,nq_open_greedy_responses_labels_train5000,strqa_baseline_responses_train --test_file_name strqa_baseline_responses_test --len_dataset_list 5000,5000,1832 --num_folds 1 --using_act layer --token answer_last --method transformer_supconv2_wp_hallu_pos --bs 270 --epochs 500 --lr_list 0.000005,0.00005,0.0005,0.005 --save_probes True --save_path /home/local/data/ms/honest_llama_data --fast_mode True  --plot_name transformer_supconv2_wp-n*aug-b --tag main-transformer-contrast-5kbestauc-comb --use_best_val_t True   --seed_list 42,101,2650 --best_using_auc True  --no_batch_sampling True

################################# transformer n*aug 1 layer : supcon+* ##########################
# python get_activations_and_probe_transformer.py hl_llama_7B multi --dataset_list trivia_qa,nq_open,strqa --train_name_list trivia_qa_greedy_responses_train5000,nq_open_greedy_responses_train5000,strqa_baseline_responses_train --train_labels_name_list trivia_qa_greedy_responses_labels_train5000,nq_open_greedy_responses_labels_train5000,strqa_baseline_responses_train --test_file_name strqa_baseline_responses_test --len_dataset_list 5000,5000,1832 --num_folds 1 --using_act layer --token answer_last --method transformer_supconv2_pos_wp_hallu_pos --bs 270 --epochs 500 --lr_list 0.000005,0.00005,0.0005,0.005 --save_probes True --save_path /home/local/data/ms/honest_llama_data --fast_mode True  --plot_name transformer_supconv2_pos_wp-n*aug-b --tag main-transformer-contrast-5kbestauc-comb --use_best_val_t True   --seed_list 42,101,2650 --best_using_auc True  --no_batch_sampling True
# python get_activations_and_probe_transformer.py hl_llama_7B multi --dataset_list trivia_qa,nq_open,strqa --train_name_list trivia_qa_greedy_responses_train5000,nq_open_greedy_responses_train5000,strqa_baseline_responses_train --train_labels_name_list trivia_qa_greedy_responses_labels_train5000,nq_open_greedy_responses_labels_train5000,strqa_baseline_responses_train --test_file_name strqa_baseline_responses_test --len_dataset_list 5000,5000,1832 --num_folds 1 --using_act layer --token answer_last --method transformer_supconv2_pos_wp_hallu_pos --bs 270 --epochs 500 --lr_list 0.000005,0.00005,0.0005,0.005 --save_probes True --save_path /home/local/data/ms/honest_llama_data --fast_mode True  --plot_name transformer_supconv2_pos_wp1-n*aug-b --tag main-transformer-contrast-5kbestauc-comb --use_best_val_t True   --seed_list 42,101,2650 --best_using_auc True  --no_batch_sampling True --sc2_wgt 2 # 1,2