python get_activations_and_probe_non_linear_supcon_bce.py hl_llama_7B multi --dataset_list city_country,player_date_birth --train_name_list city_country_sampledplus_responses_train1000,player_date_birth_sampledplus_responses_train1000 --test_file_name player_date_birth_greedy_responses_test1498 --train_labels_name_list city_country_sampledplus_responses_labels_train1000,player_date_birth_sampledplus_responses_labels_train1000 --test_labels_file_name player_date_birth_greedy_responses_labels_test1498 --len_dataset_list 11000,11000 --num_folds 1 --using_act layer --token answer_last --method individual_linear_hallu_pos --bs 128 --epochs 50 --lr_list 0.00005,0.0005,0.005,0.05,0.5 --save_probes True --save_path /home/local/data/ms/honest_llama_data --fast_mode True  --use_best_val_t True --best_using_auc True --seed_list 42,101,2650  --test_num_samples 1
python get_activations_and_probe_transformer.py hl_llama_7B multi --dataset_list city_country,player_date_birth --train_name_list city_country_sampledplus_responses_train1000,player_date_birth_sampledplus_responses_train1000 --test_file_name player_date_birth_greedy_responses_test1498 --train_labels_name_list city_country_sampledplus_responses_labels_train1000,player_date_birth_sampledplus_responses_labels_train1000 --test_labels_file_name player_date_birth_greedy_responses_labels_test1498 --len_dataset_list 11000,11000 --num_folds 1 --using_act layer --token answer_last --method transformer_hallu_pos --bs 128 --epochs 50 --lr_list 0.00005,0.0005,0.005,0.05,0.5 --save_probes True --save_path /home/local/data/ms/honest_llama_data --fast_mode True  --use_best_val_t True --best_using_auc True --seed_list 42,101,2650  --test_num_samples 1
python get_activations_and_probe_non_linear_supcon_bce.py hl_llama_7B multi --dataset_list city_country,player_date_birth --train_name_list city_country_sampledplus_responses_train1000,player_date_birth_sampledplus_responses_train1000 --test_file_name city_country_greedy_responses_test1581 --train_labels_name_list city_country_sampledplus_responses_labels_train1000,player_date_birth_sampledplus_responses_labels_train1000 --test_labels_file_name city_country_greedy_responses_labels_test1581 --len_dataset_list 11000,11000 --num_folds 1 --using_act layer --token answer_last --method individual_linear_hallu_pos --bs 128 --epochs 50 --lr_list 0.00005,0.0005,0.005,0.05,0.5 --save_probes True --save_path /home/local/data/ms/honest_llama_data --fast_mode True  --use_best_val_t True --best_using_auc True --seed_list 42,101,2650  --test_num_samples 1 --skip_train True --multi_probe_dataset_name player_date_birth
python get_activations_and_probe_transformer.py hl_llama_7B multi --dataset_list city_country,player_date_birth --train_name_list city_country_sampledplus_responses_train1000,player_date_birth_sampledplus_responses_train1000 --test_file_name city_country_greedy_responses_test1581 --train_labels_name_list city_country_sampledplus_responses_labels_train1000,player_date_birth_sampledplus_responses_labels_train1000 --test_labels_file_name city_country_greedy_responses_labels_test1581 --len_dataset_list 11000,11000 --num_folds 1 --using_act layer --token answer_last --method transformer_hallu_pos --bs 128 --epochs 50 --lr_list 0.00005,0.0005,0.005,0.05,0.5 --save_probes True --save_path /home/local/data/ms/honest_llama_data --fast_mode True  --use_best_val_t True --best_using_auc True --seed_list 42,101,2650  --test_num_samples 1 --skip_train True --multi_probe_dataset_name player_date_birth
python get_activations_and_probe_non_linear_supcon_bce.py hl_llama_7B multi --dataset_list city_country,player_date_birth --train_name_list city_country_sampledplus_responses_train1000,player_date_birth_sampledplus_responses_train1000 --test_file_name movie_cast_greedy_responses_test2179 --train_labels_name_list city_country_sampledplus_responses_labels_train1000,player_date_birth_sampledplus_responses_labels_train1000 --test_labels_file_name movie_cast_greedy_responses_labels_test2179 --len_dataset_list 11000,11000 --num_folds 1 --using_act layer --token answer_last --method individual_linear_hallu_pos --bs 128 --epochs 50 --lr_list 0.00005,0.0005,0.005,0.05,0.5 --save_probes True --save_path /home/local/data/ms/honest_llama_data --fast_mode True  --use_best_val_t True --best_using_auc True --seed_list 42,101,2650  --test_num_samples 1 --skip_train True --multi_probe_dataset_name player_date_birth
python get_activations_and_probe_transformer.py hl_llama_7B multi --dataset_list city_country,player_date_birth --train_name_list city_country_sampledplus_responses_train1000,player_date_birth_sampledplus_responses_train1000 --test_file_name movie_cast_greedy_responses_test2179 --train_labels_name_list city_country_sampledplus_responses_labels_train1000,player_date_birth_sampledplus_responses_labels_train1000 --test_labels_file_name movie_cast_greedy_responses_labels_test2179 --len_dataset_list 11000,11000 --num_folds 1 --using_act layer --token answer_last --method transformer_hallu_pos --bs 128 --epochs 50 --lr_list 0.00005,0.0005,0.005,0.05,0.5 --save_probes True --save_path /home/local/data/ms/honest_llama_data --fast_mode True  --use_best_val_t True --best_using_auc True --seed_list 42,101,2650  --test_num_samples 1 --skip_train True --multi_probe_dataset_name player_date_birth
python get_activations_and_probe_non_linear_supcon_bce.py hl_llama_7B multi --dataset_list city_country,player_date_birth --train_name_list city_country_sampledplus_responses_train1000,player_date_birth_sampledplus_responses_train1000 --test_file_name trivia_qa_greedy_responses_validation1800 --train_labels_name_list city_country_sampledplus_responses_labels_train1000,player_date_birth_sampledplus_responses_labels_train1000 --test_labels_file_name trivia_qa_greedy_responses_labels_validation1800 --len_dataset_list 11000,11000 --num_folds 1 --using_act layer --token answer_last --method individual_linear_hallu_pos --bs 128 --epochs 50 --lr_list 0.00005,0.0005,0.005,0.05,0.5 --save_probes True --save_path /home/local/data/ms/honest_llama_data --fast_mode True  --use_best_val_t True --best_using_auc True --seed_list 42,101,2650  --test_num_samples 1 --skip_train True --multi_probe_dataset_name player_date_birth
python get_activations_and_probe_transformer.py hl_llama_7B multi --dataset_list city_country,player_date_birth --train_name_list city_country_sampledplus_responses_train1000,player_date_birth_sampledplus_responses_train1000 --test_file_name trivia_qa_greedy_responses_validation1800 --train_labels_name_list city_country_sampledplus_responses_labels_train1000,player_date_birth_sampledplus_responses_labels_train1000 --test_labels_file_name trivia_qa_greedy_responses_labels_validation1800 --len_dataset_list 11000,11000 --num_folds 1 --using_act layer --token answer_last --method transformer_hallu_pos --bs 128 --epochs 50 --lr_list 0.00005,0.0005,0.005,0.05,0.5 --save_probes True --save_path /home/local/data/ms/honest_llama_data --fast_mode True  --use_best_val_t True --best_using_auc True --seed_list 42,101,2650  --test_num_samples 1 --skip_train True --multi_probe_dataset_name player_date_birth

# python get_activations_and_probe_non_linear_supcon_bce.py hl_llama_7B city_country --train_file_name city_country_greedy_responses_train6323 --test_file_name city_country_greedy_responses_test1581 --train_labels_file_name city_country_greedy_responses_labels_train6323 --test_labels_file_name city_country_greedy_responses_labels_test1581 --len_dataset 6323 --num_folds 1 --using_act layer --token answer_last --method individual_linear_hallu_pos --bs 128 --epochs 50 --lr_list 0.00005,0.0005,0.005,0.05,0.5 --save_probes True --save_path /home/local/data/ms/honest_llama_data --fast_mode True  --use_best_val_t True --best_using_auc True --seed_list 42,101,2650  --test_num_samples 1
# python get_activations_and_probe_transformer.py hl_llama_7B city_country --train_file_name city_country_greedy_responses_train6323 --test_file_name city_country_greedy_responses_test1581 --train_labels_file_name city_country_greedy_responses_labels_train6323 --test_labels_file_name city_country_greedy_responses_labels_test1581 --len_dataset 6323 --num_folds 1 --using_act layer --token answer_last --method transformer_hallu_pos --bs 128 --epochs 50 --lr_list 0.00005,0.0005,0.005 --save_probes True --save_path /home/local/data/ms/honest_llama_data --fast_mode True  --use_best_val_t True --seed_list 42,101,2650 --best_using_auc True  --test_num_samples 1
##### OOD ####
# python get_activations_and_probe_non_linear_supcon_bce.py hl_llama_7B city_country --train_file_name city_country_greedy_responses_train6323 --test_file_name player_date_birth_greedy_responses_test1498 --train_labels_file_name city_country_greedy_responses_labels_train6323 --test_labels_file_name player_date_birth_greedy_responses_labels_test1498 --len_dataset 6323 --num_folds 1 --using_act layer --token answer_last --method individual_linear_hallu_pos --bs 128 --epochs 50 --lr_list 0.00005,0.0005,0.005,0.05,0.5 --save_probes True --save_path /home/local/data/ms/honest_llama_data --fast_mode True  --use_best_val_t True --best_using_auc True --seed_list 42,101,2650  --test_num_samples 1 --ood_test True  --skip_train True
# python get_activations_and_probe_transformer.py hl_llama_7B city_country --train_file_name city_country_greedy_responses_train6323 --test_file_name player_date_birth_greedy_responses_test1498 --train_labels_file_name city_country_greedy_responses_labels_train6323 --test_labels_file_name player_date_birth_greedy_responses_labels_test1498 --len_dataset 6323 --num_folds 1 --using_act layer --token answer_last --method transformer_hallu_pos --bs 128 --epochs 50 --lr_list 0.00005,0.0005,0.005 --save_probes True --save_path /home/local/data/ms/honest_llama_data --fast_mode True  --use_best_val_t True --seed_list 42,101,2650 --best_using_auc True  --test_num_samples 1 --ood_test True  --skip_train True
###### MULTI #########
# python get_activations_and_probe_non_linear_supcon_bce.py hl_llama_7B multi --dataset_list city_country,player_date_birth --train_name_list city_country_greedy_responses_train6323,player_date_birth_greedy_responses_train5989 --test_file_name city_country_greedy_responses_test1581 --train_labels_name_list city_country_greedy_responses_labels_train6323,player_date_birth_greedy_responses_labels_train5989 --test_labels_file_name city_country_greedy_responses_labels_test1581 --len_dataset_list 6323,5989 --num_folds 1 --using_act layer --token answer_last --method individual_linear_hallu_pos --bs 128 --epochs 50 --lr_list 0.00005,0.0005,0.005,0.05,0.5 --save_probes True --save_path /home/local/data/ms/honest_llama_data --fast_mode True  --use_best_val_t True --best_using_auc True --seed_list 42,101,2650  --test_num_samples 1 --skip_train True --multi_probe_dataset_name player_date_birth
# python get_activations_and_probe_transformer.py hl_llama_7B multi --dataset_list city_country,player_date_birth --train_name_list city_country_greedy_responses_train6323,player_date_birth_greedy_responses_train5989 --test_file_name city_country_greedy_responses_test1581 --train_labels_name_list city_country_greedy_responses_labels_train6323,player_date_birth_greedy_responses_labels_train5989 --test_labels_file_name city_country_greedy_responses_labels_test1581 --len_dataset_list 6323,5989 --num_folds 1 --using_act layer --token answer_last --method transformer_hallu_pos --bs 128 --epochs 50 --lr_list 0.00005,0.0005,0.005,0.05,0.5 --save_probes True --save_path /home/local/data/ms/honest_llama_data --fast_mode True  --use_best_val_t True --best_using_auc True --seed_list 42,101,2650  --test_num_samples 1 --skip_train True --multi_probe_dataset_name player_date_birth
# n_enc=2 # python get_activations_and_probe_transformer.py hl_llama_7B multi --dataset_list city_country,player_date_birth --train_name_list city_country_greedy_responses_train6323,player_date_birth_greedy_responses_train5989 --test_file_name city_country_greedy_responses_test1581 --train_labels_name_list city_country_greedy_responses_labels_train6323,player_date_birth_greedy_responses_labels_train5989 --test_labels_file_name city_country_greedy_responses_labels_test1581 --len_dataset_list 6323,5989 --num_folds 1 --using_act layer --token answer_last --method transformer2_hallu_pos --bs 128 --epochs 50 --lr_list 0.00005,0.0005,0.005,0.05,0.5 --save_probes True --save_path /home/local/data/ms/honest_llama_data --fast_mode True  --use_best_val_t True --best_using_auc True --seed_list 42,101,2650  --test_num_samples 1 --skip_train True --multi_probe_dataset_name player_date_birth;
# sampled train # python get_activations_and_probe_non_linear_supcon_bce.py hl_llama_7B multi --dataset_list city_country,player_date_birth --train_name_list city_country_sampledplus_responses_train1000,player_date_birth_sampledplus_responses_train1000 --test_file_name city_country_greedy_responses_test1581 --train_labels_name_list city_country_sampledplus_responses_labels_train1000,player_date_birth_sampledplus_responses_labels_train1000 --test_labels_file_name city_country_greedy_responses_labels_test1581 --len_dataset_list 11000,11000 --num_folds 1 --using_act layer --token answer_last --method individual_linear_hallu_pos --bs 128 --epochs 50 --lr_list 0.00005,0.0005,0.005,0.05,0.5 --save_probes True --save_path /home/local/data/ms/honest_llama_data --fast_mode True  --use_best_val_t True --best_using_auc True --seed_list 42,101,2650  --test_num_samples 1 --skip_train True --multi_probe_dataset_name player_date_birth
# sampled train # python get_activations_and_probe_transformer.py hl_llama_7B multi --dataset_list city_country,player_date_birth --train_name_list city_country_sampledplus_responses_train1000,player_date_birth_sampledplus_responses_train1000 --test_file_name city_country_greedy_responses_test1581 --train_labels_name_list city_country_sampledplus_responses_labels_train1000,player_date_birth_sampledplus_responses_labels_train1000 --test_labels_file_name city_country_greedy_responses_labels_test1581 --len_dataset_list 11000,11000 --num_folds 1 --using_act layer --token answer_last --method transformer_hallu_pos --bs 128 --epochs 50 --lr_list 0.00005,0.0005,0.005,0.05,0.5 --save_probes True --save_path /home/local/data/ms/honest_llama_data --fast_mode True  --use_best_val_t True --best_using_auc True --seed_list 42,101,2650  --test_num_samples 1 --skip_train True --multi_probe_dataset_name player_date_birth

#######################################
# python get_activations_and_probe_non_linear_supcon_bce.py hl_llama_7B player_date_birth --train_file_name player_date_birth_greedy_responses_train5989 --test_file_name player_date_birth_greedy_responses_test1498 --train_labels_file_name player_date_birth_greedy_responses_labels_train5989 --test_labels_file_name player_date_birth_greedy_responses_labels_test1498 --len_dataset 5989 --num_folds 1 --using_act layer --token answer_last --method individual_linear_hallu_pos --bs 128 --epochs 50 --lr_list 0.00005,0.0005,0.005,0.05,0.5 --save_probes True --save_path /home/local/data/ms/honest_llama_data --fast_mode True  --use_best_val_t True --best_using_auc True --seed_list 42,101,2650  --test_num_samples 1
# python get_activations_and_probe_transformer.py hl_llama_7B player_date_birth --train_file_name player_date_birth_greedy_responses_train5989 --test_file_name player_date_birth_greedy_responses_test1498 --train_labels_file_name player_date_birth_greedy_responses_labels_train5989 --test_labels_file_name player_date_birth_greedy_responses_labels_test1498 --len_dataset 5989 --num_folds 1 --using_act layer --token answer_last --method transformer_hallu_pos --bs 128 --epochs 50 --lr_list 0.00005,0.0005,0.005 --save_probes True --save_path /home/local/data/ms/honest_llama_data --fast_mode True  --use_best_val_t True --seed_list 42,101,2650 --best_using_auc True  --test_num_samples 1
##### OOD ####
# python get_activations_and_probe_non_linear_supcon_bce.py hl_llama_7B player_date_birth --train_file_name player_date_birth_greedy_responses_train5989 --test_file_name city_country_greedy_responses_test1581 --train_labels_file_name player_date_birth_greedy_responses_labels_train5989 --test_labels_file_name city_country_greedy_responses_labels_test1581 --len_dataset 5989 --num_folds 1 --using_act layer --token answer_last --method individual_linear_hallu_pos --bs 128 --epochs 50 --lr_list 0.00005,0.0005,0.005,0.05,0.5 --save_probes True --save_path /home/local/data/ms/honest_llama_data --fast_mode True  --use_best_val_t True --best_using_auc True --seed_list 42,101,2650  --test_num_samples 1 --ood_test True  --skip_train True
# python get_activations_and_probe_transformer.py hl_llama_7B player_date_birth --train_file_name player_date_birth_greedy_responses_train5989 --test_file_name city_country_greedy_responses_test1581 --train_labels_file_name player_date_birth_greedy_responses_labels_train5989 --test_labels_file_name city_country_greedy_responses_labels_test1581 --len_dataset 5989 --num_folds 1 --using_act layer --token answer_last --method transformer_hallu_pos --bs 128 --epochs 50 --lr_list 0.00005,0.0005,0.005 --save_probes True --save_path /home/local/data/ms/honest_llama_data --fast_mode True  --use_best_val_t True --seed_list 42,101,2650 --best_using_auc True  --test_num_samples 1 --ood_test True  --skip_train True
###### MULTI #########
# python get_activations_and_probe_non_linear_supcon_bce.py hl_llama_7B multi --dataset_list city_country,player_date_birth --train_name_list city_country_greedy_responses_train6323,player_date_birth_greedy_responses_train5989 --test_file_name player_date_birth_greedy_responses_test1498 --train_labels_name_list city_country_greedy_responses_labels_train6323,player_date_birth_greedy_responses_labels_train5989 --test_labels_file_name player_date_birth_greedy_responses_labels_test1498 --len_dataset_list 6323,5989 --num_folds 1 --using_act layer --token answer_last --method individual_linear_hallu_pos --bs 128 --epochs 50 --lr_list 0.00005,0.0005,0.005,0.05,0.5 --save_probes True --save_path /home/local/data/ms/honest_llama_data --fast_mode True  --use_best_val_t True --best_using_auc True --seed_list 42,101,2650  --test_num_samples 1
# python get_activations_and_probe_transformer.py hl_llama_7B multi --dataset_list city_country,player_date_birth --train_name_list city_country_greedy_responses_train6323,player_date_birth_greedy_responses_train5989 --test_file_name player_date_birth_greedy_responses_test1498 --train_labels_name_list city_country_greedy_responses_labels_train6323,player_date_birth_greedy_responses_labels_train5989 --test_labels_file_name player_date_birth_greedy_responses_labels_test1498 --len_dataset_list 6323,5989 --num_folds 1 --using_act layer --token answer_last --method transformer_hallu_pos --bs 128 --epochs 50 --lr_list 0.00005,0.0005,0.005,0.05,0.5 --save_probes True --save_path /home/local/data/ms/honest_llama_data --fast_mode True  --use_best_val_t True --best_using_auc True --seed_list 42,101,2650  --test_num_samples 1
# n_enc=2 # python get_activations_and_probe_transformer.py hl_llama_7B multi --dataset_list city_country,player_date_birth --train_name_list city_country_greedy_responses_train6323,player_date_birth_greedy_responses_train5989 --test_file_name player_date_birth_greedy_responses_test1498 --train_labels_name_list city_country_greedy_responses_labels_train6323,player_date_birth_greedy_responses_labels_train5989 --test_labels_file_name player_date_birth_greedy_responses_labels_test1498 --len_dataset_list 6323,5989 --num_folds 1 --using_act layer --token answer_last --method transformer2_hallu_pos --bs 128 --epochs 50 --lr_list 0.00005,0.0005,0.005,0.05,0.5 --save_probes True --save_path /home/local/data/ms/honest_llama_data --fast_mode True  --use_best_val_t True --best_using_auc True --seed_list 42,101,2650  --test_num_samples 1
# sampled train # python get_activations_and_probe_non_linear_supcon_bce.py hl_llama_7B multi --dataset_list city_country,player_date_birth --train_name_list city_country_sampledplus_responses_train1000,player_date_birth_sampledplus_responses_train1000 --test_file_name player_date_birth_greedy_responses_test1498 --train_labels_name_list city_country_sampledplus_responses_labels_train1000,player_date_birth_sampledplus_responses_labels_train1000 --test_labels_file_name player_date_birth_greedy_responses_labels_test1498 --len_dataset_list 11000,11000 --num_folds 1 --using_act layer --token answer_last --method individual_linear_hallu_pos --bs 128 --epochs 50 --lr_list 0.00005,0.0005,0.005,0.05,0.5 --save_probes True --save_path /home/local/data/ms/honest_llama_data --fast_mode True  --use_best_val_t True --best_using_auc True --seed_list 42,101,2650  --test_num_samples 1
# sampled train # python get_activations_and_probe_transformer.py hl_llama_7B multi --dataset_list city_country,player_date_birth --train_name_list city_country_sampledplus_responses_train1000,player_date_birth_sampledplus_responses_train1000 --test_file_name player_date_birth_greedy_responses_test1498 --train_labels_name_list city_country_sampledplus_responses_labels_train1000,player_date_birth_sampledplus_responses_labels_train1000 --test_labels_file_name player_date_birth_greedy_responses_labels_test1498 --len_dataset_list 11000,11000 --num_folds 1 --using_act layer --token answer_last --method transformer_hallu_pos --bs 128 --epochs 50 --lr_list 0.00005,0.0005,0.005,0.05,0.5 --save_probes True --save_path /home/local/data/ms/honest_llama_data --fast_mode True  --use_best_val_t True --best_using_auc True --seed_list 42,101,2650  --test_num_samples 1

######################################
##### OOD ####
# python get_activations_and_probe_non_linear_supcon_bce.py hl_llama_7B player_date_birth --train_file_name player_date_birth_greedy_responses_train5989 --test_file_name movie_cast_greedy_responses_test2179 --train_labels_file_name player_date_birth_greedy_responses_labels_train5989 --test_labels_file_name movie_cast_greedy_responses_labels_test2179 --len_dataset 5989 --num_folds 1 --using_act layer --token answer_last --method individual_linear_hallu_pos --bs 128 --epochs 50 --lr_list 0.00005,0.0005,0.005,0.05,0.5 --save_probes True --save_path /home/local/data/ms/honest_llama_data --fast_mode True  --use_best_val_t True --best_using_auc True --seed_list 42,101,2650  --test_num_samples 1 --ood_test True  --skip_train True
# python get_activations_and_probe_transformer.py hl_llama_7B player_date_birth --train_file_name player_date_birth_greedy_responses_train5989 --test_file_name movie_cast_greedy_responses_test2179 --train_labels_file_name player_date_birth_greedy_responses_labels_train5989 --test_labels_file_name movie_cast_greedy_responses_labels_test2179 --len_dataset 5989 --num_folds 1 --using_act layer --token answer_last --method transformer_hallu_pos --bs 128 --epochs 50 --lr_list 0.00005,0.0005,0.005 --save_probes True --save_path /home/local/data/ms/honest_llama_data --fast_mode True  --use_best_val_t True --seed_list 42,101,2650 --best_using_auc True  --test_num_samples 1 --ood_test True  --skip_train True
# python get_activations_and_probe_non_linear_supcon_bce.py hl_llama_7B city_country --train_file_name city_country_greedy_responses_train6323 --test_file_name movie_cast_greedy_responses_test2179 --train_labels_file_name city_country_greedy_responses_labels_train6323 --test_labels_file_name movie_cast_greedy_responses_labels_test2179 --len_dataset 6323 --num_folds 1 --using_act layer --token answer_last --method individual_linear_hallu_pos --bs 128 --epochs 50 --lr_list 0.00005,0.0005,0.005,0.05,0.5 --save_probes True --save_path /home/local/data/ms/honest_llama_data --fast_mode True  --use_best_val_t True --best_using_auc True --seed_list 42,101,2650  --test_num_samples 1 --ood_test True  --skip_train True
# python get_activations_and_probe_transformer.py hl_llama_7B city_country --train_file_name city_country_greedy_responses_train6323 --test_file_name movie_cast_greedy_responses_test2179 --train_labels_file_name city_country_greedy_responses_labels_train6323 --test_labels_file_name movie_cast_greedy_responses_labels_test2179 --len_dataset 6323 --num_folds 1 --using_act layer --token answer_last --method transformer_hallu_pos --bs 128 --epochs 50 --lr_list 0.00005,0.0005,0.005 --save_probes True --save_path /home/local/data/ms/honest_llama_data --fast_mode True  --use_best_val_t True --seed_list 42,101,2650 --best_using_auc True  --test_num_samples 1 --ood_test True  --skip_train True
###### MULTI #########
# python get_activations_and_probe_non_linear_supcon_bce.py hl_llama_7B multi --dataset_list city_country,player_date_birth --train_name_list city_country_greedy_responses_train6323,player_date_birth_greedy_responses_train5989 --test_file_name movie_cast_greedy_responses_test2179 --train_labels_name_list city_country_greedy_responses_labels_train6323,player_date_birth_greedy_responses_labels_train5989 --test_labels_file_name movie_cast_greedy_responses_labels_test2179 --len_dataset_list 6323,5989 --num_folds 1 --using_act layer --token answer_last --method individual_linear_hallu_pos --bs 128 --epochs 50 --lr_list 0.00005,0.0005,0.005,0.05,0.5 --save_probes True --save_path /home/local/data/ms/honest_llama_data --fast_mode True  --use_best_val_t True --best_using_auc True --seed_list 42,101,2650  --test_num_samples 1 --skip_train True --multi_probe_dataset_name player_date_birth;
# python get_activations_and_probe_transformer.py hl_llama_7B multi --dataset_list city_country,player_date_birth --train_name_list city_country_greedy_responses_train6323,player_date_birth_greedy_responses_train5989 --test_file_name movie_cast_greedy_responses_test2179 --train_labels_name_list city_country_greedy_responses_labels_train6323,player_date_birth_greedy_responses_labels_train5989 --test_labels_file_name movie_cast_greedy_responses_labels_test2179 --len_dataset_list 6323,5989 --num_folds 1 --using_act layer --token answer_last --method transformer_hallu_pos --bs 128 --epochs 50 --lr_list 0.00005,0.0005,0.005,0.05,0.5 --save_probes True --save_path /home/local/data/ms/honest_llama_data --fast_mode True  --use_best_val_t True --best_using_auc True --seed_list 42,101,2650  --test_num_samples 1 --skip_train True --multi_probe_dataset_name player_date_birth;
# n_enc=2 # python get_activations_and_probe_transformer.py hl_llama_7B multi --dataset_list city_country,player_date_birth --train_name_list city_country_greedy_responses_train6323,player_date_birth_greedy_responses_train5989 --test_file_name movie_cast_greedy_responses_test2179 --train_labels_name_list city_country_greedy_responses_labels_train6323,player_date_birth_greedy_responses_labels_train5989 --test_labels_file_name movie_cast_greedy_responses_labels_test2179 --len_dataset_list 6323,5989 --num_folds 1 --using_act layer --token answer_last --method transformer2_hallu_pos --bs 128 --epochs 50 --lr_list 0.00005,0.0005,0.005,0.05,0.5 --save_probes True --save_path /home/local/data/ms/honest_llama_data --fast_mode True  --use_best_val_t True --best_using_auc True --seed_list 42,101,2650  --test_num_samples 1 --skip_train True --multi_probe_dataset_name player_date_birth;
# n_enc=2, bestusingloss # python get_activations_and_probe_transformer.py hl_llama_7B multi --dataset_list city_country,player_date_birth --train_name_list city_country_greedy_responses_train6323,player_date_birth_greedy_responses_train5989 --test_file_name movie_cast_greedy_responses_test2179 --train_labels_name_list city_country_greedy_responses_labels_train6323,player_date_birth_greedy_responses_labels_train5989 --test_labels_file_name movie_cast_greedy_responses_labels_test2179 --len_dataset_list 6323,5989 --num_folds 1 --using_act layer --token answer_last --method transformer2_hallu_pos --bs 128 --epochs 50 --lr_list 0.00005,0.0005,0.005,0.05,0.5 --save_probes True --save_path /home/local/data/ms/honest_llama_data --fast_mode True  --use_best_val_t True --best_using_auc True --seed_list 42,101,2650  --test_num_samples 1 --skip_train True --multi_probe_dataset_name player_date_birth --which_checkpoint bestusingloss;
# sampled test # python get_activations_and_probe_non_linear_supcon_bce.py hl_llama_7B multi --dataset_list city_country,player_date_birth --train_name_list city_country_greedy_responses_train6323,player_date_birth_greedy_responses_train5989 --test_file_name movie_cast_sampled_responses_test2179 --train_labels_name_list city_country_greedy_responses_labels_train6323,player_date_birth_greedy_responses_labels_train5989 --test_labels_file_name movie_cast_sampled_responses_labels_test2179 --len_dataset_list 6323,5989 --num_folds 1 --using_act layer --token answer_last --method individual_linear_hallu_pos --bs 128 --epochs 50 --lr_list 0.00005,0.0005,0.005,0.05,0.5 --save_probes True --save_path /home/local/data/ms/honest_llama_data --fast_mode True  --use_best_val_t True --best_using_auc True --seed_list 42,101,2650  --test_num_samples 10 --skip_train True --multi_probe_dataset_name player_date_birth;
# sampled test # python get_activations_and_probe_transformer.py hl_llama_7B multi --dataset_list city_country,player_date_birth --train_name_list city_country_greedy_responses_train6323,player_date_birth_greedy_responses_train5989 --test_file_name movie_cast_sampled_responses_test2179 --train_labels_name_list city_country_greedy_responses_labels_train6323,player_date_birth_greedy_responses_labels_train5989 --test_labels_file_name movie_cast_sampled_responses_labels_test2179 --len_dataset_list 6323,5989 --num_folds 1 --using_act layer --token answer_last --method transformer_hallu_pos --bs 128 --epochs 50 --lr_list 0.00005,0.0005,0.005,0.05,0.5 --save_probes True --save_path /home/local/data/ms/honest_llama_data --fast_mode True  --use_best_val_t True --best_using_auc True --seed_list 42,101,2650  --test_num_samples 10 --skip_train True --multi_probe_dataset_name player_date_birth;
# sampled train # python get_activations_and_probe_non_linear_supcon_bce.py hl_llama_7B multi --dataset_list city_country,player_date_birth --train_name_list city_country_sampledplus_responses_train1000,player_date_birth_sampledplus_responses_train1000 --test_file_name movie_cast_greedy_responses_test2179 --train_labels_name_list city_country_sampledplus_responses_labels_train1000,player_date_birth_sampledplus_responses_labels_train1000 --test_labels_file_name movie_cast_greedy_responses_labels_test2179 --len_dataset_list 11000,11000 --num_folds 1 --using_act layer --token answer_last --method individual_linear_hallu_pos --bs 128 --epochs 50 --lr_list 0.00005,0.0005,0.005,0.05,0.5 --save_probes True --save_path /home/local/data/ms/honest_llama_data --fast_mode True  --use_best_val_t True --best_using_auc True --seed_list 42,101,2650  --test_num_samples 1 --skip_train True --multi_probe_dataset_name player_date_birth
# sampled train # python get_activations_and_probe_transformer.py hl_llama_7B multi --dataset_list city_country,player_date_birth --train_name_list city_country_sampledplus_responses_train1000,player_date_birth_sampledplus_responses_train1000 --test_file_name movie_cast_greedy_responses_test2179 --train_labels_name_list city_country_sampledplus_responses_labels_train1000,player_date_birth_sampledplus_responses_labels_train1000 --test_labels_file_name movie_cast_greedy_responses_labels_test2179 --len_dataset_list 11000,11000 --num_folds 1 --using_act layer --token answer_last --method transformer_hallu_pos --bs 128 --epochs 50 --lr_list 0.00005,0.0005,0.005,0.05,0.5 --save_probes True --save_path /home/local/data/ms/honest_llama_data --fast_mode True  --use_best_val_t True --best_using_auc True --seed_list 42,101,2650  --test_num_samples 1 --skip_train True --multi_probe_dataset_name player_date_birth

#####################################
##### OOD ####
# python get_activations_and_probe_non_linear_supcon_bce.py hl_llama_7B player_date_birth --train_file_name player_date_birth_greedy_responses_train5989 --test_file_name trivia_qa_greedy_responses_validation1800 --train_labels_file_name player_date_birth_greedy_responses_labels_train5989 --test_labels_file_name trivia_qa_greedy_responses_labels_validation1800 --len_dataset 5989 --num_folds 1 --using_act layer --token answer_last --method individual_linear_hallu_pos --bs 128 --epochs 50 --lr_list 0.00005,0.0005,0.005,0.05,0.5 --save_probes True --save_path /home/local/data/ms/honest_llama_data --fast_mode True  --use_best_val_t True --best_using_auc True --seed_list 42,101,2650  --test_num_samples 1 --ood_test True  --skip_train True;
# python get_activations_and_probe_transformer.py hl_llama_7B player_date_birth --train_file_name player_date_birth_greedy_responses_train5989 --test_file_name trivia_qa_greedy_responses_validation1800 --train_labels_file_name player_date_birth_greedy_responses_labels_train5989 --test_labels_file_name trivia_qa_greedy_responses_labels_validation1800 --len_dataset 5989 --num_folds 1 --using_act layer --token answer_last --method transformer_hallu_pos --bs 128 --epochs 50 --lr_list 0.00005,0.0005,0.005 --save_probes True --save_path /home/local/data/ms/honest_llama_data --fast_mode True  --use_best_val_t True --seed_list 42,101,2650 --best_using_auc True  --test_num_samples 1 --ood_test True  --skip_train True;
# python get_activations_and_probe_non_linear_supcon_bce.py hl_llama_7B city_country --train_file_name city_country_greedy_responses_train6323 --test_file_name trivia_qa_greedy_responses_validation1800 --train_labels_file_name city_country_greedy_responses_labels_train6323 --test_labels_file_name trivia_qa_greedy_responses_labels_validation1800 --len_dataset 6323 --num_folds 1 --using_act layer --token answer_last --method individual_linear_hallu_pos --bs 128 --epochs 50 --lr_list 0.00005,0.0005,0.005,0.05,0.5 --save_probes True --save_path /home/local/data/ms/honest_llama_data --fast_mode True  --use_best_val_t True --best_using_auc True --seed_list 42,101,2650  --test_num_samples 1 --ood_test True  --skip_train True;
# python get_activations_and_probe_transformer.py hl_llama_7B city_country --train_file_name city_country_greedy_responses_train6323 --test_file_name trivia_qa_greedy_responses_validation1800 --train_labels_file_name city_country_greedy_responses_labels_train6323 --test_labels_file_name trivia_qa_greedy_responses_labels_validation1800 --len_dataset 6323 --num_folds 1 --using_act layer --token answer_last --method transformer_hallu_pos --bs 128 --epochs 50 --lr_list 0.00005,0.0005,0.005 --save_probes True --save_path /home/local/data/ms/honest_llama_data --fast_mode True  --use_best_val_t True --seed_list 42,101,2650 --best_using_auc True  --test_num_samples 1 --ood_test True  --skip_train True;
###### MULTI #########
# python get_activations_and_probe_non_linear_supcon_bce.py hl_llama_7B multi --dataset_list city_country,player_date_birth --train_name_list city_country_greedy_responses_train6323,player_date_birth_greedy_responses_train5989 --test_file_name trivia_qa_greedy_responses_validation1800 --train_labels_name_list city_country_greedy_responses_labels_train6323,player_date_birth_greedy_responses_labels_train5989 --test_labels_file_name trivia_qa_greedy_responses_labels_validation1800 --len_dataset_list 6323,5989 --num_folds 1 --using_act layer --token answer_last --method individual_linear_hallu_pos --bs 128 --epochs 50 --lr_list 0.00005,0.0005,0.005,0.05,0.5 --save_probes True --save_path /home/local/data/ms/honest_llama_data --fast_mode True  --use_best_val_t True --best_using_auc True --seed_list 42,101,2650  --test_num_samples 1 --skip_train True --multi_probe_dataset_name player_date_birth;
# python get_activations_and_probe_transformer.py hl_llama_7B multi --dataset_list city_country,player_date_birth --train_name_list city_country_greedy_responses_train6323,player_date_birth_greedy_responses_train5989 --test_file_name trivia_qa_greedy_responses_validation1800 --train_labels_name_list city_country_greedy_responses_labels_train6323,player_date_birth_greedy_responses_labels_train5989 --test_labels_file_name trivia_qa_greedy_responses_labels_validation1800 --len_dataset_list 6323,5989 --num_folds 1 --using_act layer --token answer_last --method transformer_hallu_pos --bs 128 --epochs 50 --lr_list 0.00005,0.0005,0.005,0.05,0.5 --save_probes True --save_path /home/local/data/ms/honest_llama_data --fast_mode True  --use_best_val_t True --best_using_auc True --seed_list 42,101,2650  --test_num_samples 1 --skip_train True --multi_probe_dataset_name player_date_birth;
# n_enc=2 # python get_activations_and_probe_transformer.py hl_llama_7B multi --dataset_list city_country,player_date_birth --train_name_list city_country_greedy_responses_train6323,player_date_birth_greedy_responses_train5989 --test_file_name trivia_qa_greedy_responses_validation1800 --train_labels_name_list city_country_greedy_responses_labels_train6323,player_date_birth_greedy_responses_labels_train5989 --test_labels_file_name trivia_qa_greedy_responses_labels_validation1800 --len_dataset_list 6323,5989 --num_folds 1 --using_act layer --token answer_last --method transformer2_hallu_pos --bs 128 --epochs 50 --lr_list 0.00005,0.0005,0.005,0.05,0.5 --save_probes True --save_path /home/local/data/ms/honest_llama_data --fast_mode True  --use_best_val_t True --best_using_auc True --seed_list 42,101,2650  --test_num_samples 1 --skip_train True --multi_probe_dataset_name player_date_birth;
# sampled test # python get_activations_and_probe_non_linear_supcon_bce.py hl_llama_7B multi --dataset_list city_country,player_date_birth --train_name_list city_country_greedy_responses_train6323,player_date_birth_greedy_responses_train5989 --test_file_name trivia_qa_sampled_responses_validation1800 --train_labels_name_list city_country_greedy_responses_labels_train6323,player_date_birth_greedy_responses_labels_train5989 --test_labels_file_name trivia_qa_sampled_responses_labels_validation1800 --len_dataset_list 6323,5989 --num_folds 1 --using_act layer --token answer_last --method individual_linear_hallu_pos --bs 128 --epochs 50 --lr_list 0.00005,0.0005,0.005,0.05,0.5 --save_probes True --save_path /home/local/data/ms/honest_llama_data --fast_mode True  --use_best_val_t True --best_using_auc True --seed_list 42,101,2650  --test_num_samples 10 --skip_train True --multi_probe_dataset_name player_date_birth;
# sampled test # python get_activations_and_probe_transformer.py hl_llama_7B multi --dataset_list city_country,player_date_birth --train_name_list city_country_greedy_responses_train6323,player_date_birth_greedy_responses_train5989 --test_file_name trivia_qa_sampled_responses_validation1800 --train_labels_name_list city_country_greedy_responses_labels_train6323,player_date_birth_greedy_responses_labels_train5989 --test_labels_file_name trivia_qa_sampled_responses_labels_validation1800 --len_dataset_list 6323,5989 --num_folds 1 --using_act layer --token answer_last --method transformer_hallu_pos --bs 128 --epochs 50 --lr_list 0.00005,0.0005,0.005,0.05,0.5 --save_probes True --save_path /home/local/data/ms/honest_llama_data --fast_mode True  --use_best_val_t True --best_using_auc True --seed_list 42,101,2650  --test_num_samples 10 --skip_train True --multi_probe_dataset_name player_date_birth;
# sampled train # python get_activations_and_probe_non_linear_supcon_bce.py hl_llama_7B multi --dataset_list city_country,player_date_birth --train_name_list city_country_sampledplus_responses_train1000,player_date_birth_sampledplus_responses_train1000 --test_file_name trivia_qa_greedy_responses_validation1800 --train_labels_name_list city_country_sampledplus_responses_labels_train1000,player_date_birth_sampledplus_responses_labels_train1000 --test_labels_file_name trivia_qa_greedy_responses_labels_validation1800 --len_dataset_list 11000,11000 --num_folds 1 --using_act layer --token answer_last --method individual_linear_hallu_pos --bs 128 --epochs 50 --lr_list 0.00005,0.0005,0.005,0.05,0.5 --save_probes True --save_path /home/local/data/ms/honest_llama_data --fast_mode True  --use_best_val_t True --best_using_auc True --seed_list 42,101,2650  --test_num_samples 1 --skip_train True --multi_probe_dataset_name player_date_birth
# sampled train # python get_activations_and_probe_transformer.py hl_llama_7B multi --dataset_list city_country,player_date_birth --train_name_list city_country_sampledplus_responses_train1000,player_date_birth_sampledplus_responses_train1000 --test_file_name trivia_qa_greedy_responses_validation1800 --train_labels_name_list city_country_sampledplus_responses_labels_train1000,player_date_birth_sampledplus_responses_labels_train1000 --test_labels_file_name trivia_qa_greedy_responses_labels_validation1800 --len_dataset_list 11000,11000 --num_folds 1 --using_act layer --token answer_last --method transformer_hallu_pos --bs 128 --epochs 50 --lr_list 0.00005,0.0005,0.005,0.05,0.5 --save_probes True --save_path /home/local/data/ms/honest_llama_data --fast_mode True  --use_best_val_t True --best_using_auc True --seed_list 42,101,2650  --test_num_samples 1 --skip_train True --multi_probe_dataset_name player_date_birth


######## Results #############
# python analyse_crossdataset_bce.py hl_llama_7B city_country --using_act layer --token answer_last --probes_file_name NLSC42_/hl_llama_7B_/city_country_greedy_responses_train6323_/6323_1_layerFalse_answer_last_individual_linear_hallu_pos_bs128_epochs50_ --probes_file_name_concat ba --lr_list 0.00005,0.0005,0.005,0.05,0.5 --best_threshold True --save_path /home/local/data/ms/honest_llama_data --seed_list 42,101,2650 --fpr_at_recall -1
# python analyse_crossdataset_bce_transfmr.py hl_llama_7B city_country --using_act layer --token answer_last --probes_file_name T42_/hl_llama_7B_/city_country_greedy_responses_train6323_/6323_1_layerFalse_answer_last_transformer_hallu_pos_bs128_epochs50_ --probes_file_name_concat ba --lr_list 0.00005,0.0005,0.005 --best_threshold True --save_path /home/local/data/ms/honest_llama_data --seed_list 42,101,2650 --fpr_at_recall -1
# ## OOD ##
# python analyse_crossdataset_bce.py hl_llama_7B city_country --using_act layer --token answer_last --probes_file_name NLSC42_/hl_llama_7B_/ood_city/_player_date_birth_6323_1_layerFalse_answer_last_individual_linear_hallu_pos_bs128_epochs50_ --probes_file_name_concat ba --lr_list 0.00005,0.0005,0.005,0.05,0.5 --best_threshold True --save_path /home/local/data/ms/honest_llama_data --seed_list 42,101,2650 --fpr_at_recall -1
# python analyse_crossdataset_bce_transfmr.py hl_llama_7B city_country --using_act layer --token answer_last --probes_file_name T42_/hl_llama_7B_/ood_city/_player_date_birth_6323_1_layerFalse_answer_last_transformer_hallu_pos_bs128_epochs50_ --probes_file_name_concat ba --lr_list 0.00005,0.0005,0.005 --best_threshold True --save_path /home/local/data/ms/honest_llama_data --seed_list 42,101,2650 --fpr_at_recall -1
## MULTI ##
# python analyse_crossdataset_bce.py hl_llama_7B multi --using_act layer --token answer_last --probes_file_name NLSC42_/hl_llama_7B_/multi2_/city_country_1_layerFalse_answer_last_individual_linear_hallu_pos_bs128_epochs50_ --probes_file_name_concat ba --lr_list 0.00005,0.0005,0.005,0.05,0.5 --best_threshold True --save_path /home/local/data/ms/honest_llama_data --seed_list 42,101,2650 --fpr_at_recall -1
# python analyse_crossdataset_bce_transfmr.py hl_llama_7B multi --using_act layer --token answer_last --probes_file_name T42_/hl_llama_7B_/multi2_/city_country_1_layerFalse_answer_last_transformer_hallu_pos_bs128_epochs50_ --probes_file_name_concat ba --lr_list 0.00005,0.0005,0.005 --best_threshold True --save_path /home/local/data/ms/honest_llama_data --seed_list 42,101,2650 --fpr_at_recall -1
# n_enc=2 # python analyse_crossdataset_bce_transfmr.py hl_llama_7B multi --using_act layer --token answer_last --probes_file_name T42_/hl_llama_7B_/multi2_/city_country_1_layerFalse_answer_last_transformer2_hallu_pos_bs128_epochs50_ --probes_file_name_concat ba --lr_list 0.00005,0.0005,0.005 --best_threshold True --save_path /home/local/data/ms/honest_llama_data --seed_list 42,101,2650 --fpr_at_recall -1


# python analyse_crossdataset_bce.py hl_llama_7B player_date_birth --using_act layer --token answer_last --probes_file_name NLSC42_/hl_llama_7B_/player_date_birth_greedy_responses_train5989_/5989_1_layerFalse_answer_last_individual_linear_hallu_pos_bs128_epochs50_ --probes_file_name_concat ba --lr_list 0.00005,0.0005,0.005,0.05,0.5 --best_threshold True --save_path /home/local/data/ms/honest_llama_data --seed_list 42,101,2650 --fpr_at_recall -1
# python analyse_crossdataset_bce_transfmr.py hl_llama_7B player_date_birth --using_act layer --token answer_last --probes_file_name T42_/hl_llama_7B_/player_date_birth_greedy_responses_train5989_/5989_1_layerFalse_answer_last_transformer_hallu_pos_bs128_epochs50_ --probes_file_name_concat ba --lr_list 0.00005,0.0005,0.005 --best_threshold True --save_path /home/local/data/ms/honest_llama_data --seed_list 42,101,2650 --fpr_at_recall -1
# ## OOD ##
# python analyse_crossdataset_bce.py hl_llama_7B player_date_birth --using_act layer --token answer_last --probes_file_name NLSC42_/hl_llama_7B_/ood_player/_city_country_5989_1_layerFalse_answer_last_individual_linear_hallu_pos_bs128_epochs50_ --probes_file_name_concat ba --lr_list 0.00005,0.0005,0.005,0.05,0.5 --best_threshold True --save_path /home/local/data/ms/honest_llama_data --seed_list 42,101,2650 --fpr_at_recall -1
# python analyse_crossdataset_bce_transfmr.py hl_llama_7B player_date_birth --using_act layer --token answer_last --probes_file_name T42_/hl_llama_7B_/ood_player/_city_country_5989_1_layerFalse_answer_last_transformer_hallu_pos_bs128_epochs50_ --probes_file_name_concat ba --lr_list 0.00005,0.0005,0.005 --best_threshold True --save_path /home/local/data/ms/honest_llama_data --seed_list 42,101,2650 --fpr_at_recall -1
## MULTI ##
# python analyse_crossdataset_bce.py hl_llama_7B multi --using_act layer --token answer_last --probes_file_name NLSC42_/hl_llama_7B_/multi2_/player_date_birth_1_layerFalse_answer_last_individual_linear_hallu_pos_bs128_epochs50_ --probes_file_name_concat ba --lr_list 0.00005,0.0005,0.005,0.05,0.5 --best_threshold True --save_path /home/local/data/ms/honest_llama_data --seed_list 42,101,2650 --fpr_at_recall -1
# python analyse_crossdataset_bce_transfmr.py hl_llama_7B multi --using_act layer --token answer_last --probes_file_name T42_/hl_llama_7B_/multi2_/player_date_birth_1_layerFalse_answer_last_transformer_hallu_pos_bs128_epochs50_ --probes_file_name_concat ba --lr_list 0.00005,0.0005,0.005 --best_threshold True --save_path /home/local/data/ms/honest_llama_data --seed_list 42,101,2650 --fpr_at_recall -1
# n_enc=2 # python analyse_crossdataset_bce_transfmr.py hl_llama_7B multi --using_act layer --token answer_last --probes_file_name T42_/hl_llama_7B_/multi2_/player_date_birth_1_layerFalse_answer_last_transformer2_hallu_pos_bs128_epochs50_ --probes_file_name_concat ba --lr_list 0.00005,0.0005,0.005 --best_threshold True --save_path /home/local/data/ms/honest_llama_data --seed_list 42,101,2650 --fpr_at_recall -1


# ## OOD ##
# python analyse_crossdataset_bce.py hl_llama_7B player_date_birth --using_act layer --token answer_last --probes_file_name NLSC42_/hl_llama_7B_/ood_player/_movie_cast_5989_1_layerFalse_answer_last_individual_linear_hallu_pos_bs128_epochs50_ --probes_file_name_concat ba --lr_list 0.00005,0.0005,0.005,0.05,0.5 --best_threshold True --save_path /home/local/data/ms/honest_llama_data --seed_list 42,101,2650 --fpr_at_recall -1
# python analyse_crossdataset_bce_transfmr.py hl_llama_7B player_date_birth --using_act layer --token answer_last --probes_file_name T42_/hl_llama_7B_/ood_player/_movie_cast_5989_1_layerFalse_answer_last_transformer_hallu_pos_bs128_epochs50_ --probes_file_name_concat ba --lr_list 0.00005,0.0005,0.005 --best_threshold True --save_path /home/local/data/ms/honest_llama_data --seed_list 42,101,2650 --fpr_at_recall -1
# python analyse_crossdataset_bce.py hl_llama_7B city_country --using_act layer --token answer_last --probes_file_name NLSC42_/hl_llama_7B_/ood_city/_movie_cast_6323_1_layerFalse_answer_last_individual_linear_hallu_pos_bs128_epochs50_ --probes_file_name_concat ba --lr_list 0.00005,0.0005,0.005,0.05,0.5 --best_threshold True --save_path /home/local/data/ms/honest_llama_data --seed_list 42,101,2650 --fpr_at_recall -1
# python analyse_crossdataset_bce_transfmr.py hl_llama_7B city_country --using_act layer --token answer_last --probes_file_name T42_/hl_llama_7B_/ood_city/_movie_cast_6323_1_layerFalse_answer_last_transformer_hallu_pos_bs128_epochs50_ --probes_file_name_concat ba --lr_list 0.00005,0.0005,0.005 --best_threshold True --save_path /home/local/data/ms/honest_llama_data --seed_list 42,101,2650 --fpr_at_recall -1
## MULTI ##
# python analyse_crossdataset_bce.py hl_llama_7B multi --using_act layer --token answer_last --probes_file_name NLSC42_/hl_llama_7B_/multi2_/movie_cast_1_layerFalse_answer_last_individual_linear_hallu_pos_bs128_epochs50_ --probes_file_name_concat ba --lr_list 0.00005,0.0005,0.005,0.05,0.5 --best_threshold True --save_path /home/local/data/ms/honest_llama_data --seed_list 42,101,2650 --fpr_at_recall -1
# python analyse_crossdataset_bce_transfmr.py hl_llama_7B multi --using_act layer --token answer_last --probes_file_name T42_/hl_llama_7B_/multi2_/movie_cast_1_layerFalse_answer_last_transformer_hallu_pos_bs128_epochs50_ --probes_file_name_concat ba --lr_list 0.00005,0.0005,0.005 --best_threshold True --save_path /home/local/data/ms/honest_llama_data --seed_list 42,101,2650 --fpr_at_recall -1
# n_enc=2 # python analyse_crossdataset_bce_transfmr.py hl_llama_7B multi --using_act layer --token answer_last --probes_file_name T42_/hl_llama_7B_/multi2_/movie_cast_1_layerFalse_answer_last_transformer2_hallu_pos_bs128_epochs50_ --probes_file_name_concat ba --lr_list 0.00005,0.0005,0.005 --best_threshold True --save_path /home/local/data/ms/honest_llama_data --seed_list 42,101,2650 --fpr_at_recall -1
# n_enc=2, bestusingloss # python analyse_crossdataset_bce_transfmr.py hl_llama_7B multi --using_act layer --token answer_last --probes_file_name T42_/hl_llama_7B_/multi2_/movie_cast_1_layerFalse_answer_last_transformer2_hallu_pos_bs128_epochs50_ --probes_file_name_concat ba_bestusingloss --lr_list 0.00005,0.0005,0.005 --best_threshold True --save_path /home/local/data/ms/honest_llama_data --seed_list 42,101,2650 --fpr_at_recall -1
# sampled test # python analyse_crossdataset_bce.py hl_llama_7B multi --using_act layer --token answer_last --probes_file_name NLSC42_/hl_llama_7B_/multi2_/movie_cast_1_layerFalse_answer_last_individual_linear_hallu_pos_bs128_epochs50_ --probes_file_name_concat ba --lr_list 0.00005,0.0005,0.005,0.05,0.5 --best_threshold True --save_path /home/local/data/ms/honest_llama_data --seed_list 42,101,2650 --fpr_at_recall -1 --test_num_samples 10 --filt_testprompts_catg 2
# sampled test # python analyse_crossdataset_bce_transfmr.py hl_llama_7B multi --using_act layer --token answer_last --probes_file_name T42_/hl_llama_7B_/multi2_/movie_cast_1_layerFalse_answer_last_transformer_hallu_pos_bs128_epochs50_ --probes_file_name_concat ba --lr_list 0.00005,0.0005,0.005 --best_threshold True --save_path /home/local/data/ms/honest_llama_data --seed_list 42,101,2650 --fpr_at_recall -1 --test_num_samples 10 --filt_testprompts_catg 2


# ## OOD ##
# python analyse_crossdataset_bce.py hl_llama_7B player_date_birth --using_act layer --token answer_last --probes_file_name NLSC42_/hl_llama_7B_/ood_player/_trivia_qa_5989_1_layerFalse_answer_last_individual_linear_hallu_pos_bs128_epochs50_ --probes_file_name_concat ba --lr_list 0.00005,0.0005,0.005,0.05,0.5 --best_threshold True --save_path /home/local/data/ms/honest_llama_data --seed_list 42,101,2650 --fpr_at_recall -1
# python analyse_crossdataset_bce_transfmr.py hl_llama_7B player_date_birth --using_act layer --token answer_last --probes_file_name T42_/hl_llama_7B_/ood_player/_trivia_qa_5989_1_layerFalse_answer_last_transformer_hallu_pos_bs128_epochs50_ --probes_file_name_concat ba --lr_list 0.00005,0.0005,0.005 --best_threshold True --save_path /home/local/data/ms/honest_llama_data --seed_list 42,101,2650 --fpr_at_recall -1
# python analyse_crossdataset_bce.py hl_llama_7B city_country --using_act layer --token answer_last --probes_file_name NLSC42_/hl_llama_7B_/ood_city/_trivia_qa_6323_1_layerFalse_answer_last_individual_linear_hallu_pos_bs128_epochs50_ --probes_file_name_concat ba --lr_list 0.00005,0.0005,0.005,0.05,0.5 --best_threshold True --save_path /home/local/data/ms/honest_llama_data --seed_list 42,101,2650 --fpr_at_recall -1
# python analyse_crossdataset_bce_transfmr.py hl_llama_7B city_country --using_act layer --token answer_last --probes_file_name T42_/hl_llama_7B_/ood_city/_trivia_qa_6323_1_layerFalse_answer_last_transformer_hallu_pos_bs128_epochs50_ --probes_file_name_concat ba --lr_list 0.00005,0.0005,0.005 --best_threshold True --save_path /home/local/data/ms/honest_llama_data --seed_list 42,101,2650 --fpr_at_recall -1
## MULTI ##
# python analyse_crossdataset_bce.py hl_llama_7B multi --using_act layer --token answer_last --probes_file_name NLSC42_/hl_llama_7B_/multi2_/trivia_qa_1_layerFalse_answer_last_individual_linear_hallu_pos_bs128_epochs50_ --probes_file_name_concat ba --lr_list 0.00005,0.0005,0.005,0.05,0.5 --best_threshold True --save_path /home/local/data/ms/honest_llama_data --seed_list 42,101,2650 --fpr_at_recall -1
# python analyse_crossdataset_bce_transfmr.py hl_llama_7B multi --using_act layer --token answer_last --probes_file_name T42_/hl_llama_7B_/multi2_/trivia_qa_1_layerFalse_answer_last_transformer_hallu_pos_bs128_epochs50_ --probes_file_name_concat ba --lr_list 0.00005,0.0005,0.005 --best_threshold True --save_path /home/local/data/ms/honest_llama_data --seed_list 42,101,2650 --fpr_at_recall -1
# n_enc=2 # python analyse_crossdataset_bce_transfmr.py hl_llama_7B multi --using_act layer --token answer_last --probes_file_name T42_/hl_llama_7B_/multi2_/trivia_qa_1_layerFalse_answer_last_transformer2_hallu_pos_bs128_epochs50_ --probes_file_name_concat ba --lr_list 0.00005,0.0005,0.005 --best_threshold True --save_path /home/local/data/ms/honest_llama_data --seed_list 42,101,2650 --fpr_at_recall -1
# sampled test # python analyse_crossdataset_bce.py hl_llama_7B multi --using_act layer --token answer_last --probes_file_name NLSC42_/hl_llama_7B_/multi2_/trivia_qa_1_layerFalse_answer_last_individual_linear_hallu_pos_bs128_epochs50_ --probes_file_name_concat ba --lr_list 0.00005,0.0005,0.005,0.05,0.5 --best_threshold True --save_path /home/local/data/ms/honest_llama_data --seed_list 42,101,2650 --fpr_at_recall -1 --test_num_samples 10 --filt_testprompts_catg 2
# sampled test # python analyse_crossdataset_bce_transfmr.py hl_llama_7B multi --using_act layer --token answer_last --probes_file_name T42_/hl_llama_7B_/multi2_/trivia_qa_1_layerFalse_answer_last_transformer_hallu_pos_bs128_epochs50_ --probes_file_name_concat ba --lr_list 0.00005,0.0005,0.005 --best_threshold True --save_path /home/local/data/ms/honest_llama_data --seed_list 42,101,2650 --fpr_at_recall -1 --test_num_samples 10 --filt_testprompts_catg 2