# # python get_activations_and_probe_non_linear_supcon_bce.py gemma_2B city_country --train_file_name city_country_greedy_responses_train6323 --test_file_name city_country_greedy_responses_test1581 --train_labels_file_name city_country_greedy_responses_labels_train6323 --test_labels_file_name city_country_greedy_responses_labels_test1581 --len_dataset 6323 --num_folds 1 --using_act layer --token answer_last --method individual_linear_hallu_pos --bs 128 --epochs 50 --lr_list 0.00005,0.0005,0.005 --save_probes True --save_path /home/local/data/ms/honest_llama_data --fast_mode True  --use_best_val_t True --best_using_auc True --seed_list 42,101,2650  --test_num_samples 1
python get_activations_and_probe_transformer.py gemma_2B city_country --train_file_name city_country_greedy_responses_train6323 --test_file_name city_country_greedy_responses_test1581 --train_labels_file_name city_country_greedy_responses_labels_train6323 --test_labels_file_name city_country_greedy_responses_labels_test1581 --len_dataset 6323 --num_folds 1 --using_act layer --token answer_last --method transformer_hallu_pos --bs 128 --epochs 50 --lr_list 0.00005,0.0005,0.005 --save_probes True --save_path /home/local/data/ms/honest_llama_data --fast_mode True  --use_best_val_t True --seed_list 42,101,2650 --best_using_auc True  --test_num_samples 1
#### OOD ####
# # python get_activations_and_probe_non_linear_supcon_bce.py gemma_2B city_country --train_file_name city_country_greedy_responses_train6323 --test_file_name player_date_birth_greedy_responses_test1498 --train_labels_file_name city_country_greedy_responses_labels_train6323 --test_labels_file_name player_date_birth_greedy_responses_labels_test1498 --len_dataset 6323 --num_folds 1 --using_act layer --token answer_last --method individual_linear_hallu_pos --bs 128 --epochs 50 --lr_list 0.00005,0.0005,0.005 --save_probes True --save_path /home/local/data/ms/honest_llama_data --fast_mode True  --use_best_val_t True --best_using_auc True --seed_list 42,101,2650  --test_num_samples 1 --ood_test True  --skip_train True
python get_activations_and_probe_transformer.py gemma_2B city_country --train_file_name city_country_greedy_responses_train6323 --test_file_name player_date_birth_greedy_responses_test1498 --train_labels_file_name city_country_greedy_responses_labels_train6323 --test_labels_file_name player_date_birth_greedy_responses_labels_test1498 --len_dataset 6323 --num_folds 1 --using_act layer --token answer_last --method transformer_hallu_pos --bs 128 --epochs 50 --lr_list 0.00005,0.0005,0.005 --save_probes True --save_path /home/local/data/ms/honest_llama_data --fast_mode True  --use_best_val_t True --seed_list 42,101,2650 --best_using_auc True  --test_num_samples 1 --ood_test True  --skip_train True
# # python get_activations_and_probe_non_linear_supcon_bce.py gemma_2B city_country --train_file_name city_country_greedy_responses_train6323 --test_file_name movie_cast_greedy_responses_test2179 --train_labels_file_name city_country_greedy_responses_labels_train6323 --test_labels_file_name movie_cast_greedy_responses_labels_test2179 --len_dataset 6323 --num_folds 1 --using_act layer --token answer_last --method individual_linear_hallu_pos --bs 128 --epochs 50 --lr_list 0.00005,0.0005,0.005 --save_probes True --save_path /home/local/data/ms/honest_llama_data --fast_mode True  --use_best_val_t True --best_using_auc True --seed_list 42,101,2650  --test_num_samples 1 --ood_test True  --skip_train True
python get_activations_and_probe_transformer.py gemma_2B city_country --train_file_name city_country_greedy_responses_train6323 --test_file_name movie_cast_greedy_responses_test2179 --train_labels_file_name city_country_greedy_responses_labels_train6323 --test_labels_file_name movie_cast_greedy_responses_labels_test2179 --len_dataset 6323 --num_folds 1 --using_act layer --token answer_last --method transformer_hallu_pos --bs 128 --epochs 50 --lr_list 0.00005,0.0005,0.005 --save_probes True --save_path /home/local/data/ms/honest_llama_data --fast_mode True  --use_best_val_t True --seed_list 42,101,2650 --best_using_auc True  --test_num_samples 1 --ood_test True  --skip_train True
# python get_activations_and_probe_non_linear_supcon_bce.py gemma_2B city_country --train_file_name city_country_greedy_responses_train6323 --test_file_name trivia_qa_greedy_responses_validation1800 --train_labels_file_name city_country_greedy_responses_labels_train6323 --test_labels_file_name trivia_qa_greedy_responses_labels_validation1800 --len_dataset 6323 --num_folds 1 --using_act layer --token answer_last --method individual_linear_hallu_pos --bs 128 --epochs 50 --lr_list 0.00005,0.0005,0.005 --save_probes True --save_path /home/local/data/ms/honest_llama_data --fast_mode True  --use_best_val_t True --best_using_auc True --seed_list 42,101,2650  --test_num_samples 1 --ood_test True  --skip_train True;
python get_activations_and_probe_transformer.py gemma_2B city_country --train_file_name city_country_greedy_responses_train6323 --test_file_name trivia_qa_greedy_responses_validation1800 --train_labels_file_name city_country_greedy_responses_labels_train6323 --test_labels_file_name trivia_qa_greedy_responses_labels_validation1800 --len_dataset 6323 --num_folds 1 --using_act layer --token answer_last --method transformer_hallu_pos --bs 128 --epochs 50 --lr_list 0.00005,0.0005,0.005 --save_probes True --save_path /home/local/data/ms/honest_llama_data --fast_mode True  --use_best_val_t True --seed_list 42,101,2650 --best_using_auc True  --test_num_samples 1 --ood_test True  --skip_train True;
# python get_activations_and_probe_non_linear_supcon_bce.py gemma_2B city_country --train_file_name city_country_greedy_responses_train6323 --test_file_name nq_open_greedy_responses_validation1800 --train_labels_file_name city_country_greedy_responses_labels_train6323 --test_labels_file_name nq_open_greedy_responses_labels_validation1800 --len_dataset 6323 --num_folds 1 --using_act layer --token answer_last --method individual_linear_hallu_pos --bs 128 --epochs 50 --lr_list 0.00005,0.0005,0.005 --save_probes True --save_path /home/local/data/ms/honest_llama_data --fast_mode True  --use_best_val_t True --best_using_auc True --seed_list 42,101,2650  --test_num_samples 1 --ood_test True  --skip_train True;
python get_activations_and_probe_transformer.py gemma_2B city_country --train_file_name city_country_greedy_responses_train6323 --test_file_name nq_open_greedy_responses_validation1800 --train_labels_file_name city_country_greedy_responses_labels_train6323 --test_labels_file_name nq_open_greedy_responses_labels_validation1800 --len_dataset 6323 --num_folds 1 --using_act layer --token answer_last --method transformer_hallu_pos --bs 128 --epochs 50 --lr_list 0.00005,0.0005,0.005 --save_probes True --save_path /home/local/data/ms/honest_llama_data --fast_mode True  --use_best_val_t True --seed_list 42,101,2650 --best_using_auc True  --test_num_samples 1 --ood_test True  --skip_train True;

# python get_activations_and_probe_non_linear_supcon_bce.py gemma_2B player_date_birth --train_file_name player_date_birth_greedy_responses_train5989 --test_file_name player_date_birth_greedy_responses_test1498 --train_labels_file_name player_date_birth_greedy_responses_labels_train5989 --test_labels_file_name player_date_birth_greedy_responses_labels_test1498 --len_dataset 5989 --num_folds 1 --using_act layer --token answer_last --method individual_linear_hallu_pos --bs 128 --epochs 50 --lr_list 0.00005,0.0005,0.005 --save_probes True --save_path /home/local/data/ms/honest_llama_data --fast_mode True  --use_best_val_t True --best_using_auc True --seed_list 42,101,2650  --test_num_samples 1
python get_activations_and_probe_transformer.py gemma_2B player_date_birth --train_file_name player_date_birth_greedy_responses_train5989 --test_file_name player_date_birth_greedy_responses_test1498 --train_labels_file_name player_date_birth_greedy_responses_labels_train5989 --test_labels_file_name player_date_birth_greedy_responses_labels_test1498 --len_dataset 5989 --num_folds 1 --using_act layer --token answer_last --method transformer_hallu_pos --bs 128 --epochs 50 --lr_list 0.00005,0.0005,0.005 --save_probes True --save_path /home/local/data/ms/honest_llama_data --fast_mode True  --use_best_val_t True --seed_list 42,101,2650 --best_using_auc True  --test_num_samples 1
#### OOD ####
# python get_activations_and_probe_non_linear_supcon_bce.py gemma_2B player_date_birth --train_file_name player_date_birth_greedy_responses_train5989 --test_file_name city_country_greedy_responses_test1581 --train_labels_file_name player_date_birth_greedy_responses_labels_train5989 --test_labels_file_name city_country_greedy_responses_labels_test1581 --len_dataset 5989 --num_folds 1 --using_act layer --token answer_last --method individual_linear_hallu_pos --bs 128 --epochs 50 --lr_list 0.00005,0.0005,0.005 --save_probes True --save_path /home/local/data/ms/honest_llama_data --fast_mode True  --use_best_val_t True --best_using_auc True --seed_list 42,101,2650  --test_num_samples 1 --ood_test True  --skip_train True
python get_activations_and_probe_transformer.py gemma_2B player_date_birth --train_file_name player_date_birth_greedy_responses_train5989 --test_file_name city_country_greedy_responses_test1581 --train_labels_file_name player_date_birth_greedy_responses_labels_train5989 --test_labels_file_name city_country_greedy_responses_labels_test1581 --len_dataset 5989 --num_folds 1 --using_act layer --token answer_last --method transformer_hallu_pos --bs 128 --epochs 50 --lr_list 0.00005,0.0005,0.005 --save_probes True --save_path /home/local/data/ms/honest_llama_data --fast_mode True  --use_best_val_t True --seed_list 42,101,2650 --best_using_auc True  --test_num_samples 1 --ood_test True  --skip_train True
# python get_activations_and_probe_non_linear_supcon_bce.py gemma_2B player_date_birth --train_file_name player_date_birth_greedy_responses_train5989 --test_file_name movie_cast_greedy_responses_test2179 --train_labels_file_name player_date_birth_greedy_responses_labels_train5989 --test_labels_file_name movie_cast_greedy_responses_labels_test2179 --len_dataset 5989 --num_folds 1 --using_act layer --token answer_last --method individual_linear_hallu_pos --bs 128 --epochs 50 --lr_list 0.00005,0.0005,0.005 --save_probes True --save_path /home/local/data/ms/honest_llama_data --fast_mode True  --use_best_val_t True --best_using_auc True --seed_list 42,101,2650  --test_num_samples 1 --ood_test True  --skip_train True
python get_activations_and_probe_transformer.py gemma_2B player_date_birth --train_file_name player_date_birth_greedy_responses_train5989 --test_file_name movie_cast_greedy_responses_test2179 --train_labels_file_name player_date_birth_greedy_responses_labels_train5989 --test_labels_file_name movie_cast_greedy_responses_labels_test2179 --len_dataset 5989 --num_folds 1 --using_act layer --token answer_last --method transformer_hallu_pos --bs 128 --epochs 50 --lr_list 0.00005,0.0005,0.005 --save_probes True --save_path /home/local/data/ms/honest_llama_data --fast_mode True  --use_best_val_t True --seed_list 42,101,2650 --best_using_auc True  --test_num_samples 1 --ood_test True  --skip_train True
# python get_activations_and_probe_non_linear_supcon_bce.py gemma_2B player_date_birth --train_file_name player_date_birth_greedy_responses_train5989 --test_file_name trivia_qa_greedy_responses_validation1800 --train_labels_file_name player_date_birth_greedy_responses_labels_train5989 --test_labels_file_name trivia_qa_greedy_responses_labels_validation1800 --len_dataset 5989 --num_folds 1 --using_act layer --token answer_last --method individual_linear_hallu_pos --bs 128 --epochs 50 --lr_list 0.00005,0.0005,0.005 --save_probes True --save_path /home/local/data/ms/honest_llama_data --fast_mode True  --use_best_val_t True --best_using_auc True --seed_list 42,101,2650  --test_num_samples 1 --ood_test True  --skip_train True;
python get_activations_and_probe_transformer.py gemma_2B player_date_birth --train_file_name player_date_birth_greedy_responses_train5989 --test_file_name trivia_qa_greedy_responses_validation1800 --train_labels_file_name player_date_birth_greedy_responses_labels_train5989 --test_labels_file_name trivia_qa_greedy_responses_labels_validation1800 --len_dataset 5989 --num_folds 1 --using_act layer --token answer_last --method transformer_hallu_pos --bs 128 --epochs 50 --lr_list 0.00005,0.0005,0.005 --save_probes True --save_path /home/local/data/ms/honest_llama_data --fast_mode True  --use_best_val_t True --seed_list 42,101,2650 --best_using_auc True  --test_num_samples 1 --ood_test True  --skip_train True;
# python get_activations_and_probe_non_linear_supcon_bce.py gemma_2B player_date_birth --train_file_name player_date_birth_greedy_responses_train5989 --test_file_name nq_open_greedy_responses_validation1800 --train_labels_file_name player_date_birth_greedy_responses_labels_train5989 --test_labels_file_name nq_open_greedy_responses_labels_validation1800 --len_dataset 5989 --num_folds 1 --using_act layer --token answer_last --method individual_linear_hallu_pos --bs 128 --epochs 50 --lr_list 0.00005,0.0005,0.005 --save_probes True --save_path /home/local/data/ms/honest_llama_data --fast_mode True  --use_best_val_t True --best_using_auc True --seed_list 42,101,2650  --test_num_samples 1 --ood_test True  --skip_train True;
python get_activations_and_probe_transformer.py gemma_2B player_date_birth --train_file_name player_date_birth_greedy_responses_train5989 --test_file_name nq_open_greedy_responses_validation1800 --train_labels_file_name player_date_birth_greedy_responses_labels_train5989 --test_labels_file_name nq_open_greedy_responses_labels_validation1800 --len_dataset 5989 --num_folds 1 --using_act layer --token answer_last --method transformer_hallu_pos --bs 128 --epochs 50 --lr_list 0.00005,0.0005,0.005 --save_probes True --save_path /home/local/data/ms/honest_llama_data --fast_mode True  --use_best_val_t True --seed_list 42,101,2650 --best_using_auc True  --test_num_samples 1 --ood_test True  --skip_train True;

# python get_activations_and_probe_non_linear_supcon_bce.py gemma_2B movie_cast --train_file_name movie_cast_greedy_responses_train8716 --test_file_name movie_cast_greedy_responses_test2179 --train_labels_file_name movie_cast_greedy_responses_labels_train8716 --test_labels_file_name movie_cast_greedy_responses_labels_test2179 --len_dataset 8716 --num_folds 1 --using_act layer --token answer_last --method individual_linear_hallu_pos --bs 128 --epochs 50 --lr_list 0.00005,0.0005,0.005 --save_probes True --save_path /home/local/data/ms/honest_llama_data --fast_mode True  --use_best_val_t True --best_using_auc True --seed_list 42,101,2650  --test_num_samples 1
python get_activations_and_probe_transformer.py gemma_2B movie_cast --train_file_name movie_cast_greedy_responses_train8716 --test_file_name movie_cast_greedy_responses_test2179 --train_labels_file_name movie_cast_greedy_responses_labels_train8716 --test_labels_file_name movie_cast_greedy_responses_labels_test2179 --len_dataset 8716 --num_folds 1 --using_act layer --token answer_last --method transformer_hallu_pos --bs 128 --epochs 50 --lr_list 0.00005,0.0005,0.005 --save_probes True --save_path /home/local/data/ms/honest_llama_data --fast_mode True  --use_best_val_t True --seed_list 42,101,2650 --best_using_auc True  --test_num_samples 1
#### OOD ####
# python get_activations_and_probe_non_linear_supcon_bce.py gemma_2B movie_cast --train_file_name movie_cast_greedy_responses_train8716 --test_file_name city_country_greedy_responses_test1581 --train_labels_file_name movie_cast_greedy_responses_labels_train8716 --test_labels_file_name city_country_greedy_responses_labels_test1581 --len_dataset 8716 --num_folds 1 --using_act layer --token answer_last --method individual_linear_hallu_pos --bs 128 --epochs 50 --lr_list 0.00005,0.0005,0.005 --save_probes True --save_path /home/local/data/ms/honest_llama_data --fast_mode True  --use_best_val_t True --best_using_auc True --seed_list 42,101,2650  --test_num_samples 1 --ood_test True  --skip_train True
python get_activations_and_probe_transformer.py gemma_2B movie_cast --train_file_name movie_cast_greedy_responses_train8716 --test_file_name city_country_greedy_responses_test1581 --train_labels_file_name movie_cast_greedy_responses_labels_train8716 --test_labels_file_name city_country_greedy_responses_labels_test1581 --len_dataset 8716 --num_folds 1 --using_act layer --token answer_last --method transformer_hallu_pos --bs 128 --epochs 50 --lr_list 0.00005,0.0005,0.005 --save_probes True --save_path /home/local/data/ms/honest_llama_data --fast_mode True  --use_best_val_t True --seed_list 42,101,2650 --best_using_auc True  --test_num_samples 1 --ood_test True  --skip_train True
# python get_activations_and_probe_non_linear_supcon_bce.py gemma_2B movie_cast --train_file_name movie_cast_greedy_responses_train8716 --test_file_name player_date_birth_greedy_responses_test1498 --train_labels_file_name movie_cast_greedy_responses_labels_train8716 --test_labels_file_name player_date_birth_greedy_responses_labels_test1498 --len_dataset 8716 --num_folds 1 --using_act layer --token answer_last --method individual_linear_hallu_pos --bs 128 --epochs 50 --lr_list 0.00005,0.0005,0.005 --save_probes True --save_path /home/local/data/ms/honest_llama_data --fast_mode True  --use_best_val_t True --best_using_auc True --seed_list 42,101,2650  --test_num_samples 1 --ood_test True  --skip_train True
python get_activations_and_probe_transformer.py gemma_2B movie_cast --train_file_name movie_cast_greedy_responses_train8716 --test_file_name player_date_birth_greedy_responses_test1498 --train_labels_file_name movie_cast_greedy_responses_labels_train8716 --test_labels_file_name player_date_birth_greedy_responses_labels_test1498 --len_dataset 8716 --num_folds 1 --using_act layer --token answer_last --method transformer_hallu_pos --bs 128 --epochs 50 --lr_list 0.00005,0.0005,0.005 --save_probes True --save_path /home/local/data/ms/honest_llama_data --fast_mode True  --use_best_val_t True --seed_list 42,101,2650 --best_using_auc True  --test_num_samples 1 --ood_test True  --skip_train True
# python get_activations_and_probe_non_linear_supcon_bce.py gemma_2B movie_cast --train_file_name movie_cast_greedy_responses_train8716 --test_file_name trivia_qa_greedy_responses_validation1800 --train_labels_file_name movie_cast_greedy_responses_labels_train8716 --test_labels_file_name trivia_qa_greedy_responses_labels_validation1800 --len_dataset 8716 --num_folds 1 --using_act layer --token answer_last --method individual_linear_hallu_pos --bs 128 --epochs 50 --lr_list 0.00005,0.0005,0.005 --save_probes True --save_path /home/local/data/ms/honest_llama_data --fast_mode True  --use_best_val_t True --best_using_auc True --seed_list 42,101,2650  --test_num_samples 1 --ood_test True  --skip_train True;
python get_activations_and_probe_transformer.py gemma_2B movie_cast --train_file_name movie_cast_greedy_responses_train8716 --test_file_name trivia_qa_greedy_responses_validation1800 --train_labels_file_name movie_cast_greedy_responses_labels_train8716 --test_labels_file_name trivia_qa_greedy_responses_labels_validation1800 --len_dataset 8716 --num_folds 1 --using_act layer --token answer_last --method transformer_hallu_pos --bs 128 --epochs 50 --lr_list 0.00005,0.0005,0.005 --save_probes True --save_path /home/local/data/ms/honest_llama_data --fast_mode True  --use_best_val_t True --seed_list 42,101,2650 --best_using_auc True  --test_num_samples 1 --ood_test True  --skip_train True;
# python get_activations_and_probe_non_linear_supcon_bce.py gemma_2B movie_cast --train_file_name movie_cast_greedy_responses_train8716 --test_file_name nq_open_greedy_responses_validation1800 --train_labels_file_name movie_cast_greedy_responses_labels_train8716 --test_labels_file_name nq_open_greedy_responses_labels_validation1800 --len_dataset 8716 --num_folds 1 --using_act layer --token answer_last --method individual_linear_hallu_pos --bs 128 --epochs 50 --lr_list 0.00005,0.0005,0.005 --save_probes True --save_path /home/local/data/ms/honest_llama_data --fast_mode True  --use_best_val_t True --best_using_auc True --seed_list 42,101,2650  --test_num_samples 1 --ood_test True  --skip_train True;
python get_activations_and_probe_transformer.py gemma_2B movie_cast --train_file_name movie_cast_greedy_responses_train8716 --test_file_name nq_open_greedy_responses_validation1800 --train_labels_file_name movie_cast_greedy_responses_labels_train8716 --test_labels_file_name nq_open_greedy_responses_labels_validation1800 --len_dataset 8716 --num_folds 1 --using_act layer --token answer_last --method transformer_hallu_pos --bs 128 --epochs 50 --lr_list 0.00005,0.0005,0.005 --save_probes True --save_path /home/local/data/ms/honest_llama_data --fast_mode True  --use_best_val_t True --seed_list 42,101,2650 --best_using_auc True  --test_num_samples 1 --ood_test True  --skip_train True;

# TRIVIA
#### OOD ####
# python get_activations_and_probe_non_linear_supcon_bce.py gemma_2B trivia_qa --train_file_name trivia_qa_greedy_responses_train5000 --test_file_name city_country_greedy_responses_test1581 --train_labels_file_name trivia_qa_greedy_responses_labels_train5000 --test_labels_file_name city_country_greedy_responses_labels_test1581 --len_dataset 5000 --num_folds 1 --using_act layer --token answer_last --method individual_linear_hallu_pos --bs 128 --epochs 50 --lr_list 0.00005,0.0005,0.005 --save_probes True --save_path /home/local/data/ms/honest_llama_data --fast_mode True  --use_best_val_t True --best_using_auc True --seed_list 42,101,2650  --test_num_samples 1 --ood_test True  --skip_train True
python get_activations_and_probe_transformer.py gemma_2B trivia_qa --train_file_name trivia_qa_greedy_responses_train5000 --test_file_name city_country_greedy_responses_test1581 --train_labels_file_name trivia_qa_greedy_responses_labels_train5000 --test_labels_file_name city_country_greedy_responses_labels_test1581 --len_dataset 5000 --num_folds 1 --using_act layer --token answer_last --method transformer_hallu_pos --bs 128 --epochs 50 --lr_list 0.00005,0.0005,0.005 --save_probes True --save_path /home/local/data/ms/honest_llama_data --fast_mode True  --use_best_val_t True --seed_list 42,101,2650 --best_using_auc True  --test_num_samples 1 --ood_test True  --skip_train True
# python get_activations_and_probe_non_linear_supcon_bce.py gemma_2B trivia_qa --train_file_name trivia_qa_greedy_responses_train5000 --test_file_name player_date_birth_greedy_responses_test1498 --train_labels_file_name trivia_qa_greedy_responses_labels_train5000 --test_labels_file_name player_date_birth_greedy_responses_labels_test1498 --len_dataset 5000 --num_folds 1 --using_act layer --token answer_last --method individual_linear_hallu_pos --bs 128 --epochs 50 --lr_list 0.00005,0.0005,0.005 --save_probes True --save_path /home/local/data/ms/honest_llama_data --fast_mode True  --use_best_val_t True --best_using_auc True --seed_list 42,101,2650  --test_num_samples 1 --ood_test True  --skip_train True
python get_activations_and_probe_transformer.py gemma_2B trivia_qa --train_file_name trivia_qa_greedy_responses_train5000 --test_file_name player_date_birth_greedy_responses_test1498 --train_labels_file_name trivia_qa_greedy_responses_labels_train5000 --test_labels_file_name player_date_birth_greedy_responses_labels_test1498 --len_dataset 5000 --num_folds 1 --using_act layer --token answer_last --method transformer_hallu_pos --bs 128 --epochs 50 --lr_list 0.00005,0.0005,0.005 --save_probes True --save_path /home/local/data/ms/honest_llama_data --fast_mode True  --use_best_val_t True --seed_list 42,101,2650 --best_using_auc True  --test_num_samples 1 --ood_test True  --skip_train True
# python get_activations_and_probe_non_linear_supcon_bce.py gemma_2B trivia_qa --train_file_name trivia_qa_greedy_responses_train5000 --test_file_name movie_cast_greedy_responses_test2179 --train_labels_file_name trivia_qa_greedy_responses_labels_train5000 --test_labels_file_name movie_cast_greedy_responses_labels_test2179 --len_dataset 5000 --num_folds 1 --using_act layer --token answer_last --method individual_linear_hallu_pos --bs 128 --epochs 50 --lr_list 0.00005,0.0005,0.005 --save_probes True --save_path /home/local/data/ms/honest_llama_data --fast_mode True  --use_best_val_t True --best_using_auc True --seed_list 42,101,2650  --test_num_samples 1 --ood_test True  --skip_train True
python get_activations_and_probe_transformer.py gemma_2B trivia_qa --train_file_name trivia_qa_greedy_responses_train5000 --test_file_name movie_cast_greedy_responses_test2179 --train_labels_file_name trivia_qa_greedy_responses_labels_train5000 --test_labels_file_name movie_cast_greedy_responses_labels_test2179 --len_dataset 5000 --num_folds 1 --using_act layer --token answer_last --method transformer_hallu_pos --bs 128 --epochs 50 --lr_list 0.00005,0.0005,0.005 --save_probes True --save_path /home/local/data/ms/honest_llama_data --fast_mode True  --use_best_val_t True --seed_list 42,101,2650 --best_using_auc True  --test_num_samples 1 --ood_test True  --skip_train True

# NQ
#### OOD ####
# python get_activations_and_probe_non_linear_supcon_bce.py gemma_2B nq_open --train_file_name nq_open_greedy_responses_train5000 --test_file_name city_country_greedy_responses_test1581 --train_labels_file_name nq_open_greedy_responses_labels_train5000 --test_labels_file_name city_country_greedy_responses_labels_test1581 --len_dataset 5000 --num_folds 1 --using_act layer --token answer_last --method individual_linear_hallu_pos --bs 128 --epochs 50 --lr_list 0.00005,0.0005,0.005 --save_probes True --save_path /home/local/data/ms/honest_llama_data --fast_mode True  --use_best_val_t True --best_using_auc True --seed_list 42,101,2650  --test_num_samples 1 --ood_test True  --skip_train True
python get_activations_and_probe_transformer.py gemma_2B nq_open --train_file_name nq_open_greedy_responses_train5000 --test_file_name city_country_greedy_responses_test1581 --train_labels_file_name nq_open_greedy_responses_labels_train5000 --test_labels_file_name city_country_greedy_responses_labels_test1581 --len_dataset 5000 --num_folds 1 --using_act layer --token answer_last --method transformer_hallu_pos --bs 128 --epochs 50 --lr_list 0.00005,0.0005,0.005 --save_probes True --save_path /home/local/data/ms/honest_llama_data --fast_mode True  --use_best_val_t True --seed_list 42,101,2650 --best_using_auc True  --test_num_samples 1 --ood_test True  --skip_train True
# python get_activations_and_probe_non_linear_supcon_bce.py gemma_2B nq_open --train_file_name nq_open_greedy_responses_train5000 --test_file_name player_date_birth_greedy_responses_test1498 --train_labels_file_name nq_open_greedy_responses_labels_train5000 --test_labels_file_name player_date_birth_greedy_responses_labels_test1498 --len_dataset 5000 --num_folds 1 --using_act layer --token answer_last --method individual_linear_hallu_pos --bs 128 --epochs 50 --lr_list 0.00005,0.0005,0.005 --save_probes True --save_path /home/local/data/ms/honest_llama_data --fast_mode True  --use_best_val_t True --best_using_auc True --seed_list 42,101,2650  --test_num_samples 1 --ood_test True  --skip_train True
python get_activations_and_probe_transformer.py gemma_2B nq_open --train_file_name nq_open_greedy_responses_train5000 --test_file_name player_date_birth_greedy_responses_test1498 --train_labels_file_name nq_open_greedy_responses_labels_train5000 --test_labels_file_name player_date_birth_greedy_responses_labels_test1498 --len_dataset 5000 --num_folds 1 --using_act layer --token answer_last --method transformer_hallu_pos --bs 128 --epochs 50 --lr_list 0.00005,0.0005,0.005 --save_probes True --save_path /home/local/data/ms/honest_llama_data --fast_mode True  --use_best_val_t True --seed_list 42,101,2650 --best_using_auc True  --test_num_samples 1 --ood_test True  --skip_train True
# python get_activations_and_probe_non_linear_supcon_bce.py gemma_2B nq_open --train_file_name nq_open_greedy_responses_train5000 --test_file_name movie_cast_greedy_responses_test2179 --train_labels_file_name nq_open_greedy_responses_labels_train5000 --test_labels_file_name movie_cast_greedy_responses_labels_test2179 --len_dataset 5000 --num_folds 1 --using_act layer --token answer_last --method individual_linear_hallu_pos --bs 128 --epochs 50 --lr_list 0.00005,0.0005,0.005 --save_probes True --save_path /home/local/data/ms/honest_llama_data --fast_mode True  --use_best_val_t True --best_using_auc True --seed_list 42,101,2650  --test_num_samples 1 --ood_test True  --skip_train True
python get_activations_and_probe_transformer.py gemma_2B nq_open --train_file_name nq_open_greedy_responses_train5000 --test_file_name movie_cast_greedy_responses_test2179 --train_labels_file_name nq_open_greedy_responses_labels_train5000 --test_labels_file_name movie_cast_greedy_responses_labels_test2179 --len_dataset 5000 --num_folds 1 --using_act layer --token answer_last --method transformer_hallu_pos --bs 128 --epochs 50 --lr_list 0.00005,0.0005,0.005 --save_probes True --save_path /home/local/data/ms/honest_llama_data --fast_mode True  --use_best_val_t True --seed_list 42,101,2650 --best_using_auc True  --test_num_samples 1 --ood_test True  --skip_train True


### RESULTS ###
# python analyse_crossdataset_bce.py gemma_2B city_country --using_act layer --token answer_last --probes_file_name NLSC42_/gemma_2B_/city_country_greedy_responses_train6323_/6323_1_layerFalse_answer_last_individual_linear_hallu_pos_bs128_epochs50_ --probes_file_name_concat ba --lr_list 0.00005,0.0005,0.005,0.05 --best_threshold True --save_path /home/local/data/ms/honest_llama_data --seed_list 42,101,2650 --fpr_at_recall -1
# python analyse_crossdataset_bce_transfmr.py gemma_2B city_country --using_act layer --token answer_last --probes_file_name T42_/gemma_2B_/city_country_greedy_responses_train6323_/6323_1_layerFalse_answer_last_transformer_hallu_pos_bs128_epochs50_ --probes_file_name_concat ba --lr_list 0.00005,0.0005,0.005 --best_threshold True --save_path /home/local/data/ms/honest_llama_data --seed_list 42,101,2650 --fpr_at_recall -1
## OOD
# python analyse_crossdataset_bce.py gemma_2B city_country --using_act layer --token answer_last --probes_file_name NLSC42_/gemma_2B_/ood_city/_player_date_birth_6323_1_layerFalse_answer_last_individual_linear_hallu_pos_bs128_epochs50_ --probes_file_name_concat ba --lr_list 0.00005,0.0005,0.005,0.05 --best_threshold True --save_path /home/local/data/ms/honest_llama_data --seed_list 42,101,2650 --fpr_at_recall -1
# python analyse_crossdataset_bce_transfmr.py gemma_2B city_country --using_act layer --token answer_last --probes_file_name T42_/gemma_2B_/ood_city/_player_date_birth_6323_1_layerFalse_answer_last_transformer_hallu_pos_bs128_epochs50_ --probes_file_name_concat ba --lr_list 0.00005,0.0005,0.005 --best_threshold True --save_path /home/local/data/ms/honest_llama_data --seed_list 42,101,2650 --fpr_at_recall -1
# python analyse_crossdataset_bce.py gemma_2B city_country --using_act layer --token answer_last --probes_file_name NLSC42_/gemma_2B_/ood_city/_movie_cast_6323_1_layerFalse_answer_last_individual_linear_hallu_pos_bs128_epochs50_ --probes_file_name_concat ba --lr_list 0.00005,0.0005,0.005,0.05 --best_threshold True --save_path /home/local/data/ms/honest_llama_data --seed_list 42,101,2650 --fpr_at_recall -1
# python analyse_crossdataset_bce_transfmr.py gemma_2B city_country --using_act layer --token answer_last --probes_file_name T42_/gemma_2B_/ood_city/_movie_cast_6323_1_layerFalse_answer_last_transformer_hallu_pos_bs128_epochs50_ --probes_file_name_concat ba --lr_list 0.00005,0.0005,0.005 --best_threshold True --save_path /home/local/data/ms/honest_llama_data --seed_list 42,101,2650 --fpr_at_recall -1
# python analyse_crossdataset_bce.py gemma_2B city_country --using_act layer --token answer_last --probes_file_name NLSC42_/gemma_2B_/ood_city/_trivia_qa_6323_1_layerFalse_answer_last_individual_linear_hallu_pos_bs128_epochs50_ --probes_file_name_concat ba --lr_list 0.00005,0.0005,0.005,0.05 --best_threshold True --save_path /home/local/data/ms/honest_llama_data --seed_list 42,101,2650 --fpr_at_recall -1
# python analyse_crossdataset_bce_transfmr.py gemma_2B city_country --using_act layer --token answer_last --probes_file_name T42_/gemma_2B_/ood_city/_trivia_qa_6323_1_layerFalse_answer_last_transformer_hallu_pos_bs128_epochs50_ --probes_file_name_concat ba --lr_list 0.00005,0.0005,0.005 --best_threshold True --save_path /home/local/data/ms/honest_llama_data --seed_list 42,101,2650 --fpr_at_recall -1
# python analyse_crossdataset_bce.py gemma_2B city_country --using_act layer --token answer_last --probes_file_name NLSC42_/gemma_2B_/ood_city/_nq_open_6323_1_layerFalse_answer_last_individual_linear_hallu_pos_bs128_epochs50_ --probes_file_name_concat ba --lr_list 0.00005,0.0005,0.005 --best_threshold True --save_path /home/local/data/ms/honest_llama_data --seed_list 42,101,2650 --fpr_at_recall -1
# python analyse_crossdataset_bce_transfmr.py gemma_2B city_country --using_act layer --token answer_last --probes_file_name T42_/gemma_2B_/ood_city/_nq_open_6323_1_layerFalse_answer_last_transformer_hallu_pos_bs128_epochs50_ --probes_file_name_concat ba --lr_list 0.00005,0.0005,0.005 --best_threshold True --save_path /home/local/data/ms/honest_llama_data --seed_list 42,101,2650 --fpr_at_recall -1

# python analyse_crossdataset_bce.py gemma_2B player_date_birth --using_act layer --token answer_last --probes_file_name NLSC42_/gemma_2B_/player_date_birth_greedy_responses_train5989_/5989_1_layerFalse_answer_last_individual_linear_hallu_pos_bs128_epochs50_ --probes_file_name_concat ba --lr_list 0.00005,0.0005,0.005,0.05 --best_threshold True --save_path /home/local/data/ms/honest_llama_data --seed_list 42,101,2650 --fpr_at_recall -1
# python analyse_crossdataset_bce_transfmr.py gemma_2B player_date_birth --using_act layer --token answer_last --probes_file_name T42_/gemma_2B_/player_date_birth_greedy_responses_train5989_/5989_1_layerFalse_answer_last_transformer_hallu_pos_bs128_epochs50_ --probes_file_name_concat ba --lr_list 0.00005,0.0005,0.005 --best_threshold True --save_path /home/local/data/ms/honest_llama_data --seed_list 42,101,2650 --fpr_at_recall -1
## OOD
# python analyse_crossdataset_bce.py gemma_2B player_date_birth --using_act layer --token answer_last --probes_file_name NLSC42_/gemma_2B_/ood_player/_city_country_5989_1_layerFalse_answer_last_individual_linear_hallu_pos_bs128_epochs50_ --probes_file_name_concat ba --lr_list 0.00005,0.0005,0.005,0.05 --best_threshold True --save_path /home/local/data/ms/honest_llama_data --seed_list 42,101,2650 --fpr_at_recall -1
# python analyse_crossdataset_bce_transfmr.py gemma_2B player_date_birth --using_act layer --token answer_last --probes_file_name T42_/gemma_2B_/ood_player/_city_country_5989_1_layerFalse_answer_last_transformer_hallu_pos_bs128_epochs50_ --probes_file_name_concat ba --lr_list 0.00005,0.0005,0.005 --best_threshold True --save_path /home/local/data/ms/honest_llama_data --seed_list 42,101,2650 --fpr_at_recall -1
# python analyse_crossdataset_bce.py gemma_2B player_date_birth --using_act layer --token answer_last --probes_file_name NLSC42_/gemma_2B_/ood_player/_movie_cast_5989_1_layerFalse_answer_last_individual_linear_hallu_pos_bs128_epochs50_ --probes_file_name_concat ba --lr_list 0.00005,0.0005,0.005,0.05 --best_threshold True --save_path /home/local/data/ms/honest_llama_data --seed_list 42,101,2650 --fpr_at_recall -1
# python analyse_crossdataset_bce_transfmr.py gemma_2B player_date_birth --using_act layer --token answer_last --probes_file_name T42_/gemma_2B_/ood_player/_movie_cast_5989_1_layerFalse_answer_last_transformer_hallu_pos_bs128_epochs50_ --probes_file_name_concat ba --lr_list 0.00005,0.0005,0.005 --best_threshold True --save_path /home/local/data/ms/honest_llama_data --seed_list 42,101,2650 --fpr_at_recall -1
# python analyse_crossdataset_bce.py gemma_2B player_date_birth --using_act layer --token answer_last --probes_file_name NLSC42_/gemma_2B_/ood_player/_trivia_qa_5989_1_layerFalse_answer_last_individual_linear_hallu_pos_bs128_epochs50_ --probes_file_name_concat ba --lr_list 0.00005,0.0005,0.005,0.05 --best_threshold True --save_path /home/local/data/ms/honest_llama_data --seed_list 42,101,2650 --fpr_at_recall -1
# python analyse_crossdataset_bce_transfmr.py gemma_2B player_date_birth --using_act layer --token answer_last --probes_file_name T42_/gemma_2B_/ood_player/_trivia_qa_5989_1_layerFalse_answer_last_transformer_hallu_pos_bs128_epochs50_ --probes_file_name_concat ba --lr_list 0.00005,0.0005,0.005 --best_threshold True --save_path /home/local/data/ms/honest_llama_data --seed_list 42,101,2650 --fpr_at_recall -1
# python analyse_crossdataset_bce.py gemma_2B player_date_birth --using_act layer --token answer_last --probes_file_name NLSC42_/gemma_2B_/ood_player/_nq_open_5989_1_layerFalse_answer_last_individual_linear_hallu_pos_bs128_epochs50_ --probes_file_name_concat ba --lr_list 0.00005,0.0005,0.005 --best_threshold True --save_path /home/local/data/ms/honest_llama_data --seed_list 42,101,2650 --fpr_at_recall -1
# python analyse_crossdataset_bce_transfmr.py gemma_2B player_date_birth --using_act layer --token answer_last --probes_file_name T42_/gemma_2B_/ood_player/_nq_open_5989_1_layerFalse_answer_last_transformer_hallu_pos_bs128_epochs50_ --probes_file_name_concat ba --lr_list 0.00005,0.0005,0.005 --best_threshold True --save_path /home/local/data/ms/honest_llama_data --seed_list 42,101,2650 --fpr_at_recall -1

# python analyse_crossdataset_bce.py gemma_2B movie_cast --using_act layer --token answer_last --probes_file_name NLSC42_/gemma_2B_/movie_cast_greedy_responses_train8716_/8716_1_layerFalse_answer_last_individual_linear_hallu_pos_bs128_epochs50_ --probes_file_name_concat ba --lr_list 0.00005,0.0005,0.005,0.05 --best_threshold True --save_path /home/local/data/ms/honest_llama_data --seed_list 42,101,2650 --fpr_at_recall -1
# python analyse_crossdataset_bce_transfmr.py gemma_2B movie_cast --using_act layer --token answer_last --probes_file_name T42_/gemma_2B_/movie_cast_greedy_responses_train8716_/8716_1_layerFalse_answer_last_transformer_hallu_pos_bs128_epochs50_ --probes_file_name_concat ba --lr_list 0.00005,0.0005,0.005 --best_threshold True --save_path /home/local/data/ms/honest_llama_data --seed_list 42,101,2650 --fpr_at_recall -1
## OOD
# python analyse_crossdataset_bce.py gemma_2B city_country --using_act layer --token answer_last --probes_file_name NLSC42_/gemma_2B_/ood_movie/_city_country_8716_1_layerFalse_answer_last_individual_linear_hallu_pos_bs128_epochs50_ --probes_file_name_concat ba --lr_list 0.00005,0.0005,0.005 --best_threshold True --save_path /home/local/data/ms/honest_llama_data --seed_list 42,101,2650 --fpr_at_recall -1
# python analyse_crossdataset_bce_transfmr.py gemma_2B city_country --using_act layer --token answer_last --probes_file_name T42_/gemma_2B_/ood_movie/_city_country_8716_1_layerFalse_answer_last_transformer_hallu_pos_bs128_epochs50_ --probes_file_name_concat ba --lr_list 0.00005,0.0005,0.005 --best_threshold True --save_path /home/local/data/ms/honest_llama_data --seed_list 42,101,2650 --fpr_at_recall -1
# python analyse_crossdataset_bce.py gemma_2B player_date_birth --using_act layer --token answer_last --probes_file_name NLSC42_/gemma_2B_/ood_movie/_player_date_birth_8716_1_layerFalse_answer_last_individual_linear_hallu_pos_bs128_epochs50_ --probes_file_name_concat ba --lr_list 0.00005,0.0005,0.005 --best_threshold True --save_path /home/local/data/ms/honest_llama_data --seed_list 42,101,2650 --fpr_at_recall -1
# python analyse_crossdataset_bce_transfmr.py gemma_2B player_date_birth --using_act layer --token answer_last --probes_file_name T42_/gemma_2B_/ood_movie/_player_date_birth_8716_1_layerFalse_answer_last_transformer_hallu_pos_bs128_epochs50_ --probes_file_name_concat ba --lr_list 0.00005,0.0005,0.005 --best_threshold True --save_path /home/local/data/ms/honest_llama_data --seed_list 42,101,2650 --fpr_at_recall -1
# python analyse_crossdataset_bce.py gemma_2B city_country --using_act layer --token answer_last --probes_file_name NLSC42_/gemma_2B_/ood_movie/_trivia_qa_8716_1_layerFalse_answer_last_individual_linear_hallu_pos_bs128_epochs50_ --probes_file_name_concat ba --lr_list 0.00005,0.0005,0.005 --best_threshold True --save_path /home/local/data/ms/honest_llama_data --seed_list 42,101,2650 --fpr_at_recall -1
# python analyse_crossdataset_bce_transfmr.py gemma_2B city_country --using_act layer --token answer_last --probes_file_name T42_/gemma_2B_/ood_movie/_trivia_qa_8716_1_layerFalse_answer_last_transformer_hallu_pos_bs128_epochs50_ --probes_file_name_concat ba --lr_list 0.00005,0.0005,0.005 --best_threshold True --save_path /home/local/data/ms/honest_llama_data --seed_list 42,101,2650 --fpr_at_recall -1
# python analyse_crossdataset_bce.py gemma_2B player_date_birth --using_act layer --token answer_last --probes_file_name NLSC42_/gemma_2B_/ood_movie/_nq_open_8716_1_layerFalse_answer_last_individual_linear_hallu_pos_bs128_epochs50_ --probes_file_name_concat ba --lr_list 0.00005,0.0005,0.005 --best_threshold True --save_path /home/local/data/ms/honest_llama_data --seed_list 42,101,2650 --fpr_at_recall -1
# python analyse_crossdataset_bce_transfmr.py gemma_2B player_date_birth --using_act layer --token answer_last --probes_file_name T42_/gemma_2B_/ood_movie/_nq_open_8716_1_layerFalse_answer_last_transformer_hallu_pos_bs128_epochs50_ --probes_file_name_concat ba --lr_list 0.00005,0.0005,0.005 --best_threshold True --save_path /home/local/data/ms/honest_llama_data --seed_list 42,101,2650 --fpr_at_recall -1

## OOD
# python analyse_crossdataset_bce.py gemma_2B city_country --using_act layer --token answer_last --probes_file_name NLSC42_/gemma_2B_/ood_trivia_qa/_city_country_5000_1_layerFalse_answer_last_individual_linear_hallu_pos_bs128_epochs50_ --probes_file_name_concat ba --lr_list 0.00005,0.0005,0.005,0.05 --best_threshold True --save_path /home/local/data/ms/honest_llama_data --seed_list 42,101,2650 --fpr_at_recall -1
# python analyse_crossdataset_bce_transfmr.py gemma_2B city_country --using_act layer --token answer_last --probes_file_name T42_/gemma_2B_/ood_trivia_qa/_city_country_5000_1_layerFalse_answer_last_transformer_hallu_pos_bs128_epochs50_ --probes_file_name_concat ba --lr_list 0.00005,0.0005,0.005 --best_threshold True --save_path /home/local/data/ms/honest_llama_data --seed_list 42,101,2650 --fpr_at_recall -1
# python analyse_crossdataset_bce.py gemma_2B player_date_birth --using_act layer --token answer_last --probes_file_name NLSC42_/gemma_2B_/ood_trivia_qa/_player_date_birth_5000_1_layerFalse_answer_last_individual_linear_hallu_pos_bs128_epochs50_ --probes_file_name_concat ba --lr_list 0.00005,0.0005,0.005,0.05 --best_threshold True --save_path /home/local/data/ms/honest_llama_data --seed_list 42,101,2650 --fpr_at_recall -1
# python analyse_crossdataset_bce_transfmr.py gemma_2B player_date_birth --using_act layer --token answer_last --probes_file_name T42_/gemma_2B_/ood_trivia_qa/_player_date_birth_5000_1_layerFalse_answer_last_transformer_hallu_pos_bs128_epochs50_ --probes_file_name_concat ba --lr_list 0.00005,0.0005,0.005 --best_threshold True --save_path /home/local/data/ms/honest_llama_data --seed_list 42,101,2650 --fpr_at_recall -1
# python analyse_crossdataset_bce.py gemma_2B movie_cast --using_act layer --token answer_last --probes_file_name NLSC42_/gemma_2B_/ood_trivia_qa/_movie_cast_5000_1_layerFalse_answer_last_individual_linear_hallu_pos_bs128_epochs50_ --probes_file_name_concat ba --lr_list 0.00005,0.0005,0.005,0.05 --best_threshold True --save_path /home/local/data/ms/honest_llama_data --seed_list 42,101,2650 --fpr_at_recall -1
# python analyse_crossdataset_bce_transfmr.py gemma_2B movie_cast --using_act layer --token answer_last --probes_file_name T42_/gemma_2B_/ood_trivia_qa/_movie_cast_5000_1_layerFalse_answer_last_transformer_hallu_pos_bs128_epochs50_ --probes_file_name_concat ba --lr_list 0.00005,0.0005,0.005 --best_threshold True --save_path /home/local/data/ms/honest_llama_data --seed_list 42,101,2650 --fpr_at_recall -1

## OOD
# python analyse_crossdataset_bce.py gemma_2B city_country --using_act layer --token answer_last --probes_file_name NLSC42_/gemma_2B_/ood_nq_open/_city_country_5000_1_layerFalse_answer_last_individual_linear_hallu_pos_bs128_epochs50_ --probes_file_name_concat ba --lr_list 0.00005,0.0005,0.005 --best_threshold True --save_path /home/local/data/ms/honest_llama_data --seed_list 42,101,2650 --fpr_at_recall -1
# python analyse_crossdataset_bce_transfmr.py gemma_2B city_country --using_act layer --token answer_last --probes_file_name T42_/gemma_2B_/ood_nq_open/_city_country_5000_1_layerFalse_answer_last_transformer_hallu_pos_bs128_epochs50_ --probes_file_name_concat ba --lr_list 0.00005,0.0005,0.005 --best_threshold True --save_path /home/local/data/ms/honest_llama_data --seed_list 42,101,2650 --fpr_at_recall -1
# python analyse_crossdataset_bce.py gemma_2B player_date_birth --using_act layer --token answer_last --probes_file_name NLSC42_/gemma_2B_/ood_nq_open/_player_date_birth_5000_1_layerFalse_answer_last_individual_linear_hallu_pos_bs128_epochs50_ --probes_file_name_concat ba --lr_list 0.00005,0.0005,0.005 --best_threshold True --save_path /home/local/data/ms/honest_llama_data --seed_list 42,101,2650 --fpr_at_recall -1
# python analyse_crossdataset_bce_transfmr.py gemma_2B player_date_birth --using_act layer --token answer_last --probes_file_name T42_/gemma_2B_/ood_nq_open/_player_date_birth_5000_1_layerFalse_answer_last_transformer_hallu_pos_bs128_epochs50_ --probes_file_name_concat ba --lr_list 0.00005,0.0005,0.005 --best_threshold True --save_path /home/local/data/ms/honest_llama_data --seed_list 42,101,2650 --fpr_at_recall -1
# python analyse_crossdataset_bce.py gemma_2B movie_cast --using_act layer --token answer_last --probes_file_name NLSC42_/gemma_2B_/ood_nq_open/_movie_cast_5000_1_layerFalse_answer_last_individual_linear_hallu_pos_bs128_epochs50_ --probes_file_name_concat ba --lr_list 0.00005,0.0005,0.005 --best_threshold True --save_path /home/local/data/ms/honest_llama_data --seed_list 42,101,2650 --fpr_at_recall -1
# python analyse_crossdataset_bce_transfmr.py gemma_2B movie_cast --using_act layer --token answer_last --probes_file_name T42_/gemma_2B_/ood_nq_open/_movie_cast_5000_1_layerFalse_answer_last_transformer_hallu_pos_bs128_epochs50_ --probes_file_name_concat ba --lr_list 0.00005,0.0005,0.005 --best_threshold True --save_path /home/local/data/ms/honest_llama_data --seed_list 42,101,2650 --fpr_at_recall -1