################################# transformer n 1 layer ##########################
# python plot_embedding_space.py hl_llama_7B strqa --train_file_name strqa_baseline_responses_train --test_file_name strqa_baseline_responses_test --using_act layer --token answer_last --len_dataset 1832 --save_path ~/Desktop/honest_llama_data --probes_file_name T42_hl_llama_7B_strqa_baseline_responses_train_1832_1_layerFalse_answer_last_transformer_hallu_pos_bs128_epochs50_5e-05_Falseba_model0 --plot_name hl_strqa_tr_n_plotact --plot_act True
# python plot_embedding_space.py hl_llama_7B strqa --train_file_name strqa_baseline_responses_train --test_file_name strqa_baseline_responses_test --using_act layer --token answer_last --len_dataset 1832 --save_path ~/Desktop/honest_llama_data --probes_file_name T42_hl_llama_7B_strqa_baseline_responses_train_1832_1_layerFalse_answer_last_transformer_hallu_pos_bs128_epochs50_5e-05_Falseba_model0 --plot_name hl_strqa_tr_n_plotemb
# python plot_embedding_space.py hl_llama_7B strqa --train_file_name strqa_baseline_responses_train --test_file_name strqa_baseline_responses_test --using_act layer --token answer_last --len_dataset 1832 --save_path ~/Desktop/honest_llama_data --probes_file_name T42_hl_llama_7B_multi_strqa_1_layerFalse_answer_last_transformer_hallu_pos_bs128_epochs50_5e-05_Falseba_model0 --plot_name hl_comb_strqa_tr_n_plotemb

################################### transformer n*aug 1 layer ####################################
# python plot_embedding_space.py hl_llama_7B strqa --train_file_name strqa_sampledplus_responses_train --test_file_name strqa_baseline_responses_test --using_act layer --token answer_last --len_dataset 16479 --save_path ~/Desktop/honest_llama_data --probes_file_name T42_hl_llama_7B_strqa_sampledplus_responses_train_16479_1_layerFalse_answer_last_transformer_hallu_pos_bs128_epochs50_5e-05_Falseba_model0 --plot_name hl_strqa_tr_naug_plotact --plot_act True
# python plot_embedding_space.py hl_llama_7B strqa --train_file_name strqa_sampledplus_responses_train --test_file_name strqa_baseline_responses_test --using_act layer --token answer_last --len_dataset 16479 --save_path ~/Desktop/honest_llama_data --probes_file_name T42_hl_llama_7B_strqa_sampledplus_responses_train_16479_1_layerFalse_answer_last_transformer_hallu_pos_bs128_epochs50_5e-05_Falseba_model0 --plot_name hl_strqa_tr_naug_plotemb
# python plot_embedding_space.py hl_llama_7B strqa --train_file_name strqa_sampledplus_responses_train --test_file_name strqa_baseline_responses_test --using_act layer --token answer_last --len_dataset 16479 --save_path ~/Desktop/honest_llama_data --probes_file_name T42_hl_llama_7B_strqa_sampledplus_responses_train_16479_1_layerFalse_answer_last_transformer_hallu_pos_bs288_epochs50_5e-05_Falseba_model0 --plot_name hl_strqa_tr_naugb_plotemb

# python plot_embedding_space.py hl_llama_7B strqa --train_file_name strqa_sampledplus_responses_train --test_file_name strqa_baseline_responses_test --using_act layer --token answer_last --len_dataset 16479 --save_path ~/Desktop/honest_llama_data --probes_file_name T42_hl_llama_7B_strqa_sampledplus_responses_train_16479_1_layerFalse_answer_last_transformer_hallu_pos_bs128_epochs50_5e-05_Falseba_model0 --plot_name hl_strqa_tr_naug_plotaugact --plot_act True --plot_aug True
# python plot_embedding_space.py hl_llama_7B strqa --train_file_name strqa_sampledplus_responses_train --test_file_name strqa_baseline_responses_test --using_act layer --token answer_last --len_dataset 16479 --save_path ~/Desktop/honest_llama_data --probes_file_name T42_hl_llama_7B_strqa_sampledplus_responses_train_16479_1_layerFalse_answer_last_transformer_hallu_pos_bs128_epochs50_5e-05_Falseba_model0 --plot_name hl_strqa_tr_naug_plotaugemb --plot_aug True
# python plot_embedding_space.py hl_llama_7B strqa --train_file_name strqa_sampledplus_responses_train --test_file_name strqa_baseline_responses_test --using_act layer --token answer_last --len_dataset 16479 --save_path ~/Desktop/honest_llama_data --probes_file_name T42_hl_llama_7B_strqa_sampledplus_responses_train_16479_1_layerFalse_answer_last_transformer_hallu_pos_bs288_epochs50_5e-05_Falseba_model0 --plot_name hl_strqa_tr_naugb_plotaugemb --plot_aug True
################################# transformer n 1 layer : supcon ##########################
# python plot_embedding_space.py hl_llama_7B strqa --train_file_name strqa_baseline_responses_train --test_file_name strqa_baseline_responses_test --using_act layer --token answer_last --len_dataset 1832 --save_path ~/Desktop/honest_llama_data --probes_file_name T42_hl_llama_7B_strqa_baseline_responses_train_1832_1_layerFalse_answer_last_transformer_supconv2_hallu_pos_bs256_epochs500_5e-05_Falseba_model0 --plot_name hl_strqa_tr_sc_n_plotemb

################################# transformer n*aug 1 layer : supcon ##########################
# python plot_embedding_space.py hl_llama_7B strqa --train_file_name strqa_sampledplus_responses_train --test_file_name strqa_baseline_responses_test --using_act layer --token answer_last --len_dataset 16479 --save_path ~/Desktop/honest_llama_data --probes_file_name T42_hl_llama_7B_strqa_sampledplus_responses_train_16479_1_layerFalse_answer_last_transformer_supconv2_hallu_pos_bs256_epochs500_5e-05_Falseba_model0 --plot_name hl_strqa_tr_sc_naug_plotemb
# python plot_embedding_space.py hl_llama_7B strqa --train_file_name strqa_sampledplus_responses_train --test_file_name strqa_baseline_responses_test --using_act layer --token answer_last --len_dataset 16479 --save_path ~/Desktop/honest_llama_data --probes_file_name T42_hl_llama_7B_strqa_sampledplus_responses_train_16479_1_layerFalse_answer_last_transformer_supconv2_hallu_pos_bs288_epochs500_5e-05_Falseba_model0 --plot_name hl_strqa_tr_sc_naugb_plotemb

# python plot_embedding_space.py hl_llama_7B strqa --train_file_name strqa_sampledplus_responses_train --test_file_name strqa_baseline_responses_test --using_act layer --token answer_last --len_dataset 16479 --save_path ~/Desktop/honest_llama_data --probes_file_name T42_hl_llama_7B_strqa_sampledplus_responses_train_16479_1_layerFalse_answer_last_transformer_supconv2_hallu_pos_bs256_epochs500_5e-05_Falseba_model0 --plot_name hl_strqa_tr_sc_naug_plotaugemb --plot_aug True
# python plot_embedding_space.py hl_llama_7B strqa --train_file_name strqa_sampledplus_responses_train --test_file_name strqa_baseline_responses_test --using_act layer --token answer_last --len_dataset 16479 --save_path ~/Desktop/honest_llama_data --probes_file_name T42_hl_llama_7B_strqa_sampledplus_responses_train_16479_1_layerFalse_answer_last_transformer_supconv2_hallu_pos_bs288_epochs500_5e-05_Falseba_model0 --plot_name hl_strqa_tr_sc_naugb_plotaugemb --plot_aug True
################################# transformer n 1 layer : supcon ##########################
# python plot_embedding_space.py hl_llama_7B strqa --train_file_name strqa_baseline_responses_train --test_file_name strqa_baseline_responses_test --using_act layer --token answer_last --len_dataset 1832 --save_path ~/Desktop/honest_llama_data --probes_file_name T42_hl_llama_7B_strqa_baseline_responses_train_1832_1_layerFalse_answer_last_transformer_supconv2_pos_hallu_pos_bs256_epochs500_5e-05_Falseba_model0 --plot_name hl_strqa_tr_scp_n_plotemb

################################# transformer n*aug 1 layer : supcon+ ##########################
# python plot_embedding_space.py hl_llama_7B strqa --train_file_name strqa_sampledplus_responses_train --test_file_name strqa_baseline_responses_test --using_act layer --token answer_last --len_dataset 16479 --save_path ~/Desktop/honest_llama_data --probes_file_name T42_hl_llama_7B_strqa_sampledplus_responses_train_16479_1_layerFalse_answer_last_transformer_supconv2_pos_hallu_pos_bs256_epochs500_5e-05_Falseba_model0 --plot_name hl_strqa_tr_scp_naug_plotemb
# python plot_embedding_space.py hl_llama_7B strqa --train_file_name strqa_sampledplus_responses_train --test_file_name strqa_baseline_responses_test --using_act layer --token answer_last --len_dataset 16479 --save_path ~/Desktop/honest_llama_data --probes_file_name T42_hl_llama_7B_strqa_sampledplus_responses_train_16479_1_layerFalse_answer_last_transformer_supconv2_pos_hallu_pos_bs288_epochs500_5e-05_Falseba_model0 --plot_name hl_strqa_tr_scp_naugb_plotemb

# python plot_embedding_space.py hl_llama_7B strqa --train_file_name strqa_sampledplus_responses_train --test_file_name strqa_baseline_responses_test --using_act layer --token answer_last --len_dataset 16479 --save_path ~/Desktop/honest_llama_data --probes_file_name T42_hl_llama_7B_strqa_sampledplus_responses_train_16479_1_layerFalse_answer_last_transformer_supconv2_pos_hallu_pos_bs256_epochs500_5e-05_Falseba_model0 --plot_name hl_strqa_tr_scp_naug_plotaugemb --plot_aug True
# python plot_embedding_space.py hl_llama_7B strqa --train_file_name strqa_sampledplus_responses_train --test_file_name strqa_baseline_responses_test --using_act layer --token answer_last --len_dataset 16479 --save_path ~/Desktop/honest_llama_data --probes_file_name T42_hl_llama_7B_strqa_sampledplus_responses_train_16479_1_layerFalse_answer_last_transformer_supconv2_pos_hallu_pos_bs288_epochs500_5e-05_Falseba_model0 --plot_name hl_strqa_tr_scp_naugb_plotaugemb --plot_aug True
################################# transformer n*aug 1 layer : supcon* ##########################
# python plot_embedding_space.py hl_llama_7B strqa --train_file_name strqa_sampledplus_responses_train --test_file_name strqa_baseline_responses_test --using_act layer --token answer_last --len_dataset 16479 --save_path ~/Desktop/honest_llama_data --probes_file_name T42_hl_llama_7B_strqa_sampledplus_responses_train_16479_1_layerFalse_answer_last_transformer_supconv2_wp_hallu_pos_bs288_epochs500_5e-05_Falseba_model0 --plot_name hl_strqa_tr_scwp_naugb_plotemb

# python plot_embedding_space.py hl_llama_7B strqa --train_file_name strqa_sampledplus_responses_train --test_file_name strqa_baseline_responses_test --using_act layer --token answer_last --len_dataset 16479 --save_path ~/Desktop/honest_llama_data --probes_file_name T42_hl_llama_7B_strqa_sampledplus_responses_train_16479_1_layerFalse_answer_last_transformer_supconv2_wp_hallu_pos_bs288_epochs500_5e-05_Falseba_model0 --plot_name hl_strqa_tr_scwp_naugb_plotaugemb --plot_aug True
################################# transformer n*aug 1 layer : supcon+* ##########################
# python plot_embedding_space.py hl_llama_7B strqa --train_file_name strqa_sampledplus_responses_train --test_file_name strqa_baseline_responses_test --using_act layer --token answer_last --len_dataset 16479 --save_path ~/Desktop/honest_llama_data --probes_file_name T42_hl_llama_7B_strqa_sampledplus_responses_train_16479_1_layerFalse_answer_last_transformer_supconv2_pos_wp_hallu_pos_bs288_epochs500_5e-05_Falseba_model0 --plot_name hl_strqa_tr_scpwp_naugb_plotemb

# python plot_embedding_space.py hl_llama_7B strqa --train_file_name strqa_sampledplus_responses_train --test_file_name strqa_baseline_responses_test --using_act layer --token answer_last --len_dataset 16479 --save_path ~/Desktop/honest_llama_data --probes_file_name T42_hl_llama_7B_strqa_sampledplus_responses_train_16479_1_layerFalse_answer_last_transformer_supconv2_pos_wp_hallu_pos_bs288_epochs500_5e-05_Falseba_model0 --plot_name hl_strqa_tr_scpwp_naugb_plotaugemb --plot_aug True



################################ transformer n 1 layer ##########################
python plot_embedding_space.py hl_llama_7B trivia_qa --train_file_name trivia_qa_greedy_responses_train5000 --test_file_name trivia_qa_greedy_responses_validation1800 --train_labels_file_name trivia_qa_greedy_responses_labels_train5000 --test_labels_file_name trivia_qa_greedy_responses_labels_validation1800 --using_act layer --token answer_last --len_dataset 5000 --save_path /home/local/data/ms/honest_llama_data --probes_file_name T42_hl_llama_7B_trivia_qa_greedy_responses_train5000_5000_1_layerFalse_answer_last_transformer_hallu_pos_bs128_epochs50_5e-05_False_model0 --plot_name hl_trivia_qa_tr_n_plotact --plot_act True
python plot_embedding_space.py hl_llama_7B trivia_qa --train_file_name trivia_qa_greedy_responses_train5000 --test_file_name trivia_qa_greedy_responses_validation1800 --train_labels_file_name trivia_qa_greedy_responses_labels_train5000 --test_labels_file_name trivia_qa_greedy_responses_labels_validation1800 --using_act layer --token answer_last --len_dataset 5000 --save_path /home/local/data/ms/honest_llama_data --probes_file_name T42_hl_llama_7B_trivia_qa_greedy_responses_train5000_5000_1_layerFalse_answer_last_transformer_hallu_pos_bs128_epochs50_5e-05_False_model0 --plot_name hl_trivia_qa_tr_n_plotemb
python plot_embedding_space.py hl_llama_7B trivia_qa --train_file_name trivia_qa_greedy_responses_train5000 --test_file_name trivia_qa_greedy_responses_validation1800 --train_labels_file_name trivia_qa_greedy_responses_labels_train5000 --test_labels_file_name trivia_qa_greedy_responses_labels_validation1800 --using_act layer --token answer_last --len_dataset 5000 --save_path /home/local/data/ms/honest_llama_data --probes_file_name T42_hl_llama_7B_multi_trivia_qa_1_layerFalse_answer_last_transformer_hallu_pos_bs128_epochs50_5e-05_False_model0 --plot_name hl_comb_trivia_qa_tr_n_plotemb

################################## transformer n*aug 1 layer ####################################
python plot_embedding_space.py hl_llama_7B trivia_qa --train_file_name trivia_qa_sampledplus_responses_train5000 --test_file_name trivia_qa_greedy_responses_validation1800 --train_labels_file_name trivia_qa_sampledplus_responses_labels_train5000 --test_labels_file_name trivia_qa_greedy_responses_labels_validation1800 --using_act layer --token answer_last --len_dataset 55000 --save_path /home/local/data/ms/honest_llama_data --probes_file_name T42_hl_llama_7B_trivia_qa_sampledplus_responses_train5000_55000_1_layerFalse_answer_last_transformer_hallu_pos_bs128_epochs50_5e-05_Falseba_model0 --plot_name hl_trivia_qa_tr_naug_plotact --plot_act True
python plot_embedding_space.py hl_llama_7B trivia_qa --train_file_name trivia_qa_sampledplus_responses_train5000 --test_file_name trivia_qa_greedy_responses_validation1800 --train_labels_file_name trivia_qa_sampledplus_responses_labels_train5000 --test_labels_file_name trivia_qa_greedy_responses_labels_validation1800 --using_act layer --token answer_last --len_dataset 55000 --save_path /home/local/data/ms/honest_llama_data --probes_file_name T42_hl_llama_7B_trivia_qa_sampledplus_responses_train5000_55000_1_layerFalse_answer_last_transformer_hallu_pos_bs128_epochs50_5e-05_Falseba_model0 --plot_name hl_trivia_qa_tr_naug_plotemb
python plot_embedding_space.py hl_llama_7B trivia_qa --train_file_name trivia_qa_sampledplus_responses_train5000 --test_file_name trivia_qa_greedy_responses_validation1800 --train_labels_file_name trivia_qa_sampledplus_responses_labels_train5000 --test_labels_file_name trivia_qa_greedy_responses_labels_validation1800 --using_act layer --token answer_last --len_dataset 55000 --save_path /home/local/data/ms/honest_llama_data --probes_file_name T42_hl_llama_7B_trivia_qa_sampledplus_responses_train5000_55000_1_layerFalse_answer_last_transformer_hallu_pos_bs352_epochs50_5e-05_Falseba_model0 --plot_name hl_trivia_qa_tr_naugb_plotemb

python plot_embedding_space.py hl_llama_7B trivia_qa --train_file_name trivia_qa_sampledplus_responses_train5000 --test_file_name trivia_qa_greedy_responses_validation1800 --train_labels_file_name trivia_qa_sampledplus_responses_labels_train5000 --test_labels_file_name trivia_qa_greedy_responses_labels_validation1800 --using_act layer --token answer_last --len_dataset 55000 --save_path /home/local/data/ms/honest_llama_data --probes_file_name T42_hl_llama_7B_trivia_qa_sampledplus_responses_train5000_55000_1_layerFalse_answer_last_transformer_hallu_pos_bs128_epochs50_5e-05_Falseba_model0 --plot_name hl_trivia_qa_tr_naug_plotaugact --plot_act True --plot_aug True
python plot_embedding_space.py hl_llama_7B trivia_qa --train_file_name trivia_qa_sampledplus_responses_train5000 --test_file_name trivia_qa_greedy_responses_validation1800 --train_labels_file_name trivia_qa_sampledplus_responses_labels_train5000 --test_labels_file_name trivia_qa_greedy_responses_labels_validation1800 --using_act layer --token answer_last --len_dataset 55000 --save_path /home/local/data/ms/honest_llama_data --probes_file_name T42_hl_llama_7B_trivia_qa_sampledplus_responses_train5000_55000_1_layerFalse_answer_last_transformer_hallu_pos_bs128_epochs50_5e-05_Falseba_model0 --plot_name hl_trivia_qa_tr_naug_plotaugemb --plot_aug True
python plot_embedding_space.py hl_llama_7B trivia_qa --train_file_name trivia_qa_sampledplus_responses_train5000 --test_file_name trivia_qa_greedy_responses_validation1800 --train_labels_file_name trivia_qa_sampledplus_responses_labels_train5000 --test_labels_file_name trivia_qa_greedy_responses_labels_validation1800 --using_act layer --token answer_last --len_dataset 55000 --save_path /home/local/data/ms/honest_llama_data --probes_file_name T42_hl_llama_7B_trivia_qa_sampledplus_responses_train5000_55000_1_layerFalse_answer_last_transformer_hallu_pos_bs352_epochs50_5e-05_Falseba_model0 --plot_name hl_trivia_qa_tr_naugb_plotaugemb --plot_aug True
################################ transformer n 1 layer : supcon ##########################
python plot_embedding_space.py hl_llama_7B trivia_qa --train_file_name trivia_qa_greedy_responses_train5000 --test_file_name trivia_qa_greedy_responses_validation1800 --train_labels_file_name trivia_qa_greedy_responses_labels_train5000 --test_labels_file_name trivia_qa_greedy_responses_labels_validation1800 --using_act layer --token answer_last --len_dataset 5000 --save_path /home/local/data/ms/honest_llama_data --probes_file_name T42_hl_llama_7B_trivia_qa_greedy_responses_train5000_5000_1_layerFalse_answer_last_transformer_supconv2_hallu_pos_bs256_epochs500_5e-05_Falseba_model0 --plot_name hl_trivia_qa_tr_sc_n_plotemb

################################ transformer n*aug 1 layer : supcon ##########################
python plot_embedding_space.py hl_llama_7B trivia_qa --train_file_name trivia_qa_sampledplus_responses_train5000 --test_file_name trivia_qa_greedy_responses_validation1800 --train_labels_file_name trivia_qa_sampledplus_responses_labels_train5000 --test_labels_file_name trivia_qa_greedy_responses_labels_validation1800 --using_act layer --token answer_last --len_dataset 55000 --save_path /home/local/data/ms/honest_llama_data --probes_file_name T42_hl_llama_7B_trivia_qa_sampledplus_responses_train5000_55000_1_layerFalse_answer_last_transformer_supconv2_hallu_pos_bs256_epochs500_5e-05_Falseba_model0 --plot_name hl_trivia_qa_tr_sc_naug_plotemb
python plot_embedding_space.py hl_llama_7B trivia_qa --train_file_name trivia_qa_sampledplus_responses_train5000 --test_file_name trivia_qa_greedy_responses_validation1800 --train_labels_file_name trivia_qa_sampledplus_responses_labels_train5000 --test_labels_file_name trivia_qa_greedy_responses_labels_validation1800 --using_act layer --token answer_last --len_dataset 55000 --save_path /home/local/data/ms/honest_llama_data --probes_file_name T42_hl_llama_7B_trivia_qa_sampledplus_responses_train5000_55000_1_layerFalse_answer_last_transformer_supconv2_hallu_pos_bs352_epochs500_5e-05_Falseba_model0 --plot_name hl_trivia_qa_tr_sc_naugb_plotemb

python plot_embedding_space.py hl_llama_7B trivia_qa --train_file_name trivia_qa_sampledplus_responses_train5000 --test_file_name trivia_qa_greedy_responses_validation1800 --train_labels_file_name trivia_qa_sampledplus_responses_labels_train5000 --test_labels_file_name trivia_qa_greedy_responses_labels_validation1800 --using_act layer --token answer_last --len_dataset 55000 --save_path /home/local/data/ms/honest_llama_data --probes_file_name T42_hl_llama_7B_trivia_qa_sampledplus_responses_train5000_55000_1_layerFalse_answer_last_transformer_supconv2_hallu_pos_bs256_epochs500_5e-05_Falseba_model0 --plot_name hl_trivia_qa_tr_sc_naug_plotaugemb --plot_aug True
python plot_embedding_space.py hl_llama_7B trivia_qa --train_file_name trivia_qa_sampledplus_responses_train5000 --test_file_name trivia_qa_greedy_responses_validation1800 --train_labels_file_name trivia_qa_sampledplus_responses_labels_train5000 --test_labels_file_name trivia_qa_greedy_responses_labels_validation1800 --using_act layer --token answer_last --len_dataset 55000 --save_path /home/local/data/ms/honest_llama_data --probes_file_name T42_hl_llama_7B_trivia_qa_sampledplus_responses_train5000_55000_1_layerFalse_answer_last_transformer_supconv2_hallu_pos_bs352_epochs500_5e-05_Falseba_model0 --plot_name hl_trivia_qa_tr_sc_naugb_plotaugemb --plot_aug True
################################ transformer n 1 layer : supcon+ ##########################
python plot_embedding_space.py hl_llama_7B trivia_qa --train_file_name trivia_qa_greedy_responses_train5000 --test_file_name trivia_qa_greedy_responses_validation1800 --train_labels_file_name trivia_qa_greedy_responses_labels_train5000 --test_labels_file_name trivia_qa_greedy_responses_labels_validation1800 --using_act layer --token answer_last --len_dataset 5000 --save_path /home/local/data/ms/honest_llama_data --probes_file_name T42_hl_llama_7B_trivia_qa_greedy_responses_train5000_5000_1_layerFalse_answer_last_transformer_supconv2_pos_hallu_pos_bs256_epochs500_5e-05_Falseba_model0 --plot_name hl_trivia_qa_tr_scp_n_plotemb

################################ transformer n*aug 1 layer : supcon+ ##########################
python plot_embedding_space.py hl_llama_7B trivia_qa --train_file_name trivia_qa_sampledplus_responses_train5000 --test_file_name trivia_qa_greedy_responses_validation1800 --train_labels_file_name trivia_qa_sampledplus_responses_labels_train5000 --test_labels_file_name trivia_qa_greedy_responses_labels_validation1800 --using_act layer --token answer_last --len_dataset 55000 --save_path /home/local/data/ms/honest_llama_data --probes_file_name T42_hl_llama_7B_trivia_qa_sampledplus_responses_train5000_55000_1_layerFalse_answer_last_transformer_supconv2_pos_hallu_pos_bs256_epochs500_5e-05_Falseba_model0 --plot_name hl_trivia_qa_tr_scp_naug_plotemb
python plot_embedding_space.py hl_llama_7B trivia_qa --train_file_name trivia_qa_sampledplus_responses_train5000 --test_file_name trivia_qa_greedy_responses_validation1800 --train_labels_file_name trivia_qa_sampledplus_responses_labels_train5000 --test_labels_file_name trivia_qa_greedy_responses_labels_validation1800 --using_act layer --token answer_last --len_dataset 55000 --save_path /home/local/data/ms/honest_llama_data --probes_file_name T42_hl_llama_7B_trivia_qa_sampledplus_responses_train5000_55000_1_layerFalse_answer_last_transformer_supconv2_pos_hallu_pos_bs352_epochs500_5e-05_Falseba_model0 --plot_name hl_trivia_qa_tr_scp_naugb_plotemb

python plot_embedding_space.py hl_llama_7B trivia_qa --train_file_name trivia_qa_sampledplus_responses_train5000 --test_file_name trivia_qa_greedy_responses_validation1800 --train_labels_file_name trivia_qa_sampledplus_responses_labels_train5000 --test_labels_file_name trivia_qa_greedy_responses_labels_validation1800 --using_act layer --token answer_last --len_dataset 55000 --save_path /home/local/data/ms/honest_llama_data --probes_file_name T42_hl_llama_7B_trivia_qa_sampledplus_responses_train5000_55000_1_layerFalse_answer_last_transformer_supconv2_pos_hallu_pos_bs256_epochs500_5e-05_Falseba_model0 --plot_name hl_trivia_qa_tr_scp_naug_plotaugemb --plot_aug True
python plot_embedding_space.py hl_llama_7B trivia_qa --train_file_name trivia_qa_sampledplus_responses_train5000 --test_file_name trivia_qa_greedy_responses_validation1800 --train_labels_file_name trivia_qa_sampledplus_responses_labels_train5000 --test_labels_file_name trivia_qa_greedy_responses_labels_validation1800 --using_act layer --token answer_last --len_dataset 55000 --save_path /home/local/data/ms/honest_llama_data --probes_file_name T42_hl_llama_7B_trivia_qa_sampledplus_responses_train5000_55000_1_layerFalse_answer_last_transformer_supconv2_pos_hallu_pos_bs352_epochs500_5e-05_Falseba_model0 --plot_name hl_trivia_qa_tr_scp_naugb_plotaugemb --plot_aug True
################################ transformer n*aug 1 layer : supcon* ##########################
python plot_embedding_space.py hl_llama_7B trivia_qa --train_file_name trivia_qa_sampledplus_responses_train5000 --test_file_name trivia_qa_greedy_responses_validation1800 --train_labels_file_name trivia_qa_sampledplus_responses_labels_train5000 --test_labels_file_name trivia_qa_greedy_responses_labels_validation1800 --using_act layer --token answer_last --len_dataset 55000 --save_path /home/local/data/ms/honest_llama_data --probes_file_name T42_hl_llama_7B_trivia_qa_sampledplus_responses_train5000_55000_1_layerFalse_answer_last_transformer_supconv2_wp_hallu_pos_bs352_epochs500_5e-05_Falseba_model0 --plot_name hl_trivia_qa_tr_scwp_naugb_plotemb

python plot_embedding_space.py hl_llama_7B trivia_qa --train_file_name trivia_qa_sampledplus_responses_train5000 --test_file_name trivia_qa_greedy_responses_validation1800 --train_labels_file_name trivia_qa_sampledplus_responses_labels_train5000 --test_labels_file_name trivia_qa_greedy_responses_labels_validation1800 --using_act layer --token answer_last --len_dataset 55000 --save_path /home/local/data/ms/honest_llama_data --probes_file_name T42_hl_llama_7B_trivia_qa_sampledplus_responses_train5000_55000_1_layerFalse_answer_last_transformer_supconv2_wp_hallu_pos_bs352_epochs500_5e-05_Falseba_model0 --plot_name hl_trivia_qa_tr_scwp_naugb_plotaugemb --plot_aug True
################################ transformer n*aug 1 layer : supcon+* ##########################
python plot_embedding_space.py hl_llama_7B trivia_qa --train_file_name trivia_qa_sampledplus_responses_train5000 --test_file_name trivia_qa_greedy_responses_validation1800 --train_labels_file_name trivia_qa_sampledplus_responses_labels_train5000 --test_labels_file_name trivia_qa_greedy_responses_labels_validation1800 --using_act layer --token answer_last --len_dataset 55000 --save_path /home/local/data/ms/honest_llama_data --probes_file_name T42_hl_llama_7B_trivia_qa_sampledplus_responses_train5000_55000_1_layerFalse_answer_last_transformer_supconv2_pos_wp_hallu_pos_bs352_epochs500_5e-05_Falseba_model0 --plot_name hl_trivia_qa_tr_scpwp_naugb_plotemb

python plot_embedding_space.py hl_llama_7B trivia_qa --train_file_name trivia_qa_sampledplus_responses_train5000 --test_file_name trivia_qa_greedy_responses_validation1800 --train_labels_file_name trivia_qa_sampledplus_responses_labels_train5000 --test_labels_file_name trivia_qa_greedy_responses_labels_validation1800 --using_act layer --token answer_last --len_dataset 55000 --save_path /home/local/data/ms/honest_llama_data --probes_file_name T42_hl_llama_7B_trivia_qa_sampledplus_responses_train5000_55000_1_layerFalse_answer_last_transformer_supconv2_pos_wp_hallu_pos_bs352_epochs500_5e-05_Falseba_model0 --plot_name hl_trivia_qa_tr_scpwp_naugb_plotaugemb --plot_aug True




################################ transformer n 1 layer ##########################
python plot_embedding_space.py hl_llama_7B nq_open --train_file_name nq_open_greedy_responses_train5000 --test_file_name nq_open_greedy_responses_validation1800 --train_labels_file_name nq_open_greedy_responses_labels_train5000 --test_labels_file_name nq_open_greedy_responses_labels_validation1800 --using_act layer --token answer_last --len_dataset 5000 --save_path /home/local/data/ms/honest_llama_data --probes_file_name T42_hl_llama_7B_nq_open_greedy_responses_train5000_5000_1_layerFalse_answer_last_transformer_hallu_pos_bs128_epochs50_5e-05_False_model0 --plot_name hl_nq_open_tr_n_plotact --plot_act True
python plot_embedding_space.py hl_llama_7B nq_open --train_file_name nq_open_greedy_responses_train5000 --test_file_name nq_open_greedy_responses_validation1800 --train_labels_file_name nq_open_greedy_responses_labels_train5000 --test_labels_file_name nq_open_greedy_responses_labels_validation1800 --using_act layer --token answer_last --len_dataset 5000 --save_path /home/local/data/ms/honest_llama_data --probes_file_name T42_hl_llama_7B_nq_open_greedy_responses_train5000_5000_1_layerFalse_answer_last_transformer_hallu_pos_bs128_epochs50_5e-05_False_model0 --plot_name hl_nq_open_tr_n_plotemb
python plot_embedding_space.py hl_llama_7B nq_open --train_file_name nq_open_greedy_responses_train5000 --test_file_name nq_open_greedy_responses_validation1800 --train_labels_file_name nq_open_greedy_responses_labels_train5000 --test_labels_file_name nq_open_greedy_responses_labels_validation1800 --using_act layer --token answer_last --len_dataset 5000 --save_path /home/local/data/ms/honest_llama_data --probes_file_name T42_hl_llama_7B_multi_nq_open_1_layerFalse_answer_last_transformer_hallu_pos_bs128_epochs50_5e-05_False_model0 --plot_name hl_comb_nq_open_tr_n_plotemb

################################## transformer n*aug 1 layer ####################################
python plot_embedding_space.py hl_llama_7B nq_open --train_file_name nq_open_sampledplus_responses_train5000 --test_file_name nq_open_greedy_responses_validation1800 --train_labels_file_name nq_open_sampledplus_responses_labels_train5000 --test_labels_file_name nq_open_greedy_responses_labels_validation1800 --using_act layer --token answer_last --len_dataset 55000 --save_path /home/local/data/ms/honest_llama_data --probes_file_name T42_hl_llama_7B_nq_open_sampledplus_responses_train5000_55000_1_layerFalse_answer_last_transformer_hallu_pos_bs128_epochs50_5e-05_Falseba_model0 --plot_name hl_nq_open_tr_naug_plotact --plot_act True
python plot_embedding_space.py hl_llama_7B nq_open --train_file_name nq_open_sampledplus_responses_train5000 --test_file_name nq_open_greedy_responses_validation1800 --train_labels_file_name nq_open_sampledplus_responses_labels_train5000 --test_labels_file_name nq_open_greedy_responses_labels_validation1800 --using_act layer --token answer_last --len_dataset 55000 --save_path /home/local/data/ms/honest_llama_data --probes_file_name T42_hl_llama_7B_nq_open_sampledplus_responses_train5000_55000_1_layerFalse_answer_last_transformer_hallu_pos_bs128_epochs50_5e-05_Falseba_model0 --plot_name hl_nq_open_tr_naug_plotemb
python plot_embedding_space.py hl_llama_7B nq_open --train_file_name nq_open_sampledplus_responses_train5000 --test_file_name nq_open_greedy_responses_validation1800 --train_labels_file_name nq_open_sampledplus_responses_labels_train5000 --test_labels_file_name nq_open_greedy_responses_labels_validation1800 --using_act layer --token answer_last --len_dataset 55000 --save_path /home/local/data/ms/honest_llama_data --probes_file_name T42_hl_llama_7B_nq_open_sampledplus_responses_train5000_55000_1_layerFalse_answer_last_transformer_hallu_pos_bs352_epochs50_5e-05_Falseba_model0 --plot_name hl_nq_open_tr_naugb_plotemb

python plot_embedding_space.py hl_llama_7B nq_open --train_file_name nq_open_sampledplus_responses_train5000 --test_file_name nq_open_greedy_responses_validation1800 --train_labels_file_name nq_open_sampledplus_responses_labels_train5000 --test_labels_file_name nq_open_greedy_responses_labels_validation1800 --using_act layer --token answer_last --len_dataset 55000 --save_path /home/local/data/ms/honest_llama_data --probes_file_name T42_hl_llama_7B_nq_open_sampledplus_responses_train5000_55000_1_layerFalse_answer_last_transformer_hallu_pos_bs128_epochs50_5e-05_Falseba_model0 --plot_name hl_nq_open_tr_naug_plotaugact --plot_act True --plot_aug True
python plot_embedding_space.py hl_llama_7B nq_open --train_file_name nq_open_sampledplus_responses_train5000 --test_file_name nq_open_greedy_responses_validation1800 --train_labels_file_name nq_open_sampledplus_responses_labels_train5000 --test_labels_file_name nq_open_greedy_responses_labels_validation1800 --using_act layer --token answer_last --len_dataset 55000 --save_path /home/local/data/ms/honest_llama_data --probes_file_name T42_hl_llama_7B_nq_open_sampledplus_responses_train5000_55000_1_layerFalse_answer_last_transformer_hallu_pos_bs128_epochs50_5e-05_Falseba_model0 --plot_name hl_nq_open_tr_naug_plotaugemb --plot_aug True
python plot_embedding_space.py hl_llama_7B nq_open --train_file_name nq_open_sampledplus_responses_train5000 --test_file_name nq_open_greedy_responses_validation1800 --train_labels_file_name nq_open_sampledplus_responses_labels_train5000 --test_labels_file_name nq_open_greedy_responses_labels_validation1800 --using_act layer --token answer_last --len_dataset 55000 --save_path /home/local/data/ms/honest_llama_data --probes_file_name T42_hl_llama_7B_nq_open_sampledplus_responses_train5000_55000_1_layerFalse_answer_last_transformer_hallu_pos_bs352_epochs50_5e-05_Falseba_model0 --plot_name hl_nq_open_tr_naugb_plotaugemb --plot_aug True
################################ transformer n 1 layer : supcon ##########################
python plot_embedding_space.py hl_llama_7B nq_open --train_file_name nq_open_greedy_responses_train5000 --test_file_name nq_open_greedy_responses_validation1800 --train_labels_file_name nq_open_greedy_responses_labels_train5000 --test_labels_file_name nq_open_greedy_responses_labels_validation1800 --using_act layer --token answer_last --len_dataset 5000 --save_path /home/local/data/ms/honest_llama_data --probes_file_name T42_hl_llama_7B_nq_open_greedy_responses_train5000_5000_1_layerFalse_answer_last_transformer_supconv2_hallu_pos_bs256_epochs500_5e-05_Falseba_model0 --plot_name hl_nq_open_tr_sc_n_plotemb

################################ transformer n*aug 1 layer : supcon ##########################
python plot_embedding_space.py hl_llama_7B nq_open --train_file_name nq_open_sampledplus_responses_train5000 --test_file_name nq_open_greedy_responses_validation1800 --train_labels_file_name nq_open_sampledplus_responses_labels_train5000 --test_labels_file_name nq_open_greedy_responses_labels_validation1800 --using_act layer --token answer_last --len_dataset 55000 --save_path /home/local/data/ms/honest_llama_data --probes_file_name T42_hl_llama_7B_nq_open_sampledplus_responses_train5000_55000_1_layerFalse_answer_last_transformer_supconv2_hallu_pos_bs256_epochs500_5e-05_Falseba_model0 --plot_name hl_nq_open_tr_sc_naug_plotemb
python plot_embedding_space.py hl_llama_7B nq_open --train_file_name nq_open_sampledplus_responses_train5000 --test_file_name nq_open_greedy_responses_validation1800 --train_labels_file_name nq_open_sampledplus_responses_labels_train5000 --test_labels_file_name nq_open_greedy_responses_labels_validation1800 --using_act layer --token answer_last --len_dataset 55000 --save_path /home/local/data/ms/honest_llama_data --probes_file_name T42_hl_llama_7B_nq_open_sampledplus_responses_train5000_55000_1_layerFalse_answer_last_transformer_supconv2_hallu_pos_bs352_epochs500_5e-05_Falseba_model0 --plot_name hl_nq_open_tr_sc_naugb_plotemb

python plot_embedding_space.py hl_llama_7B nq_open --train_file_name nq_open_sampledplus_responses_train5000 --test_file_name nq_open_greedy_responses_validation1800 --train_labels_file_name nq_open_sampledplus_responses_labels_train5000 --test_labels_file_name nq_open_greedy_responses_labels_validation1800 --using_act layer --token answer_last --len_dataset 55000 --save_path /home/local/data/ms/honest_llama_data --probes_file_name T42_hl_llama_7B_nq_open_sampledplus_responses_train5000_55000_1_layerFalse_answer_last_transformer_supconv2_hallu_pos_bs256_epochs500_5e-05_Falseba_model0 --plot_name hl_nq_open_tr_sc_naug_plotaugemb --plot_aug True
python plot_embedding_space.py hl_llama_7B nq_open --train_file_name nq_open_sampledplus_responses_train5000 --test_file_name nq_open_greedy_responses_validation1800 --train_labels_file_name nq_open_sampledplus_responses_labels_train5000 --test_labels_file_name nq_open_greedy_responses_labels_validation1800 --using_act layer --token answer_last --len_dataset 55000 --save_path /home/local/data/ms/honest_llama_data --probes_file_name T42_hl_llama_7B_nq_open_sampledplus_responses_train5000_55000_1_layerFalse_answer_last_transformer_supconv2_hallu_pos_bs352_epochs500_5e-05_Falseba_model0 --plot_name hl_nq_open_tr_sc_naugb_plotaugemb --plot_aug True
################################ transformer n 1 layer : supcon+ ##########################
python plot_embedding_space.py hl_llama_7B nq_open --train_file_name nq_open_greedy_responses_train5000 --test_file_name nq_open_greedy_responses_validation1800 --train_labels_file_name nq_open_greedy_responses_labels_train5000 --test_labels_file_name nq_open_greedy_responses_labels_validation1800 --using_act layer --token answer_last --len_dataset 5000 --save_path /home/local/data/ms/honest_llama_data --probes_file_name T42_hl_llama_7B_nq_open_greedy_responses_train5000_5000_1_layerFalse_answer_last_transformer_supconv2_pos_hallu_pos_bs256_epochs500_5e-05_Falseba_model0 --plot_name hl_nq_open_tr_scp_n_plotemb

################################ transformer n*aug 1 layer : supcon+ ##########################
python plot_embedding_space.py hl_llama_7B nq_open --train_file_name nq_open_sampledplus_responses_train5000 --test_file_name nq_open_greedy_responses_validation1800 --train_labels_file_name nq_open_sampledplus_responses_labels_train5000 --test_labels_file_name nq_open_greedy_responses_labels_validation1800 --using_act layer --token answer_last --len_dataset 55000 --save_path /home/local/data/ms/honest_llama_data --probes_file_name T42_hl_llama_7B_nq_open_sampledplus_responses_train5000_55000_1_layerFalse_answer_last_transformer_supconv2_pos_hallu_pos_bs256_epochs500_5e-05_Falseba_model0 --plot_name hl_nq_open_tr_scp_naug_plotemb
python plot_embedding_space.py hl_llama_7B nq_open --train_file_name nq_open_sampledplus_responses_train5000 --test_file_name nq_open_greedy_responses_validation1800 --train_labels_file_name nq_open_sampledplus_responses_labels_train5000 --test_labels_file_name nq_open_greedy_responses_labels_validation1800 --using_act layer --token answer_last --len_dataset 55000 --save_path /home/local/data/ms/honest_llama_data --probes_file_name T42_hl_llama_7B_nq_open_sampledplus_responses_train5000_55000_1_layerFalse_answer_last_transformer_supconv2_pos_hallu_pos_bs352_epochs500_5e-05_Falseba_model0 --plot_name hl_nq_open_tr_scp_naugb_plotemb

python plot_embedding_space.py hl_llama_7B nq_open --train_file_name nq_open_sampledplus_responses_train5000 --test_file_name nq_open_greedy_responses_validation1800 --train_labels_file_name nq_open_sampledplus_responses_labels_train5000 --test_labels_file_name nq_open_greedy_responses_labels_validation1800 --using_act layer --token answer_last --len_dataset 55000 --save_path /home/local/data/ms/honest_llama_data --probes_file_name T42_hl_llama_7B_nq_open_sampledplus_responses_train5000_55000_1_layerFalse_answer_last_transformer_supconv2_pos_hallu_pos_bs256_epochs500_5e-05_Falseba_model0 --plot_name hl_nq_open_tr_scp_naug_plotaugemb --plot_aug True
python plot_embedding_space.py hl_llama_7B nq_open --train_file_name nq_open_sampledplus_responses_train5000 --test_file_name nq_open_greedy_responses_validation1800 --train_labels_file_name nq_open_sampledplus_responses_labels_train5000 --test_labels_file_name nq_open_greedy_responses_labels_validation1800 --using_act layer --token answer_last --len_dataset 55000 --save_path /home/local/data/ms/honest_llama_data --probes_file_name T42_hl_llama_7B_nq_open_sampledplus_responses_train5000_55000_1_layerFalse_answer_last_transformer_supconv2_pos_hallu_pos_bs352_epochs500_5e-05_Falseba_model0 --plot_name hl_nq_open_tr_scp_naugb_plotaugemb --plot_aug True
################################ transformer n*aug 1 layer : supcon* ##########################
python plot_embedding_space.py hl_llama_7B nq_open --train_file_name nq_open_sampledplus_responses_train5000 --test_file_name nq_open_greedy_responses_validation1800 --train_labels_file_name nq_open_sampledplus_responses_labels_train5000 --test_labels_file_name nq_open_greedy_responses_labels_validation1800 --using_act layer --token answer_last --len_dataset 55000 --save_path /home/local/data/ms/honest_llama_data --probes_file_name T42_hl_llama_7B_nq_open_sampledplus_responses_train5000_55000_1_layerFalse_answer_last_transformer_supconv2_wp_hallu_pos_bs352_epochs500_5e-05_Falseba_model0 --plot_name hl_nq_open_tr_scwp_naugb_plotemb

python plot_embedding_space.py hl_llama_7B nq_open --train_file_name nq_open_sampledplus_responses_train5000 --test_file_name nq_open_greedy_responses_validation1800 --train_labels_file_name nq_open_sampledplus_responses_labels_train5000 --test_labels_file_name nq_open_greedy_responses_labels_validation1800 --using_act layer --token answer_last --len_dataset 55000 --save_path /home/local/data/ms/honest_llama_data --probes_file_name T42_hl_llama_7B_nq_open_sampledplus_responses_train5000_55000_1_layerFalse_answer_last_transformer_supconv2_wp_hallu_pos_bs352_epochs500_5e-05_Falseba_model0 --plot_name hl_nq_open_tr_scwp_naugb_plotaugemb --plot_aug True
################################ transformer n*aug 1 layer : supcon+* ##########################
python plot_embedding_space.py hl_llama_7B nq_open --train_file_name nq_open_sampledplus_responses_train5000 --test_file_name nq_open_greedy_responses_validation1800 --train_labels_file_name nq_open_sampledplus_responses_labels_train5000 --test_labels_file_name nq_open_greedy_responses_labels_validation1800 --using_act layer --token answer_last --len_dataset 55000 --save_path /home/local/data/ms/honest_llama_data --probes_file_name T42_hl_llama_7B_nq_open_sampledplus_responses_train5000_55000_1_layerFalse_answer_last_transformer_supconv2_pos_wp_hallu_pos_bs352_epochs500_5e-05_Falseba_model0 --plot_name hl_nq_open_tr_scpwp_naugb_plotemb

python plot_embedding_space.py hl_llama_7B nq_open --train_file_name nq_open_sampledplus_responses_train5000 --test_file_name nq_open_greedy_responses_validation1800 --train_labels_file_name nq_open_sampledplus_responses_labels_train5000 --test_labels_file_name nq_open_greedy_responses_labels_validation1800 --using_act layer --token answer_last --len_dataset 55000 --save_path /home/local/data/ms/honest_llama_data --probes_file_name T42_hl_llama_7B_nq_open_sampledplus_responses_train5000_55000_1_layerFalse_answer_last_transformer_supconv2_pos_wp_hallu_pos_bs352_epochs500_5e-05_Falseba_model0 --plot_name hl_nq_open_tr_scpwp_naugb_plotaugemb --plot_aug True




################################# transformer n 1 layer ##########################
# python plot_embedding_space.py alpaca_7B strqa --train_file_name strqa_baseline_responses_train --test_file_name strqa_baseline_responses_test --using_act layer --token answer_last --len_dataset 1832 --save_path ~/Desktop/honest_llama_data --probes_file_name T42_alpaca_7B_strqa_baseline_responses_train_1832_1_layerFalse_answer_last_transformer_hallu_pos_bs128_epochs50_5e-05_False_model0 --plot_name al_strqa_tr_n_plotact --plot_act True
# python plot_embedding_space.py alpaca_7B strqa --train_file_name strqa_baseline_responses_train --test_file_name strqa_baseline_responses_test --using_act layer --token answer_last --len_dataset 1832 --save_path ~/Desktop/honest_llama_data --probes_file_name T42_alpaca_7B_strqa_baseline_responses_train_1832_1_layerFalse_answer_last_transformer_hallu_pos_bs128_epochs50_5e-05_False_model0 --plot_name al_strqa_tr_n_plotemb
# python plot_embedding_space.py alpaca_7B strqa --train_file_name strqa_baseline_responses_train --test_file_name strqa_baseline_responses_test --using_act layer --token answer_last --len_dataset 1832 --save_path ~/Desktop/honest_llama_data --probes_file_name T42_alpaca_7B_multi_strqa_1_layerFalse_answer_last_transformer_hallu_pos_bs128_epochs50_5e-05_False_model0 --plot_name hl_comb_strqa_tr_n_plotemb

################################### transformer n*aug 1 layer ####################################
# python plot_embedding_space.py alpaca_7B strqa --train_file_name strqa_sampledplus_responses_train --test_file_name strqa_baseline_responses_test --using_act layer --token answer_last --len_dataset 16479 --save_path ~/Desktop/honest_llama_data --probes_file_name T42_alpaca_7B_strqa_sampledplus_responses_train_16479_1_layerFalse_answer_last_transformer_hallu_pos_bs128_epochs50_5e-05_Falseba_model0 --plot_name al_strqa_tr_naug_plotact --plot_act True
# python plot_embedding_space.py alpaca_7B strqa --train_file_name strqa_sampledplus_responses_train --test_file_name strqa_baseline_responses_test --using_act layer --token answer_last --len_dataset 16479 --save_path ~/Desktop/honest_llama_data --probes_file_name T42_alpaca_7B_strqa_sampledplus_responses_train_16479_1_layerFalse_answer_last_transformer_hallu_pos_bs128_epochs50_5e-05_Falseba_model0 --plot_name al_strqa_tr_naug_plotemb
# python plot_embedding_space.py alpaca_7B strqa --train_file_name strqa_sampledplus_responses_train --test_file_name strqa_baseline_responses_test --using_act layer --token answer_last --len_dataset 16479 --save_path ~/Desktop/honest_llama_data --probes_file_name T42_alpaca_7B_strqa_sampledplus_responses_train_16479_1_layerFalse_answer_last_transformer_hallu_pos_bs288_epochs50_5e-05_Falseba_model0 --plot_name al_strqa_tr_naugb_plotemb

# python plot_embedding_space.py alpaca_7B strqa --train_file_name strqa_sampledplus_responses_train --test_file_name strqa_baseline_responses_test --using_act layer --token answer_last --len_dataset 16479 --save_path ~/Desktop/honest_llama_data --probes_file_name T42_alpaca_7B_strqa_sampledplus_responses_train_16479_1_layerFalse_answer_last_transformer_hallu_pos_bs128_epochs50_5e-05_Falseba_model0 --plot_name al_strqa_tr_naug_plotaugact --plot_act True --plot_aug True
# python plot_embedding_space.py alpaca_7B strqa --train_file_name strqa_sampledplus_responses_train --test_file_name strqa_baseline_responses_test --using_act layer --token answer_last --len_dataset 16479 --save_path ~/Desktop/honest_llama_data --probes_file_name T42_alpaca_7B_strqa_sampledplus_responses_train_16479_1_layerFalse_answer_last_transformer_hallu_pos_bs128_epochs50_5e-05_Falseba_model0 --plot_name al_strqa_tr_naug_plotaugemb --plot_aug True
# python plot_embedding_space.py alpaca_7B strqa --train_file_name strqa_sampledplus_responses_train --test_file_name strqa_baseline_responses_test --using_act layer --token answer_last --len_dataset 16479 --save_path ~/Desktop/honest_llama_data --probes_file_name T42_alpaca_7B_strqa_sampledplus_responses_train_16479_1_layerFalse_answer_last_transformer_hallu_pos_bs288_epochs50_5e-05_Falseba_model0 --plot_name al_strqa_tr_naugb_plotaugemb --plot_aug True
################################# transformer n 1 layer : supcon ##########################
# python plot_embedding_space.py alpaca_7B strqa --train_file_name strqa_baseline_responses_train --test_file_name strqa_baseline_responses_test --using_act layer --token answer_last --len_dataset 1832 --save_path ~/Desktop/honest_llama_data --probes_file_name T42_alpaca_7B_strqa_baseline_responses_train_1832_1_layerFalse_answer_last_transformer_supconv2_hallu_pos_bs256_epochs500_5e-05_False_model0 --plot_name al_strqa_tr_sc_n_plotemb

################################# transformer n*aug 1 layer : supcon ##########################
# python plot_embedding_space.py alpaca_7B strqa --train_file_name strqa_sampledplus_responses_train --test_file_name strqa_baseline_responses_test --using_act layer --token answer_last --len_dataset 16479 --save_path ~/Desktop/honest_llama_data --probes_file_name T42_alpaca_7B_strqa_sampledplus_responses_train_16479_1_layerFalse_answer_last_transformer_supconv2_hallu_pos_bs256_epochs500_5e-05_Falseba_model0 --plot_name al_strqa_tr_sc_naug_plotemb
# python plot_embedding_space.py alpaca_7B strqa --train_file_name strqa_sampledplus_responses_train --test_file_name strqa_baseline_responses_test --using_act layer --token answer_last --len_dataset 16479 --save_path ~/Desktop/honest_llama_data --probes_file_name T42_alpaca_7B_strqa_sampledplus_responses_train_16479_1_layerFalse_answer_last_transformer_supconv2_hallu_pos_bs288_epochs500_5e-05_Falseba_model0 --plot_name al_strqa_tr_sc_naugb_plotemb

# python plot_embedding_space.py alpaca_7B strqa --train_file_name strqa_sampledplus_responses_train --test_file_name strqa_baseline_responses_test --using_act layer --token answer_last --len_dataset 16479 --save_path ~/Desktop/honest_llama_data --probes_file_name T42_alpaca_7B_strqa_sampledplus_responses_train_16479_1_layerFalse_answer_last_transformer_supconv2_hallu_pos_bs256_epochs500_5e-05_Falseba_model0 --plot_name al_strqa_tr_sc_naug_plotaugemb --plot_aug True
# python plot_embedding_space.py alpaca_7B strqa --train_file_name strqa_sampledplus_responses_train --test_file_name strqa_baseline_responses_test --using_act layer --token answer_last --len_dataset 16479 --save_path ~/Desktop/honest_llama_data --probes_file_name T42_alpaca_7B_strqa_sampledplus_responses_train_16479_1_layerFalse_answer_last_transformer_supconv2_hallu_pos_bs288_epochs500_5e-05_Falseba_model0 --plot_name al_strqa_tr_sc_naugb_plotaugemb --plot_aug True
################################# transformer n 1 layer : supcon ##########################
# python plot_embedding_space.py alpaca_7B strqa --train_file_name strqa_baseline_responses_train --test_file_name strqa_baseline_responses_test --using_act layer --token answer_last --len_dataset 1832 --save_path ~/Desktop/honest_llama_data --probes_file_name T42_alpaca_7B_strqa_baseline_responses_train_1832_1_layerFalse_answer_last_transformer_supconv2_pos_hallu_pos_bs256_epochs500_5e-05_Falseba_model0 --plot_name al_strqa_tr_scp_n_plotemb

################################# transformer n*aug 1 layer : supcon+ ##########################
# python plot_embedding_space.py alpaca_7B strqa --train_file_name strqa_sampledplus_responses_train --test_file_name strqa_baseline_responses_test --using_act layer --token answer_last --len_dataset 16479 --save_path ~/Desktop/honest_llama_data --probes_file_name T42_alpaca_7B_strqa_sampledplus_responses_train_16479_1_layerFalse_answer_last_transformer_supconv2_pos_hallu_pos_bs256_epochs500_5e-05_Falseba_model0 --plot_name al_strqa_tr_scp_naug_plotemb
# python plot_embedding_space.py alpaca_7B strqa --train_file_name strqa_sampledplus_responses_train --test_file_name strqa_baseline_responses_test --using_act layer --token answer_last --len_dataset 16479 --save_path ~/Desktop/honest_llama_data --probes_file_name T42_alpaca_7B_strqa_sampledplus_responses_train_16479_1_layerFalse_answer_last_transformer_supconv2_pos_hallu_pos_bs288_epochs500_5e-05_Falseba_model0 --plot_name al_strqa_tr_scp_naugb_plotemb

# python plot_embedding_space.py alpaca_7B strqa --train_file_name strqa_sampledplus_responses_train --test_file_name strqa_baseline_responses_test --using_act layer --token answer_last --len_dataset 16479 --save_path ~/Desktop/honest_llama_data --probes_file_name T42_alpaca_7B_strqa_sampledplus_responses_train_16479_1_layerFalse_answer_last_transformer_supconv2_pos_hallu_pos_bs256_epochs500_5e-05_Falseba_model0 --plot_name al_strqa_tr_scp_naug_plotaugemb --plot_aug True
# python plot_embedding_space.py alpaca_7B strqa --train_file_name strqa_sampledplus_responses_train --test_file_name strqa_baseline_responses_test --using_act layer --token answer_last --len_dataset 16479 --save_path ~/Desktop/honest_llama_data --probes_file_name T42_alpaca_7B_strqa_sampledplus_responses_train_16479_1_layerFalse_answer_last_transformer_supconv2_pos_hallu_pos_bs288_epochs500_5e-05_Falseba_model0 --plot_name al_strqa_tr_scp_naugb_plotaugemb --plot_aug True
################################# transformer n*aug 1 layer : supcon* ##########################
# python plot_embedding_space.py alpaca_7B strqa --train_file_name strqa_sampledplus_responses_train --test_file_name strqa_baseline_responses_test --using_act layer --token answer_last --len_dataset 16479 --save_path ~/Desktop/honest_llama_data --probes_file_name T42_alpaca_7B_strqa_sampledplus_responses_train_16479_1_layerFalse_answer_last_transformer_supconv2_wp_hallu_pos_bs288_epochs500_5e-05_Falseba_model0 --plot_name al_strqa_tr_scwp_naugb_plotemb

# python plot_embedding_space.py alpaca_7B strqa --train_file_name strqa_sampledplus_responses_train --test_file_name strqa_baseline_responses_test --using_act layer --token answer_last --len_dataset 16479 --save_path ~/Desktop/honest_llama_data --probes_file_name T42_alpaca_7B_strqa_sampledplus_responses_train_16479_1_layerFalse_answer_last_transformer_supconv2_wp_hallu_pos_bs288_epochs500_5e-05_Falseba_model0 --plot_name al_strqa_tr_scwp_naugb_plotaugemb --plot_aug True
################################# transformer n*aug 1 layer : supcon+* ##########################
# python plot_embedding_space.py alpaca_7B strqa --train_file_name strqa_sampledplus_responses_train --test_file_name strqa_baseline_responses_test --using_act layer --token answer_last --len_dataset 16479 --save_path ~/Desktop/honest_llama_data --probes_file_name T42_alpaca_7B_strqa_sampledplus_responses_train_16479_1_layerFalse_answer_last_transformer_supconv2_pos_wp_hallu_pos_bs288_epochs500_5e-05_Falseba_model0 --plot_name al_strqa_tr_scpwp_naugb_plotemb

# python plot_embedding_space.py alpaca_7B strqa --train_file_name strqa_sampledplus_responses_train --test_file_name strqa_baseline_responses_test --using_act layer --token answer_last --len_dataset 16479 --save_path ~/Desktop/honest_llama_data --probes_file_name T42_alpaca_7B_strqa_sampledplus_responses_train_16479_1_layerFalse_answer_last_transformer_supconv2_pos_wp_hallu_pos_bs288_epochs500_5e-05_Falseba_model0 --plot_name al_strqa_tr_scpwp_naugb_plotaugemb --plot_aug True



################################ transformer n 1 layer ##########################
# python plot_embedding_space.py alpaca_7B trivia_qa --train_file_name trivia_qa_greedy_responses_train5000 --test_file_name trivia_qa_greedy_responses_validation1800 --train_labels_file_name trivia_qa_greedy_responses_labels_train5000 --test_labels_file_name trivia_qa_greedy_responses_labels_validation1800 --using_act layer --token answer_last --len_dataset 5000 --save_path /home/local/data/ms/honest_llama_data --probes_file_name T42_alpaca_7B_trivia_qa_greedy_responses_train5000_5000_1_layerFalse_answer_last_transformer_hallu_pos_bs128_epochs50_5e-05_False_model0 --plot_name al_trivia_qa_tr_n_plotact --plot_act True
# python plot_embedding_space.py alpaca_7B trivia_qa --train_file_name trivia_qa_greedy_responses_train5000 --test_file_name trivia_qa_greedy_responses_validation1800 --train_labels_file_name trivia_qa_greedy_responses_labels_train5000 --test_labels_file_name trivia_qa_greedy_responses_labels_validation1800 --using_act layer --token answer_last --len_dataset 5000 --save_path /home/local/data/ms/honest_llama_data --probes_file_name T42_alpaca_7B_trivia_qa_greedy_responses_train5000_5000_1_layerFalse_answer_last_transformer_hallu_pos_bs128_epochs50_5e-05_False_model0 --plot_name al_trivia_qa_tr_n_plotemb
# python plot_embedding_space.py alpaca_7B trivia_qa --train_file_name trivia_qa_greedy_responses_train5000 --test_file_name trivia_qa_greedy_responses_validation1800 --train_labels_file_name trivia_qa_greedy_responses_labels_train5000 --test_labels_file_name trivia_qa_greedy_responses_labels_validation1800 --using_act layer --token answer_last --len_dataset 5000 --save_path /home/local/data/ms/honest_llama_data --probes_file_name T42_alpaca_7B_multi_trivia_qa_1_layerFalse_answer_last_transformer_hallu_pos_bs128_epochs50_5e-05_False_model0 --plot_name hl_comb_trivia_qa_tr_n_plotemb

# ################################## transformer n*aug 1 layer ####################################
# python plot_embedding_space.py alpaca_7B trivia_qa --train_file_name trivia_qa_sampledplus_responses_train5000 --test_file_name trivia_qa_greedy_responses_validation1800 --train_labels_file_name trivia_qa_sampledplus_responses_labels_train5000 --test_labels_file_name trivia_qa_greedy_responses_labels_validation1800 --using_act layer --token answer_last --len_dataset 55000 --save_path /home/local/data/ms/honest_llama_data --probes_file_name T42_alpaca_7B_trivia_qa_sampledplus_responses_train5000_55000_1_layerFalse_answer_last_transformer_hallu_pos_bs128_epochs50_5e-05_Falseba_model0 --plot_name al_trivia_qa_tr_naug_plotact --plot_act True
# python plot_embedding_space.py alpaca_7B trivia_qa --train_file_name trivia_qa_sampledplus_responses_train5000 --test_file_name trivia_qa_greedy_responses_validation1800 --train_labels_file_name trivia_qa_sampledplus_responses_labels_train5000 --test_labels_file_name trivia_qa_greedy_responses_labels_validation1800 --using_act layer --token answer_last --len_dataset 55000 --save_path /home/local/data/ms/honest_llama_data --probes_file_name T42_alpaca_7B_trivia_qa_sampledplus_responses_train5000_55000_1_layerFalse_answer_last_transformer_hallu_pos_bs128_epochs50_5e-05_Falseba_model0 --plot_name al_trivia_qa_tr_naug_plotemb
# python plot_embedding_space.py alpaca_7B trivia_qa --train_file_name trivia_qa_sampledplus_responses_train5000 --test_file_name trivia_qa_greedy_responses_validation1800 --train_labels_file_name trivia_qa_sampledplus_responses_labels_train5000 --test_labels_file_name trivia_qa_greedy_responses_labels_validation1800 --using_act layer --token answer_last --len_dataset 55000 --save_path /home/local/data/ms/honest_llama_data --probes_file_name T42_alpaca_7B_trivia_qa_sampledplus_responses_train5000_55000_1_layerFalse_answer_last_transformer_hallu_pos_bs352_epochs50_5e-05_Falseba_model0 --plot_name al_trivia_qa_tr_naugb_plotemb

# python plot_embedding_space.py alpaca_7B trivia_qa --train_file_name trivia_qa_sampledplus_responses_train5000 --test_file_name trivia_qa_greedy_responses_validation1800 --train_labels_file_name trivia_qa_sampledplus_responses_labels_train5000 --test_labels_file_name trivia_qa_greedy_responses_labels_validation1800 --using_act layer --token answer_last --len_dataset 55000 --save_path /home/local/data/ms/honest_llama_data --probes_file_name T42_alpaca_7B_trivia_qa_sampledplus_responses_train5000_55000_1_layerFalse_answer_last_transformer_hallu_pos_bs128_epochs50_5e-05_Falseba_model0 --plot_name al_trivia_qa_tr_naug_plotaugact --plot_act True --plot_aug True
# python plot_embedding_space.py alpaca_7B trivia_qa --train_file_name trivia_qa_sampledplus_responses_train5000 --test_file_name trivia_qa_greedy_responses_validation1800 --train_labels_file_name trivia_qa_sampledplus_responses_labels_train5000 --test_labels_file_name trivia_qa_greedy_responses_labels_validation1800 --using_act layer --token answer_last --len_dataset 55000 --save_path /home/local/data/ms/honest_llama_data --probes_file_name T42_alpaca_7B_trivia_qa_sampledplus_responses_train5000_55000_1_layerFalse_answer_last_transformer_hallu_pos_bs128_epochs50_5e-05_Falseba_model0 --plot_name al_trivia_qa_tr_naug_plotaugemb --plot_aug True
# python plot_embedding_space.py alpaca_7B trivia_qa --train_file_name trivia_qa_sampledplus_responses_train5000 --test_file_name trivia_qa_greedy_responses_validation1800 --train_labels_file_name trivia_qa_sampledplus_responses_labels_train5000 --test_labels_file_name trivia_qa_greedy_responses_labels_validation1800 --using_act layer --token answer_last --len_dataset 55000 --save_path /home/local/data/ms/honest_llama_data --probes_file_name T42_alpaca_7B_trivia_qa_sampledplus_responses_train5000_55000_1_layerFalse_answer_last_transformer_hallu_pos_bs352_epochs50_5e-05_Falseba_model0 --plot_name al_trivia_qa_tr_naugb_plotaugemb --plot_aug True
# ################################ transformer n 1 layer : supcon ##########################
# python plot_embedding_space.py alpaca_7B trivia_qa --train_file_name trivia_qa_greedy_responses_train5000 --test_file_name trivia_qa_greedy_responses_validation1800 --train_labels_file_name trivia_qa_greedy_responses_labels_train5000 --test_labels_file_name trivia_qa_greedy_responses_labels_validation1800 --using_act layer --token answer_last --len_dataset 5000 --save_path /home/local/data/ms/honest_llama_data --probes_file_name T42_alpaca_7B_trivia_qa_greedy_responses_train5000_5000_1_layerFalse_answer_last_transformer_supconv2_hallu_pos_bs256_epochs500_5e-05_False_model0 --plot_name al_trivia_qa_tr_sc_n_plotemb

# ################################ transformer n*aug 1 layer : supcon ##########################
# python plot_embedding_space.py alpaca_7B trivia_qa --train_file_name trivia_qa_sampledplus_responses_train5000 --test_file_name trivia_qa_greedy_responses_validation1800 --train_labels_file_name trivia_qa_sampledplus_responses_labels_train5000 --test_labels_file_name trivia_qa_greedy_responses_labels_validation1800 --using_act layer --token answer_last --len_dataset 55000 --save_path /home/local/data/ms/honest_llama_data --probes_file_name T42_alpaca_7B_trivia_qa_sampledplus_responses_train5000_55000_1_layerFalse_answer_last_transformer_supconv2_hallu_pos_bs256_epochs500_5e-05_Falseba_model0 --plot_name al_trivia_qa_tr_sc_naug_plotemb
# python plot_embedding_space.py alpaca_7B trivia_qa --train_file_name trivia_qa_sampledplus_responses_train5000 --test_file_name trivia_qa_greedy_responses_validation1800 --train_labels_file_name trivia_qa_sampledplus_responses_labels_train5000 --test_labels_file_name trivia_qa_greedy_responses_labels_validation1800 --using_act layer --token answer_last --len_dataset 55000 --save_path /home/local/data/ms/honest_llama_data --probes_file_name T42_alpaca_7B_trivia_qa_sampledplus_responses_train5000_55000_1_layerFalse_answer_last_transformer_supconv2_hallu_pos_bs352_epochs500_5e-05_Falseba_model0 --plot_name al_trivia_qa_tr_sc_naugb_plotemb

# python plot_embedding_space.py alpaca_7B trivia_qa --train_file_name trivia_qa_sampledplus_responses_train5000 --test_file_name trivia_qa_greedy_responses_validation1800 --train_labels_file_name trivia_qa_sampledplus_responses_labels_train5000 --test_labels_file_name trivia_qa_greedy_responses_labels_validation1800 --using_act layer --token answer_last --len_dataset 55000 --save_path /home/local/data/ms/honest_llama_data --probes_file_name T42_alpaca_7B_trivia_qa_sampledplus_responses_train5000_55000_1_layerFalse_answer_last_transformer_supconv2_hallu_pos_bs256_epochs500_5e-05_Falseba_model0 --plot_name al_trivia_qa_tr_sc_naug_plotaugemb --plot_aug True
# python plot_embedding_space.py alpaca_7B trivia_qa --train_file_name trivia_qa_sampledplus_responses_train5000 --test_file_name trivia_qa_greedy_responses_validation1800 --train_labels_file_name trivia_qa_sampledplus_responses_labels_train5000 --test_labels_file_name trivia_qa_greedy_responses_labels_validation1800 --using_act layer --token answer_last --len_dataset 55000 --save_path /home/local/data/ms/honest_llama_data --probes_file_name T42_alpaca_7B_trivia_qa_sampledplus_responses_train5000_55000_1_layerFalse_answer_last_transformer_supconv2_hallu_pos_bs352_epochs500_5e-05_Falseba_model0 --plot_name al_trivia_qa_tr_sc_naugb_plotaugemb --plot_aug True
# ################################ transformer n 1 layer : supcon ##########################
# python plot_embedding_space.py alpaca_7B trivia_qa --train_file_name trivia_qa_greedy_responses_train5000 --test_file_name trivia_qa_greedy_responses_validation1800 --train_labels_file_name trivia_qa_greedy_responses_labels_train5000 --test_labels_file_name trivia_qa_greedy_responses_labels_validation1800 --using_act layer --token answer_last --len_dataset 5000 --save_path /home/local/data/ms/honest_llama_data --probes_file_name T42_alpaca_7B_trivia_qa_greedy_responses_train5000_5000_1_layerFalse_answer_last_transformer_supconv2_pos_hallu_pos_bs256_epochs500_5e-05_Falseba_model0 --plot_name al_trivia_qa_tr_scp_n_plotemb

# ################################ transformer n*aug 1 layer : supcon+ ##########################
# python plot_embedding_space.py alpaca_7B trivia_qa --train_file_name trivia_qa_sampledplus_responses_train5000 --test_file_name trivia_qa_greedy_responses_validation1800 --train_labels_file_name trivia_qa_sampledplus_responses_labels_train5000 --test_labels_file_name trivia_qa_greedy_responses_labels_validation1800 --using_act layer --token answer_last --len_dataset 55000 --save_path /home/local/data/ms/honest_llama_data --probes_file_name T42_alpaca_7B_trivia_qa_sampledplus_responses_train5000_55000_1_layerFalse_answer_last_transformer_supconv2_pos_hallu_pos_bs256_epochs500_5e-05_Falseba_model0 --plot_name al_trivia_qa_tr_scp_naug_plotemb
# python plot_embedding_space.py alpaca_7B trivia_qa --train_file_name trivia_qa_sampledplus_responses_train5000 --test_file_name trivia_qa_greedy_responses_validation1800 --train_labels_file_name trivia_qa_sampledplus_responses_labels_train5000 --test_labels_file_name trivia_qa_greedy_responses_labels_validation1800 --using_act layer --token answer_last --len_dataset 55000 --save_path /home/local/data/ms/honest_llama_data --probes_file_name T42_alpaca_7B_trivia_qa_sampledplus_responses_train5000_55000_1_layerFalse_answer_last_transformer_supconv2_pos_hallu_pos_bs352_epochs500_5e-05_Falseba_model0 --plot_name al_trivia_qa_tr_scp_naugb_plotemb

# python plot_embedding_space.py alpaca_7B trivia_qa --train_file_name trivia_qa_sampledplus_responses_train5000 --test_file_name trivia_qa_greedy_responses_validation1800 --train_labels_file_name trivia_qa_sampledplus_responses_labels_train5000 --test_labels_file_name trivia_qa_greedy_responses_labels_validation1800 --using_act layer --token answer_last --len_dataset 55000 --save_path /home/local/data/ms/honest_llama_data --probes_file_name T42_alpaca_7B_trivia_qa_sampledplus_responses_train5000_55000_1_layerFalse_answer_last_transformer_supconv2_pos_hallu_pos_bs256_epochs500_5e-05_Falseba_model0 --plot_name al_trivia_qa_tr_scp_naug_plotaugemb --plot_aug True
# python plot_embedding_space.py alpaca_7B trivia_qa --train_file_name trivia_qa_sampledplus_responses_train5000 --test_file_name trivia_qa_greedy_responses_validation1800 --train_labels_file_name trivia_qa_sampledplus_responses_labels_train5000 --test_labels_file_name trivia_qa_greedy_responses_labels_validation1800 --using_act layer --token answer_last --len_dataset 55000 --save_path /home/local/data/ms/honest_llama_data --probes_file_name T42_alpaca_7B_trivia_qa_sampledplus_responses_train5000_55000_1_layerFalse_answer_last_transformer_supconv2_pos_hallu_pos_bs352_epochs500_5e-05_Falseba_model0 --plot_name al_trivia_qa_tr_scp_naugb_plotaugemb --plot_aug True
# ################################ transformer n*aug 1 layer : supcon* ##########################
# python plot_embedding_space.py alpaca_7B trivia_qa --train_file_name trivia_qa_sampledplus_responses_train5000 --test_file_name trivia_qa_greedy_responses_validation1800 --train_labels_file_name trivia_qa_sampledplus_responses_labels_train5000 --test_labels_file_name trivia_qa_greedy_responses_labels_validation1800 --using_act layer --token answer_last --len_dataset 55000 --save_path /home/local/data/ms/honest_llama_data --probes_file_name T42_alpaca_7B_trivia_qa_sampledplus_responses_train5000_55000_1_layerFalse_answer_last_transformer_supconv2_wp_hallu_pos_bs352_epochs500_5e-05_Falseba_model0 --plot_name al_trivia_qa_tr_scwp_naugb_plotemb

# python plot_embedding_space.py alpaca_7B trivia_qa --train_file_name trivia_qa_sampledplus_responses_train5000 --test_file_name trivia_qa_greedy_responses_validation1800 --train_labels_file_name trivia_qa_sampledplus_responses_labels_train5000 --test_labels_file_name trivia_qa_greedy_responses_labels_validation1800 --using_act layer --token answer_last --len_dataset 55000 --save_path /home/local/data/ms/honest_llama_data --probes_file_name T42_alpaca_7B_trivia_qa_sampledplus_responses_train5000_55000_1_layerFalse_answer_last_transformer_supconv2_wp_hallu_pos_bs352_epochs500_5e-05_Falseba_model0 --plot_name al_trivia_qa_tr_scwp_naugb_plotaugemb --plot_aug True
# ################################ transformer n*aug 1 layer : supcon+* ##########################
# python plot_embedding_space.py alpaca_7B trivia_qa --train_file_name trivia_qa_sampledplus_responses_train5000 --test_file_name trivia_qa_greedy_responses_validation1800 --train_labels_file_name trivia_qa_sampledplus_responses_labels_train5000 --test_labels_file_name trivia_qa_greedy_responses_labels_validation1800 --using_act layer --token answer_last --len_dataset 55000 --save_path /home/local/data/ms/honest_llama_data --probes_file_name T42_alpaca_7B_trivia_qa_sampledplus_responses_train5000_55000_1_layerFalse_answer_last_transformer_supconv2_pos_wp_hallu_pos_bs352_epochs500_5e-05_Falseba_model0 --plot_name al_trivia_qa_tr_scpwp_naugb_plotemb

# python plot_embedding_space.py alpaca_7B trivia_qa --train_file_name trivia_qa_sampledplus_responses_train5000 --test_file_name trivia_qa_greedy_responses_validation1800 --train_labels_file_name trivia_qa_sampledplus_responses_labels_train5000 --test_labels_file_name trivia_qa_greedy_responses_labels_validation1800 --using_act layer --token answer_last --len_dataset 55000 --save_path /home/local/data/ms/honest_llama_data --probes_file_name T42_alpaca_7B_trivia_qa_sampledplus_responses_train5000_55000_1_layerFalse_answer_last_transformer_supconv2_pos_wp_hallu_pos_bs352_epochs500_5e-05_Falseba_model0 --plot_name al_trivia_qa_tr_scpwp_naugb_plotaugemb --plot_aug True




# ################################ transformer n 1 layer ##########################
# python plot_embedding_space.py alpaca_7B nq_open --train_file_name nq_open_greedy_responses_train5000 --test_file_name nq_open_greedy_responses_validation1800 --train_labels_file_name nq_open_greedy_responses_labels_train5000 --test_labels_file_name nq_open_greedy_responses_labels_validation1800 --using_act layer --token answer_last --len_dataset 5000 --save_path /home/local/data/ms/honest_llama_data --probes_file_name T42_alpaca_7B_nq_open_greedy_responses_train5000_5000_1_layerFalse_answer_last_transformer_hallu_pos_bs128_epochs50_5e-05_Falseba_model0 --plot_name al_nq_open_tr_n_plotact --plot_act True
# python plot_embedding_space.py alpaca_7B nq_open --train_file_name nq_open_greedy_responses_train5000 --test_file_name nq_open_greedy_responses_validation1800 --train_labels_file_name nq_open_greedy_responses_labels_train5000 --test_labels_file_name nq_open_greedy_responses_labels_validation1800 --using_act layer --token answer_last --len_dataset 5000 --save_path /home/local/data/ms/honest_llama_data --probes_file_name T42_alpaca_7B_nq_open_greedy_responses_train5000_5000_1_layerFalse_answer_last_transformer_hallu_pos_bs128_epochs50_5e-05_Falseba_model0 --plot_name al_nq_open_tr_n_plotemb
# python plot_embedding_space.py alpaca_7B nq_open --train_file_name nq_open_greedy_responses_train5000 --test_file_name nq_open_greedy_responses_validation1800 --train_labels_file_name nq_open_greedy_responses_labels_train5000 --test_labels_file_name nq_open_greedy_responses_labels_validation1800 --using_act layer --token answer_last --len_dataset 5000 --save_path /home/local/data/ms/honest_llama_data --probes_file_name T42_alpaca_7B_multi_nq_open_1_layerFalse_answer_last_transformer_hallu_pos_bs128_epochs50_5e-05_Falseba_model0 --plot_name hl_comb_nq_open_tr_n_plotemb

# ################################## transformer n*aug 1 layer ####################################
# python plot_embedding_space.py alpaca_7B nq_open --train_file_name nq_open_sampledplus_responses_train5000 --test_file_name nq_open_greedy_responses_validation1800 --train_labels_file_name nq_open_sampledplus_responses_labels_train5000 --test_labels_file_name nq_open_greedy_responses_labels_validation1800 --using_act layer --token answer_last --len_dataset 55000 --save_path /home/local/data/ms/honest_llama_data --probes_file_name T42_alpaca_7B_nq_open_sampledplus_responses_train5000_55000_1_layerFalse_answer_last_transformer_hallu_pos_bs128_epochs50_5e-05_Falseba_model0 --plot_name al_nq_open_tr_naug_plotact --plot_act True
# python plot_embedding_space.py alpaca_7B nq_open --train_file_name nq_open_sampledplus_responses_train5000 --test_file_name nq_open_greedy_responses_validation1800 --train_labels_file_name nq_open_sampledplus_responses_labels_train5000 --test_labels_file_name nq_open_greedy_responses_labels_validation1800 --using_act layer --token answer_last --len_dataset 55000 --save_path /home/local/data/ms/honest_llama_data --probes_file_name T42_alpaca_7B_nq_open_sampledplus_responses_train5000_55000_1_layerFalse_answer_last_transformer_hallu_pos_bs128_epochs50_5e-05_Falseba_model0 --plot_name al_nq_open_tr_naug_plotemb
# python plot_embedding_space.py alpaca_7B nq_open --train_file_name nq_open_sampledplus_responses_train5000 --test_file_name nq_open_greedy_responses_validation1800 --train_labels_file_name nq_open_sampledplus_responses_labels_train5000 --test_labels_file_name nq_open_greedy_responses_labels_validation1800 --using_act layer --token answer_last --len_dataset 55000 --save_path /home/local/data/ms/honest_llama_data --probes_file_name T42_alpaca_7B_nq_open_sampledplus_responses_train5000_55000_1_layerFalse_answer_last_transformer_hallu_pos_bs352_epochs50_5e-05_Falseba_model0 --plot_name al_nq_open_tr_naugb_plotemb

# python plot_embedding_space.py alpaca_7B nq_open --train_file_name nq_open_sampledplus_responses_train5000 --test_file_name nq_open_greedy_responses_validation1800 --train_labels_file_name nq_open_sampledplus_responses_labels_train5000 --test_labels_file_name nq_open_greedy_responses_labels_validation1800 --using_act layer --token answer_last --len_dataset 55000 --save_path /home/local/data/ms/honest_llama_data --probes_file_name T42_alpaca_7B_nq_open_sampledplus_responses_train5000_55000_1_layerFalse_answer_last_transformer_hallu_pos_bs128_epochs50_5e-05_Falseba_model0 --plot_name al_nq_open_tr_naug_plotaugact --plot_act True --plot_aug True
# python plot_embedding_space.py alpaca_7B nq_open --train_file_name nq_open_sampledplus_responses_train5000 --test_file_name nq_open_greedy_responses_validation1800 --train_labels_file_name nq_open_sampledplus_responses_labels_train5000 --test_labels_file_name nq_open_greedy_responses_labels_validation1800 --using_act layer --token answer_last --len_dataset 55000 --save_path /home/local/data/ms/honest_llama_data --probes_file_name T42_alpaca_7B_nq_open_sampledplus_responses_train5000_55000_1_layerFalse_answer_last_transformer_hallu_pos_bs128_epochs50_5e-05_Falseba_model0 --plot_name al_nq_open_tr_naug_plotaugemb --plot_aug True
# python plot_embedding_space.py alpaca_7B nq_open --train_file_name nq_open_sampledplus_responses_train5000 --test_file_name nq_open_greedy_responses_validation1800 --train_labels_file_name nq_open_sampledplus_responses_labels_train5000 --test_labels_file_name nq_open_greedy_responses_labels_validation1800 --using_act layer --token answer_last --len_dataset 55000 --save_path /home/local/data/ms/honest_llama_data --probes_file_name T42_alpaca_7B_nq_open_sampledplus_responses_train5000_55000_1_layerFalse_answer_last_transformer_hallu_pos_bs352_epochs50_5e-05_Falseba_model0 --plot_name al_nq_open_tr_naugb_plotaugemb --plot_aug True
# ################################ transformer n 1 layer : supcon ##########################
# python plot_embedding_space.py alpaca_7B nq_open --train_file_name nq_open_greedy_responses_train5000 --test_file_name nq_open_greedy_responses_validation1800 --train_labels_file_name nq_open_greedy_responses_labels_train5000 --test_labels_file_name nq_open_greedy_responses_labels_validation1800 --using_act layer --token answer_last --len_dataset 5000 --save_path /home/local/data/ms/honest_llama_data --probes_file_name T42_alpaca_7B_nq_open_greedy_responses_train5000_5000_1_layerFalse_answer_last_transformer_supconv2_hallu_pos_bs256_epochs500_5e-05_Falseba_model0 --plot_name al_nq_open_tr_sc_n_plotemb

# ################################ transformer n*aug 1 layer : supcon ##########################
# python plot_embedding_space.py alpaca_7B nq_open --train_file_name nq_open_sampledplus_responses_train5000 --test_file_name nq_open_greedy_responses_validation1800 --train_labels_file_name nq_open_sampledplus_responses_labels_train5000 --test_labels_file_name nq_open_greedy_responses_labels_validation1800 --using_act layer --token answer_last --len_dataset 55000 --save_path /home/local/data/ms/honest_llama_data --probes_file_name T42_alpaca_7B_nq_open_sampledplus_responses_train5000_55000_1_layerFalse_answer_last_transformer_supconv2_hallu_pos_bs256_epochs500_5e-05_Falseba_model0 --plot_name al_nq_open_tr_sc_naug_plotemb
# python plot_embedding_space.py alpaca_7B nq_open --train_file_name nq_open_sampledplus_responses_train5000 --test_file_name nq_open_greedy_responses_validation1800 --train_labels_file_name nq_open_sampledplus_responses_labels_train5000 --test_labels_file_name nq_open_greedy_responses_labels_validation1800 --using_act layer --token answer_last --len_dataset 55000 --save_path /home/local/data/ms/honest_llama_data --probes_file_name T42_alpaca_7B_nq_open_sampledplus_responses_train5000_55000_1_layerFalse_answer_last_transformer_supconv2_hallu_pos_bs352_epochs500_5e-05_Falseba_model0 --plot_name al_nq_open_tr_sc_naugb_plotemb

# python plot_embedding_space.py alpaca_7B nq_open --train_file_name nq_open_sampledplus_responses_train5000 --test_file_name nq_open_greedy_responses_validation1800 --train_labels_file_name nq_open_sampledplus_responses_labels_train5000 --test_labels_file_name nq_open_greedy_responses_labels_validation1800 --using_act layer --token answer_last --len_dataset 55000 --save_path /home/local/data/ms/honest_llama_data --probes_file_name T42_alpaca_7B_nq_open_sampledplus_responses_train5000_55000_1_layerFalse_answer_last_transformer_supconv2_hallu_pos_bs256_epochs500_5e-05_Falseba_model0 --plot_name al_nq_open_tr_sc_naug_plotaugemb --plot_aug True
# python plot_embedding_space.py alpaca_7B nq_open --train_file_name nq_open_sampledplus_responses_train5000 --test_file_name nq_open_greedy_responses_validation1800 --train_labels_file_name nq_open_sampledplus_responses_labels_train5000 --test_labels_file_name nq_open_greedy_responses_labels_validation1800 --using_act layer --token answer_last --len_dataset 55000 --save_path /home/local/data/ms/honest_llama_data --probes_file_name T42_alpaca_7B_nq_open_sampledplus_responses_train5000_55000_1_layerFalse_answer_last_transformer_supconv2_hallu_pos_bs352_epochs500_5e-05_Falseba_model0 --plot_name al_nq_open_tr_sc_naugb_plotaugemb --plot_aug True
# ################################ transformer n 1 layer : supcon ##########################
# python plot_embedding_space.py alpaca_7B nq_open --train_file_name nq_open_greedy_responses_train5000 --test_file_name nq_open_greedy_responses_validation1800 --train_labels_file_name nq_open_greedy_responses_labels_train5000 --test_labels_file_name nq_open_greedy_responses_labels_validation1800 --using_act layer --token answer_last --len_dataset 5000 --save_path /home/local/data/ms/honest_llama_data --probes_file_name T42_alpaca_7B_nq_open_greedy_responses_train5000_5000_1_layerFalse_answer_last_transformer_supconv2_pos_hallu_pos_bs256_epochs500_5e-05_Falseba_model0 --plot_name al_nq_open_tr_scp_n_plotemb

# ################################ transformer n*aug 1 layer : supcon+ ##########################
# python plot_embedding_space.py alpaca_7B nq_open --train_file_name nq_open_sampledplus_responses_train5000 --test_file_name nq_open_greedy_responses_validation1800 --train_labels_file_name nq_open_sampledplus_responses_labels_train5000 --test_labels_file_name nq_open_greedy_responses_labels_validation1800 --using_act layer --token answer_last --len_dataset 55000 --save_path /home/local/data/ms/honest_llama_data --probes_file_name T42_alpaca_7B_nq_open_sampledplus_responses_train5000_55000_1_layerFalse_answer_last_transformer_supconv2_pos_hallu_pos_bs256_epochs500_5e-05_Falseba_model0 --plot_name al_nq_open_tr_scp_naug_plotemb
# python plot_embedding_space.py alpaca_7B nq_open --train_file_name nq_open_sampledplus_responses_train5000 --test_file_name nq_open_greedy_responses_validation1800 --train_labels_file_name nq_open_sampledplus_responses_labels_train5000 --test_labels_file_name nq_open_greedy_responses_labels_validation1800 --using_act layer --token answer_last --len_dataset 55000 --save_path /home/local/data/ms/honest_llama_data --probes_file_name T42_alpaca_7B_nq_open_sampledplus_responses_train5000_55000_1_layerFalse_answer_last_transformer_supconv2_pos_hallu_pos_bs352_epochs500_5e-05_Falseba_model0 --plot_name al_nq_open_tr_scp_naugb_plotemb

# python plot_embedding_space.py alpaca_7B nq_open --train_file_name nq_open_sampledplus_responses_train5000 --test_file_name nq_open_greedy_responses_validation1800 --train_labels_file_name nq_open_sampledplus_responses_labels_train5000 --test_labels_file_name nq_open_greedy_responses_labels_validation1800 --using_act layer --token answer_last --len_dataset 55000 --save_path /home/local/data/ms/honest_llama_data --probes_file_name T42_alpaca_7B_nq_open_sampledplus_responses_train5000_55000_1_layerFalse_answer_last_transformer_supconv2_pos_hallu_pos_bs256_epochs500_5e-05_Falseba_model0 --plot_name al_nq_open_tr_scp_naug_plotaugemb --plot_aug True
# python plot_embedding_space.py alpaca_7B nq_open --train_file_name nq_open_sampledplus_responses_train5000 --test_file_name nq_open_greedy_responses_validation1800 --train_labels_file_name nq_open_sampledplus_responses_labels_train5000 --test_labels_file_name nq_open_greedy_responses_labels_validation1800 --using_act layer --token answer_last --len_dataset 55000 --save_path /home/local/data/ms/honest_llama_data --probes_file_name T42_alpaca_7B_nq_open_sampledplus_responses_train5000_55000_1_layerFalse_answer_last_transformer_supconv2_pos_hallu_pos_bs352_epochs500_5e-05_Falseba_model0 --plot_name al_nq_open_tr_scp_naugb_plotaugemb --plot_aug True
# ################################ transformer n*aug 1 layer : supcon* ##########################
# python plot_embedding_space.py alpaca_7B nq_open --train_file_name nq_open_sampledplus_responses_train5000 --test_file_name nq_open_greedy_responses_validation1800 --train_labels_file_name nq_open_sampledplus_responses_labels_train5000 --test_labels_file_name nq_open_greedy_responses_labels_validation1800 --using_act layer --token answer_last --len_dataset 55000 --save_path /home/local/data/ms/honest_llama_data --probes_file_name T42_alpaca_7B_nq_open_sampledplus_responses_train5000_55000_1_layerFalse_answer_last_transformer_supconv2_wp_hallu_pos_bs352_epochs500_5e-05_Falseba_model0 --plot_name al_nq_open_tr_scwp_naugb_plotemb

# python plot_embedding_space.py alpaca_7B nq_open --train_file_name nq_open_sampledplus_responses_train5000 --test_file_name nq_open_greedy_responses_validation1800 --train_labels_file_name nq_open_sampledplus_responses_labels_train5000 --test_labels_file_name nq_open_greedy_responses_labels_validation1800 --using_act layer --token answer_last --len_dataset 55000 --save_path /home/local/data/ms/honest_llama_data --probes_file_name T42_alpaca_7B_nq_open_sampledplus_responses_train5000_55000_1_layerFalse_answer_last_transformer_supconv2_wp_hallu_pos_bs352_epochs500_5e-05_Falseba_model0 --plot_name al_nq_open_tr_scwp_naugb_plotaugemb --plot_aug True
# ################################ transformer n*aug 1 layer : supcon+* ##########################
# python plot_embedding_space.py alpaca_7B nq_open --train_file_name nq_open_sampledplus_responses_train5000 --test_file_name nq_open_greedy_responses_validation1800 --train_labels_file_name nq_open_sampledplus_responses_labels_train5000 --test_labels_file_name nq_open_greedy_responses_labels_validation1800 --using_act layer --token answer_last --len_dataset 55000 --save_path /home/local/data/ms/honest_llama_data --probes_file_name T42_alpaca_7B_nq_open_sampledplus_responses_train5000_55000_1_layerFalse_answer_last_transformer_supconv2_pos_wp_hallu_pos_bs352_epochs500_5e-05_Falseba_model0 --plot_name al_nq_open_tr_scpwp_naugb_plotemb

# python plot_embedding_space.py alpaca_7B nq_open --train_file_name nq_open_sampledplus_responses_train5000 --test_file_name nq_open_greedy_responses_validation1800 --train_labels_file_name nq_open_sampledplus_responses_labels_train5000 --test_labels_file_name nq_open_greedy_responses_labels_validation1800 --using_act layer --token answer_last --len_dataset 55000 --save_path /home/local/data/ms/honest_llama_data --probes_file_name T42_alpaca_7B_nq_open_sampledplus_responses_train5000_55000_1_layerFalse_answer_last_transformer_supconv2_pos_wp_hallu_pos_bs352_epochs500_5e-05_Falseba_model0 --plot_name al_nq_open_tr_scpwp_naugb_plotaugemb --plot_aug True
