# python get_activations_and_probe_non_linear_supcon_bce.py gemma_2B trivia_qa --train_file_name trivia_qa_greedy_responses_train5000 --test_file_name trivia_qa_greedy_responses_validation1800 --train_labels_file_name trivia_qa_greedy_responses_labels_train5000 --test_labels_file_name trivia_qa_greedy_responses_labels_validation1800 --len_dataset 5000 --num_folds 1 --using_act ah --token answer_last --method individual_linear_hallu_pos --bs 128 --epochs 50 --lr_list 0.0005,0.005 --save_probes True --save_path /home/local/data/ms/honest_llama_data --fast_mode True  --use_best_val_t True --best_using_auc True --seed_list 42,101,2650 --test_num_samples 1;
# python get_activations_and_probe_non_linear_supcon_bce.py gemma_2B nq_open --train_file_name nq_open_greedy_responses_train5000 --test_file_name nq_open_greedy_responses_validation1800 --train_labels_file_name nq_open_greedy_responses_labels_train5000 --test_labels_file_name nq_open_greedy_responses_labels_validation1800 --len_dataset 5000 --num_folds 1 --using_act ah --token answer_last --method individual_linear_hallu_pos --bs 128 --epochs 50 --lr_list 0.0005,0.005 --save_probes True --save_path /home/local/data/ms/honest_llama_data --fast_mode True  --use_best_val_t True --best_using_auc True --seed_list 42,101,2650 --test_num_samples 1;
# python get_activations_and_probe_non_linear_supcon_bce.py gemma_2B strqa --train_file_name strqa_baseline_responses_train --test_file_name strqa_baseline_responses_test --len_dataset 1832 --num_folds 1 --using_act ah --token answer_last --method individual_linear_hallu_pos --bs 128 --epochs 50 --lr_list 0.0005,0.005 --save_probes True --save_path /home/local/data/ms/honest_llama_data --fast_mode True  --use_best_val_t True --best_using_auc True --seed_list 42,101,2650 --test_num_samples 1;

# python get_activations_and_probe_non_linear_supcon_bce.py llama3.1_8B_Instruct trivia_qa --train_file_name trivia_qa_greedy_responses_train5000 --test_file_name trivia_qa_greedy_responses_validation1800 --train_labels_file_name trivia_qa_greedy_responses_labels_train5000 --test_labels_file_name trivia_qa_greedy_responses_labels_validation1800 --len_dataset 5000 --num_folds 1 --using_act ah --token answer_last --method individual_linear_hallu_pos --bs 128 --epochs 50 --lr_list 0.0005,0.005 --save_probes True --save_path /home/local/data/ms/honest_llama_data --fast_mode True  --use_best_val_t True --best_using_auc True --seed_list 42,101,2650 --test_num_samples 1;
# python get_activations_and_probe_non_linear_supcon_bce.py llama3.1_8B_Instruct nq_open --train_file_name nq_open_greedy_responses_train5000 --test_file_name nq_open_greedy_responses_validation1800 --train_labels_file_name nq_open_greedy_responses_labels_train5000 --test_labels_file_name nq_open_greedy_responses_labels_validation1800 --len_dataset 5000 --num_folds 1 --using_act ah --token answer_last --method individual_linear_hallu_pos --bs 128 --epochs 50 --lr_list 0.0005,0.005 --save_probes True --save_path /home/local/data/ms/honest_llama_data --fast_mode True  --use_best_val_t True --best_using_auc True --seed_list 42,101,2650 --test_num_samples 1;
# python get_activations_and_probe_non_linear_supcon_bce.py llama3.1_8B_Instruct strqa --train_file_name strqa_baseline_responses_train --test_file_name strqa_baseline_responses_test --len_dataset 1832 --num_folds 1 --using_act ah --token answer_last --method individual_linear_hallu_pos --bs 128 --epochs 50 --lr_list 0.0005,0.005 --save_probes True --save_path /home/local/data/ms/honest_llama_data --fast_mode True  --use_best_val_t True --best_using_auc True --seed_list 42,101,2650 --test_num_samples 1;

# python get_activations_and_probe_non_linear_supcon_bce.py gemma_2B trivia_qa --train_file_name trivia_qa_greedy_responses_train5000 --test_file_name trivia_qa_sampled_responses_validation1800 --train_labels_file_name trivia_qa_greedy_responses_labels_train5000 --test_labels_file_name trivia_qa_sampled_responses_labels_validation1800 --len_dataset 5000 --num_folds 1 --using_act ah --token answer_last --method individual_linear_hallu_pos --bs 128 --epochs 50 --lr_list 0.0005,0.005 --save_probes True --save_path /home/local/data/ms/honest_llama_data --fast_mode True  --use_best_val_t True --best_using_auc True --seed_list 42,101,2650 --test_num_samples 10
# python get_activations_and_probe_non_linear_supcon_bce.py gemma_2B nq_open --train_file_name nq_open_greedy_responses_train5000 --test_file_name nq_open_sampled_responses_validation1800 --train_labels_file_name nq_open_greedy_responses_labels_train5000 --test_labels_file_name nq_open_sampled_responses_labels_validation1800 --len_dataset 5000 --num_folds 1 --using_act ah --token answer_last --method individual_linear_hallu_pos --bs 128 --epochs 50 --lr_list 0.0005,0.005 --save_probes True --save_path /home/local/data/ms/honest_llama_data --fast_mode True  --use_best_val_t True --best_using_auc True --seed_list 42,101,2650 --test_num_samples 10
# python get_activations_and_probe_non_linear_supcon_bce.py gemma_2B strqa --train_file_name strqa_baseline_responses_train --test_file_name strqa_sampled_responses_test --len_dataset 1832 --num_folds 1 --using_act ah --token answer_last --method individual_linear_hallu_pos --bs 128 --epochs 50 --lr_list 0.0005,0.005 --save_probes True --save_path /home/local/data/ms/honest_llama_data --fast_mode True  --use_best_val_t True --best_using_auc True --seed_list 42,101,2650 --test_num_samples 8

# python get_activations_and_probe_non_linear_supcon_bce.py llama3.1_8B_Instruct trivia_qa --train_file_name trivia_qa_greedy_responses_train5000 --test_file_name trivia_qa_sampled_responses_validation1800 --train_labels_file_name trivia_qa_greedy_responses_labels_train5000 --test_labels_file_name trivia_qa_sampled_responses_labels_validation1800 --len_dataset 5000 --num_folds 1 --using_act ah --token answer_last --method individual_linear_hallu_pos --bs 128 --epochs 50 --lr_list 0.0005,0.005 --save_probes True --save_path /home/local/data/ms/honest_llama_data --fast_mode True  --use_best_val_t True --best_using_auc True --seed_list 42,101,2650 --test_num_samples 10
# python get_activations_and_probe_non_linear_supcon_bce.py llama3.1_8B_Instruct nq_open --train_file_name nq_open_greedy_responses_train5000 --test_file_name nq_open_sampled_responses_validation1800 --train_labels_file_name nq_open_greedy_responses_labels_train5000 --test_labels_file_name nq_open_sampled_responses_labels_validation1800 --len_dataset 5000 --num_folds 1 --using_act ah --token answer_last --method individual_linear_hallu_pos --bs 128 --epochs 50 --lr_list 0.0005,0.005 --save_probes True --save_path /home/local/data/ms/honest_llama_data --fast_mode True  --use_best_val_t True --best_using_auc True --seed_list 42,101,2650 --test_num_samples 10
# python get_activations_and_probe_non_linear_supcon_bce.py llama3.1_8B_Instruct strqa --train_file_name strqa_baseline_responses_train --test_file_name strqa_sampled_responses_test --len_dataset 1832 --num_folds 1 --using_act ah --token answer_last --method individual_linear_hallu_pos --bs 128 --epochs 50 --lr_list 0.0005,0.005 --save_probes True --save_path /home/local/data/ms/honest_llama_data --fast_mode True  --use_best_val_t True --best_using_auc True --seed_list 42,101,2650 --test_num_samples 8

python get_activations_and_probe_non_linear_supcon_bce.py hl_llama_7B trivia_qa --train_file_name trivia_qa_greedy_responses_train5000 --test_file_name trivia_qa_sampled_responses_validation1800 --train_labels_file_name trivia_qa_greedy_responses_labels_train5000 --test_labels_file_name trivia_qa_sampled_responses_labels_validation1800 --len_dataset 5000 --num_folds 1 --using_act ah --token answer_last --method individual_linear_hallu_pos --bs 128 --epochs 50 --lr_list 0.0005,0.005 --save_probes True --save_path /home/local/data/ms/honest_llama_data --fast_mode True  --use_best_val_t True --best_using_auc True --seed_list 42,101,2650 --test_num_samples 10 --skip_train True
python get_activations_and_probe_non_linear_supcon_bce.py hl_llama_7B nq_open --train_file_name nq_open_greedy_responses_train5000 --test_file_name nq_open_sampled_responses_validation1800 --train_labels_file_name nq_open_greedy_responses_labels_train5000 --test_labels_file_name nq_open_sampled_responses_labels_validation1800 --len_dataset 5000 --num_folds 1 --using_act ah --token answer_last --method individual_linear_hallu_pos --bs 128 --epochs 50 --lr_list 0.0005,0.005 --save_probes True --save_path /home/local/data/ms/honest_llama_data --fast_mode True  --use_best_val_t True --best_using_auc True --seed_list 42,101,2650 --test_num_samples 10 --skip_train True
python get_activations_and_probe_non_linear_supcon_bce.py hl_llama_7B strqa --train_file_name strqa_baseline_responses_train --test_file_name strqa_sampled_responses_test --len_dataset 1832 --num_folds 1 --using_act ah --token answer_last --method individual_linear_hallu_pos --bs 128 --epochs 50 --lr_list 0.0005,0.005 --save_probes True --save_path /home/local/data/ms/honest_llama_data --fast_mode True  --use_best_val_t True --best_using_auc True --seed_list 42,101,2650 --test_num_samples 8 --skip_train True

# python get_activations_and_probe_non_linear_supcon_bce.py alpaca_7B trivia_qa --train_file_name trivia_qa_greedy_responses_train5000 --test_file_name trivia_qa_sampled_responses_validation1800 --train_labels_file_name trivia_qa_greedy_responses_labels_train5000 --test_labels_file_name trivia_qa_sampled_responses_labels_validation1800 --len_dataset 5000 --num_folds 1 --using_act ah --token answer_last --method individual_linear_hallu_pos --bs 128 --epochs 50 --lr_list 0.0005,0.005 --save_probes True --save_path /home/local/data/ms/honest_llama_data --fast_mode True  --use_best_val_t True --best_using_auc True --seed_list 42,101,2650 --test_num_samples 10 --skip_train True
# python get_activations_and_probe_non_linear_supcon_bce.py alpaca_7B nq_open --train_file_name nq_open_greedy_responses_train5000 --test_file_name nq_open_sampled_responses_validation1800 --train_labels_file_name nq_open_greedy_responses_labels_train5000 --test_labels_file_name nq_open_sampled_responses_labels_validation1800 --len_dataset 5000 --num_folds 1 --using_act ah --token answer_last --method individual_linear_hallu_pos --bs 128 --epochs 50 --lr_list 0.0005,0.005 --save_probes True --save_path /home/local/data/ms/honest_llama_data --fast_mode True  --use_best_val_t True --best_using_auc True --seed_list 42,101,2650 --test_num_samples 10 --skip_train True
# python get_activations_and_probe_non_linear_supcon_bce.py alpaca_7B strqa --train_file_name strqa_baseline_responses_train --test_file_name strqa_sampled_responses_test --len_dataset 1832 --num_folds 1 --using_act ah --token answer_last --method individual_linear_hallu_pos --bs 128 --epochs 50 --lr_list 0.0005,0.005 --save_probes True --save_path /home/local/data/ms/honest_llama_data --fast_mode True  --use_best_val_t True --best_using_auc True --seed_list 42,101,2650 --test_num_samples 8 --skip_train True

# python get_activations_and_probe_non_linear_supcon_bce.py vicuna_7B trivia_qa --train_file_name trivia_qa_greedy_responses_train5000 --test_file_name trivia_qa_sampled_responses_validation1800 --train_labels_file_name trivia_qa_greedy_responses_labels_train5000 --test_labels_file_name trivia_qa_sampled_responses_labels_validation1800 --len_dataset 5000 --num_folds 1 --using_act ah --token answer_last --method individual_linear_hallu_pos --bs 128 --epochs 50 --lr_list 0.0005,0.005 --save_probes True --save_path /home/local/data/ms/honest_llama_data --fast_mode True  --use_best_val_t True --best_using_auc True --seed_list 42,101,2650 --test_num_samples 10 --skip_train True
# python get_activations_and_probe_non_linear_supcon_bce.py vicuna_7B nq_open --train_file_name nq_open_greedy_responses_train5000 --test_file_name nq_open_sampled_responses_validation1800 --train_labels_file_name nq_open_greedy_responses_labels_train5000 --test_labels_file_name nq_open_sampled_responses_labels_validation1800 --len_dataset 5000 --num_folds 1 --using_act ah --token answer_last --method individual_linear_hallu_pos --bs 128 --epochs 50 --lr_list 0.0005,0.005 --save_probes True --save_path /home/local/data/ms/honest_llama_data --fast_mode True  --use_best_val_t True --best_using_auc True --seed_list 42,101,2650 --test_num_samples 10 --skip_train True
# python get_activations_and_probe_non_linear_supcon_bce.py vicuna_7B strqa --train_file_name strqa_baseline_responses_train --test_file_name strqa_sampled_responses_test --len_dataset 1832 --num_folds 1 --using_act ah --token answer_last --method individual_linear_hallu_pos --bs 128 --epochs 50 --lr_list 0.0005,0.005 --save_probes True --save_path /home/local/data/ms/honest_llama_data --fast_mode True  --use_best_val_t True --best_using_auc True --seed_list 42,101,2650 --test_num_samples 8 --skip_train True

##
# python analyse_crossdataset_bce.py gemma_2B trivia_qa --using_act ah --token answer_last --probes_file_name NLSC42_/gemma_2B_/trivia_qa_greedy_responses_train5000_/5000_1_ahFalse_answer_last_individual_linear_hallu_pos_bs128_epochs50_ --probes_file_name_concat ba --lr_list 0.0005,0.005 --best_threshold True --save_path /home/local/data/ms/honest_llama_data --seed_list 42,101,2650 --fpr_at_recall -1 --test_num_samples 1 --layer_strat ma
# python analyse_crossdataset_bce.py gemma_2B nq_open --using_act ah --token answer_last --probes_file_name NLSC42_/gemma_2B_/nq_open_greedy_responses_train5000_/5000_1_ahFalse_answer_last_individual_linear_hallu_pos_bs128_epochs50_ --probes_file_name_concat ba --lr_list 0.0005,0.005 --best_threshold True --save_path /home/local/data/ms/honest_llama_data --seed_list 42,101,2650 --fpr_at_recall -1 --test_num_samples 1 --layer_strat ma
# python analyse_crossdataset_bce.py gemma_2B strqa --using_act ah --token answer_last --probes_file_name NLSC42_/gemma_2B_/strqa_baseline_responses_train_/5000_1_ahFalse_answer_last_individual_linear_hallu_pos_bs128_epochs50_ --probes_file_name_concat ba --lr_list 0.0005,0.005 --best_threshold True --save_path /home/local/data/ms/honest_llama_data --seed_list 42,101,2650 --fpr_at_recall -1 --test_num_samples 1 --layer_strat ma

#

# python analyse_crossdataset_bce.py gemma_2B trivia_qa --using_act ah --token answer_last --probes_file_name NLSC42_/gemma_2B_/trivia_qa_greedy_responses_train5000_trivia_qa_sampled_responses_validation1800_/5000_1_ahFalse_answer_last_individual_linear_hallu_pos_bs128_epochs50_ --probes_file_name_concat ba --lr_list 0.0005,0.005 --best_threshold True --save_path /home/local/data/ms/honest_llama_data --seed_list 42,101,2650 --fpr_at_recall -1 --test_num_samples 10 --layer_strat ma
# python analyse_crossdataset_bce.py gemma_2B nq_open --using_act ah --token answer_last --probes_file_name NLSC42_/gemma_2B_/nq_open_greedy_responses_train5000_nq_open_sampled_responses_validation1800_/5000_1_ahFalse_answer_last_individual_linear_hallu_pos_bs128_epochs50_ --probes_file_name_concat ba --lr_list 0.0005,0.005 --best_threshold True --save_path /home/local/data/ms/honest_llama_data --seed_list 42,101,2650 --fpr_at_recall -1 --test_num_samples 10 --layer_strat ma
# python analyse_crossdataset_bce.py gemma_2B strqa --using_act ah --token answer_last --probes_file_name NLSC42_/gemma_2B_/strqa_baseline_responses_train_strqa_sampled_responses_test_/5000_1_ahFalse_answer_last_individual_linear_hallu_pos_bs128_epochs50_ --probes_file_name_concat ba --lr_list 0.0005,0.005 --best_threshold True --save_path /home/local/data/ms/honest_llama_data --seed_list 42,101,2650 --fpr_at_recall -1 --test_num_samples 10 --layer_strat ma