python get_activations.py hl_llama_7B trivia_qa --token prompt_last_onwards --file_name trivia_qa_greedy_responses_train5000  --device 0 --save_path /home/local/data/ms/honest_llama_data;
python get_activations.py hl_llama_7B trivia_qa --token prompt_last_onwards --file_name trivia_qa_greedy_responses_validation1800  --device 0 --save_path /home/local/data/ms/honest_llama_data;
python get_activations.py hl_llama_7B trivia_qa --token prompt_last_onwards --file_name trivia_qa_sampledplus_responses_train5000  --device 0 --save_path /home/local/data/ms/honest_llama_data --num_samples 11;
python get_activations.py hl_llama_7B trivia_qa --token prompt_last_onwards --file_name trivia_qa_sampled_responses_validation1800  --device 0 --save_path /home/local/data/ms/honest_llama_data --num_samples 10;

python get_activations.py gemma_2B trivia_qa --token answer_last --file_name trivia_qa_greedy_responses_train5000  --device 0 --save_path /home/local/data/ms/honest_llama_data;
python get_activations.py gemma_2B trivia_qa --token answer_last --file_name trivia_qa_greedy_responses_validation1800  --device 0 --save_path /home/local/data/ms/honest_llama_data;
python get_activations.py gemma_2B trivia_qa --token prompt_last_onwards --file_name trivia_qa_greedy_responses_train5000  --device 0 --save_path /home/local/data/ms/honest_llama_data;
python get_activations.py gemma_2B trivia_qa --token prompt_last_onwards --file_name trivia_qa_greedy_responses_validation1800  --device 0 --save_path /home/local/data/ms/honest_llama_data;

## Train Probes

# python get_activations_and_probe_transformer.py hl_llama_7B trivia_qa --train_file_name trivia_qa_greedy_responses_train5000 --test_file_name trivia_qa_greedy_responses_validation1800 --train_labels_file_name trivia_qa_greedy_responses_labels_train5000 --test_labels_file_name trivia_qa_greedy_responses_labels_validation1800 --len_dataset 2000 --num_folds 1 --using_act layer --token answer_last --method transformer2_hallu_pos --bs 128 --epochs 50 --lr_list 0.00005,0.0005,0.005 --save_probes True --save_path /home/local/data/ms/honest_llama_data --fast_mode True  --use_best_val_t True  --seed_list 42 --best_using_auc True --test_num_samples 1
# python get_activations_and_probe_non_linear_supcon_bce.py hl_llama_7B trivia_qa --train_file_name trivia_qa_greedy_responses_train5000 --test_file_name trivia_qa_greedy_responses_validation1800 --train_labels_file_name trivia_qa_greedy_responses_labels_train5000 --test_labels_file_name trivia_qa_greedy_responses_labels_validation1800 --len_dataset 2000 --num_folds 1 --using_act layer_att_res --token prompt_last_onwards --method individual_att_pool_hallu_pos --bs 128 --epochs 50 --lr_list 0.00005,0.0005,0.005 --save_probes True --save_path /home/local/data/ms/honest_llama_data --fast_mode True  --use_best_val_t True  --seed_list 42 --best_using_auc True --test_num_samples 1
# python get_activations_and_probe_non_linear_supcon_bce.py hl_llama_7B trivia_qa --train_file_name trivia_qa_greedy_responses_train5000 --test_file_name trivia_qa_greedy_responses_validation1800 --train_labels_file_name trivia_qa_greedy_responses_labels_train5000 --test_labels_file_name trivia_qa_greedy_responses_labels_validation1800 --len_dataset 2000 --num_folds 1 --using_act att_pool_emb --token prompt_last_onwards --method ens_att_pool_hallu_pos --bs 128 --epochs 50 --lr_list 0.00005,0.0005,0.005 --save_probes True --save_path /home/local/data/ms/honest_llama_data --fast_mode True  --use_best_val_t True  --seed_list 42 --best_using_auc True --test_num_samples 1

# Baseline # LP-MA # python get_activations_and_probe_non_linear_supcon_bce.py gemma_2B trivia_qa --train_file_name trivia_qa_greedy_responses_train5000 --test_file_name trivia_qa_greedy_responses_validation1800 --train_labels_file_name trivia_qa_greedy_responses_labels_train5000 --test_labels_file_name trivia_qa_greedy_responses_labels_validation1800 --len_dataset 2000 --num_folds 1 --using_act layer --token answer_last --method individual_linear_hallu_pos --bs 128 --epochs 50 --lr_list 0.00005,0.0005,0.005 --save_probes True --save_path /home/local/data/ms/honest_llama_data --fast_mode True  --use_best_val_t True  --seed_list 42,101,2650 --best_using_auc True --test_num_samples 1
# Baseline # NLP-MA # python get_activations_and_probe_non_linear_supcon_bce.py gemma_2B trivia_qa --train_file_name trivia_qa_greedy_responses_train5000 --test_file_name trivia_qa_greedy_responses_validation1800 --train_labels_file_name trivia_qa_greedy_responses_labels_train5000 --test_labels_file_name trivia_qa_greedy_responses_labels_validation1800 --len_dataset 2000 --num_folds 1 --using_act layer --token answer_last --method individual_non_linear_4_hallu_pos --bs 128 --epochs 50 --lr_list 0.00005,0.0005,0.005 --save_probes True --save_path /home/local/data/ms/honest_llama_data --fast_mode True  --use_best_val_t True  --seed_list 42,101,2650 --best_using_auc True --test_num_samples 1
# Baseline # CLAP # python get_activations_and_probe_transformer.py gemma_2B trivia_qa --train_file_name trivia_qa_greedy_responses_train5000 --test_file_name trivia_qa_greedy_responses_validation1800 --train_labels_file_name trivia_qa_greedy_responses_labels_train5000 --test_labels_file_name trivia_qa_greedy_responses_labels_validation1800 --len_dataset 2000 --num_folds 1 --using_act layer --token answer_last --method transformer2_hallu_pos --bs 128 --epochs 50 --lr_list 0.00005,0.0005,0.005 --save_probes True --save_path /home/local/data/ms/honest_llama_data --fast_mode True  --use_best_val_t True  --seed_list 42,101,2650 --best_using_auc True --test_num_samples 1
# Add Sub-Layers # LP-MA # python get_activations_and_probe_non_linear_supcon_bce.py gemma_2B trivia_qa --train_file_name trivia_qa_greedy_responses_train5000 --test_file_name trivia_qa_greedy_responses_validation1800 --train_labels_file_name trivia_qa_greedy_responses_labels_train5000 --test_labels_file_name trivia_qa_greedy_responses_labels_validation1800 --len_dataset 2000 --num_folds 1 --using_act layer_att_res --token answer_last --method individual_linear_hallu_pos --bs 128 --epochs 50 --lr_list 0.00005,0.0005,0.005 --save_probes True --save_path /home/local/data/ms/honest_llama_data --fast_mode True  --use_best_val_t True  --seed_list 42,101,2650 --best_using_auc True --test_num_samples 1
# Add Sub-Layers # NLP-MA # python get_activations_and_probe_non_linear_supcon_bce.py gemma_2B trivia_qa --train_file_name trivia_qa_greedy_responses_train5000 --test_file_name trivia_qa_greedy_responses_validation1800 --train_labels_file_name trivia_qa_greedy_responses_labels_train5000 --test_labels_file_name trivia_qa_greedy_responses_labels_validation1800 --len_dataset 2000 --num_folds 1 --using_act layer_att_res --token answer_last --method individual_non_linear_4_hallu_pos --bs 128 --epochs 50 --lr_list 0.00005,0.0005,0.005 --save_probes True --save_path /home/local/data/ms/honest_llama_data --fast_mode True  --use_best_val_t True  --seed_list 42,101,2650 --best_using_auc True --test_num_samples 1
# Add Sub-Layers # CLAP # python get_activations_and_probe_transformer.py gemma_2B trivia_qa --train_file_name trivia_qa_greedy_responses_train5000 --test_file_name trivia_qa_greedy_responses_validation1800 --train_labels_file_name trivia_qa_greedy_responses_labels_train5000 --test_labels_file_name trivia_qa_greedy_responses_labels_validation1800 --len_dataset 2000 --num_folds 1 --using_act layer_att_res --token answer_last --method transformer2_hallu_pos --bs 128 --epochs 50 --lr_list 0.00005,0.0005,0.005 --save_probes True --save_path /home/local/data/ms/honest_llama_data --fast_mode True  --use_best_val_t True  --seed_list 42,101,2650 --best_using_auc True --test_num_samples 1
# Att-Pool # python get_activations_and_probe_non_linear_supcon_bce.py gemma_2B trivia_qa --train_file_name trivia_qa_greedy_responses_train5000 --test_file_name trivia_qa_greedy_responses_validation1800 --train_labels_file_name trivia_qa_greedy_responses_labels_train5000 --test_labels_file_name trivia_qa_greedy_responses_labels_validation1800 --len_dataset 2000 --num_folds 1 --using_act layer_att_res --token prompt_last_onwards --method individual_att_pool_hallu_pos --bs 128 --epochs 50 --lr_list 0.00005,0.0005,0.005 --save_probes True --save_path /home/local/data/ms/honest_llama_data --fast_mode True  --use_best_val_t True  --seed_list 42 --best_using_auc True --test_num_samples 1
# Not-implemented Att-Pool + Ensemble # python get_activations_and_probe_non_linear_supcon_bce.py gemma_2B trivia_qa --train_file_name trivia_qa_greedy_responses_train5000 --test_file_name trivia_qa_greedy_responses_validation1800 --train_labels_file_name trivia_qa_greedy_responses_labels_train5000 --test_labels_file_name trivia_qa_greedy_responses_labels_validation1800 --len_dataset 2000 --num_folds 1 --using_act att_pool_emb --token prompt_last_onwards --method individual_linear_hallu_pos --cfr_no_bias True --bs 128 --epochs 50 --lr_list 0.00005,0.0005,0.005 --save_probes True --save_path /home/local/data/ms/honest_llama_data --fast_mode True  --use_best_val_t True  --seed_list 42 --best_using_auc True --test_num_samples 1
# Add Sub-Layers + Att Pooling # CLAP # python get_activations_and_probe_transformer.py gemma_2B trivia_qa --train_file_name trivia_qa_greedy_responses_train5000 --test_file_name trivia_qa_greedy_responses_validation1800 --train_labels_file_name trivia_qa_greedy_responses_labels_train5000 --test_labels_file_name trivia_qa_greedy_responses_labels_validation1800 --len_dataset 2000 --num_folds 1 --using_act layer_att_res --token prompt_last_onwards --method transformer2_hallu_pos --bs 128 --epochs 50 --lr_list 0.00005,0.0005,0.005 --save_probes True --save_path /home/local/data/ms/honest_llama_data --fast_mode True  --use_best_val_t True  --seed_list 42,101,2650 --best_using_auc True --test_num_samples 1


## Get Results
python analyse_crossdataset_bce.py gemma_2B trivia_qa --using_act layer --token answer_last --probes_file_name NLSC42_/gemma_2B_/trivia_qa_greedy_responses_train5000_/2000_1_layerFalse_answer_last_individual_linear_hallu_pos_bs128_epochs50_ --probes_file_name_concat ba --lr_list 0.00005,0.0005,0.005 --best_threshold True --save_path /home/local/data/ms/honest_llama_data --seed_list 42,101,2650 --fpr_at_recall -1 --test_num_samples 1 --layer_strat ma
python analyse_crossdataset_bce.py gemma_2B trivia_qa --using_act layer --token answer_last --probes_file_name NLSC42_/gemma_2B_/trivia_qa_greedy_responses_train5000_/2000_1_layerFalse_answer_last_individual_non_linear_4_hallu_pos_bs128_epochs50_ --probes_file_name_concat ba --lr_list 0.00005,0.0005,0.005 --best_threshold True --save_path /home/local/data/ms/honest_llama_data --seed_list 42,101,2650 --fpr_at_recall -1 --test_num_samples 1 --layer_strat ma
python analyse_crossdataset_bce_transfmr.py gemma_2B trivia_qa --using_act layer --token answer_last --probes_file_name T42_/gemma_2B_/trivia_qa_greedy_responses_train5000_/2000_1_layerFalse_answer_last_transformer_hallu_pos_bs128_epochs50_ --probes_file_name_concat ba --lr_list 0.00005,0.0005,0.005 --best_threshold True --save_path /home/local/data/ms/honest_llama_data --seed_list 42,101,2650 --fpr_at_recall -1 --test_num_samples 1
python analyse_crossdataset_bce_transfmr.py gemma_2B trivia_qa --using_act layer --token answer_last --probes_file_name T42_/gemma_2B_/trivia_qa_greedy_responses_train5000_/2000_1_layerFalse_answer_last_transformer2_hallu_pos_bs128_epochs50_ --probes_file_name_concat ba --lr_list 0.00005,0.0005,0.005 --best_threshold True --save_path /home/local/data/ms/honest_llama_data --seed_list 42,101,2650 --fpr_at_recall -1 --test_num_samples 1 # 76.2-seed42
#
python analyse_crossdataset_bce.py gemma_2B trivia_qa --using_act layer_att_res --token answer_last --probes_file_name NLSC42_/gemma_2B_/trivia_qa_greedy_responses_train5000_/2000_1_layer_att_resFalse_answer_last_individual_linear_hallu_pos_bs128_epochs50_ --probes_file_name_concat ba --lr_list 0.00005,0.0005,0.005 --best_threshold True --save_path /home/local/data/ms/honest_llama_data --seed_list 42,101,2650 --fpr_at_recall -1 --test_num_samples 1 --layer_strat ma
python analyse_crossdataset_bce.py gemma_2B trivia_qa --using_act layer_att_res --token answer_last --probes_file_name NLSC42_/gemma_2B_/trivia_qa_greedy_responses_train5000_/2000_1_layer_att_resFalse_answer_last_individual_non_linear_4_hallu_pos_bs128_epochs50_ --probes_file_name_concat ba --lr_list 0.00005,0.0005,0.005 --best_threshold True --save_path /home/local/data/ms/honest_llama_data --seed_list 42,101,2650 --fpr_at_recall -1 --test_num_samples 1 --layer_strat ma
python analyse_crossdataset_bce_transfmr.py gemma_2B trivia_qa --using_act layer_att_res --token answer_last --probes_file_name T42_/gemma_2B_/trivia_qa_greedy_responses_train5000_/2000_1_layer_att_resFalse_answer_last_transformer_hallu_pos_bs128_epochs50_ --probes_file_name_concat ba --lr_list 0.00005,0.0005,0.005 --best_threshold True --save_path /home/local/data/ms/honest_llama_data --seed_list 42,101,2650 --fpr_at_recall -1 --test_num_samples 1
python analyse_crossdataset_bce_transfmr.py gemma_2B trivia_qa --using_act layer_att_res --token answer_last --probes_file_name T42_/gemma_2B_/trivia_qa_greedy_responses_train5000_/2000_1_layer_att_resFalse_answer_last_transformer2_hallu_pos_bs128_epochs50_ --probes_file_name_concat ba --lr_list 0.00005,0.0005,0.005 --best_threshold True --save_path /home/local/data/ms/honest_llama_data --seed_list 42,101,2650 --fpr_at_recall -1 --test_num_samples 1
#
python analyse_crossdataset_bce.py gemma_2B trivia_qa --using_act layer_att_res --token prompt_last_onwards --probes_file_name NLSC42_/gemma_2B_/trivia_qa_greedy_responses_train5000_/2000_1_layer_att_resFalse_prompt_last_onwards_individual_att_pool_hallu_pos_bs128_epochs50_ --probes_file_name_concat ba --lr_list 0.00005,0.0005,0.005 --best_threshold True --save_path /home/local/data/ms/honest_llama_data --seed_list 42,101,2650 --fpr_at_recall -1 --test_num_samples 1 --layer_strat ma # 77.5-seed42
python analyse_crossdataset_bce_transfmr.py gemma_2B trivia_qa --using_act layer_att_res --token answer_last --probes_file_name T42_/gemma_2B_/trivia_qa_greedy_responses_train5000_/2000_1_layer_att_resFalse_prompt_last_onwards_transformer_hallu_pos_bs128_epochs50_ --probes_file_name_concat ba --lr_list 0.00005,0.0005,0.005 --best_threshold True --save_path /home/local/data/ms/honest_llama_data --seed_list 42,101,2650 --fpr_at_recall -1 --test_num_samples 1
python analyse_crossdataset_bce_transfmr.py gemma_2B trivia_qa --using_act layer_att_res --token answer_last --probes_file_name T42_/gemma_2B_/trivia_qa_greedy_responses_train5000_/2000_1_layer_att_resFalse_prompt_last_onwards_transformer2_hallu_pos_bs128_epochs50_ --probes_file_name_concat ba --lr_list 0.00005,0.0005,0.005 --best_threshold True --save_path /home/local/data/ms/honest_llama_data --seed_list 42,101,2650 --fpr_at_recall -1 --test_num_samples 1