python check_model_responses.py hl_llama_7B trivia_qa_sampledplus_responses_train5000 11
python check_model_responses.py hl_llama_7B trivia_qa_greedy_responses_validation1800 1
python check_model_responses.py hl_llama_7B trivia_qa_sampled_responses_validation1800 10
python check_model_responses.py hl_llama_7B nq_open_sampledplus_responses_train5000 11
python check_model_responses.py hl_llama_7B nq_open_greedy_responses_validation1800 1
python check_model_responses.py hl_llama_7B nq_open_sampled_responses_validation1800 10
python check_model_responses.py hl_llama_7B strqa_sampledplus_responses_train 9
python check_model_responses.py hl_llama_7B strqa_baseline_responses_test 1
python check_model_responses.py hl_llama_7B strqa_sampled_responses_test 8

python check_model_responses.py alpaca_7B trivia_qa_sampledplus_responses_train5000 11
python check_model_responses.py alpaca_7B trivia_qa_greedy_responses_validation1800 1
python check_model_responses.py alpaca_7B trivia_qa_sampled_responses_validation1800 10
python check_model_responses.py alpaca_7B nq_open_sampledplus_responses_train5000 11
python check_model_responses.py alpaca_7B nq_open_greedy_responses_validation1800 1
python check_model_responses.py alpaca_7B nq_open_sampled_responses_validation1800 10
python check_model_responses.py alpaca_7B strqa_sampledplus_responses_train 9
python check_model_responses.py alpaca_7B strqa_baseline_responses_test 1
python check_model_responses.py alpaca_7B strqa_sampled_responses_test 8

python check_model_responses.py vicuna_7B trivia_qa_sampledplus_responses_train5000 11
python check_model_responses.py vicuna_7B trivia_qa_greedy_responses_validation1800 1
python check_model_responses.py vicuna_7B trivia_qa_sampled_responses_validation1800 10
python check_model_responses.py vicuna_7B nq_open_sampledplus_responses_train5000 11
python check_model_responses.py vicuna_7B nq_open_greedy_responses_validation1800 1
python check_model_responses.py vicuna_7B nq_open_sampled_responses_validation1800 10
python check_model_responses.py vicuna_7B strqa_sampledplus_responses_train 9
python check_model_responses.py vicuna_7B strqa_baseline_responses_test 1
python check_model_responses.py vicuna_7B strqa_sampled_responses_test 8

python check_model_responses.py gemma_2B trivia_qa_sampledplus_responses_train5000 11
python check_model_responses.py gemma_2B trivia_qa_greedy_responses_validation1800 1
python check_model_responses.py gemma_2B trivia_qa_sampled_responses_validation1800 10
python check_model_responses.py gemma_2B nq_open_sampledplus_responses_train5000 11
python check_model_responses.py gemma_2B nq_open_greedy_responses_validation1800 1
python check_model_responses.py gemma_2B nq_open_sampled_responses_validation1800 10
python check_model_responses.py gemma_2B strqa_sampledplus_responses_train 9
python check_model_responses.py gemma_2B strqa_baseline_responses_test 1
python check_model_responses.py gemma_2B strqa_sampled_responses_test 8

python check_model_responses.py llama3.1_8B_Instruct trivia_qa_sampledplus_responses_train5000 11
python check_model_responses.py llama3.1_8B_Instruct trivia_qa_greedy_responses_validation1800 1
python check_model_responses.py llama3.1_8B_Instruct trivia_qa_sampled_responses_validation1800 10
python check_model_responses.py llama3.1_8B_Instruct strqa_sampledplus_responses_train 9
python check_model_responses.py llama3.1_8B_Instruct strqa_baseline_responses_test 1
python check_model_responses.py llama3.1_8B_Instruct strqa_sampled_responses_test 8