# python get_uncertainty_scores.py hl_llama_7B trivia_qa --file_name sampledplus_responses_train5000 --save_path /home/local/data/ms/honest_llama_data --num_samples 10  # We only need sampled responses (no greedy responses) for SE
# python get_uncertainty_scores.py hl_llama_7B nq_open --file_name sampledplus_responses_train5000 --save_path /home/local/data/ms/honest_llama_data --num_samples 10  # We only need sampled responses (no greedy responses) for SE
# python get_uncertainty_scores.py hl_llama_7B city_country --file_name sampledplus_responses_train1000 --save_path /home/local/data/ms/honest_llama_data --num_samples 10  # We only need sampled responses (no greedy responses) for SE
# python get_uncertainty_scores.py hl_llama_7B player_date_birth --file_name sampledplus_responses_train1000 --save_path /home/local/data/ms/honest_llama_data --num_samples 10  # We only need sampled responses (no greedy responses) for SE
# python get_uncertainty_scores.py hl_llama_7B movie_cast --file_name sampled_responses_train1000 --save_path /home/local/data/ms/honest_llama_data --num_samples 10  # We only need sampled responses (no greedy responses) for SE
# python get_uncertainty_scores.py gemma_2B trivia_qa --file_name sampledplus_responses_train5000 --save_path /home/local/data/ms/honest_llama_data --num_samples 10;
# python get_uncertainty_scores.py gemma_2B nq_open --file_name sampledplus_responses_train5000 --save_path /home/local/data/ms/honest_llama_data --num_samples 10;
# python get_uncertainty_scores.py gemma_2B city_country --file_name sampled_responses_train1000 --save_path /home/local/data/ms/honest_llama_data --num_samples 10;
# python get_uncertainty_scores.py gemma_2B player_date_birth --file_name sampled_responses_train1000 --save_path /home/local/data/ms/honest_llama_data --num_samples 10;
# python get_uncertainty_scores.py gemma_2B movie_cast --file_name sampled_responses_train1000 --save_path /home/local/data/ms/honest_llama_data --num_samples 10;
python get_uncertainty_scores.py alpaca_7B trivia_qa --file_name sampledplus_responses_train5000 --save_path ~/Desktop/honest_llama_data --num_samples 10;
python get_uncertainty_scores.py alpaca_7B nq_open --file_name sampledplus_responses_train5000 --save_path ~/Desktop/honest_llama_data --num_samples 10;
python get_uncertainty_scores.py alpaca_7B city_country --file_name sampled_responses_train1000 --save_path ~/Desktop/honest_llama_data --num_samples 10;
python get_uncertainty_scores.py alpaca_7B player_date_birth --file_name sampled_responses_train1000 --save_path ~/Desktop/honest_llama_data --num_samples 10;
python get_uncertainty_scores.py alpaca_7B movie_cast --file_name sampled_responses_train1000 --save_path ~/Desktop/honest_llama_data --num_samples 10;
python get_uncertainty_scores.py vicuna_7B trivia_qa --file_name sampledplus_responses_train5000 --save_path ~/Desktop/honest_llama_data --num_samples 10;
python get_uncertainty_scores.py vicuna_7B nq_open --file_name sampledplus_responses_train5000 --save_path ~/Desktop/honest_llama_data --num_samples 10;
python get_uncertainty_scores.py vicuna_7B city_country --file_name sampled_responses_train1000 --save_path ~/Desktop/honest_llama_data --num_samples 10;
python get_uncertainty_scores.py vicuna_7B player_date_birth --file_name sampled_responses_train1000 --save_path ~/Desktop/honest_llama_data --num_samples 10;
python get_uncertainty_scores.py vicuna_7B movie_cast --file_name sampled_responses_train1000 --save_path ~/Desktop/honest_llama_data --num_samples 10;


# python get_semantic_entropy.py hl_llama_7B trivia_qa --file_name sampledplus_responses_train5000 --len_dataset 1000 --save_path /home/local/data/ms/honest_llama_data --num_samples 10 # We only need sampled responses (no greedy responses) for SE
# python get_semantic_entropy.py hl_llama_7B nq_open --file_name sampledplus_responses_train5000 --len_dataset 1000  --save_path /home/local/data/ms/honest_llama_data --num_samples 10 # We only need sampled responses (no greedy responses) for SE
# python get_semantic_entropy.py hl_llama_7B city_country --file_name sampledplus_responses_train1000 --save_path /home/local/data/ms/honest_llama_data --num_samples 10 # We only need sampled responses (no greedy responses) for SE
# python get_semantic_entropy.py hl_llama_7B player_date_birth --file_name sampledplus_responses_train1000 --save_path /home/local/data/ms/honest_llama_data --num_samples 10 # We only need sampled responses (no greedy responses) for SE
# python get_semantic_entropy_fast.py hl_llama_7B movie_cast --file_name sampled_responses_train1000 --save_path /home/local/data/ms/honest_llama_data --num_samples 10 # We only need sampled responses (no greedy responses) for SE
# python get_semantic_entropy.py hl_llama_7B strqa --file_name sampledplus_responses_train  --save_path /home/local/data/ms/honest_llama_data --num_samples 8 # We only need sampled responses (no greedy responses) for SE
# python get_semantic_entropy.py gemma_2B trivia_qa --file_name sampledplus_responses_train5000 --len_dataset 1000 --save_path /home/local/data/ms/honest_llama_data --num_samples 10;
# python get_semantic_entropy.py gemma_2B nq_open --file_name sampledplus_responses_train5000 --len_dataset 1000  --save_path /home/local/data/ms/honest_llama_data --num_samples 10;
# python get_semantic_entropy.py gemma_2B city_country --file_name sampled_responses_train1000 --save_path /home/local/data/ms/honest_llama_data --num_samples 10;
# python get_semantic_entropy.py gemma_2B player_date_birth --file_name sampled_responses_train1000 --save_path /home/local/data/ms/honest_llama_data --num_samples 10;
# python get_semantic_entropy.py gemma_2B movie_cast --file_name sampled_responses_train1000 --save_path /home/local/data/ms/honest_llama_data --num_samples 10;


# python get_activations_and_probe_non_linear_supcon_bce.py hl_llama_7B strqa --train_file_name strqa_baseline_responses_train --train_labels_file_name strqa_sampledplus_responses_train_se_labels --test_file_name strqa_baseline_responses_test --len_dataset 1832 --num_folds 1 --using_act layer --token answer_last --method individual_linear_hallu_pos --bs 128 --epochs 50 --lr_list 0.005 --save_probes True --save_path /home/local/data/ms/honest_llama_data --fast_mode True  --use_best_val_t True --best_using_auc True --seed_list 42,101,2650 --test_num_samples 1
# python get_activations_and_probe_non_linear_supcon_bce.py hl_llama_7B strqa --train_file_name strqa_baseline_responses_train --train_labels_file_name strqa_sampledplus_responses_train_se_labels --test_file_name strqa_sampled_responses_test --len_dataset 1832 --num_folds 1 --using_act layer --token answer_last --method individual_linear_hallu_pos --bs 128 --epochs 50 --lr_list 0.005 --save_probes True --save_path /home/local/data/ms/honest_llama_data --fast_mode True  --use_best_val_t True --best_using_auc True --seed_list 42,101,2650 --test_num_samples 8 --skip_train


# ID
# python get_activations_and_probe_non_linear_supcon_bce.py hl_llama_7B city_country --train_file_name city_country_greedy_responses_train6323 --test_file_name city_country_greedy_responses_test1581 --train_labels_file_name city_country_sampledplus_responses_train1000_se_labels --test_labels_file_name city_country_greedy_responses_labels_test1581 --len_dataset 1000 --num_folds 1 --using_act layer --token answer_last --method individual_linear_hallu_pos --bs 128 --epochs 50 --lr_list 0.005 --save_probes True --save_path /home/local/data/ms/honest_llama_data --fast_mode True  --use_best_val_t True --best_using_auc True --seed_list 42,101,2650  --test_num_samples 1 --last_only True;
# python get_activations_and_probe_non_linear_supcon_bce.py hl_llama_7B player_date_birth --train_file_name player_date_birth_greedy_responses_train5989 --test_file_name player_date_birth_greedy_responses_test1498 --train_labels_file_name player_date_birth_sampledplus_responses_train1000_se_labels --test_labels_file_name player_date_birth_greedy_responses_labels_test1498 --len_dataset 1000 --num_folds 1 --using_act layer --token answer_last --method individual_linear_hallu_pos --bs 128 --epochs 50 --lr_list 0.005 --save_probes True --save_path /home/local/data/ms/honest_llama_data --fast_mode True  --use_best_val_t True --best_using_auc True --seed_list 42,101,2650  --test_num_samples 1 --last_only True;
# python get_activations_and_probe_non_linear_supcon_bce.py hl_llama_7B movie_cast --train_file_name movie_cast_greedy_responses_train8716 --test_file_name movie_cast_greedy_responses_test2179 --train_labels_file_name movie_cast_sampled_responses_train1000_se_labels --test_labels_file_name movie_cast_greedy_responses_labels_test2179 --len_dataset 1000 --num_folds 1 --using_act layer --token answer_last --method individual_linear_hallu_pos --bs 128 --epochs 50 --lr_list 0.005 --save_probes True --save_path /home/local/data/ms/honest_llama_data --fast_mode True  --use_best_val_t True --best_using_auc True --seed_list 42,101,2650  --test_num_samples 1 --last_only True;
# python get_activations_and_probe_non_linear_supcon_bce.py hl_llama_7B trivia_qa --train_file_name trivia_qa_greedy_responses_train5000 --test_file_name trivia_qa_greedy_responses_validation1800 --train_labels_file_name trivia_qa_sampledplus_responses_train5000_se_labels --test_labels_file_name trivia_qa_greedy_responses_labels_validation1800 --len_dataset 1000 --num_folds 1 --using_act layer --token answer_last --method individual_linear_hallu_pos --bs 128 --epochs 50 --lr_list 0.005 --save_probes True --save_path /home/local/data/ms/honest_llama_data --fast_mode True  --use_best_val_t True --best_using_auc True --seed_list 42,101,2650  --test_num_samples 1 --last_only True;
# python get_activations_and_probe_non_linear_supcon_bce.py hl_llama_7B nq_open --train_file_name nq_open_greedy_responses_train5000 --test_file_name nq_open_greedy_responses_validation1800 --train_labels_file_name nq_open_sampledplus_responses_train5000_se_labels --test_labels_file_name nq_open_greedy_responses_labels_validation1800 --len_dataset 1000 --num_folds 1 --using_act layer --token answer_last --method individual_linear_hallu_pos --bs 128 --epochs 50 --lr_list 0.005 --save_probes True --save_path /home/local/data/ms/honest_llama_data --fast_mode True  --use_best_val_t True --best_using_auc True --seed_list 42,101,2650  --test_num_samples 1 --last_only True;
# python get_activations_and_probe_non_linear_supcon_bce.py gemma_2B city_country --train_file_name city_country_greedy_responses_train6323 --test_file_name city_country_greedy_responses_test1581 --train_labels_file_name city_country_sampled_responses_train1000_se_labels --test_labels_file_name city_country_greedy_responses_labels_test1581 --len_dataset 1000 --num_folds 1 --using_act layer --token answer_last --method individual_linear_hallu_pos --bs 128 --epochs 50 --lr_list 0.005 --save_probes True --save_path /home/local/data/ms/honest_llama_data --fast_mode True  --use_best_val_t True --best_using_auc True --seed_list 42,101,2650  --test_num_samples 1 --last_only True;
# python get_activations_and_probe_non_linear_supcon_bce.py gemma_2B player_date_birth --train_file_name player_date_birth_greedy_responses_train5989 --test_file_name player_date_birth_greedy_responses_test1498 --train_labels_file_name player_date_birth_sampled_responses_train1000_se_labels --test_labels_file_name player_date_birth_greedy_responses_labels_test1498 --len_dataset 1000 --num_folds 1 --using_act layer --token answer_last --method individual_linear_hallu_pos --bs 128 --epochs 50 --lr_list 0.005 --save_probes True --save_path /home/local/data/ms/honest_llama_data --fast_mode True  --use_best_val_t True --best_using_auc True --seed_list 42,101,2650  --test_num_samples 1 --last_only True;
# python get_activations_and_probe_non_linear_supcon_bce.py gemma_2B movie_cast --train_file_name movie_cast_greedy_responses_train8716 --test_file_name movie_cast_greedy_responses_test2179 --train_labels_file_name movie_cast_sampled_responses_train1000_se_labels --test_labels_file_name movie_cast_greedy_responses_labels_test2179 --len_dataset 1000 --num_folds 1 --using_act layer --token answer_last --method individual_linear_hallu_pos --bs 128 --epochs 50 --lr_list 0.005 --save_probes True --save_path /home/local/data/ms/honest_llama_data --fast_mode True  --use_best_val_t True --best_using_auc True --seed_list 42,101,2650  --test_num_samples 1 --last_only True;
# python get_activations_and_probe_non_linear_supcon_bce.py gemma_2B trivia_qa --train_file_name trivia_qa_greedy_responses_train5000 --test_file_name trivia_qa_greedy_responses_validation1800 --train_labels_file_name trivia_qa_sampledplus_responses_train5000_se_labels --test_labels_file_name trivia_qa_greedy_responses_labels_validation1800 --len_dataset 1000 --num_folds 1 --using_act layer --token answer_last --method individual_linear_hallu_pos --bs 128 --epochs 50 --lr_list 0.005 --save_probes True --save_path /home/local/data/ms/honest_llama_data --fast_mode True  --use_best_val_t True --best_using_auc True --seed_list 42,101,2650  --test_num_samples 1 --last_only True;
# python get_activations_and_probe_non_linear_supcon_bce.py gemma_2B nq_open --train_file_name nq_open_greedy_responses_train5000 --test_file_name nq_open_greedy_responses_validation1800 --train_labels_file_name nq_open_sampledplus_responses_train5000_se_labels --test_labels_file_name nq_open_greedy_responses_labels_validation1800 --len_dataset 1000 --num_folds 1 --using_act layer --token answer_last --method individual_linear_hallu_pos --bs 128 --epochs 50 --lr_list 0.005 --save_probes True --save_path /home/local/data/ms/honest_llama_data --fast_mode True  --use_best_val_t True --best_using_auc True --seed_list 42,101,2650  --test_num_samples 1 --last_only True;

# OOD
# python get_activations_and_probe_non_linear_supcon_bce.py hl_llama_7B city_country --train_file_name city_country_greedy_responses_train6323 --test_file_name player_date_birth_greedy_responses_test1498 --train_labels_file_name city_country_sampledplus_responses_train1000_se_labels --test_labels_file_name player_date_birth_greedy_responses_labels_test1498 --len_dataset 1000 --num_folds 1 --using_act layer --token answer_last --method individual_linear_hallu_pos --bs 128 --epochs 50 --lr_list 0.005 --save_probes True --save_path /home/local/data/ms/honest_llama_data --fast_mode True  --use_best_val_t True --best_using_auc True --seed_list 42,101,2650  --test_num_samples 1 --last_only True --ood_test True --skip_train True;
# python get_activations_and_probe_non_linear_supcon_bce.py hl_llama_7B city_country --train_file_name city_country_greedy_responses_train6323 --test_file_name movie_cast_greedy_responses_test2179 --train_labels_file_name city_country_sampledplus_responses_train1000_se_labels --test_labels_file_name movie_cast_greedy_responses_labels_test2179 --len_dataset 1000 --num_folds 1 --using_act layer --token answer_last --method individual_linear_hallu_pos --bs 128 --epochs 50 --lr_list 0.005 --save_probes True --save_path /home/local/data/ms/honest_llama_data --fast_mode True  --use_best_val_t True --best_using_auc True --seed_list 42,101,2650  --test_num_samples 1 --last_only True --ood_test True --skip_train True;
# python get_activations_and_probe_non_linear_supcon_bce.py hl_llama_7B city_country --train_file_name city_country_greedy_responses_train6323 --test_file_name trivia_qa_greedy_responses_validation1800 --train_labels_file_name city_country_sampledplus_responses_train1000_se_labels --test_labels_file_name trivia_qa_greedy_responses_labels_validation1800 --len_dataset 1000 --num_folds 1 --using_act layer --token answer_last --method individual_linear_hallu_pos --bs 128 --epochs 50 --lr_list 0.005 --save_probes True --save_path /home/local/data/ms/honest_llama_data --fast_mode True  --use_best_val_t True --best_using_auc True --seed_list 42,101,2650  --test_num_samples 1 --last_only True --ood_test True --skip_train True;
# python get_activations_and_probe_non_linear_supcon_bce.py hl_llama_7B city_country --train_file_name city_country_greedy_responses_train6323 --test_file_name nq_open_greedy_responses_validation1800 --train_labels_file_name city_country_sampledplus_responses_train1000_se_labels --test_labels_file_name nq_open_greedy_responses_labels_validation1800 --len_dataset 1000 --num_folds 1 --using_act layer --token answer_last --method individual_linear_hallu_pos --bs 128 --epochs 50 --lr_list 0.005 --save_probes True --save_path /home/local/data/ms/honest_llama_data --fast_mode True  --use_best_val_t True --best_using_auc True --seed_list 42,101,2650  --test_num_samples 1 --last_only True --ood_test True --skip_train True;
python get_activations_and_probe_non_linear_supcon_bce.py gemma_2B city_country --train_file_name city_country_greedy_responses_train6323 --test_file_name player_date_birth_greedy_responses_test1498 --train_labels_file_name city_country_sampled_responses_train1000_se_labels --test_labels_file_name player_date_birth_greedy_responses_labels_test1498 --len_dataset 1000 --num_folds 1 --using_act layer --token answer_last --method individual_linear_hallu_pos --bs 128 --epochs 50 --lr_list 0.005 --save_probes True --save_path /home/local/data/ms/honest_llama_data --fast_mode True  --use_best_val_t True --best_using_auc True --seed_list 42,101,2650  --test_num_samples 1 --last_only True --ood_test True --skip_train True;
python get_activations_and_probe_non_linear_supcon_bce.py gemma_2B city_country --train_file_name city_country_greedy_responses_train6323 --test_file_name movie_cast_greedy_responses_test2179 --train_labels_file_name city_country_sampled_responses_train1000_se_labels --test_labels_file_name movie_cast_greedy_responses_labels_test2179 --len_dataset 1000 --num_folds 1 --using_act layer --token answer_last --method individual_linear_hallu_pos --bs 128 --epochs 50 --lr_list 0.005 --save_probes True --save_path /home/local/data/ms/honest_llama_data --fast_mode True  --use_best_val_t True --best_using_auc True --seed_list 42,101,2650  --test_num_samples 1 --last_only True --ood_test True --skip_train True;
python get_activations_and_probe_non_linear_supcon_bce.py gemma_2B city_country --train_file_name city_country_greedy_responses_train6323 --test_file_name trivia_qa_greedy_responses_validation1800 --train_labels_file_name city_country_sampled_responses_train1000_se_labels --test_labels_file_name trivia_qa_greedy_responses_labels_validation1800 --len_dataset 1000 --num_folds 1 --using_act layer --token answer_last --method individual_linear_hallu_pos --bs 128 --epochs 50 --lr_list 0.005 --save_probes True --save_path /home/local/data/ms/honest_llama_data --fast_mode True  --use_best_val_t True --best_using_auc True --seed_list 42,101,2650  --test_num_samples 1 --last_only True --ood_test True --skip_train True;
python get_activations_and_probe_non_linear_supcon_bce.py gemma_2B city_country --train_file_name city_country_greedy_responses_train6323 --test_file_name nq_open_greedy_responses_validation1800 --train_labels_file_name city_country_sampled_responses_train1000_se_labels --test_labels_file_name nq_open_greedy_responses_labels_validation1800 --len_dataset 1000 --num_folds 1 --using_act layer --token answer_last --method individual_linear_hallu_pos --bs 128 --epochs 50 --lr_list 0.005 --save_probes True --save_path /home/local/data/ms/honest_llama_data --fast_mode True  --use_best_val_t True --best_using_auc True --seed_list 42,101,2650  --test_num_samples 1 --last_only True --ood_test True --skip_train True;

# python get_activations_and_probe_non_linear_supcon_bce.py hl_llama_7B player_date_birth --train_file_name player_date_birth_greedy_responses_train5989 --test_file_name city_country_greedy_responses_test1581 --train_labels_file_name player_date_birth_sampledplus_responses_train1000_se_labels --test_labels_file_name city_country_greedy_responses_labels_test1581 --len_dataset 1000 --num_folds 1 --using_act layer --token answer_last --method individual_linear_hallu_pos --bs 128 --epochs 50 --lr_list 0.005 --save_probes True --save_path /home/local/data/ms/honest_llama_data --fast_mode True  --use_best_val_t True --best_using_auc True --seed_list 42,101,2650  --test_num_samples 1 --last_only True --ood_test True --skip_train True;
# python get_activations_and_probe_non_linear_supcon_bce.py hl_llama_7B player_date_birth --train_file_name player_date_birth_greedy_responses_train5989 --test_file_name movie_cast_greedy_responses_test2179 --train_labels_file_name player_date_birth_sampledplus_responses_train1000_se_labels --test_labels_file_name movie_cast_greedy_responses_labels_test2179 --len_dataset 1000 --num_folds 1 --using_act layer --token answer_last --method individual_linear_hallu_pos --bs 128 --epochs 50 --lr_list 0.005 --save_probes True --save_path /home/local/data/ms/honest_llama_data --fast_mode True  --use_best_val_t True --best_using_auc True --seed_list 42,101,2650  --test_num_samples 1 --last_only True --ood_test True --skip_train True;
# python get_activations_and_probe_non_linear_supcon_bce.py hl_llama_7B player_date_birth --train_file_name player_date_birth_greedy_responses_train5989 --test_file_name trivia_qa_greedy_responses_validation1800 --train_labels_file_name player_date_birth_sampledplus_responses_train1000_se_labels --test_labels_file_name trivia_qa_greedy_responses_labels_validation1800 --len_dataset 1000 --num_folds 1 --using_act layer --token answer_last --method individual_linear_hallu_pos --bs 128 --epochs 50 --lr_list 0.005 --save_probes True --save_path /home/local/data/ms/honest_llama_data --fast_mode True  --use_best_val_t True --best_using_auc True --seed_list 42,101,2650  --test_num_samples 1 --last_only True --ood_test True --skip_train True;
# python get_activations_and_probe_non_linear_supcon_bce.py hl_llama_7B player_date_birth --train_file_name player_date_birth_greedy_responses_train5989 --test_file_name nq_open_greedy_responses_validation1800 --train_labels_file_name player_date_birth_sampledplus_responses_train1000_se_labels --test_labels_file_name nq_open_greedy_responses_labels_validation1800 --len_dataset 1000 --num_folds 1 --using_act layer --token answer_last --method individual_linear_hallu_pos --bs 128 --epochs 50 --lr_list 0.005 --save_probes True --save_path /home/local/data/ms/honest_llama_data --fast_mode True  --use_best_val_t True --best_using_auc True --seed_list 42,101,2650  --test_num_samples 1 --last_only True --ood_test True --skip_train True;
python get_activations_and_probe_non_linear_supcon_bce.py gemma_2B player_date_birth --train_file_name player_date_birth_greedy_responses_train5989 --test_file_name city_country_greedy_responses_test1581 --train_labels_file_name player_date_birth_sampled_responses_train1000_se_labels --test_labels_file_name city_country_greedy_responses_labels_test1581 --len_dataset 1000 --num_folds 1 --using_act layer --token answer_last --method individual_linear_hallu_pos --bs 128 --epochs 50 --lr_list 0.005 --save_probes True --save_path /home/local/data/ms/honest_llama_data --fast_mode True  --use_best_val_t True --best_using_auc True --seed_list 42,101,2650  --test_num_samples 1 --last_only True --ood_test True --skip_train True;
python get_activations_and_probe_non_linear_supcon_bce.py gemma_2B player_date_birth --train_file_name player_date_birth_greedy_responses_train5989 --test_file_name movie_cast_greedy_responses_test2179 --train_labels_file_name player_date_birth_sampled_responses_train1000_se_labels --test_labels_file_name movie_cast_greedy_responses_labels_test2179 --len_dataset 1000 --num_folds 1 --using_act layer --token answer_last --method individual_linear_hallu_pos --bs 128 --epochs 50 --lr_list 0.005 --save_probes True --save_path /home/local/data/ms/honest_llama_data --fast_mode True  --use_best_val_t True --best_using_auc True --seed_list 42,101,2650  --test_num_samples 1 --last_only True --ood_test True --skip_train True;
python get_activations_and_probe_non_linear_supcon_bce.py gemma_2B player_date_birth --train_file_name player_date_birth_greedy_responses_train5989 --test_file_name trivia_qa_greedy_responses_validation1800 --train_labels_file_name player_date_birth_sampled_responses_train1000_se_labels --test_labels_file_name trivia_qa_greedy_responses_labels_validation1800 --len_dataset 1000 --num_folds 1 --using_act layer --token answer_last --method individual_linear_hallu_pos --bs 128 --epochs 50 --lr_list 0.005 --save_probes True --save_path /home/local/data/ms/honest_llama_data --fast_mode True  --use_best_val_t True --best_using_auc True --seed_list 42,101,2650  --test_num_samples 1 --last_only True --ood_test True --skip_train True;
python get_activations_and_probe_non_linear_supcon_bce.py gemma_2B player_date_birth --train_file_name player_date_birth_greedy_responses_train5989 --test_file_name nq_open_greedy_responses_validation1800 --train_labels_file_name player_date_birth_sampled_responses_train1000_se_labels --test_labels_file_name nq_open_greedy_responses_labels_validation1800 --len_dataset 1000 --num_folds 1 --using_act layer --token answer_last --method individual_linear_hallu_pos --bs 128 --epochs 50 --lr_list 0.005 --save_probes True --save_path /home/local/data/ms/honest_llama_data --fast_mode True  --use_best_val_t True --best_using_auc True --seed_list 42,101,2650  --test_num_samples 1 --last_only True --ood_test True --skip_train True;

# python get_activations_and_probe_non_linear_supcon_bce.py hl_llama_7B movie_cast --train_file_name movie_cast_greedy_responses_train8716 --test_file_name city_country_greedy_responses_test1581 --train_labels_file_name movie_cast_sampled_responses_train1000_se_labels --test_labels_file_name city_country_greedy_responses_labels_test1581 --len_dataset 1000 --num_folds 1 --using_act layer --token answer_last --method individual_linear_hallu_pos --bs 128 --epochs 50 --lr_list 0.005 --save_probes True --save_path /home/local/data/ms/honest_llama_data --fast_mode True  --use_best_val_t True --best_using_auc True --seed_list 42,101,2650  --test_num_samples 1 --last_only True --ood_test True --skip_train True;
# python get_activations_and_probe_non_linear_supcon_bce.py hl_llama_7B movie_cast --train_file_name movie_cast_greedy_responses_train8716 --test_file_name player_date_birth_greedy_responses_test1498 --train_labels_file_name movie_cast_sampled_responses_train1000_se_labels --test_labels_file_name player_date_birth_greedy_responses_labels_test1498 --len_dataset 1000 --num_folds 1 --using_act layer --token answer_last --method individual_linear_hallu_pos --bs 128 --epochs 50 --lr_list 0.005 --save_probes True --save_path /home/local/data/ms/honest_llama_data --fast_mode True  --use_best_val_t True --best_using_auc True --seed_list 42,101,2650  --test_num_samples 1 --last_only True --ood_test True --skip_train True;
# python get_activations_and_probe_non_linear_supcon_bce.py hl_llama_7B movie_cast --train_file_name movie_cast_greedy_responses_train8716 --test_file_name trivia_qa_greedy_responses_validation1800 --train_labels_file_name movie_cast_sampled_responses_train1000_se_labels --test_labels_file_name trivia_qa_greedy_responses_labels_validation1800 --len_dataset 1000 --num_folds 1 --using_act layer --token answer_last --method individual_linear_hallu_pos --bs 128 --epochs 50 --lr_list 0.005 --save_probes True --save_path /home/local/data/ms/honest_llama_data --fast_mode True  --use_best_val_t True --best_using_auc True --seed_list 42,101,2650  --test_num_samples 1 --last_only True --ood_test True --skip_train True;
# python get_activations_and_probe_non_linear_supcon_bce.py hl_llama_7B movie_cast --train_file_name movie_cast_greedy_responses_train8716 --test_file_name nq_open_greedy_responses_validation1800 --train_labels_file_name movie_cast_sampled_responses_train1000_se_labels --test_labels_file_name nq_open_greedy_responses_labels_validation1800 --len_dataset 1000 --num_folds 1 --using_act layer --token answer_last --method individual_linear_hallu_pos --bs 128 --epochs 50 --lr_list 0.005 --save_probes True --save_path /home/local/data/ms/honest_llama_data --fast_mode True  --use_best_val_t True --best_using_auc True --seed_list 42,101,2650  --test_num_samples 1 --last_only True --ood_test True --skip_train True;
python get_activations_and_probe_non_linear_supcon_bce.py gemma_2B movie_cast --train_file_name movie_cast_greedy_responses_train8716 --test_file_name city_country_greedy_responses_test1581 --train_labels_file_name movie_cast_sampled_responses_train1000_se_labels --test_labels_file_name city_country_greedy_responses_labels_test1581 --len_dataset 1000 --num_folds 1 --using_act layer --token answer_last --method individual_linear_hallu_pos --bs 128 --epochs 50 --lr_list 0.005 --save_probes True --save_path /home/local/data/ms/honest_llama_data --fast_mode True  --use_best_val_t True --best_using_auc True --seed_list 42,101,2650  --test_num_samples 1 --last_only True --ood_test True --skip_train True;
python get_activations_and_probe_non_linear_supcon_bce.py gemma_2B movie_cast --train_file_name movie_cast_greedy_responses_train8716 --test_file_name player_date_birth_greedy_responses_test1498 --train_labels_file_name movie_cast_sampled_responses_train1000_se_labels --test_labels_file_name player_date_birth_greedy_responses_labels_test1498 --len_dataset 1000 --num_folds 1 --using_act layer --token answer_last --method individual_linear_hallu_pos --bs 128 --epochs 50 --lr_list 0.005 --save_probes True --save_path /home/local/data/ms/honest_llama_data --fast_mode True  --use_best_val_t True --best_using_auc True --seed_list 42,101,2650  --test_num_samples 1 --last_only True --ood_test True --skip_train True;
python get_activations_and_probe_non_linear_supcon_bce.py gemma_2B movie_cast --train_file_name movie_cast_greedy_responses_train8716 --test_file_name trivia_qa_greedy_responses_validation1800 --train_labels_file_name movie_cast_sampled_responses_train1000_se_labels --test_labels_file_name trivia_qa_greedy_responses_labels_validation1800 --len_dataset 1000 --num_folds 1 --using_act layer --token answer_last --method individual_linear_hallu_pos --bs 128 --epochs 50 --lr_list 0.005 --save_probes True --save_path /home/local/data/ms/honest_llama_data --fast_mode True  --use_best_val_t True --best_using_auc True --seed_list 42,101,2650  --test_num_samples 1 --last_only True --ood_test True --skip_train True;
python get_activations_and_probe_non_linear_supcon_bce.py gemma_2B movie_cast --train_file_name movie_cast_greedy_responses_train8716 --test_file_name nq_open_greedy_responses_validation1800 --train_labels_file_name movie_cast_sampled_responses_train1000_se_labels --test_labels_file_name nq_open_greedy_responses_labels_validation1800 --len_dataset 1000 --num_folds 1 --using_act layer --token answer_last --method individual_linear_hallu_pos --bs 128 --epochs 50 --lr_list 0.005 --save_probes True --save_path /home/local/data/ms/honest_llama_data --fast_mode True  --use_best_val_t True --best_using_auc True --seed_list 42,101,2650  --test_num_samples 1 --last_only True --ood_test True --skip_train True;

# python get_activations_and_probe_non_linear_supcon_bce.py hl_llama_7B trivia_qa --train_file_name trivia_qa_greedy_responses_train5000 --test_file_name city_country_greedy_responses_test1581 --train_labels_file_name trivia_qa_sampledplus_responses_train5000_se_labels --test_labels_file_name city_country_greedy_responses_labels_test1581 --len_dataset 1000 --num_folds 1 --using_act layer --token answer_last --method individual_linear_hallu_pos --bs 128 --epochs 50 --lr_list 0.005 --save_probes True --save_path /home/local/data/ms/honest_llama_data --fast_mode True  --use_best_val_t True --best_using_auc True --seed_list 42,101,2650  --test_num_samples 1 --last_only True --ood_test True --skip_train True;
# python get_activations_and_probe_non_linear_supcon_bce.py hl_llama_7B trivia_qa --train_file_name trivia_qa_greedy_responses_train5000 --test_file_name player_date_birth_greedy_responses_test1498 --train_labels_file_name trivia_qa_sampledplus_responses_train5000_se_labels --test_labels_file_name player_date_birth_greedy_responses_labels_test1498 --len_dataset 1000 --num_folds 1 --using_act layer --token answer_last --method individual_linear_hallu_pos --bs 128 --epochs 50 --lr_list 0.005 --save_probes True --save_path /home/local/data/ms/honest_llama_data --fast_mode True  --use_best_val_t True --best_using_auc True --seed_list 42,101,2650  --test_num_samples 1 --last_only True --ood_test True --skip_train True;
# python get_activations_and_probe_non_linear_supcon_bce.py hl_llama_7B trivia_qa --train_file_name trivia_qa_greedy_responses_train5000 --test_file_name movie_cast_greedy_responses_test2179 --train_labels_file_name trivia_qa_sampledplus_responses_train5000_se_labels --test_labels_file_name movie_cast_greedy_responses_labels_test2179 --len_dataset 1000 --num_folds 1 --using_act layer --token answer_last --method individual_linear_hallu_pos --bs 128 --epochs 50 --lr_list 0.005 --save_probes True --save_path /home/local/data/ms/honest_llama_data --fast_mode True  --use_best_val_t True --best_using_auc True --seed_list 42,101,2650  --test_num_samples 1 --last_only True --ood_test True --skip_train True;
# python get_activations_and_probe_non_linear_supcon_bce.py hl_llama_7B trivia_qa --train_file_name trivia_qa_greedy_responses_train5000 --test_file_name nq_open_greedy_responses_validation1800 --train_labels_file_name trivia_qa_sampledplus_responses_train5000_se_labels --test_labels_file_name nq_open_greedy_responses_labels_validation1800 --len_dataset 1000 --num_folds 1 --using_act layer --token answer_last --method individual_linear_hallu_pos --bs 128 --epochs 50 --lr_list 0.005 --save_probes True --save_path /home/local/data/ms/honest_llama_data --fast_mode True  --use_best_val_t True --best_using_auc True --seed_list 42,101,2650  --test_num_samples 1 --last_only True --ood_test True --skip_train True;
python get_activations_and_probe_non_linear_supcon_bce.py gemma_2B trivia_qa --train_file_name trivia_qa_greedy_responses_train5000 --test_file_name city_country_greedy_responses_test1581 --train_labels_file_name trivia_qa_sampledplus_responses_train5000_se_labels --test_labels_file_name city_country_greedy_responses_labels_test1581 --len_dataset 1000 --num_folds 1 --using_act layer --token answer_last --method individual_linear_hallu_pos --bs 128 --epochs 50 --lr_list 0.005 --save_probes True --save_path /home/local/data/ms/honest_llama_data --fast_mode True  --use_best_val_t True --best_using_auc True --seed_list 42,101,2650  --test_num_samples 1 --last_only True --ood_test True --skip_train True;
python get_activations_and_probe_non_linear_supcon_bce.py gemma_2B trivia_qa --train_file_name trivia_qa_greedy_responses_train5000 --test_file_name player_date_birth_greedy_responses_test1498 --train_labels_file_name trivia_qa_sampledplus_responses_train5000_se_labels --test_labels_file_name player_date_birth_greedy_responses_labels_test1498 --len_dataset 1000 --num_folds 1 --using_act layer --token answer_last --method individual_linear_hallu_pos --bs 128 --epochs 50 --lr_list 0.005 --save_probes True --save_path /home/local/data/ms/honest_llama_data --fast_mode True  --use_best_val_t True --best_using_auc True --seed_list 42,101,2650  --test_num_samples 1 --last_only True --ood_test True --skip_train True;
python get_activations_and_probe_non_linear_supcon_bce.py gemma_2B trivia_qa --train_file_name trivia_qa_greedy_responses_train5000 --test_file_name movie_cast_greedy_responses_test2179 --train_labels_file_name trivia_qa_sampledplus_responses_train5000_se_labels --test_labels_file_name movie_cast_greedy_responses_labels_test2179 --len_dataset 1000 --num_folds 1 --using_act layer --token answer_last --method individual_linear_hallu_pos --bs 128 --epochs 50 --lr_list 0.005 --save_probes True --save_path /home/local/data/ms/honest_llama_data --fast_mode True  --use_best_val_t True --best_using_auc True --seed_list 42,101,2650  --test_num_samples 1 --last_only True --ood_test True --skip_train True;
python get_activations_and_probe_non_linear_supcon_bce.py gemma_2B trivia_qa --train_file_name trivia_qa_greedy_responses_train5000 --test_file_name nq_open_greedy_responses_validation1800 --train_labels_file_name trivia_qa_sampledplus_responses_train5000_se_labels --test_labels_file_name nq_open_greedy_responses_labels_validation1800 --len_dataset 1000 --num_folds 1 --using_act layer --token answer_last --method individual_linear_hallu_pos --bs 128 --epochs 50 --lr_list 0.005 --save_probes True --save_path /home/local/data/ms/honest_llama_data --fast_mode True  --use_best_val_t True --best_using_auc True --seed_list 42,101,2650  --test_num_samples 1 --last_only True --ood_test True --skip_train True;

# python get_activations_and_probe_non_linear_supcon_bce.py hl_llama_7B nq_open --train_file_name nq_open_greedy_responses_train5000 --test_file_name city_country_greedy_responses_test1581 --train_labels_file_name nq_open_sampledplus_responses_train5000_se_labels --test_labels_file_name city_country_greedy_responses_labels_test1581 --len_dataset 1000 --num_folds 1 --using_act layer --token answer_last --method individual_linear_hallu_pos --bs 128 --epochs 50 --lr_list 0.005 --save_probes True --save_path /home/local/data/ms/honest_llama_data --fast_mode True  --use_best_val_t True --best_using_auc True --seed_list 42,101,2650  --test_num_samples 1 --last_only True --ood_test True --skip_train True;
# python get_activations_and_probe_non_linear_supcon_bce.py hl_llama_7B nq_open --train_file_name nq_open_greedy_responses_train5000 --test_file_name player_date_birth_greedy_responses_test1498 --train_labels_file_name nq_open_sampledplus_responses_train5000_se_labels --test_labels_file_name player_date_birth_greedy_responses_labels_test1498 --len_dataset 1000 --num_folds 1 --using_act layer --token answer_last --method individual_linear_hallu_pos --bs 128 --epochs 50 --lr_list 0.005 --save_probes True --save_path /home/local/data/ms/honest_llama_data --fast_mode True  --use_best_val_t True --best_using_auc True --seed_list 42,101,2650  --test_num_samples 1 --last_only True --ood_test True --skip_train True;
# python get_activations_and_probe_non_linear_supcon_bce.py hl_llama_7B nq_open --train_file_name nq_open_greedy_responses_train5000 --test_file_name movie_cast_greedy_responses_test2179 --train_labels_file_name nq_open_sampledplus_responses_train5000_se_labels --test_labels_file_name movie_cast_greedy_responses_labels_test2179 --len_dataset 1000 --num_folds 1 --using_act layer --token answer_last --method individual_linear_hallu_pos --bs 128 --epochs 50 --lr_list 0.005 --save_probes True --save_path /home/local/data/ms/honest_llama_data --fast_mode True  --use_best_val_t True --best_using_auc True --seed_list 42,101,2650  --test_num_samples 1 --last_only True --ood_test True --skip_train True;
# python get_activations_and_probe_non_linear_supcon_bce.py hl_llama_7B nq_open --train_file_name nq_open_greedy_responses_train5000 --test_file_name trivia_qa_greedy_responses_validation1800 --train_labels_file_name nq_open_sampledplus_responses_train5000_se_labels --test_labels_file_name trivia_qa_greedy_responses_labels_validation1800 --len_dataset 1000 --num_folds 1 --using_act layer --token answer_last --method individual_linear_hallu_pos --bs 128 --epochs 50 --lr_list 0.005 --save_probes True --save_path /home/local/data/ms/honest_llama_data --fast_mode True  --use_best_val_t True --best_using_auc True --seed_list 42,101,2650  --test_num_samples 1 --last_only True --ood_test True --skip_train True;
python get_activations_and_probe_non_linear_supcon_bce.py gemma_2B nq_open --train_file_name nq_open_greedy_responses_train5000 --test_file_name city_country_greedy_responses_test1581 --train_labels_file_name nq_open_sampledplus_responses_train5000_se_labels --test_labels_file_name city_country_greedy_responses_labels_test1581 --len_dataset 1000 --num_folds 1 --using_act layer --token answer_last --method individual_linear_hallu_pos --bs 128 --epochs 50 --lr_list 0.005 --save_probes True --save_path /home/local/data/ms/honest_llama_data --fast_mode True  --use_best_val_t True --best_using_auc True --seed_list 42,101,2650  --test_num_samples 1 --last_only True --ood_test True --skip_train True;
python get_activations_and_probe_non_linear_supcon_bce.py gemma_2B nq_open --train_file_name nq_open_greedy_responses_train5000 --test_file_name player_date_birth_greedy_responses_test1498 --train_labels_file_name nq_open_sampledplus_responses_train5000_se_labels --test_labels_file_name player_date_birth_greedy_responses_labels_test1498 --len_dataset 1000 --num_folds 1 --using_act layer --token answer_last --method individual_linear_hallu_pos --bs 128 --epochs 50 --lr_list 0.005 --save_probes True --save_path /home/local/data/ms/honest_llama_data --fast_mode True  --use_best_val_t True --best_using_auc True --seed_list 42,101,2650  --test_num_samples 1 --last_only True --ood_test True --skip_train True;
python get_activations_and_probe_non_linear_supcon_bce.py gemma_2B nq_open --train_file_name nq_open_greedy_responses_train5000 --test_file_name movie_cast_greedy_responses_test2179 --train_labels_file_name nq_open_sampledplus_responses_train5000_se_labels --test_labels_file_name movie_cast_greedy_responses_labels_test2179 --len_dataset 1000 --num_folds 1 --using_act layer --token answer_last --method individual_linear_hallu_pos --bs 128 --epochs 50 --lr_list 0.005 --save_probes True --save_path /home/local/data/ms/honest_llama_data --fast_mode True  --use_best_val_t True --best_using_auc True --seed_list 42,101,2650  --test_num_samples 1 --last_only True --ood_test True --skip_train True;
python get_activations_and_probe_non_linear_supcon_bce.py gemma_2B nq_open --train_file_name nq_open_greedy_responses_train5000 --test_file_name trivia_qa_greedy_responses_validation1800 --train_labels_file_name nq_open_sampledplus_responses_train5000_se_labels --test_labels_file_name trivia_qa_greedy_responses_labels_validation1800 --len_dataset 1000 --num_folds 1 --using_act layer --token answer_last --method individual_linear_hallu_pos --bs 128 --epochs 50 --lr_list 0.005 --save_probes True --save_path /home/local/data/ms/honest_llama_data --fast_mode True  --use_best_val_t True --best_using_auc True --seed_list 42,101,2650  --test_num_samples 1 --last_only True --ood_test True --skip_train True;


### Results
# python analyse_crossdataset_bce.py hl_llama_7B city_country --using_act layer --token answer_last --probes_file_name NLSC42_/hl_llama_7B_/city_country_greedy_responses_train6323_se_labels_/1000_1_layerFalse_answer_last_individual_linear_hallu_pos_bs128_epochs50_ --probes_file_name_concat ba --lr_list 0.005 --best_threshold True --save_path /home/local/data/ms/honest_llama_data --seed_list 42,101,2650 --fpr_at_recall -1
# python analyse_crossdataset_bce.py hl_llama_7B player_date_birth --using_act layer --token answer_last --probes_file_name NLSC42_/hl_llama_7B_/player_date_birth_greedy_responses_train5989_se_labels_/1000_1_layerFalse_answer_last_individual_linear_hallu_pos_bs128_epochs50_ --probes_file_name_concat ba --lr_list 0.005 --best_threshold True --save_path /home/local/data/ms/honest_llama_data --seed_list 42,101,2650 --fpr_at_recall -1
# python analyse_crossdataset_bce.py hl_llama_7B movie_cast --using_act layer --token answer_last --probes_file_name NLSC42_/hl_llama_7B_/movie_cast_greedy_responses_train8716_se_labels_/1000_1_layerFalse_answer_last_individual_linear_hallu_pos_bs128_epochs50_ --probes_file_name_concat ba --lr_list 0.005 --best_threshold True --save_path /home/local/data/ms/honest_llama_data --seed_list 42,101,2650 --fpr_at_recall -1
# python analyse_crossdataset_bce.py hl_llama_7B trivia_qa --using_act layer --token answer_last --probes_file_name NLSC42_/hl_llama_7B_/trivia_qa_greedy_responses_train5000_se_labels_/1000_1_layerFalse_answer_last_individual_linear_hallu_pos_bs128_epochs50_ --probes_file_name_concat ba --lr_list 0.005 --best_threshold True --save_path /home/local/data/ms/honest_llama_data --seed_list 42,101,2650 --fpr_at_recall -1
# python analyse_crossdataset_bce.py hl_llama_7B nq_open --using_act layer --token answer_last --probes_file_name NLSC42_/hl_llama_7B_/nq_open_greedy_responses_train5000_se_labels_/1000_1_layerFalse_answer_last_individual_linear_hallu_pos_bs128_epochs50_ --probes_file_name_concat ba --lr_list 0.005 --best_threshold True --save_path /home/local/data/ms/honest_llama_data --seed_list 42,101,2650 --fpr_at_recall -1
# python analyse_crossdataset_bce.py gemma_2B city_country --using_act layer --token answer_last --probes_file_name NLSC42_/gemma_2B_/city_country_greedy_responses_train6323_se_labels_/1000_1_layerFalse_answer_last_individual_linear_hallu_pos_bs128_epochs50_ --probes_file_name_concat ba --lr_list 0.005 --best_threshold True --save_path /home/local/data/ms/honest_llama_data --seed_list 42,101,2650 --fpr_at_recall -1
# python analyse_crossdataset_bce.py gemma_2B player_date_birth --using_act layer --token answer_last --probes_file_name NLSC42_/gemma_2B_/player_date_birth_greedy_responses_train5989_se_labels_/1000_1_layerFalse_answer_last_individual_linear_hallu_pos_bs128_epochs50_ --probes_file_name_concat ba --lr_list 0.005 --best_threshold True --save_path /home/local/data/ms/honest_llama_data --seed_list 42,101,2650 --fpr_at_recall -1
# python analyse_crossdataset_bce.py gemma_2B movie_cast --using_act layer --token answer_last --probes_file_name NLSC42_/gemma_2B_/movie_cast_greedy_responses_train8716_se_labels_/1000_1_layerFalse_answer_last_individual_linear_hallu_pos_bs128_epochs50_ --probes_file_name_concat ba --lr_list 0.005 --best_threshold True --save_path /home/local/data/ms/honest_llama_data --seed_list 42,101,2650 --fpr_at_recall -1
# python analyse_crossdataset_bce.py gemma_2B trivia_qa --using_act layer --token answer_last --probes_file_name NLSC42_/gemma_2B_/trivia_qa_greedy_responses_train5000_se_labels_/1000_1_layerFalse_answer_last_individual_linear_hallu_pos_bs128_epochs50_ --probes_file_name_concat ba --lr_list 0.005 --best_threshold True --save_path /home/local/data/ms/honest_llama_data --seed_list 42,101,2650 --fpr_at_recall -1
# python analyse_crossdataset_bce.py gemma_2B nq_open --using_act layer --token answer_last --probes_file_name NLSC42_/gemma_2B_/nq_open_greedy_responses_train5000_se_labels_/1000_1_layerFalse_answer_last_individual_linear_hallu_pos_bs128_epochs50_ --probes_file_name_concat ba --lr_list 0.005 --best_threshold True --save_path /home/local/data/ms/honest_llama_data --seed_list 42,101,2650 --fpr_at_recall -1


# python analyse_crossdataset_bce.py hl_llama_7B city_country --using_act layer --token answer_last --probes_file_name NLSC42_/hl_llama_7B_/ood_city_se_labels/_player_date_birth_1000_1_layerFalse_answer_last_individual_linear_hallu_pos_bs128_epochs50_ --probes_file_name_concat ba --lr_list 0.005 --best_threshold True --save_path /home/local/data/ms/honest_llama_data --seed_list 42,101,2650 --fpr_at_recall -1
# python analyse_crossdataset_bce.py hl_llama_7B city_country --using_act layer --token answer_last --probes_file_name NLSC42_/hl_llama_7B_/ood_city_se_labels/_movie_cast_1000_1_layerFalse_answer_last_individual_linear_hallu_pos_bs128_epochs50_ --probes_file_name_concat ba --lr_list 0.005 --best_threshold True --save_path /home/local/data/ms/honest_llama_data --seed_list 42,101,2650 --fpr_at_recall -1
# python analyse_crossdataset_bce.py hl_llama_7B city_country --using_act layer --token answer_last --probes_file_name NLSC42_/hl_llama_7B_/ood_city_se_labels/_trivia_qa_1000_1_layerFalse_answer_last_individual_linear_hallu_pos_bs128_epochs50_ --probes_file_name_concat ba --lr_list 0.005 --best_threshold True --save_path /home/local/data/ms/honest_llama_data --seed_list 42,101,2650 --fpr_at_recall -1
# python analyse_crossdataset_bce.py hl_llama_7B city_country --using_act layer --token answer_last --probes_file_name NLSC42_/hl_llama_7B_/ood_city_se_labels/_nq_open_1000_1_layerFalse_answer_last_individual_linear_hallu_pos_bs128_epochs50_ --probes_file_name_concat ba --lr_list 0.005 --best_threshold True --save_path /home/local/data/ms/honest_llama_data --seed_list 42,101,2650 --fpr_at_recall -1
# python analyse_crossdataset_bce.py gemma_2B city_country --using_act layer --token answer_last --probes_file_name NLSC42_/gemma_2B_/ood_city_se_labels/_player_date_birth_1000_1_layerFalse_answer_last_individual_linear_hallu_pos_bs128_epochs50_ --probes_file_name_concat ba --lr_list 0.005 --best_threshold True --save_path /home/local/data/ms/honest_llama_data --seed_list 42,101,2650 --fpr_at_recall -1
# python analyse_crossdataset_bce.py gemma_2B city_country --using_act layer --token answer_last --probes_file_name NLSC42_/gemma_2B_/ood_city_se_labels/_movie_cast_1000_1_layerFalse_answer_last_individual_linear_hallu_pos_bs128_epochs50_ --probes_file_name_concat ba --lr_list 0.005 --best_threshold True --save_path /home/local/data/ms/honest_llama_data --seed_list 42,101,2650 --fpr_at_recall -1
# python analyse_crossdataset_bce.py gemma_2B city_country --using_act layer --token answer_last --probes_file_name NLSC42_/gemma_2B_/ood_city_se_labels/_trivia_qa_1000_1_layerFalse_answer_last_individual_linear_hallu_pos_bs128_epochs50_ --probes_file_name_concat ba --lr_list 0.005 --best_threshold True --save_path /home/local/data/ms/honest_llama_data --seed_list 42,101,2650 --fpr_at_recall -1
# python analyse_crossdataset_bce.py gemma_2B city_country --using_act layer --token answer_last --probes_file_name NLSC42_/gemma_2B_/ood_city_se_labels/_nq_open_1000_1_layerFalse_answer_last_individual_linear_hallu_pos_bs128_epochs50_ --probes_file_name_concat ba --lr_list 0.005 --best_threshold True --save_path /home/local/data/ms/honest_llama_data --seed_list 42,101,2650 --fpr_at_recall -1

# python analyse_crossdataset_bce.py hl_llama_7B player_date_birth --using_act layer --token answer_last --probes_file_name NLSC42_/hl_llama_7B_/ood_player_se_labels/_city_country_1000_1_layerFalse_answer_last_individual_linear_hallu_pos_bs128_epochs50_ --probes_file_name_concat ba --lr_list 0.005 --best_threshold True --save_path /home/local/data/ms/honest_llama_data --seed_list 42,101,2650 --fpr_at_recall -1
# python analyse_crossdataset_bce.py hl_llama_7B player_date_birth --using_act layer --token answer_last --probes_file_name NLSC42_/hl_llama_7B_/ood_player_se_labels/_movie_cast_1000_1_layerFalse_answer_last_individual_linear_hallu_pos_bs128_epochs50_ --probes_file_name_concat ba --lr_list 0.005 --best_threshold True --save_path /home/local/data/ms/honest_llama_data --seed_list 42,101,2650 --fpr_at_recall -1
# python analyse_crossdataset_bce.py hl_llama_7B player_date_birth --using_act layer --token answer_last --probes_file_name NLSC42_/hl_llama_7B_/ood_player_se_labels/_trivia_qa_1000_1_layerFalse_answer_last_individual_linear_hallu_pos_bs128_epochs50_ --probes_file_name_concat ba --lr_list 0.005 --best_threshold True --save_path /home/local/data/ms/honest_llama_data --seed_list 42,101,2650 --fpr_at_recall -1
# python analyse_crossdataset_bce.py hl_llama_7B player_date_birth --using_act layer --token answer_last --probes_file_name NLSC42_/hl_llama_7B_/ood_player_se_labels/_nq_open_1000_1_layerFalse_answer_last_individual_linear_hallu_pos_bs128_epochs50_ --probes_file_name_concat ba --lr_list 0.005 --best_threshold True --save_path /home/local/data/ms/honest_llama_data --seed_list 42,101,2650 --fpr_at_recall -1
# python analyse_crossdataset_bce.py gemma_2B player_date_birth --using_act layer --token answer_last --probes_file_name NLSC42_/gemma_2B_/ood_player_se_labels/_city_country_1000_1_layerFalse_answer_last_individual_linear_hallu_pos_bs128_epochs50_ --probes_file_name_concat ba --lr_list 0.005 --best_threshold True --save_path /home/local/data/ms/honest_llama_data --seed_list 42,101,2650 --fpr_at_recall -1
# python analyse_crossdataset_bce.py gemma_2B player_date_birth --using_act layer --token answer_last --probes_file_name NLSC42_/gemma_2B_/ood_player_se_labels/_movie_cast_1000_1_layerFalse_answer_last_individual_linear_hallu_pos_bs128_epochs50_ --probes_file_name_concat ba --lr_list 0.005 --best_threshold True --save_path /home/local/data/ms/honest_llama_data --seed_list 42,101,2650 --fpr_at_recall -1
# python analyse_crossdataset_bce.py gemma_2B player_date_birth --using_act layer --token answer_last --probes_file_name NLSC42_/gemma_2B_/ood_player_se_labels/_trivia_qa_1000_1_layerFalse_answer_last_individual_linear_hallu_pos_bs128_epochs50_ --probes_file_name_concat ba --lr_list 0.005 --best_threshold True --save_path /home/local/data/ms/honest_llama_data --seed_list 42,101,2650 --fpr_at_recall -1
# python analyse_crossdataset_bce.py gemma_2B player_date_birth --using_act layer --token answer_last --probes_file_name NLSC42_/gemma_2B_/ood_player_se_labels/_nq_open_1000_1_layerFalse_answer_last_individual_linear_hallu_pos_bs128_epochs50_ --probes_file_name_concat ba --lr_list 0.005 --best_threshold True --save_path /home/local/data/ms/honest_llama_data --seed_list 42,101,2650 --fpr_at_recall -1

# python analyse_crossdataset_bce.py hl_llama_7B movie_cast --using_act layer --token answer_last --probes_file_name NLSC42_/hl_llama_7B_/ood_movie_se_labels/_city_country_1000_1_layerFalse_answer_last_individual_linear_hallu_pos_bs128_epochs50_ --probes_file_name_concat ba --lr_list 0.005 --best_threshold True --save_path /home/local/data/ms/honest_llama_data --seed_list 42,101,2650 --fpr_at_recall -1
# python analyse_crossdataset_bce.py hl_llama_7B movie_cast --using_act layer --token answer_last --probes_file_name NLSC42_/hl_llama_7B_/ood_movie_se_labels/_player_date_birth_1000_1_layerFalse_answer_last_individual_linear_hallu_pos_bs128_epochs50_ --probes_file_name_concat ba --lr_list 0.005 --best_threshold True --save_path /home/local/data/ms/honest_llama_data --seed_list 42,101,2650 --fpr_at_recall -1
# python analyse_crossdataset_bce.py hl_llama_7B movie_cast --using_act layer --token answer_last --probes_file_name NLSC42_/hl_llama_7B_/ood_movie_se_labels/_trivia_qa_1000_1_layerFalse_answer_last_individual_linear_hallu_pos_bs128_epochs50_ --probes_file_name_concat ba --lr_list 0.005 --best_threshold True --save_path /home/local/data/ms/honest_llama_data --seed_list 42,101,2650 --fpr_at_recall -1
# python analyse_crossdataset_bce.py hl_llama_7B movie_cast --using_act layer --token answer_last --probes_file_name NLSC42_/hl_llama_7B_/ood_movie_se_labels/_nq_open_1000_1_layerFalse_answer_last_individual_linear_hallu_pos_bs128_epochs50_ --probes_file_name_concat ba --lr_list 0.005 --best_threshold True --save_path /home/local/data/ms/honest_llama_data --seed_list 42,101,2650 --fpr_at_recall -1
# python analyse_crossdataset_bce.py gemma_2B movie_cast --using_act layer --token answer_last --probes_file_name NLSC42_/gemma_2B_/ood_movie_se_labels/_city_country_1000_1_layerFalse_answer_last_individual_linear_hallu_pos_bs128_epochs50_ --probes_file_name_concat ba --lr_list 0.005 --best_threshold True --save_path /home/local/data/ms/honest_llama_data --seed_list 42,101,2650 --fpr_at_recall -1
# python analyse_crossdataset_bce.py gemma_2B movie_cast --using_act layer --token answer_last --probes_file_name NLSC42_/gemma_2B_/ood_movie_se_labels/_player_date_birth_1000_1_layerFalse_answer_last_individual_linear_hallu_pos_bs128_epochs50_ --probes_file_name_concat ba --lr_list 0.005 --best_threshold True --save_path /home/local/data/ms/honest_llama_data --seed_list 42,101,2650 --fpr_at_recall -1
# python analyse_crossdataset_bce.py gemma_2B movie_cast --using_act layer --token answer_last --probes_file_name NLSC42_/gemma_2B_/ood_movie_se_labels/_trivia_qa_1000_1_layerFalse_answer_last_individual_linear_hallu_pos_bs128_epochs50_ --probes_file_name_concat ba --lr_list 0.005 --best_threshold True --save_path /home/local/data/ms/honest_llama_data --seed_list 42,101,2650 --fpr_at_recall -1
# python analyse_crossdataset_bce.py gemma_2B movie_cast --using_act layer --token answer_last --probes_file_name NLSC42_/gemma_2B_/ood_movie_se_labels/_nq_open_1000_1_layerFalse_answer_last_individual_linear_hallu_pos_bs128_epochs50_ --probes_file_name_concat ba --lr_list 0.005 --best_threshold True --save_path /home/local/data/ms/honest_llama_data --seed_list 42,101,2650 --fpr_at_recall -1

# python analyse_crossdataset_bce.py hl_llama_7B trivia_qa --using_act layer --token answer_last --probes_file_name NLSC42_/hl_llama_7B_/ood_trivia_qa_se_labels/_city_country_1000_1_layerFalse_answer_last_individual_linear_hallu_pos_bs128_epochs50_ --probes_file_name_concat ba --lr_list 0.005 --best_threshold True --save_path /home/local/data/ms/honest_llama_data --seed_list 42,101,2650 --fpr_at_recall -1
# python analyse_crossdataset_bce.py hl_llama_7B trivia_qa --using_act layer --token answer_last --probes_file_name NLSC42_/hl_llama_7B_/ood_trivia_qa_se_labels/_player_date_birth_1000_1_layerFalse_answer_last_individual_linear_hallu_pos_bs128_epochs50_ --probes_file_name_concat ba --lr_list 0.005 --best_threshold True --save_path /home/local/data/ms/honest_llama_data --seed_list 42,101,2650 --fpr_at_recall -1
# python analyse_crossdataset_bce.py hl_llama_7B trivia_qa --using_act layer --token answer_last --probes_file_name NLSC42_/hl_llama_7B_/ood_trivia_qa_se_labels/_movie_cast_1000_1_layerFalse_answer_last_individual_linear_hallu_pos_bs128_epochs50_ --probes_file_name_concat ba --lr_list 0.005 --best_threshold True --save_path /home/local/data/ms/honest_llama_data --seed_list 42,101,2650 --fpr_at_recall -1
# python analyse_crossdataset_bce.py hl_llama_7B trivia_qa --using_act layer --token answer_last --probes_file_name NLSC42_/hl_llama_7B_/ood_trivia_qa_se_labels/_nq_open_1000_1_layerFalse_answer_last_individual_linear_hallu_pos_bs128_epochs50_ --probes_file_name_concat ba --lr_list 0.005 --best_threshold True --save_path /home/local/data/ms/honest_llama_data --seed_list 42,101,2650 --fpr_at_recall -1
# python analyse_crossdataset_bce.py gemma_2B trivia_qa --using_act layer --token answer_last --probes_file_name NLSC42_/gemma_2B_/ood_trivia_qa_se_labels/_city_country_1000_1_layerFalse_answer_last_individual_linear_hallu_pos_bs128_epochs50_ --probes_file_name_concat ba --lr_list 0.005 --best_threshold True --save_path /home/local/data/ms/honest_llama_data --seed_list 42,101,2650 --fpr_at_recall -1
# python analyse_crossdataset_bce.py gemma_2B trivia_qa --using_act layer --token answer_last --probes_file_name NLSC42_/gemma_2B_/ood_trivia_qa_se_labels/_player_date_birth_1000_1_layerFalse_answer_last_individual_linear_hallu_pos_bs128_epochs50_ --probes_file_name_concat ba --lr_list 0.005 --best_threshold True --save_path /home/local/data/ms/honest_llama_data --seed_list 42,101,2650 --fpr_at_recall -1
# python analyse_crossdataset_bce.py gemma_2B trivia_qa --using_act layer --token answer_last --probes_file_name NLSC42_/gemma_2B_/ood_trivia_qa_se_labels/_movie_cast_1000_1_layerFalse_answer_last_individual_linear_hallu_pos_bs128_epochs50_ --probes_file_name_concat ba --lr_list 0.005 --best_threshold True --save_path /home/local/data/ms/honest_llama_data --seed_list 42,101,2650 --fpr_at_recall -1
# python analyse_crossdataset_bce.py gemma_2B trivia_qa --using_act layer --token answer_last --probes_file_name NLSC42_/gemma_2B_/ood_trivia_qa_se_labels/_nq_open_1000_1_layerFalse_answer_last_individual_linear_hallu_pos_bs128_epochs50_ --probes_file_name_concat ba --lr_list 0.005 --best_threshold True --save_path /home/local/data/ms/honest_llama_data --seed_list 42,101,2650 --fpr_at_recall -1

# python analyse_crossdataset_bce.py hl_llama_7B nq_open --using_act layer --token answer_last --probes_file_name NLSC42_/hl_llama_7B_/ood_nq_open_se_labels/_city_country_1000_1_layerFalse_answer_last_individual_linear_hallu_pos_bs128_epochs50_ --probes_file_name_concat ba --lr_list 0.005 --best_threshold True --save_path /home/local/data/ms/honest_llama_data --seed_list 42,101,2650 --fpr_at_recall -1
# python analyse_crossdataset_bce.py hl_llama_7B nq_open --using_act layer --token answer_last --probes_file_name NLSC42_/hl_llama_7B_/ood_nq_open_se_labels/_player_date_birth_1000_1_layerFalse_answer_last_individual_linear_hallu_pos_bs128_epochs50_ --probes_file_name_concat ba --lr_list 0.005 --best_threshold True --save_path /home/local/data/ms/honest_llama_data --seed_list 42,101,2650 --fpr_at_recall -1
# python analyse_crossdataset_bce.py hl_llama_7B nq_open --using_act layer --token answer_last --probes_file_name NLSC42_/hl_llama_7B_/ood_nq_open_se_labels/_movie_cast_1000_1_layerFalse_answer_last_individual_linear_hallu_pos_bs128_epochs50_ --probes_file_name_concat ba --lr_list 0.005 --best_threshold True --save_path /home/local/data/ms/honest_llama_data --seed_list 42,101,2650 --fpr_at_recall -1
# python analyse_crossdataset_bce.py hl_llama_7B nq_open --using_act layer --token answer_last --probes_file_name NLSC42_/hl_llama_7B_/ood_nq_open_se_labels/_trivia_qa_1000_1_layerFalse_answer_last_individual_linear_hallu_pos_bs128_epochs50_ --probes_file_name_concat ba --lr_list 0.005 --best_threshold True --save_path /home/local/data/ms/honest_llama_data --seed_list 42,101,2650 --fpr_at_recall -1
# python analyse_crossdataset_bce.py gemma_2B nq_open --using_act layer --token answer_last --probes_file_name NLSC42_/gemma_2B_/ood_nq_open_se_labels/_city_country_1000_1_layerFalse_answer_last_individual_linear_hallu_pos_bs128_epochs50_ --probes_file_name_concat ba --lr_list 0.005 --best_threshold True --save_path /home/local/data/ms/honest_llama_data --seed_list 42,101,2650 --fpr_at_recall -1
# python analyse_crossdataset_bce.py gemma_2B nq_open --using_act layer --token answer_last --probes_file_name NLSC42_/gemma_2B_/ood_nq_open_se_labels/_player_date_birth_1000_1_layerFalse_answer_last_individual_linear_hallu_pos_bs128_epochs50_ --probes_file_name_concat ba --lr_list 0.005 --best_threshold True --save_path /home/local/data/ms/honest_llama_data --seed_list 42,101,2650 --fpr_at_recall -1
# python analyse_crossdataset_bce.py gemma_2B nq_open --using_act layer --token answer_last --probes_file_name NLSC42_/gemma_2B_/ood_nq_open_se_labels/_movie_cast_1000_1_layerFalse_answer_last_individual_linear_hallu_pos_bs128_epochs50_ --probes_file_name_concat ba --lr_list 0.005 --best_threshold True --save_path /home/local/data/ms/honest_llama_data --seed_list 42,101,2650 --fpr_at_recall -1
# python analyse_crossdataset_bce.py gemma_2B nq_open --using_act layer --token answer_last --probes_file_name NLSC42_/gemma_2B_/ood_nq_open_se_labels/_trivia_qa_1000_1_layerFalse_answer_last_individual_linear_hallu_pos_bs128_epochs50_ --probes_file_name_concat ba --lr_list 0.005 --best_threshold True --save_path /home/local/data/ms/honest_llama_data --seed_list 42,101,2650 --fpr_at_recall -1